packages/ui/ViewManager/TransitionGroup.js

This patch fixes the `Too many doclets` error when parsing `ui/ViewManager` when using https://github.com/enactjs/docs.
Removed the jsdoc comment for `childrenEquals` in `ui/ViewManager/TransitionGroup` since it is not exported anyway.
PLAT-52439
Enact-DCO-1.0-Signed-off-by: Dave Freeman <dave.freeman@lge.com>

PLAT-52439: Enact docs: fix too many doclets error

---

packages/moonstone/CHANGELOG.md
packages/moonstone/ToggleItem/ToggleItem.js
packages/ui/CHANGELOG.md
packages/ui/ComponentOverride/ComponentOverride.js
packages/ui/ToggleItem/ToggleItem.js

ComponentOverride doesn't accept strings.
Now it does, and ToggleItem also accepts strings like "div" for its `iconComponent`

ENYO-5072: ComponentOverride should support strings as HTML tag names

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VirtualList/VirtualListBase.js
packages/moonstone/VirtualList/tests/VirtualList-specs.js
packages/moonstone/docs/virtual-list-scroller.md
packages/sampler/stories/moonstone-stories/VirtualGridList.js
packages/sampler/stories/moonstone-stories/VirtualList.js
packages/sampler/stories/qa-stories/VirtualGridList.js
packages/sampler/stories/qa-stories/VirtualList.js
packages/ui/CHANGELOG.md
packages/ui/VirtualList/VirtualListBase.js
packages/ui/VirtualList/VirtualListBaseNative.js
packages/ui/VirtualList/tests/VirtualList-specs.js

Rename the `component` prop as `itemRenderer` because
- the name of the `component` could cause misunderstanding
- only a function could be defined as the `component` prop
- Rename `component` as `itemRenderer`
- Update samplers
- Update VirtualList, Scroller developer guide
PLAT-52178

PLAT-52178: Rename `component` in `VirtualList as `itemRenderer` (develop)

---

packages/moonstone/CHANGELOG.md
packages/moonstone/IncrementSlider/IncrementSlider.js
packages/moonstone/Slider/Slider.js
packages/moonstone/Slider/SliderBar.js
packages/moonstone/Slider/SliderTooltip.js
packages/moonstone/Slider/tests/Slider-specs.js
packages/moonstone/internal/SliderDecorator/SliderDecorator.js
packages/sampler/stories/moonstone-stories/IncrementSlider.js
packages/sampler/stories/moonstone-stories/ProgressBar.js
packages/sampler/stories/moonstone-stories/Slider.js
packages/sampler/stories/qa-stories/ProgressBar.js
packages/sampler/stories/qa-stories/Slider.js
packages/sampler/stories/qa-stories/components/IncrementSliderDelayValue/IncrementSliderDelayValue.js
packages/ui/CHANGELOG.md
packages/ui/ProgressBar/ProgressBar.js
packages/ui/ProgressBar/ProgressBar.less
packages/ui/ProgressBar/tests/ProgressBar-specs.js

`vertical` is a 1-dimensional property without room for extension over time.
`vertical` has been replaced with `orientation` in all Slider and ProgressBar iterations. `orientation` accepts a customizable string, which will allow for easy future development.

ENYO-5074: Replace `vertical` with `orientation`

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Slider/Slider.js
packages/moonstone/Slider/SliderTooltip.js

Because `Slider.sliderTooltip` is moving to `Tooltip.ProgressBarTooltip` in 2.0.0 in #1467 , `sliderTooltip` needs to be deprecated for in 1.x
ENYO-4978

ENYO-4978: Deprecate sliderTooltip in 1.x

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Slider/Slider.js
packages/moonstone/Slider/SliderTooltip.js

Reverts enactjs/enact#1478 instead of merging #1513

Revert "ENYO-4978: Deprecate sliderTooltip in 1.x"

---

packages/moonstone/Input/InputSpotlightDecorator.js

InputSpotlightDecorator would restart spotlight whenever the state updated.
Only unpause spotlight if the focus target changes
ENYO-5085

Prevent blurring on state update

---

packages/moonstone/ProgressBar/ProgressBar.js

ProgressBar needs to accept `orientation` to set `vertical` to apply vertical styles correctly.
PLAT-52586

PLAT-52586: Fix ProgressBar tooltip in vertical orientation

---

packages/sampler/stories/qa-stories/ExpandableInput.js

This patch adds a QA sample that displays two `ExpandableInput`s.
ENYO-5046
Enact-DCO-1.0-Signed-off-by: Dave Freeman dave.freeman@lge.com

ENYO-5046: Need to Create QA ExpandableInput Sample with Two ExpandableInputs 

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VirtualList/VirtualListBase.js

Spotlight in `VirtualList` and `VirtualGridList` Hides on Page Down/Up
In some edge cases, Spotlight in `VirtualList` did not show properly after hiding it. So I fixed the condition to hide it.
ENYO-5006

ENYO-5006: Spotlight Hides on Page Down/Up

---

packages/moonstone/CHANGELOG.md
packages/moonstone/MoonstoneDecorator/MoonstoneDecorator.less
packages/moonstone/ProgressBar/ProgressBar.js
packages/moonstone/ProgressBar/ProgressBarTooltip.js
packages/moonstone/ProgressBar/ProgressBarTooltip.less
packages/moonstone/Slider/Slider.js
packages/moonstone/Slider/Slider.less
packages/moonstone/styles/variables.less

`ProgressBarTooltip` (formerly `SliderTooltip`) used some pretty outdated and non-functional techniques.
Essentially now, the `ProgressBarTooltip` component just transmits its proportion value directly to CSS. CSS then does calculations and positioning for every orientation of the tooltip. `Slider` can define a moonstone CSS "offset" variable which is then factored into the `ProgressBarTooltip` positioning calculation so it too is properly positioned.
Does Storybook not support CSS variables? My Storybook was erroring and it didn't make sense as to why. My installation may be out of date.

ENYO-5088: Refactor ProgressBarTooltip to use CSS variables for positioning

---

packages/moonstone/CHANGELOG.md
packages/moonstone/styles/colors-light.less
packages/moonstone/styles/colors.less

The colors for ProgressBar make it difficult to differentiate the stages of progress, as well as they don't look very good on random background colors, like photos or videos.
Update the colors to match the requirements and make the affected components more visually "contrasty".
This affects both ProgressBar *and* Slider, since Slider uses these color values.

ENYO-5054: Update ProgressBar and Slider colors

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VirtualList/VirtualListBase.js
packages/moonstone/VirtualList/VirtualListBaseNative.js

In Enact 2.0 (https://github.com/enactjs/enact/pull/1524), we'd like to remove the `data` prop in a `VirtualList`.
Add the log to deprecate `data` prop in `VirtualList`
PLAT-52443

PLAT-52443: Add the log to deprecate `data` prop in `VirtualList` (release 1.x)

---

packages/moonstone/VideoPlayer/FeedbackTooltip.js

The proposed change eliminates the ability to specify a component or an HTML node name, requiring instead an instance which doesn't automatically get the prescribed class, which was the previous functionality.
This uses ComponentOverride to allow both the proposed format and the original format, and retain the built-in class.
I was not able to detect wasted paints caused by the internal workings of ComponentOverride in the perf testing I did. However, the testing tools have changed since React 16.
**Perf implications should be reviewed before accepting this PR.**

Use ComponentOverride

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Input/InputSpotlightDecorator.js

After the changes made in #1473, Input no longer allowed directly navigating to adjacent components via 5-way when the input is active and the cursor is at the start or end of the text. This was caused by the internal state of `InputSpotlightDecorator` being out of sync with the desired state.
When pressing left or right at the start or end, respectively, of the text, `InputSpotlightDecorator` would focus the next control. When the internal `<input>` was blurred while still in 5-way mode, `InputSpotlightDecorator` would then try to focus the decorator assuming that was the expected next target. As a result, focus would move to an external component and then immediately pulled back to the input decorator.
[//]: # …

ENYO-5092: Fix navigating out of moonstone/Input via 5-way

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Panels/Arrangers.js
packages/moonstone/Panels/Viewport.js

When altering the children of ActivityPanels, the active panel will incorrectly be offset for breadcrumbs multiple times.
This is due to a logic error in the ActivityPanelsArranger which failed to clear the current transform before setting the offset.
* Add a `clearTransform` to the `stay` arranger
* Also fix a bug in Viewport to support `null` children
Enyo-DCO-1.1-Signed-off-by: Ryan Duffy (ryan.duffy@lge.com)

ENYO-5071: Fix ActivityPanels layout after adding panels

---

packages/ui/FloatingLayer/FloatingLayer.js
packages/ui/FloatingLayer/FloatingLayerDecorator.js

* Prerendering was failing due to usage of `document.createElement`
* Guard for existence of `document`.

ENYO-5093: Guard against document to allow proper prerendering.

---

packages/ui/CHANGELOG.md
packages/ui/Transition/Transition.js

`mooonstone/ExpandableItem.ExpandableSpotlightDecorator` depends on pausing and resuming spotlight from `ui/Transition`'s `onShow` and `onHide` events. However, when there are no children provided, then `Transition` never fires those events, resulting in indefinite spotlight pause.
Change `Transition` to handle empty `children` and fire events when `visible` prop changes.

ENYO-5013: Fix ui/Transition to handle empty children

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/MediaTitle.js
packages/moonstone/VideoPlayer/VideoPlayer.js

`moonstone/VideoPlayer` only accepts string as title the proptype. In case of app wanting to use a image or an `Icon` as part of the title, it will throw a proptype warning.
Change propType declaration to accept node type for `title` prop.

PLAT-52582: Change media title to accept node type

---

packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js
packages/moonstone/Scroller/Scroller.js
packages/moonstone/VirtualList/VirtualListBase.js
packages/ui/Scrollable/Scrollable.js
packages/ui/Scrollable/ScrollableNative.js
packages/ui/Scroller/Scroller.js
packages/ui/VirtualList/VirtualListBase.js

Sometimes we referred the child or the grandchild's props even though those props could be referred from the current component.
e.g
AS-IS
```
const {direction} = this.uiRef.props;
```
TO-BE
```
const {direction} = this.props;
```
Refer the props efficiently between Moonstone and UI libraries and between Scrollable and VirtualList from this.
Renamed the following variables
```
childComponentProps as childUiComponentProps
initContainerRef as initUiContainerRef …
```

PLAT-52825: Refactoring to reduce ref usage in VirtualList, Scrollable

---

packages/sampler/CHANGELOG.md
packages/sampler/src/MoonstoneEnvironment/MoonstoneEnvironment.js

It looks like the `background` knob was accidentally removed during the Storybook upgrade
This restores the knob and replaces the old images with images that load faster and are higher resolution

ENYO-5126: Add background images knob to sampler

---

packages/sampler/.qa-storybook/.babelrc
packages/sampler/.storybook/.babelrc

* Babel configs were referencing an removed/nonexistent plugin.
* Remove broken plugin references.

ENYO-5133: Fix Babel configuration in Sampler

---

packages/sampler/stories/moonstone-stories/ProgressBar.js
packages/sampler/stories/qa-stories/ProgressBar.js

Add `tooltipSide` to `ProgressBar` sampler
ENYO-5136

ENYO-5136: Add tooltipSide knob for ProgressBar samples

---

packages/moonstone/CHANGELOG.md
packages/moonstone/TimePicker/TimePickerBase.js

`moonstone/TimePickerBase` to show `meridiem` correctly in all locales by setting the `meridiem` picker width dynamically based on the length of the meridiem * 2
ENYO-4981

ENYO-4981: Fix TimePicker to support variable length meridiems

---

packages/moonstone/CHANGELOG.md
packages/moonstone/ExpandableItem/ExpandableItem.js
packages/moonstone/ExpandableItem/ExpandableItem.less

Prevent applying `open` class when `disabled`
ENYO-5134 ENYO-5119

ENYO-5134: Fix ExpandableItem from Applying Open Class When Disabled

---

packages/sampler/stories/moonstone-stories/VideoPlayer.js

When the sampler is run locally, VideoPlayer sample throws an unknown event handler warning. This is related to the recent change in #1459.
Remove webOS media event handler from the sampler.

ENYO-5076: Remove webOS media event from storybook

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Panels/ApplicationCloseButton.js
packages/moonstone/Panels/Panels.js
packages/moonstone/Panels/tests/Panels-specs.js

There's no way to override a11y string on Exit App button of Panels
Add Panels property `exitAppAriaLabel` to override readout string on 
PLAT-52106

PLAT-52106: Add closeButtonAriaLabel prop to moonstone/Panels

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/VideoPlayer.js

When the media controls are hidden, pressing 5-way select does not show them
* Add back call to `showControls()` when the spotlight placeholder is "clicked" (triggered by the simulated click by spottable)
We could change this to be a key handler instead but this was the prior behavior and simpler to add back. Open for debate :)

ENYO-5160: Fix VideoPlayer to show controls on 5-way select

---

packages/ui/CHANGELOG.md
packages/ui/VirtualList/VirtualListBase.js

Even though calling this.forceUpdate() app side, VirtualList items are not re-rendered because we cached them to enhance performance by blocking re-rendering them.
While scrolling a VirtuslList, we still use the cached items. But while updating it, we re-render the items.
PLAT-53640

PLAT-53640: Allow to force to re-render VirtualList items if needed

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/ScrollButton.js
packages/moonstone/Scrollable/ScrollButtons.js
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js
packages/moonstone/Scroller/tests/Scroller-specs.js
packages/moonstone/VirtualList/tests/VirtualList-specs.js

There's no way to override a11y string on scrollbar scroll buttons.
Add Scrollable/ScrollableNative props - horizontalScrollbarNextButtonAriaLabel, horizontalScrollbarPreviousButtonAriaLabel, verticalScrollbarNextButtonAriaLabel, verticalScrollbarPreviousButtonAriaLabel to override readout string on
PLAT-52108

PLAT-52108: Accessibility: Add props for overriding inner focusable component - VirtualList, Scroller

---

packages/moonstone/Button/Button.less

The selectors were targeting only a subset of the states of Button. This removes older code that targeted non-disabled state and allows disabled and non-disabled to share color rules.

Simplify the disabled selector logic

---

packages/core/CHANGELOG.md
packages/core/kind/kind.js
packages/core/util/tests/memoize-specs.js
packages/core/util/util.js

While experimenting with using memoized event handlers with `core/kind`, I discovered that `core/util.memoize` doesn't send all args to provided function.
* Fixed `core/util.memoize` pass all args to provided function
* Added test for the above
* Changed the generated handlers from `core/kind` to return the result of the handler. This won't affect the majority of cases because returned values are ignored by React (afaik) but will enable the memoized handlers with which I was experimenting.

ENYO-5186: Fix memoize to forward all args to provided function

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/VideoPlayer.js
packages/sampler/stories/moonstone-stories/VideoPlayer.js

Deprecate `tooltipHideDelay` prop in `moonstone/VideoPlayer`. Seems like it's a cruft leftover from #815

ENYO-5188: Deprecate tooltipHideDelay in VideoPlayer

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/VideoPlayer.js
packages/sampler/stories/moonstone-stories/VideoPlayer.js

Remove `tooltipHideDelay` prop in `moonstone/VideoPlayer`. Seems like it's a cruft leftover from #815

ENYO-5188: Remove tooltipHideDelay prop in VideoPlayer

---

packages/core/CHANGELOG.md
packages/core/snapshot/package.json
packages/core/snapshot/snapshot.js

Would be good to have a utility for enqueuing window-dependent callbacks in a snapshot-compatible way.
* add `core/snapshot` module with `onWindowReady` and `windowReady` methods to enqueue callbacks and flush the queue, respectively
Also need a CLI and dev-utils PR to complete the feature.

ENYO-5191: Add core/snapshot module

---

packages/ui/CHANGELOG.md
packages/ui/VirtualList/VirtualListBase.js

VirtualGridList shows blank when `direction` prop changed after scroll.
This issue only occurs in "JS" version of VirtualLists.
After syncing the DOM structure of "JS" list with "Native" list, we made contentRef for "JS" list and transform it when the scroll occurs.
But when the `direction` prop changed after scroll position changed, we didn't reset the transform value for contentRef.
So added reset transform code for contentRef. …

ENYO-5141: VirtualGridList: Fix showing blank when direction prop changed

---

packages/moonstone/CHANGELOG.md
packages/moonstone/MoonstoneDecorator/I18nFontDecorator.js
packages/moonstone/MoonstoneDecorator/fontGenerator.js
packages/moonstone/styles/fonts.less
packages/ui/internal/localized-fonts/localized-fonts.js

Currently too much (unnecessary) work is happening when attempting to load localized fonts into the dom. Localized font definitions are being generated on render regardless of whether they are already inserted in the dom. Also we're needlessly specifying miso-museo font unicode-range definitions, which add to overall load time bloat.
1) Optimize font loading by only generating font definitions when necessary:
-a) generate required static/unchanging font css definitions when they have not been loaded already
-b) generate locale-specific font css definitions only when the current locale needs them
2) Remove the miso-museo font unicode-range definition rules.

PLAT-49780: Optimize localized font loading performance

---

packages/core/package.json
packages/i18n/package.json
packages/moonstone/package.json
packages/sampler/package.json
packages/spotlight/package.json
packages/ui/package.json

* Dependencies are at a loose `^16.2.0` for React/ReactDOM.
* Bump to an explicit `^16.3.2` dependency range for React/ReactDOM.

PLAT-53067: Move dependencies to React 16.3

---

packages/moonstone/ExpandableItem/Expandable.js
packages/moonstone/Panels/CancelDecorator.js
packages/ui/CHANGELOG.md
packages/ui/Cancelable/Cancelable.js
packages/ui/Cancelable/tests/Cancelable-specs.js
packages/ui/FloatingLayer/FloatingLayer.js

Current logic uses return values to mark a cancel event "handled" and prevent other upstream or modal handlers for being called. That's inconsistent with other event handlers and was incompatible with the prop-based approach which didn't receive an event payload and could never stop propagation.
* Add a consistent event payload to all `onCancel` handlers that includes `type` and `stopPropagation()` the latter which can be called to indicate the cancel was "handled" and no further handlers should be called.
[//]: # …

PLAT-53652: Change ui/Cancelable to use stopPropagation instead of return values

---

packages/moonstone/CHANGELOG.md
packages/moonstone/GridListImageItem/GridListImageItem.js

We didn't pass `placeholder` and `selectionOverlay` prop to ui/GridListImageItem properly in moonstone/GridListImageItem.
Fixed not passing props
ENYO-5130

ENYO-5130: Fixed not showing proper placeholder and selectionOverlay in GridListImageItem

---

packages/moonstone/ExpandableItem/ExpandableItem.js
packages/moonstone/ExpandableItem/ExpandableItem.less

Add missing `noneText` and `.enact-text-large` support for `ExpandableItem` min-height change.

ENYO-4977: Add missing min-height support to ExpandableItem

---

packages/ui/CHANGELOG.md
packages/ui/Transition/Transition.js

The docs sorely need updating for `Transition`
Also, there's no way to customize the transition duration.
Fixed the docs
and
Updated duration value to accept not only the preset values, but also custom values, like numbers and strings.

ENYO-5201: Update ui/Transition docs

---

packages/moonstone/Notification/Notification.js
packages/moonstone/SwitchItem/SwitchItem.js
packages/moonstone/SwitchItem/SwitchItem.less

`Notification` requires the `buttons` prop, which may not be necessary in all cases. Requiring it adds unnecessary restriction.
`SwitchItem` is restrictive in its implementation and should be expanded to support other use cases.
`Notification` no longer requires `buttons` and `SwitchItem` has a default-assigned, but overridable, `Switch` component to allow for more flexible usage.

PLAT-49776: Allow more flexible usage of Notification and SwitchItem

---

packages/moonstone/VirtualList/VirtualListBase.js

When a 5-way key is pressed on a list, an error occurs by trying to call a function variable which value is `undefined`.
Currently, there are two `defaultProps`s in VirtualList by merging #1593 and #1551. If we merge them, this issue is resolved.
This PR is to merge two `defaultProps` into one.
PLAT-54727

Fixed VirtualList not to have two defaultProps

---

packages/ui/CHANGELOG.md
packages/ui/Layout/Cell.js
packages/ui/Layout/Layout.js

I discovered a bug with `ui/Layout.Cell` which needed to be addressed to facilitate other work.
A long-standing layout issue occurring when `size` and `shrink` were set and the content extended beyond the bounds of the `Layout` component. `Cell` contents no longer overflow, even if they are too large. The documentation was also updated, and is less confusing now.

PLAT-49776: Layout fixes and docs improvements

---

packages/moonstone/Panels/Header.js
packages/ui/Layout/Cell.js

Header got *jacked up* with the latest Layout changes.
A child cell used a parent's cell as a measurement for itself, causing it to be far too small. The fix was to explicitly "blank out" the sizing if no sizing or shrink was set on the cell, so it didn't inherit from its ancestor.

ENYO-5216: Fixed header layout

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js
packages/moonstone/VirtualList/VirtualListBase.js

When jumping over the disabled items in VirtualList, the focus in it gone.
If calling `setState` or `forceUpdate` app side while jumping, the focus information that we have to give gone because we get focus, scroll the list, then initialize the focus information. So for the case, we add a flag  not to scroll on focus
ENYO-5039

ENYO-5039:  Add flag to ignore to scroll on focus when jumping

---

packages/moonstone/ContextualPopupDecorator/ContextualPopupDecorator.js

`ContextualPopupDecorator` with `spotlightRestrict: 'self-only'` tries to blur before if there is a spottable component inside the popup. However, there's a case where there's no focused element prior to opening the popup. Adding a check before blur can solve the problem.

ENYO-5041: Check before blurring for self-only type contextual popup

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js
packages/ui/Scrollable/Scrollable.js
packages/ui/Scrollable/ScrollableNative.js

Even though pressing a page up/down key in VirtualList with all disabled items, the list does not scroll.
We tried to cache the value of the scroll distance when mounting a VirtualList.
But at that time after updating React version, the list's client height equals 0 when `componentDidMount` called, then the cached value also equals 0 and finally the list does not scroll.
Sometimes the client size and scroll direction could be changed dynamically. So I think that it would be better not to cache it instead of checking if they are changed or not.
[//]: # (Are there …

ENYO-5228: Fix to scroll properly with all disabled items in VirtualList

---

packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js

While doing UI migration, I get the spotlight ID from the wrong DOM element.
I use the right DOM element to get the spotlight ID in Scrollable.
ENYO-5231

ENYO-5231: Fix the wrong spotlight ID in Scrollable

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/ScrollButtons.js

When apply RTL to Scroller, wrong aria-labels were applied to Scrollbar buttons. (`scroll left` to the right button, `scroll right` to the left button)
Depending on RTL, I apply the aria-label in the buttons properly.
ENYO-5236

ENYO-5236: Fix Scrollbar button's aria-lable in RTL

---

packages/moonstone/Scrollable/ScrollButtons.js

The aria-labels in vertical Scroll bar buttons with RTL mode are switched each other.
Fix the aria-labels in vertical scroll bar buttons.
When pressing the buttons, Scroller announce the wrong text because we passed it incorrectly in RTL mode.
ENYO-5236

ENYO-5236: Fix vertical scroll bar button aria-label in RTL

---

packages/ui/CHANGELOG.md
packages/ui/Marquee/MarqueeDecorator.js

`MarqueeDecorator` resets animation when `children` is updated which was checked by strict equality operator (`===`). This won't work for array type children. Proposing it to compare using `shallowEqual` to handle the case.

ENYO-5109: Fix to correctly reset marquee animation when children updates

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Item/Item.js
packages/moonstone/SlotItem/SlotItem.js
packages/moonstone/ToggleItem/ToggleItem.js

Don’t need to apply `className` in `moonstone` when the same className is applied in `ui`. Removing `className` from `moonstone/Item` and other components.

ENYO-5223: Remove duplicate classNames in moonstone/Item family

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Slider/utils.js

`onChange` fires on every key down event even if when it reaches the boundary and 5-way out of it. Fixed by checking the value with min/max value prior to firing `onChange` event.

ENYO-5195: Fix to not fire onChange event when 5-ways out of boundary

---

packages/core/CHANGELOG.md
packages/core/dispatcher/dispatcher.js
packages/core/dispatcher/listeners.js
packages/core/dispatcher/tests/dispatcher-specs.js

It was possible to duplicate event handlers
Prevent adding the same handler twice to a target
It could be argued that the root cause of duplicate handlers should be addressed.
ENYO-5241

ENYO-5241: Prevent adding duplicate handlers with core/dispatcher

---

packages/moonstone/CHANGELOG.md
packages/moonstone/ExpandableItem/ExpandableItem.js
packages/sampler/stories/qa-stories/ExpandableList.js
packages/spotlight/src/container.js

If disabled items appeared at the top/bottom of Expandables, the `autoClose`,
`lockBottom` and `noLockBottom` props could be ignored
Used some internal spotlight-fu to ensure focus stays within the inner container
when navigating up/down
ENYO-5154

ENYO-5154 Account for disabled items in ExpandableItem

---

packages/ui/CHANGELOG.md
packages/ui/Marquee/MarqueeDecorator.js

`Marquee` stops the animation when some of the props value updates, however it should always marquee if `marqueeOn` value is set to `render`. 
Updated condition to always start the animation for `marqueeOn="render"` and restart when `stop` is called.
I'm not 100% sure if marquee should restart when `forceDirection` is updated because of the rare chance of apps needing to change at runtime. Given that, some props change (e.g. `marqueeDelay`, `marqueeResetDelay`) won't update the animation state even with the fix. Should we check for them as well?
In regards to recent react 16.3.x update, we should consider refactoring animation check logic in `componentWillReceiveProps` to  `componentDidUpdate`. …

ENYO-5210: Fix Marquee to always animate when marqueeOn="render"

---

packages/sampler/stories/qa-stories/SelectableItem.js
packages/sampler/stories/qa-stories/SwitchItem.js

Apply `disabled` prop to `<Group>` as well
ENYO-5111

ENYO-5111: Update Group QA samples to apply disabled prop

---

CHANGELOG.md
packages/moonstone/CHANGELOG.md
packages/moonstone/IconButton/IconButton.js
packages/moonstone/IconButton/IconButton.less
packages/ui/IconButton/IconButton.js

IconButton isn't visually customizable the way Button is, which is _just wrong_.
Added ComponentOverride to ui/IconButton so moonstone/IconButton could send its `css` into the Button component for customization. Also had to include the two customizable classes in the moonstone/IconButton.less file so they're available for override externally.

ENYO-5143: IconButton is now visually customizable

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Image/Image.js
packages/moonstone/Image/Image.less
packages/sampler/stories/moonstone-stories/Image.js

An image on the screen doesn't update when the screen is resized and new imagery should be swapped in for the source. A refresh is required.
Images now automatically detect when a screen size change occurs and re-renders only if a new image source (src) is available and appropriate.
The Sample was also updated to be more helpful. It now has a border and uses appropriate scaling of images (1x,2x,4x -> 2x,3x,6x) to more accurately represent the relative scale between 720, 1080, and 4k

ENYO-5221: Automatic Image src swapping during resolution change

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Popup/Popup.js

`Popup` would seem to ignore the `spotlightRestrict` setting if it was open on mount
`onShow` is not fired for `Transition` that is open at start anymore, regardless of animation
setting.  Always attach keyboard handler when open at mount.
Due to some strangeness with Sampler, it is possible for `onTransitionEnd` to fire when
refreshing a page with an open-at-the-start transition in it.  I was not able to …

ENYO-5213: Fix Popup spotlightRestrict handling

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js

If pressing a page up/down key in VirtualList with pointer mode, the VirtualList scrolls. It should not do.
I checked pointer mode before handling key events in Scrollable.
ENYO-5089

ENYO-5089: Check pointer mode before handling key events in Scrollable

---

packages/spotlight/CHANGELOG.md
packages/spotlight/src/spotlight.js

Fixed case where spotlight focus was erroneously remaining on the incorrect spottable item.
Spotlight no longer forces `_pointerMoveDuringKeyPress = true;` when handling pointer events because wheeling isn't necessarily moving.
ENYO-4747
Enact-DCO-1.0-Signed-off-by: Dave Freeman (dave.freeman@lge.com)

ENYO-4747: Fix spotlight handling 5-way events when in pointer mode

---

packages/moonstone/CHANGELOG.md
packages/moonstone/ExpandableInput/ExpandableInput.js
packages/moonstone/Input/Input.js
packages/moonstone/Input/util.js

Added support for `<input>` props `autoComplete, list, maxLength, minLength, pattern, required, size` to `moonstone/Input` and `moonstone/ExpandableInput`
ENYO-5243

ENYO-5243: Add valid Input props

---

packages/moonstone/CHANGELOG.md
packages/moonstone/styles/colors-light.less
packages/moonstone/styles/colors.less

The disabled color seems to have drifted toward more (too) transparent over time.
This corrects the value back to "normal" based on the latest iteration of the design visuals.

ENYO-5227: Updated the disabled color of items

---

packages/spotlight/CHANGELOG.md
packages/spotlight/src/spotlight.js

There are edge-cases where spotlight cannot set focus during the window focus event, because the last focused element (prior to the window blurring) is disabled (or perhaps missing).
Allow spotlight to set focus as a failsafe, in case the previously focused element cannot gain focus.

ENYO-5252: Add fallback focus attempt on window focus

---

packages/moonstone/CHANGELOG.md
packages/moonstone/SelectableItem/SelectableItem.js
packages/moonstone/SlotItem/SlotItem.js
packages/moonstone/ToggleButton/ToggleButton.js
packages/moonstone/ToggleItem/ToggleItem.js
packages/moonstone/ToggleItem/ToggleItem.less
packages/sampler/stories/moonstone-stories/ToggleButton.js
packages/ui/CHANGELOG.md
packages/ui/ToggleItem/ToggleItem.js
packages/ui/ToggleItem/tests/ToggleItem-specs.js
packages/ui/Toggleable/Toggleable.js

`moonstone/ToggleItem` forwards custom events (i.e. `{remeasure: true}`) when `onFocus`/`onBlur`. This is due to `moonstone/SlotItem`, a base component for `moonstone/ToggleItem`, being wrapped in `Toggleable` which activates/deactivates `onFocus` and `onBlur` respectively to notify `Remeasurable`. This behavior is not applicable to `moonstone/ToggleItem` as toggled "selected" states do not appear or disappear on focus/blur. Proposing to clean up HOCs in `ToggleItem`.

ENYO-5156: Change ToggleItem to forward native events for onFocus and onBlur

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js

If `data-spotlight-container-disabled` prop was defined in VirtualList, VirtualList, or Scroller, it was passed to their internal DOM element instead of their outer DOM element.
`data-spotlight-container-disabled` prop is passed to their outer DOM element.
ENYO-5251

ENYO-5251: Handle `data-spotlight-container-disabled` prop properly in Scrollable

---

packages/ui/Touchable/ClickAllow.js

Selecting a component via 5-way would emit 2 `onTap` events.
Suppress any non-`click` event from emitting an `onTap` event.

ENYO-5264: Fix Touchable to only send one tap on emulated mouse click

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VirtualList/VirtualListBase.js

If the items from the 2nd to 5th in VirtualList are visible, and the 3rd item get focus, the first item get focus if pressing a page up key. The 2nd item should get focus.
There are missing page up/down key requirements in VirtualList if it has all enabled items. So I implemented them as we did with some disabled items.
ENYO-5115

ENYO-5115: Fix to scroll properly with all enabled items via a page up or down key

---

packages/moonstone/CHANGELOG.md
packages/moonstone/ContextualPopupDecorator/ContextualPopupDecorator.js

`ContextualPopupDecorator` was indiscriminately setting focus to its activator on close regardless of where the focus may have been set under the assumption it had captured focus. If an app had programmatically set the focus elsewhere, the focus would be stolen. :sadpanda:
Since focusing the activator occurs in `componentDidUpdate` (good) but the container has already been unmounted then, I added a new state member, `shouldFocusActivator` which is calculated in `componentWillReceiveProps` to determine the focus behavior after update.

ENYO-5250: ContextualPopupDecorator to not steal focus on close

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/MediaControls.js
packages/moonstone/VideoPlayer/VideoPlayer.js

Fix default spotlight focus to media controls. In an attempt to remove any `MediaControls` knowledge from `VideoPlayer` in #1574, there was a cruft left over in how default focus should work. Resolved by moving the logic to `MediaControlsBase` where the default spotlight should go.

ENYO-5230: Fix default spotlight focus to media controls

---

packages/ui/CHANGELOG.md
packages/ui/Touchable/ClickAllow.js

ClickAllow can't handle null events
Add a guard to ClickAllow to handle check if event exists.
PLAT-58301
Enact-DCO-1.0-Signed-off-by: Derek Tor (derek.tor@lge.com)

PLAT-58301: Fix Touchable runtime error from simulated onMouseUp from Spottable

---

packages/moonstone/CHANGELOG.md
packages/moonstone/ProgressBar/ProgressBar.js
packages/moonstone/ProgressBar/ProgressBar.less
packages/moonstone/styles/colors-light.less
packages/moonstone/styles/colors.less
packages/sampler/stories/moonstone-stories/ProgressBar.js
packages/sampler/stories/qa-stories/ProgressBar.js

Apps have no way to customize the color of a ProgressBar. If a ProgressBar is surrounded by other text-based elements, it would either completely blend in, or be mistaken for a simple horizontal line.
Added a new prop to `moonstone/ProgressBar` to allow an app to easily call attention to a ProgressBar, which sets the foreground ("fill" color) to the common spotlight color.

PLAT-52482: Added a `highlighted` prop to ProgressBar

---

packages/ui/Marquee/MarqueeDecorator.js

This patch corrects the docs for the `disabled` prop in `MarqueeDecorator`.
ENYO-5222
Enact-DCO-1.0-Signed-off-by: Dave Freeman (dave.freeman@lge.com)

ENYO-5222: Update doc for disabled prop in Marquee

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/VideoPlayer.js
packages/sampler/stories/qa-stories/VideoPlayer.js

VideoPlayer should show `MediaControls` on mount and also whenever it switches to another video.
Set the default state to show the title and `MediaControls` and show controls if the `source` is changed.
ENYO-5273

ENYO-5273: VideoPlayer show MediaControls on mount

---

packages/core/CHANGELOG.md
packages/core/handle/handle.js
packages/ui/Touchable/Touchable.js

Debugging `core/handle` usage can be frustrating when everything is named `anonymous`.
* Added some names to internal functions that show up in the call stack
* Added `named()` to handlers to provide a means to name them when dev tools can't figure it out
* Added `bindAs()` to handlers to combine binding and naming when using `core/handle` with ES6 classes
* Adopting naming in `ui/Touchable` which is used everyone and could benefit from the naming the most
Was | Now
-----|-----
See https://github.com/ariya/phantomjs/issues/14310 for why the `try`/`catch` block exists :( Its `__DEV__` only so a minor …

ENYO-5271: Add debugging utilities to core/handle

---

packages/spotlight/CHANGELOG.md
packages/spotlight/Spottable/Spottable.js

The logic in `componentWillReceiveProps` was incorrectly setting the `spottableDisabled` state to `true` for `spotlightDisabled` components
* Always (correctly) update the value of `spottableDisabled` on prop change so the state is accurate
* Do not consider `spotlightDisabled` in the value of `spottableDisabled` because it is included in the `spottable` determination in `render()`.
* Fixed a regression from #1570 which inadvertently dropped assignment of `this.node`

ENYO-5253: Fix Spottable to prevent making component spottable when disabled

---

packages/moonstone/CHANGELOG.md
packages/ui/Marquee/MarqueeController.js
packages/ui/Marquee/MarqueeDecorator.js

MarqueeController batches up cancel animation requests so that multiple synced marquees don't incur extra work when multiple cancel at the same time. However, if the cancellation was due to a change in prop and the synced marquees should start on render, they will likely be cancelled (when the job timer fires) before they can start (after the `marqueeOnRenderDelay`).
* Prevent starting the cancel job if there aren't any marquees running.
* (Incidentally) Avoid trying to start a marquee if `marqueeDisabled`

ENYO-5280: Fix MarqueeController incorrectly canceling valid animations

---

packages/sampler/stories/qa-stories/ContextualPopupDecorator.js
packages/sampler/stories/qa-stories/Input.js

A little bit of margin for some breathing room for QA samplers
ENYO-5110

ENYO-5110: Fix layout of Input and ContextualPopup QA samples

---

packages/ui/CHANGELOG.md
packages/ui/Touchable/Touchable.js

Add a blur handler to end gestures when the focused component is blurred.
ENYO-5112

ENYO-5112: Touchable End Gestures when Blurred

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/VideoPlayer.js

`firstPlayReadFlag` was added in #1318, hoping that it wouldn't read at first mount. But it's actually preventing from reading when play button is clicked or play remote key is pressed the first time. Removed unnecessary flag to addressed the issue..

ENYO-5254: Fix first play read out

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Slider/SliderBehaviorDecorator.js

An error message is being output due to incorrect proptypes.
TV don't read a11y because the slider role is missing.
Fixed incorrect proptypes (oneOf compares the values. oneOfType is correct.)
Added role="slider" in Slider component
ENYO-5237

ENYO-5237: Add slider role and fix incorrect proptypes in SliderBehaviorDecorator

---

packages/ui/CHANGELOG.md
packages/ui/VirtualList/VirtualListBase.js

Fixed not focusing scroll buttons from items via 5way
Fixed not focusing next items via 5way
When VirtualList's container's width happened to have a value between x.5 ~ x.0, the content of VL and scroll buttons seem to overlap.
To remedy this, when we set the content width/height of VL, minus 1px to make sure the item and scroll buttons can't overlap.
ENYO-5245, PLAT-58103

ENYO-5245: Fixed not focusing scroll buttons from items via 5way

---

packages/moonstone/CHANGELOG.md
packages/moonstone/ContextualPopupDecorator/ContextualPopupDecorator.js

In react 16, [event  bubbling in `Portal`](https://reactjs.org/docs/portals.html#event-bubbling-through-portals) acts the same way as a normal React child, meaning that it will fire up the chain to the parent instead of the root node. This change has affected the event propagation path for `ContextualPopupDecorator` as it tries intercept keydown event to handle popup showing/closing. Since `keydown` event listener was attached to `document`, it no longer correctly stops event propagation. 
Proposed solution suggests to 
1. attach the `onKeyDown` handler directly to the popup container for handling the closing
2. only handle spotlight focus from the activator to the popup container at `document` …

ENYO-5199: Fix ContextualPopupDecorator to properly stop keydown event propagation

---

packages/moonstone/Button/Button.js
packages/moonstone/CHANGELOG.md
packages/moonstone/IconButton/IconButton.js
packages/moonstone/Panels/ApplicationCloseButton.js
packages/moonstone/Panels/Panels.js
packages/moonstone/ToggleButton/ToggleButton.js
packages/moonstone/VideoPlayer/MediaControls.js
packages/sampler/stories/moonstone-stories/Button.js
packages/sampler/stories/moonstone-stories/ToggleButton.js
packages/sampler/stories/qa-stories/Button.js
packages/sampler/stories/qa-stories/ToggleButton.js

`minWidth` prop's default value is set to `true`, and by `nullifying` the boolean value, it will always set to `true` even if the knob is set to `false`. Fixed by removing `nullifying` in the select knob.
- Button's props weren't being properly merged in the info section and made an update to it. It seems like other components that uses `ui` as a base component show similar pattern and we need to update them all.
- Any props that were added by HOCs (e.g. `casing` prop from `i18n/Uppercase`) will not be fetched and need to be set with constants. Should we declare those …

ENYO-5153: Fix Button's sampler to toggle minWidth correctly

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/MediaControls.js
packages/moonstone/VideoPlayer/VideoPlayer.js

Added `onClose` prop to `moonstone/VideoPlayer.MediaControls` and updated `MediaControlsDecorator` to handle back key. 
When the back key is pressed, 
- It should close the media controls, if more components are NOT showing
- It should transition back to playback controls from more components, if more components are showing
Also updated the documentation to reflect recent changes in `VideoPlayer` and `MediaControls`
In cases back keys are handled either by the `MediaControls` or `VideoPlayer`, the event will stop propagating. This was intentional for two reasons:
1. Since the states being managed for two cases are separated in MediaControls and VideoPlayer (i.e. visibility of MediaControls is managed by …

ENYO-5255: Handle back key in MediaControls

---

packages/ui/FloatingLayer/FloatingLayer.js

`FloatingLayer` stops every cancel event even if not handled (see #1666). Changed to forward onDismiss and stop propagation only if it is handled. 

ENYO-5299: Forward onDismiss and stop propagation only if defined

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scroller/Scroller.js

Scroller would not properly scroll to last focused item while the scroller was still animating.
The logic to calculate scroll top was getting stuck on the first condition, which should be a fall back condition. So we moved it to the bottom so focus will try to focus above or below first then fallback to the top scroll position.
ENYO-5234
Enact-DCO-1.0-Signed-off-by: Derek Tor (derek.tor@lge.com)

ENYO-5234: Fix Scroller's logic for calculating focus scrollTop

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scroller/Scroller.js

`moonstone/Scroller` was not passing a container id to spotlight when attempting to determine the next spottable by position. As a result, spotlight was ignoring the spottables that were out of bounds and selecting a different, in bounds, target.
Update `moonstone/Scroller.scrollToNextPage` to access `spotlightId` instead of `containerId` which is the correct object member passed to the function.

ENYO-5231: Fix scrolling by page down at Scroller bounds

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/VideoPlayer.js

When video loads, `duration`'s default value is `NaN` until it receives the `durationchange` event. It's possible for the user to click on slider while source hasn't been loaded properly (i.e. duration is `NaN`), and video player will throw an error trying to `seek()` to the poistion. 
Proposing to disable MediaSlider when the video source is unavailable.
While adding a check in `seek` function for `isNaN(duration)` is sufficient for the fix, it seemed awkward how the slider can be selected while the source is unavailable. Since this change introduces a UX change, I am open for discussion and won't push too hard on the change if others have concerns with it.
Enact-DCO-1.0-Signed-off-by: Stephen Choi …

ENYO-5282: Disable MediaSlider if the source is unavailable

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/MediaSliderDecorator.js

Seeking in 5-way select does not work. Fixed by adding back `keyup` handler in `MediaSliderDecorator`.
ref: #1662

ENYO-5313: Fix seeking in 5-way mode

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/VideoPlayer.js

VideoPlayer's title and info section should not hide when more components are shown. Fixed the condition for resetting the timer when showing more state changes.

ENYO-5314: Fix to not hide title and info when showing more components

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/VideoPlayer.js

Thumbnail in `MediaSlider` should only appear when it's focused. However, the thumbnail appears even if it's not focused while playing. 
`feedbackVisible` and `feebackIconVisible` states were not properly reset when the slider loses focus. Plus, these states need to be reset when controls appear and disappear.

ENYO-5315: Fix to show thumbnail only when focused on slider

---

packages/moonstone/CHANGELOG.md
packages/moonstone/IncrementSlider/IncrementSlider.js

We changed the tooltip approach for slider and progress bar but forgot to remove the `children` prop from `IncrementSlider`. It didn't function so it's only a documentation change.
Remove `children` prop from docs and forwarded to `Slider`

ENYO-5312: Remove unsupported children prop from IncrementSlider

---

packages/ui/CHANGELOG.md
packages/ui/FloatingLayer/FloatingLayer.js

If `FloatingLayer` is `open`ed at mounting time, it does not render correctly. More specifically, the `this.context.getFloatingLayer()` would not be available until it has been mounted, which in turn will fail to create a node to attach to the `floatingLayer` DOM tree.
I believe we haven't run into the issue as rerendering of the parent component usually resolves the problem. (e.g. `View`, animated `Popup`, etc.)
Created a state `nodeRendered` so that `FloatingLayer` only renders the children when it is inserted into DOM tree.

ENYO-5293: Fix FloatingLayer to render if already opened at mounting time

---

packages/spotlight/CHANGELOG.md
packages/spotlight/src/navigate.js

Spotlight sometimes fails to select the expected "most natural" spottable element when using 5-way. We adjusted the spotlight partitions and priorities in #1495. That fix appears to be ever-so-slightly heavy-handed in its execution - as there are rare cases where 5-way does not perform as expected after that change.
When pressing a 5-way directional key, spotlight calculates where the "next" element is located on a 9-tile grid location, relative to the currently focused element (top-left, top-center, top-right, middle-left, etc). The correct grid location of "next" (when not an internal group) should be based on an additional factors we aren't taking into consideration at the time - 5-way direction pressed. The "next" element could actually live in multiple grid locations. We are able to …

ENYO-5151: Adjust Spotlight Partitions/Priorities

---

packages/sampler/stories/moonstone-stories/MediaOverlay.js

There's no proper way to see placeholder in `MediaOverlay` sampler. Resolved by adding bad image source in one of the options in `imageOverlay` knob

ENYO-5320: Add bad image source for testing placeholder

---

packages/webos/CHANGELOG.md
packages/webos/speech/readAlert.js

`readAlert` response time suffered because it was checking on the audio guidance state every time.
Subscribe to changes in audio guidance so we can use a module-scoped variable to check state rather than checking settings every time.

ENYO-5029: Fix readAlert to subscribe to audio guidance changes

---

packages/spotlight/CHANGELOG.md
packages/spotlight/Spottable/Spottable.js

Spottable components introduced odd scrolling behaviors in ScrollableNative due to built-in scroll on focus behaviors for the browser. On webOS, this can be prevented with the custom {{data-preventscrollonfocus}} attribute until the browser is updated to support the FocusOptions arg to `element.focus()`.
Added the `data-preventscrollonfocus` to spottable but included it before the spread so that it can be overridden by applications. Given the scope of the change and that there is no clear way to describe this API in a cross-platform manner, I've left it off the prop types and public documentation. I'm not …

ENYO-5217: Fix Spottable to prevent scroll on focus on webOS

---

packages/ui/FloatingLayer/FloatingLayer.js

A recent change (#1688) in `FloatingLayer` has adopted the recommendation of react portals, and added `removeChild` in `componentWillUnmount`. However, `removeChild` should be guarded against `null`. 

ENYO-5322: Fix floatingLayer unmount condition

---

packages/sampler/CHANGELOG.md
packages/sampler/stories/qa-stories/Slider.js

Fixed run-time error in 'qa-sampler/Slider'.
`data` prop of `moonstone/VirtualList` is deprecated, and item render function which is passed to a list as `itemRenderer` should fetch data not from arguments but from in-app code.
Fixed `itemRenderer` to refer to own `items` variable instead of deprecated `data` prop.
PLAT-60211

PLAT-60211: Fixed qa-sampler slider runtime error

---

packages/moonstone/CHANGELOG.md
packages/moonstone/TooltipDecorator/TooltipDecorator.js
packages/ui/CHANGELOG.md
packages/ui/FloatingLayer/index.js

`TooltipDecorator` assumes that it only appears on focus and disappears on blur. However, `ui/FloatingLayer `'s `context.closeAllFloatingLayers()` function expects all the layers to be closed by calling `onDismiss`. Fixed to handle `onDismiss` event in `TooltipDecorator` to hide tooltip when the event has been received.

ENYO-5329: Fix TooltipDecorator to hide tooltip on onDismiss

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/MediaControls.js
packages/moonstone/VideoPlayer/VideoPlayer.js

Attaching key event handlers to `document` for media control is not desirable and we need to confine the scope of handling to the player. 
~Suggest passing down the player node to `MediaControls` and attach key event handlers to it.~
Suggest handling key down event when current focus is in `VideoPlayer` 

ENYO-5268: Fix MediaControls to only handle directional events when player has focus

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Popup/Popup.js
packages/ui/CHANGELOG.md
packages/ui/FloatingLayer/FloatingLayer.js

When Popup is open by default, it unsuccessfully tries to spot its contents on mount before it was even rendered to FloatingLayer.
Ryan:
* the change in FloatingLayer to not fire `onOpen` on mount and instead only from `componentDidUpdate` when the child node has rendered
* the addition of `spotPopupContent` to the `onOpen` callback in Popup
ENYO-5333

ENYO-5333: Popup spot content correctly on mount

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/VideoPlayer.js

Apps want to disable playback controls until it's playable. Changed `this.state.sourceUnavailable`'s default value to `true` which will be updated to `false` only when there's enough data to play. Note that this is equivalent to `oncanplaythrough` event condition which means we can handle the event instead of managing the condition at the component level, but given that we allow custom media components, I chose not to expand the required events for `mediaComponents.
Some clarifications:
- `loading` state in `VideoPlayer` not only represents the initial loading of the video, but also anytime the video doesn't have enough content to play. IOW, buffering.
- The app only wants to disable playback controls during the …

PLAT-54548: Disable VideoPlayer playback controls until it's playable

---

CHANGELOG.md
packages/moonstone/CHANGELOG.md
packages/moonstone/EditableIntegerPicker/EditableIntegerPicker.js
packages/moonstone/EditableIntegerPicker/tests/EditableIntegerPicker-specs.js
packages/moonstone/Picker/Picker.js
packages/moonstone/Picker/tests/Picker-specs.js
packages/moonstone/RangePicker/RangePicker.js
packages/moonstone/RangePicker/tests/RangePicker-specs.js
packages/moonstone/internal/Picker/Picker.js
packages/moonstone/internal/Picker/SpottablePicker.js

* Picker, when joined, was spottable even with no children.
* Refactored `SpottablePicker` to be applied on `internal/Picker` directly.
* Updated `moonstone/Picker` to compute disabled property accounting to `>1` children.
* Updated `moonstone/EditibleIntegerPicker`, and `moonstone/RangePicker` to compute disabled property according to single item range.

ENYO-4947:  Ensure Picker disables when containing 1 or no items

---

.travis.yml

* Currently not using Travis cache support and pulling fresh modules from NPM everytime.
* Cache NPM's cache directory to improve speed and performance of `npm install`, as well as reduce out number of downloads from NPM servers.
* On a test run, It reduced Enact CLI install time from 78s down to 25s.

Updated Travis with cached NPM cache

---

CHANGELOG.md
packages/ui/CHANGELOG.md
packages/ui/VirtualList/VirtualListBase.js

Due to `data-preventscrollonfocus` is handled by `Spottable`, we can remove adding logic from `VirtualList`.
Remove it!
ENYO-5346
ENYO-5217
Enact-DCO-1.0-Signed-off-by: Yeram Choi (yeram.choi@lge.com)

ENYO-5346: Fix VirtualList to allow scrollingon focus on webOS

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/ScrollButtons.js

The scrollbar button in VirtualList moves a previous or next page when releasing a page up or down key. It should move when pressing the key.
I handles page up and down keys when receiving `onKeyDown` instead of `onKeyUp`.
- `onKeyDown`, `onMouseDown`, and `onDown` 
The events are used in the ScrollButton. There is no reason to use more than one event. So all code excepting navigating via page up/down keys moves to the `onDown` event handlers.
- Renamed event …

PLAT-53458: ScrollButton to move a previous or next page when pressing a page up or down key

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/Video.js

Video player was going into an infinite loop when changing the source, but the preload source stayed the same.
Added a guard to stop `componentDidUpdate` from setting state indefinitely 
ENYO-5351
Enact-DCO-1.0-Signed-off-by: Derek Tor (derek.tor@lge.com)

ENYO-5351: Fix Video infinite state loop when only updating the primary source

---

CHANGELOG.md
packages/spotlight/CHANGELOG.md
packages/spotlight/Spottable/Spottable.js

Stuttering still occurs with `data-preventscrollonfocus` property.
It's not enough to just exist `data-preventscrollonfocus` attribute on dom to fix issue.
So I added `true` value on it to be handled by web engine correctly.
ENYO-5217
PLAT-43386
Enact-DCO-1.0-Signed-off-by: Yeram Choi (yeram.choi@lge.com)

ENYO-5217: add "true" string to data-preventscrollonfocus property

---

packages/moonstone/ExpandablePicker/ExpandablePicker.js
packages/moonstone/IncrementSlider/IncrementSlider.js
packages/moonstone/internal/Picker/Picker.js

When same component is used on one screen,
data-webos-voice-group-label has to declared to each IconButton.

PLAT-61063: Delegate voice group label to IconButton

---

packages/sampler/.storybook/webos-meta/appinfo.json

Add the disableBackHistoryAPI flag to the appinfo.json of Enact sampler
We expect popup close when pressing back key but App goes history back without this flag
PLAT-61040

PLAT-61040: (release/1.x branch) Add disableBackHistoryAPI with `true` option to the appinfo.json of sampler

---

packages/core/util/util.js
packages/i18n/$L/$L.js
packages/i18n/I18nDecorator/I18nDecorator.js
packages/i18n/I18nDecorator/getI18nClasses.js
packages/i18n/README.md
packages/i18n/Uppercase/Uppercase.js
packages/i18n/docs/index.md
packages/i18n/docs/updating-locale.md
packages/i18n/util/util.js
packages/moonstone/MoonstoneDecorator/I18nFontDecorator.js
packages/moonstone/VideoPlayer/VideoPlayer.js
packages/moonstone/VideoPlayer/util.js
packages/spotlight/src/container.js
packages/ui/resolution/ResolutionDecorator.js

Update `i18n` documentation.
A couple of things I noticed in our current doc (http://enactjs.com/docs/modules/i18n/$L/):
1. `util` module is not shown. I'm assuming this module is public, here. Though our recommendation is to use `i18nDecorator` and `Uppercase` HOC over using `isRTLText` or all the casing functions, it seems reasonable to make it public IMO. I'm open for debate on this.
2. `docs/iLib` and `docs/updateLocale` link is hard to find
3. There are mentions of `moonstone` in `docs/index.md` and `update-locale.md`. I wonder if these need to be modified so that it shows the example of using in non-moonstone context.

PLAT-61277: Update i18n docs

---

packages/sampler/stories/moonstone-stories/MediaOverlay.js
packages/sampler/stories/moonstone-stories/VideoPlayer.js

The knobs for video sources in `VideoPlayer` and `MediaOverlay` wasn't updated to the format needed to work with `enact-knobs`. Updated the knobs to properly show video titles and properly plug in the correct sources.
ENYO-5362

ENYO-5362: Fix sampler knobs for VideoPlayer and MediaOverlay

---

packages/moonstone/CHANGELOG.md
packages/moonstone/ProgressBar/ProgressBar.js

Warning logs are displayed in console when using `highlighted` prop in `ProgressBar`.
I deleted `highlighted` prop in render function to not pass that to div node.
ENYO-5359
Enact-DCO-1.0-Signed-off-by: Sangwook Lee (sangwook1203.lee@lge.com)

ENYO-5359: ProgressBar: warning is displayed in console for `highlighted` prop

---

packages/moonstone/VideoPlayer/MediaControls.js
packages/sampler/stories/moonstone-stories/VideoPlayer.js

Add `moreButtonColor` knob to `VideoPlayer` sample
Not excited about adding `color` prop in `onlyUpdateForKeys()` for `MediaButton`. In a normal use case, no developer would ever change that unless they want to confuse the hell out of the user. I wonder if there's a way we can configure that only for the sampler context?

PLAT-61706: Add moreButtonColor knob to VideoPlayer sample

---

packages/moonstone/CHANGELOG.md
packages/moonstone/TooltipDecorator/TooltipDecorator.js

`TooltipDecorator` always re-renders (to hide the tooltip) when losing focus, even when a tooltip is not yet visible.
We should check that the `showing` state of `TooltipDecorator` is `true` before setting it to `false`. 

ENYO-5378: Fix TooltipDecorator to prevent unnecessary renders

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Divider/Divider.less
packages/moonstone/styles/variables.less

Divider changes in height when switching locales
Set `Divider` to a fixed height that can accommodate even the tallest glyphs in any locale.

ENYO-5162: Divider now always uses a fixed height

---

packages/moonstone/CHANGELOG.md
packages/moonstone/MoonstoneDecorator/MoonstoneDecorator.js

The `.enact-fit` class is currently a required addition to `MoonstoneDecorator`. It means that if Moonstone is used in a normal DOM node, it takes up no space, so layout does not flow around it as one would expect.
This change will give consumers an option to exclude the `.enact-fit` class which, by default expects that MoonstoneDecorator will be used in a "full screen" context.
This absolute position breaks some other places. e.g. MoonstonePreview in the docs.

ENYO-5387: Add disableFullscreen config to MoonstoneDecorator

---

packages/sampler/stories/moonstone-stories/Button.js
packages/sampler/stories/qa-stories/Button.js
packages/sampler/stories/qa-stories/CheckboxItem.js
packages/sampler/stories/qa-stories/ContextualPopupDecorator.js
packages/sampler/stories/qa-stories/Divider.js
packages/sampler/stories/qa-stories/ExpandableInput.js
packages/sampler/stories/qa-stories/ExpandableList.js
packages/sampler/stories/qa-stories/Header.js
packages/sampler/stories/qa-stories/Input.js
packages/sampler/stories/qa-stories/Item.js
packages/sampler/stories/qa-stories/Marquee.js
packages/sampler/stories/qa-stories/Picker.js
packages/sampler/stories/qa-stories/Popup.js
packages/sampler/stories/qa-stories/ProgressBar.js
packages/sampler/stories/qa-stories/RadioItem.js
packages/sampler/stories/qa-stories/Scroller.js
packages/sampler/stories/qa-stories/SelectableItem.js
packages/sampler/stories/qa-stories/Slider.js
packages/sampler/stories/qa-stories/Spinner.js
packages/sampler/stories/qa-stories/Spotlight.js
packages/sampler/stories/qa-stories/SwitchItem.js
packages/sampler/stories/qa-stories/ToggleButton.js
packages/sampler/stories/qa-stories/Touchable.js
packages/sampler/stories/qa-stories/VideoPlayer.js
packages/sampler/stories/qa-stories/VirtualGridList.js
packages/sampler/stories/qa-stories/VirtualList.js

Update QA Sampler knobs and fix `Button`'s `minWidth` knob to work as expected.
`Button`'s `minWidth` is the only prop that is `true` by default so we want to hide `minWidth` in the Storybook JSX by default, but show `minWidth={false}`. As a result, we have this for `minWidth` knob: `storybookBoolean('minWidth', true) ? void 0 : false`, where `void 0` hides the prop when `true`.
PLAT-61006

PLAT-61006: QA-Sampler - Update Knobs

---

packages/moonstone/CHANGELOG.md
packages/moonstone/ContextualPopupDecorator/ContextualPopupDecorator.js

`moonstone/ContextualPopup` may need to update its position if the position or dimensions of the activator or popup updates. Unfortunately, `moonstone/ContextualPopupDecorator` is not suited for monitoring those states. We can think about different ways of handling positioing so that it always positions relative to the activator and the window. Howver, given the complexity and time required for the suggested change, we choose to provide an imperative API for developers to call `positionContextualPopup` method to adjust positions if needed.
See also: #1717 

ENYO-5338: Add positionContextualPopup method

---

packages/moonstone/CHANGELOG.md
packages/moonstone/TooltipDecorator/TooltipDecorator.js

`TooltipDecorator`'s `<FloatingLayerBase>` would incorrectly dismiss the tooltip in certain cases.
Adding `noAutoDismiss` corrects the behavior.
ENYO-5396
Enact-DCO-1.0-Signed-off-by: Dave Freeman (dave.freeman@lge.com)

ENYO-5396: Fix TooltipDecorator to remain visible when window is clicked

---

packages/sampler/src/enact-knobs/select.js

Storybook knob is returning a string `'null'` when given `null`. Change `null` values to empty strings for select knobs that takes null values.
ENYO-5397

ENYO-5397: Sampler - Null select knob fix

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js
packages/moonstone/VirtualList/VirtualListBase.js

If pressing a page up or down key in pointer mode in VirtualList or Scroller, the key is ignored
We misunderstood the Spotlight requirement, then we ignored key events in pointer mode. So we removed the guard ignoring it and focus an item after changing from pointer mode to 5 way key mode.
There is the known issue that Scroller shuttles when pressing page up/down key. We'll fix it in PLAT-62228
PLAT-61242

PLAT-61242: VirtualList/Scroller: Handle a page up or down key in pointer mode

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/ScrollButtons.js
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js

Even though pressing up/down/left/right keys in the ScrollButton when `focusableScrollbar` is false, the ScrollButton keep get focus.
If there is any spottable component to the direction of the key, give it focus. If not, give a content focus.
The expected result with my PR is...
Step
1. Launch http://nebula.lgsvl.com/enyojs/enact-sampler/develop/
2. Select VirtualList
3. Wheel a little bit
- Hover the previous ScrollButton, then press a 'right' key.
Expected result is that the VirtualList item gets focus.
- Hover the previous ScrollButton, then press a 'left' key.
Expected result is that the VirtualList …

PLAT-61241: Handle direction keys properly over ScrollButtons when `focusableScrollbar` is false

---

packages/moonstone/ContextualPopupDecorator/ContextualPopupDecorator.js
packages/moonstone/DaySelector/DaySelectorDecorator.js

Limit voice control area using by data-webos-voice-exclusive attribute

PLAT-62147: Limit voice control area of ContexturePopup

---

packages/sampler/CHANGELOG.md
packages/sampler/src/addons.js
packages/sampler/src/webos-fix.js

* A recent change to the browser userAgent parsing/identification package `bowser`, updated to support LG webOS userAgent. https://github.com/lancedikson/bowser/commit/49746c5547d8a0999d8daf5833937ab7413ef576
* In doing so, webOS TVs, signage, and raspberry pi devices are no longer being identified by Chrome version in `inline-style-prefixer` and feature detection has changed. Normally not a big issue, but when coupled with https://github.com/tomkp/react-split-pane/issues/289, it results in the Storybook panel not rendering correctly.
* Patches the `detect` function in `bowser` to re-detect without `Web0S` useragent token on blink-based webOS. This results in getting detected as Chrome 53 correctly on webOS, and allowing expected feature mapping.
* Can be removed once …

ENYO-5399: Workaround sampler browser detection for webOS

---

packages/moonstone/internal/Picker/Picker.js
packages/moonstone/internal/Picker/PickerButton.js

When joined option is activated in Picker,
voice control realted attribute is need.

PLAT-62171: Support voice control to joined picker

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Spinner/Spinner.js

Spotlight still shows when spinner is showing and it is movable.
Blur spotlight to when spinner is up. 
ENYO-5393
Enact-DCO-1.0-Signed-off-by: Derek Tor <derek.tor@lge.com>

ENYO-5393 - Added spotlight blur when spinner is launched

---

packages/moonstone/Spinner/Spinner.js

If spotlight isn't set when a Spinner is unmounted, the application will generate a runtime error.
Check for existence of a focused element before blurring

Fix Spinner to check existence of focused element before blurring

---

packages/moonstone/TooltipDecorator/TooltipDecorator.js

`rtl` wasn't removed from the DOM in `TooltipDecorator`. Introduced by #1767 within 2.0.0-rc.1
Remove the prop in `render()`

ENYO-5410: Fix TooltipDecorator to remove rtl prop from DOM

---

packages/sampler/stories/moonstone-stories/IncrementSlider.js
packages/sampler/stories/moonstone-stories/ProgressBar.js
packages/sampler/stories/moonstone-stories/Slider.js
packages/sampler/stories/qa-stories/ContextualPopupDecorator.js
packages/sampler/stories/qa-stories/ExpandableList.js

Setup knobs correctly for the components that have two groups of knobs and fix other things that were missed by #1754 
Fixes: `ContextualPopup` QA, `ExpandableList` QA, `Slider`, `IncrementSlider`, and `ProgressBar` samples.
ENYO-5413

ENYO-5413: Fix errors in Storybook enact-knobs usage

---

packages/sampler/stories/qa-stories/Scroller.js

We need the way to check if a `Scroller` supports `data-spotlight-container-disabled` prop well.
I added `data-spotlight-container-disabled` knob in Scroller qa-sampler
PLAT-62334

PLAT-62334:  Add data-spotlight-container-disabled knob in Scroller qa-sampler

---

packages/moonstone/CHANGELOG.md
packages/moonstone/ProgressBar/ProgressBarTooltip.js

Warning logs are displayed in console when using `rtl` prop in `ProgressBarTooltip`.
I deleted `rtl` prop in render function to not pass that to `Tooltip` node.
ENYO-5414
Enact-DCO-1.0-Signed-off-by: Sangwook Lee (sangwook1203.lee@lge.com)

ENYO-5414: ProgressBarTooltip: warning is displayed in console for `rtl` prop

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/ScrollButtons.js

We called native event's stopPropagation function incorrectly. So we could not stop to propagate a react synthetic event.
To stop to propagate a react synthetic event, we call react event's stopPropagation function.
`ev.preventDefault();` was useless. So I removed it.
ENYO-5415

ENYO-5415: Fix to call stopPropagation() properly

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VirtualList/VirtualListBase.js

When in pointer mode, pressing a 5-way directional key (switching from pointer-mode to 5-way mode) while a `VirtualList` a) is using an `isItemDisabled` function prop and b) contains a currently focused item, focus will:
- not change on Chrome and is unable to switch into 5-way mode, even with repeated 5-way directional presses
- not change initially on TV, but will only change with successive 5-way directional presses
There is some logic in the `VirtualList` internal method `jumpToSpottableItem` that is not called or used unless the instance is using a `isItemDisabled` prop. That logic will request focus to be changed to the "next" list item. However, since this method is being called via an internal `keydown` event (and propagation will be stopped anyway), spotlight will be unable to …

PLAT-58640: Fix VirtualList focus behavior when entering 5way mode

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js

… event
Flick events emitted in `Scrollable` can cause the spotlight container within to become stuck in a "disabled" state, making it impossible to set focus to components within the `Scroller`.
Flick events in `Scrollable` immediately disable the container, relying on its own scroller `stop` method to re-enable the container when the scrolling (or "flicked") animation comes to an end. When disabling the container, `Scrollable` was not taking into account whether or not its contents can actually scroll or not. If the contents cannot scroll, then the `stop` method is not called, thus can never re-enable the container.
Before disabling the container, we should check to see the `direction` of the flick event and whether or not we can scroll in that direction.
Enact-DCO-1.1-Signed-off-by: …

PLAT-62474: Fix spotlight in Scrollable after flick

---

packages/moonstone/CHANGELOG.md
packages/moonstone/internal/Picker/Picker.js

When using 5-way to navigate between buttons in a non-joined `Picker` component, certain layouts can cause focus to change to other outside elements, rather than the intended alternate `Picker` button. 
Spotlight attempts to set focus to the natural "next" target based on the direction pressed. The targets gaining focus here are generally expected, however when pressing a 5-way directional key towards an opposing `Picker` button, it is always assumed that the other button should gain focus.
Since we handle the `Picker`'s internal button `keydown` events and have access to the spottables, we can decide during `keydown` when to prevent default spotlight behavior and set focus elsewhere, if needed.

ENYO-5405: Fix Picker 5-way focus behavior

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/FeedbackTooltip.js
packages/moonstone/VideoPlayer/VideoPlayer.js

Feedback tooltip should display only time when hovering out from slider while playing. Currently, it hides the tooltip.
We do not have a boolean condition for showing feedback icon as "play" relies on "idle", "focus", and "blur" conditions to display either both icon and time or just time in the tooltip.
Replaced `noFeedback` prop with `action` prop in `FeedbackTooltip` to handle the state.

ENYO-5356: Fix Feedback tooltip showing condition

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js
packages/moonstone/VirtualList/VirtualListBase.js

Last focus index of `VirtualList` was not remembered when focused by mouse
Extract the index when focusing an item in a `VirtualList` with mouse
I renamed an internal API used by `Scrollable`/`ScrollableNative`.
ENYO-5432

ENYO-5432: Fix restoring focus in moonstone/VirtualList

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/ScrollButtons.js

Fixed a bug that a list or a scroller does not scroll until a user releases the button if a user holds down a paging control button right after pressing the opposite paging control button.
After #1570, a focus does not move to the opposite paired button but it stays on the current button even if the button is disabled by scrolling. This bug occurs by old code to prevent scrolling from `holdpulse` events when a focus moved to the opposite button during holding down.
So, removed the old code.
PLAT-62418

PLAT-62418: Fixed to scroll properly when holding down paging control buttons

---

packages/spotlight/CHANGELOG.md
packages/spotlight/src/spotlight.js

Fix focus disappearing issue relates to pointerMode
At least calling `notifyKeyDown` when keydown even if in spotlight pause mode.
ENYO-5457

ENYO-5457: Spotlight: focus disappears when spinner is unmounted

---

packages/moonstone/CHANGELOG.md
packages/moonstone/ExpandableItem/ExpandableSpotlightDecorator.js
packages/spotlight/CHANGELOG.md

When switching from pointer mode to 5-way mode after an expandable
with `closeOnSelect` collapsed it was possible for spotlight to remain
on the hidden contents of the expandable.
Blur the hidden item when in pointer mode.
I removed an old test that would unconditionally try to spotlight the header
when in pointer mode and closing.  I believe the current solution works
better than what the previous code was …

ENYO-5454 - Fix closeOnSelect spotlight action

---

packages/ui/Scrollable/Scrollable.js
packages/ui/Scrollable/ScrollableNative.js

ui/Scrollable.componentDidUpdate tried to restore scroll position and focus, then this.scrollToInfo is equal to `null`.
But moonstone/Scrollable.componentDidUpdate also tried to sync scroll position if this.scrollToInfo is equal to `null`.
So two logics conflicted, then the VirtualList worked incorrectly.
For the case to restore scroll position, we don't need to sync scroll position in moonstone/Scrollable. To do it, I deferred to reset this.scrollToInfo to `null`. …

ENYO-5442: Defer to reset Scrollable restore flag

---

packages/moonstone/CHANGELOG.md
packages/moonstone/styles/colors-light.less
packages/moonstone/styles/colors.less

Overscroll effects are not recognizable by eye due to the color of the effect is as same as our focus effect color.
Changed the overscroll effect color to bright gray (almost white) for a dark theme and dark gray for a light theme.
ENYO-5417

ENYO-5417: Changed overscroll color more recognizable on the focused element

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/ScrollButtons.js
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js
packages/moonstone/VirtualList/VirtualListBase.js

When pressing a page up or down key over the item in a VirtualList with a pointer mode, VirtualList could not move focus properly.
VirtualList called Spotlight.focus(). But the VirtualList could not move focus because it was in a pointer mode.
As we did in a VirtualList with the #1778, I forced to call `Spotlight.setPointerMode(false) ` when pressing a key.
When pressing a 4 direction key over the page control in a VirtualList with a pointer mode to move another …

PLAT-62228: Set a 5way key mode when pressing a key to focus an item

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js
packages/moonstone/Scroller/Scroller.js
packages/moonstone/VirtualList/VirtualListBase.js

Scroller scrolls differently from VirtualList via page up or down key if it has disabled items.
1. Find spottable item in viewport
2. Find a spottable item in the next page
3. Find a spottable item in the whole content to the key direction
VirtualList and Scroller support page up and down key navigation when they scrolls vertically. So I removed the code to scroll horizontally via page up/down keys in the VirtualList.
ENYO-5419 …

ENYO-5419: Sync page up/down navigation spec between VirtualList and Scroller

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/MediaControls.js
packages/moonstone/VideoPlayer/VideoPlayer.js

- Fixed not to read out what is not needed when panel disappears after clicking more button of Videoplayer
- Fixed an order of information(Video information + focused button) read after clicking a more button.
- Add `this.props.visible` as a condition to read more button.
- Change a role from `alert` to `region`.
ENYO-5455

ENYO-5455: Fix more button audio guidance in VideoPlayer

---

packages/sampler/stories/qa-stories/Marquee.js

Add `forceDirection` knob to Marquee's QA-sampler
PLAT-61006

PLAT-61006: QA-Sampler add forceDirection knob to Marquee

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Image/Image.js
packages/ui/CHANGELOG.md
packages/ui/Scrollable/Scrollable.js

Certain elements (selected text, images, links) are draggable by default in the web platform. When dragging on those within a scroller, the scroller did not function correctly (at least for scrolling by focus) because the scroller was stuck in "drag" mode.
* Only handle Touchable's synthetic drag events in Scrollable
* Prevent dragging for `moonstone/Image` to minimize future exposure

ENYO-5489: Fix Scrollable to ignore native drag events

---

packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js
packages/moonstone/VirtualList/VirtualListBase.js
packages/ui/Scrollable/Scrollable.js
packages/ui/Scrollable/ScrollableNative.js

1. The patch for ENYO-5442: Needed to remove `setTimeout` if possible and created a new patch
2. The patches for ENYO-3984 and ENYO-5339:  We found some unnecessary code while creating several patches (`moonstone/Scrollable.componentDidUpdate()` is not needed anymore)
1. The patch for ENYO-5442
: `this.isScrolledByJump` variable could not get a chance to be `false`. Then the bug in ENYO-5442 was reproduced. I fixed it to set `this.isScrolledByJump` variable to `false` when receiving a key event
2. The patches for ENYO-3984 and ENYO-5339
- Removed `moonstone/Scrollable.componentDidUpdate()` because we …

PLAT-63668: Revise Scrollable-related patches

---

packages/core/kind/kind.js
packages/core/kind/tests/kind-specs.js
packages/moonstone/Button/Button.js
packages/moonstone/Icon/Icon.js
packages/moonstone/IconButton/IconButton.js
packages/ui/Button/Button.js
packages/ui/IconButton/IconButton.js
packages/ui/Slottable/tests/Slottable-specs.js

On low powered devices, the overhead of component layers add up and result in a material performance degradation.
While we can eliminate layers in places, it's beneficial to be able to "inline" functional components, particularly in the `ui` layer, in the themes to reduce layers. This PR adds a currently private static `inline()` method to components created with `core/kind` which can be called to inline the contents of the component into the host rather than introducing another component boundary within React.

PLAT-62487: Add inline support to kinds

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js

In case of RTL, scroll option has to changed oppositely
https://jira2.lgsvl.com/browse/ENYO-5506

ENYO-5506: Fix scrolling by voice control in RTL locales

---

packages/moonstone/Button/Button.js

Removes deprecation warnings added by #1712

Remove deprecation warning for Button tooltip props

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js
packages/moonstone/Scroller/Scroller.js

When pressing a page down key over the last visible item in the Scroller, the Scroller jumps more than one page.
Fix to go to next page properly via page up/down keys in Scroller.
ENYO-5508

ENYO-5508: Go to next page properly via page up/down keys in Scroller

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Dialog/Dialog.js

Fixed the reading order of Dialog's prop `buttons` and `children`
- AS-IS
- Title + TitleBelow + **Buttons + Children** + Focused button
- TO-BE
- Title + TitleBelow + **Children + Buttons** + Focused button
- Set a unique id(Using IdProvider) for each props(title, titleBelow, buttons, and children)
- Set the id to aria-labelledby according to reading order
ENYO-5493

ENYO-5493: Fix Dialog read order

---

packages/spotlight/CHANGELOG.md
packages/spotlight/src/spotlight.js

When on TV, using pointer-mode to focus an input, then moving the pointer to the VKB results in the VKB hiding.
This is a result of #1826  calling the window `onBlur` event when the pointer leaves the window. Spotlight is attempting to blur the currently-focused control, which is causing the VKB to immediately hide. We prevent this by checking if spotlight is paused or not.
Ideally, this check would be done from within the `onBlur` method directly, however - I'm noticing some inconsistencies in behavior when blurring the window (via VKB or via the remote menu button) then switching pointer-mode status, then re-activating the application. Sometimes some internal vars like `_spotOnWindowFocus` can get into a bad state where the application will not set focus when the window re-gains focus. …

ENYO-5519: dont blur window when pointer leaves while paused

---

packages/sampler/.qa-storybook/config.js
packages/sampler/.storybook/config.js
packages/sampler/src/MoonstoneEnvironment/MoonstoneEnvironment.less
packages/sampler/stories/moonstone-stories/About.js

QA Sampler was imposing the wrong sizes on components in stories.
Develop more specific rules to only target the offending `addon-info` div when it's present.

ENYO-5515: Make story sizing rule selectors more specific

---

packages/moonstone/Image/Image.js
packages/ui/CHANGELOG.md
packages/ui/GridListImageItem/GridListImageItem.js
packages/ui/Image/Image.js

`ui/Image` cannot display placeholder images when `src` is not set.
The `src` prop was marked as required before the implementation of `placeholder`. Since then, we were unable to display placeholders in cases where the source is not yet known. This fix provides a fallback to `placeholder` in those cases, which aids developers when dealing with delayed images. A `warning` is applied, requiring either of the 2 props to be specified, to make up for removing `.isRequired` on the `src` prop-type.

ENYO-5488: ui/Image to require either src or placeholder props

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/Scrollable.js
packages/ui/Scrollable/Scrollable.js

A horizontal Scroller scrolls to unexpected position during 5-way key navigation in RTL mode.
To prevent scrolls originating from focus events, we reset the `scrollLeft` of the Scroller when receiving `onscroll` event. But we did not consider the RTL case. So I update the `scrollLeft` properly based on the scrollbounds and the RTL mode of the Scroller
ENYO-5531

ENYO-5531: Fix not to scroll to wrong position via 5way navigation in RTL languages

---

packages/moonstone/CHANGELOG.md
packages/moonstone/EditableIntegerPicker/EditableIntegerPickerDecorator.js

Enact-DCO-1.0-Signed-off-by: Jeremy Thomas <jeremy.thomas@lge.com>
`EditableIntegerPicker` managed its own pointer-mode, but did so incorrectly. It could set pointer mode incorrectly when restoring/unfreezing spotlight behavior after blurring the `<input />`.
The related (recently-merged) PR https://github.com/enactjs/enact/pull/1812 allows pointer mode to remain accurate while spotlight is paused, thus negating the need for `EditableIntegerPicker` to manage any pointer-mode state.
- While this achieves the intended result, I did notice an unexpected behavior. If the `<input />` has focus while pointer mode is active, pointer mode will not be set to `false` if the pointer hides on TV due to a timeout. This appears to also be the case with `Input` as well, so ... a) as it is not isolated …

ENYO-5463: Fix pointer mode management in EditableIntegerPicker

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Popup/Popup.js
packages/sampler/stories/qa-stories/Popup.js

`moonstone/Popup` components handle focus movement redundantly. 
In `moonstone/Popup` case with two or more buttons, focus is moved twice at one 5way-key input.
In `moonstone/Popup` keydown event handler, it called `Spotlight.move(dir)` without stopPropagation() . So `Spotlight` handle the key event redundantly.
`moonstone/Popup` is fixed to prevent additional key event handling after focus changed using stopPropagation() and preventDefault(). 
And added more button to verify the spotlight operation in Popup story of qa-sampler . …

PLAT-64158: Fix Popup to prevent duplicated 5-way navigation

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/MediaControls.js

In many cases, apps switch to the next video when the media has reached the end.  When switching videos, `VideoPlayer/MediaControls` will be disabled until there's enough data loaded to play. And if it were caused by a jump with the right key down, then there's a chance the key up handle is ignored because key events do not get handled while disabled.
related:  #1713
Reset key down hold loop when `MediaControls` becomes disabled.

ENYO-5496: Reset key down hold when media becomes unavailable

---

packages/ui/LabeledIcon/tests/LabeledIcon-specs.js

LabeledIcon tests were warning for an invalid prop type which will fail when our mocha test util is updated.
Fix the test!

PLAT-62882: Fix LabeledIcon test to pass proptype

---

packages/moonstone/CHANGELOG.md
packages/moonstone/LabeledIcon/LabeledIcon.less

Labels in the horizontal arrangements appear off-center due to unbalanced margin around the `Icon` component. "Above" is particularly broken as it had extra space below but none between the label and the icon.
Built a comprehensive set of margin rules for all scenarios so no margin is applied when there shouldn't be, and correct margins are added always. This means that the label is always aligned and the external styling rules (application of margin) always behave in a predictable manner.

ENYO-5536: Fix ui/LabeledIcon alignment and spacing

---

packages/spotlight/CHANGELOG.md
packages/spotlight/src/spotlight.js

Spotlight's pointer mode isn't updated when attempting to switch modes while the VKB is visible (ex: when an input has focus).
While the VKB is visible, spotlight or currently-focused components (ex: `Input`) are unable to receive key events (`keydown`) events. During this time a user can change from pointer to 5-way mode. This prevents spotlight from restoring focus in some cases after dismissing the VKB, since spotlight falsely thinks it is still in pointer mode - which prevents programmatic focus changes.
Since we know pointer-mode can change while the VKB is open, we can remedy this issue by setting the platform pointer mode as a response to the webOS event `keyboardStateChange` when the VKB closes.

ENYO-5523: Update pointer mode after hiding VKB

---

CHANGELOG.md
packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js
packages/moonstone/Scroller/Scroller.js

I noticed a disconnect between the original requirement for adding onUpdate and the way in which it was implemented. The requirement surfaced due to a need to scroll a Component (in that case, the entire ExpandableList) into view when that component caused a change in scroll bounds. It appears in the original implementation that we asserted that nearly any update of the component should cause this behavior but discovered that updates introduced upstream (as was described in this ticket) would inadvertently cause scrolling.
The gap in my view is that we didn't verify that the scroll bounds changed before …

ENYO-5480: Fix prevent scrolling on focus in pointer mode

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/VideoPlayer.js
packages/sampler/stories/moonstone-stories/VideoPlayer.js

App wants to hide the media slider when pressing "rew" or "ff" from the remote.
Added a new prop `noMediaSliderFeedback` to disable slider feedback

PLAT-62964: Add prop to control MediaSlider visibility

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/MediaControls.js
packages/moonstone/VideoPlayer/VideoPlayer.js
packages/sampler/stories/moonstone-stories/VideoPlayer.js

There's no way to only disable play/pause button. Added `playPauseButtonDisabled` property in `MediaControlsBase`.
Note that if play/pause button is disabled, spotlight needs to fallback to focus on other spottable item in playback controls. Changed the outer wrapper of `MediaControls` to `SpotlightContainer` with the default spotlight behavior configured to the spec.

ENYO-5511: Add VideoPlayer prop to disable play/pause button

---

packages/moonstone/CHANGELOG.md
packages/moonstone/internal/Picker/Picker.js
packages/moonstone/internal/Picker/PickerButton.js

On TV-only, after a hold event `Picker` can get into a state where selecting a `PickerButton` once can result in the picker value changing multiple times.
This issue appears to be the result of a performance issue on TV (whether through Storybook or specifically-created app) where the `keyup` isn't able to register in time before a `holdPulse` event is able to fire (causing the additional value change). The solution for the time being appears to be delaying the hold event for the `PickerButton` so that `holdPulse` isn't fired before the actual hold event is registered.
This is more of a remedy, as an actual fix would require preventing the TV from getting into the odd state where this issue is observed. However, it isn't obvious to us how this is happening or how to prevent this.

ENYO-5354: Delay PickerButton hold event

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Slider/tests/Slider-specs.js
packages/moonstone/Slider/utils.js

`Slider` can emit an `onChange` event when `value` has not actually changed. The issue is a result of `value` being unset and `Slider` incorrectly checking `value` against `min` before firing the `onChange` event.
Since `value` (when unset) should default to `min`, we need to ensure that is the case when we compare these values in the `isNotMin` method of `Slider/utils`.

ENYO-5551: When comparing Slider value against min, ensure value is set

---

packages/ui/CHANGELOG.md
packages/ui/FloatingLayer/FloatingLayerDecorator.js

In certain circumstances React would warn of missing keys from
the FloatingLayerDecorator.
Add keys to the decorator.
In theory, this should not be required.  This is very low impact, however.
ENYP-5550

Add keys to FloatingLayerDecorator

---

packages/sampler/CHANGELOG.md
packages/sampler/stories/moonstone-stories/VirtualList.js

`moonstone/Item` was used in `ui/VirtualList` sampler.
Replaced `moonstone/Item` with `ui/Item`.
PLAT-64857

PLAT-64857: Replace moonstone/Item with ui/Item in ui/VirtualList sampler

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/VideoPlayer.js

In #1701, we removed activity detection from the global `keydown` handler to allow 5-way down to show pointer controls. The unforseen regression of that was an inability to detect 5-way navigation in floating layers (e.g. ContextualPopup) opened from the media controls. We have a `keypress` handler but that isn't called when focus changes on `keydown` as is often the case for spotlight navigation.
Add back the call to `activityDetected` along with `returnsTrue` to ensure that the subsequent handlers still fire.

ENYO-5560: Fix VideoPlayer to detect activity via keydown

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VirtualList/VirtualListBase.js

Fix `VirtualList` couldn't restore last focused in case of no placeholder scenario
Convert `data-index` to `Number` to be compared correctly
ENYO-5561
https://jsperf.com/number-vs-parseint-vs-plus/24
Enact-DCO-1.0-Signed-off-by: Yeram Choi <yeram.choi@lge.com>

ENYO-5561: Fix VirtualList to restore focus correctly

---

packages/sampler/stories/moonstone-stories/Scroller.js
packages/sampler/stories/moonstone-stories/VirtualGridList.js
packages/sampler/stories/moonstone-stories/VirtualList.js
packages/sampler/stories/qa-stories/Scroller.js
packages/sampler/stories/qa-stories/VirtualList.js

Samples for Scroller use an awkward static height.
Update the samples to use the full height available in the window.
By default, VirtualList, VirtualGridList, and Scroller stretches to fit to a window. So we don't need `width: 100%; height: 100%` style in them. I removed it.
PLAT-64761

PLAT-64761: Full-height Scroller Samples

---

packages/spotlight/CHANGELOG.md
packages/spotlight/SpotlightContainerDecorator/SpotlightContainerDecorator.js

Fix unexpected removing container config when `spotlightId` is changed
Check `this.state.preserveId` to execute `Spotlight.remove()` or `Spotlight.unmount()`
ENYO-5563
Enact-DCO-1.0-Signed-off-by: Yeram Choi <yeram.choi@lge.com>

ENYO-5563: SpotlightContainerDecorator: container config is removed when spotlightId prop is changed

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/OverscrollEffect.less
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js
packages/ui/Scrollable/Scrollable.js
packages/ui/Scrollable/ScrollableNative.js

We have a requirement to show overscroll effect only on wheel input in `moonstone` so far and current our components support various types of inputs including wheel, drag, arrow key, and so on.
So, limited overscroll effects to wheel input only to meet the requirement.
We only need effects on wheel input for `moonstone` for now, but it does not mean that we don't need to support other types of input for future requirements. We also need to be ready for other theme libraries beside `moonstone`.
In this PR, a way to select types of input for overscroll effects is added and `moonstone` supports only wheel …

ENYO-5529: Limited overscroll effects to wheel input only in `moonstone`

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/VideoPlayer.js

`VideoPlayer` does not detect activity when attempting to 5-way navigate from the media slider. Attempts to 5-way left/right or down (when the media controls are available) results in the controls hiding prematurely.
We essentially need to call `this.activityDetected` in cases where attempts to press keys from the slider fails to do so currently. In 2 specific cases activity is correctly detected (when pressing 5-way up and when pressing 5-way down - when media controls are *not* available). In all other cases, we simply need to call `this.activityDetected`.
This regression stems from the change here: https://github.com/enactjs/enact/pull/1890/files#diff-598514a33c478cdac5391092c58009feL1788
I've opted to avoid the potential mess of having to manage multiple keydown handlers from …

ENYO-5571: Fix VideoPlayer activity detection

---

packages/ui/Scrollable/Scrollable.js
packages/ui/Scrollable/ScrollableNative.js

When overscroll is enabled on drag, if a user drags a scroller to one direction and drags to the opposite direction while the effect is displayed by the first dragging, the effect should disappear but it stays.
It was a simply bug of `if` statement. Fixed to handle it properly.
ENYO-5364

 ENYO-5364: Fixed to hide overscroll effect properly on drag

---

packages/ui/Scrollable/ScrollableNative.js

`onScroll` event handler is responsible for updating scroller's scroll thumb position and scroller button disabled state.
Each event handling takes up about ~16ms on TV.
Refactored `onScroll` handler to do less amount of work and used `requestAnimationFrame` to handle UI updates.
The `onScroll` event handler now takes up about ~3ms, and each UI update (which takes about ~10ms) occurs less.

ENYO-5569: Handle less in onScroll event

---

packages/moonstone/Skinnable/Skinnable.js
packages/ui/Skinnable/Skinnable.js

* `@enact/moonstone/Skinnable` is importing and exporting `withSkinnableProps` which was removed with the recent https://github.com/enactjs/enact/pull/1827. This is purely a simple cleanup PR.
* Remove the unused withSkinnableProps import/export.  

Remove unused withSkinnableProps import/export.

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js
packages/moonstone/VirtualList/VirtualListBase.js

When pressing Page Down over the last fully visible item in VirtualList, VirtualList move focus not to the next page but to the next item which is visible partially.
I reduced the spotlight boundary as the `getTargetByDirectionFromPosition` parameter to find fully visible and spottable item in a current page.
In addition, I tried to selected the candidate items among fully visible items in the next page to which VirtualList jumps.
Scrolling horizontally via page …

ENYO-5577: VirtualList> Fix to jump to the next page properly via page down key

---

packages/moonstone/CHANGELOG.md
packages/moonstone/ExpandableItem/ExpandableItem.js

When `ExpandableItem` has a `true` value of `lockBottom` prop and `down` key is pressed on the last item of `ExpandableItem`, a scroller which contains `ExpandableItem` scrolls unexpectedly.
Fixed not to make a scrolling in this case. Since `lockBottom` is `true`, there will be no action.
Edit:
Thanks to @MikyungKim, I found that the issue also happens on `up` key when `ExpandableItem` is located on the top of a viewport of a scroller (regardless `lockBottom` is set or not).
Added the fix for this, too.
A scrolling is a default behavior of web engine by `up` or `down` key. So added `preventDefault()`.
[//]: …

PLAT-64196: Fix unexpected scrolling by 5-way key from inside an ExpandableItem

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scroller/Scroller.js

When focus moves into a spotlight container in a scroller, if the container is larger than the scroller *and* the focused item is close to the top (such that the distance between the top of the container and the bottom of the focused item is less than the height of the scroller), only the focused item is scrolled into view rather than as much of the container as possible.
Adjust the scroll top calculation to scroll more of the container into the view

ENYO-5582: Fix Scroller to scroll container into view

---

packages/ui/CHANGELOG.md
packages/ui/Marquee/Marquee.less

For some reason on TV `flex` doesn't play well with dynamic `position: relative`. It causes overlapping text to be shown.
Stop dynamically setting `position: relative`. We had this in previously, but we changed it because we needed a work around for `ScrollerNative` it turns out we don't need it for `ScrollerNative` to work smoothly.
This seems to work fine, but marquee may notice a minor performance hit since, but it doesn't seem to be noticeable.
ENYO-5554

ENYO-5554: Fix layout of Picker components on webOS

---

packages/moonstone/ProgressBar/ProgressBar.js

We didn't include docs on the `tooltip` prop to inform authors that some props would be passed to a custom component.
This behavior is consistent with many other instances of overriding components so we don't need to change anything but updated docs are warranted.
I didn't include .a changelog for this since it was doc only.

ENYO:5594: Update docs for ProgressBar prop tooltip

---

packages/i18n/locale/locale.js
packages/i18n/src/resBundle.js

* Since https://github.com/enactjs/enact/pull/1800, the location for cached ResBundle changed, breaking the experimental/private/temporary support for cache pre-populating via a window-based object.
* Use `ilib.cache['ResBundle-strings']` location rather than `ResBundle.strings.cache` to correctly be found by iLib and avoid XHR.
* Verified by building/running with Enact Browser against latest iLib.

ENYO-5598: Fix support for pre-populating iLib ResBundle cache.

---

packages/spotlight/CHANGELOG.md
packages/spotlight/Spottable/Spottable.js
packages/spotlight/src/container.js
packages/spotlight/src/spotlight.js

webOS applications using VirtualList were experiencing focus problems when using `isItemDisabled` event when native scrolling wasn't enabled for the app.
Support using the [focusOptions param of the `focus()` API](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus) to suppress scrolling focused elements into view. This PR "connects" the usage of the API with the `overflow` spotlight container config which indicates that the container supports focusable components out of view (e.g. from a scroller). …

ENYO-5579: Prevent browser scrolling components into view on focus

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js
packages/moonstone/VirtualList/VirtualListBase.js
packages/spotlight/src/spotlight.js

`VirtualList` stops `onKeyDown` from propagating so other components can't receive the event. This is done to prevent spotlight from calling focus again on its `onKeyDown`.
Instead of using stopPropagation we can pause spotlight temporarily so we don't get two `focus` calls, but we can still have the event propagate. We pause Spotlight `onKeyDown` and remove it `onKeyUp`.
ENYO-5580

ENYO-5580 - It is impossible to handle up/down keycode when using isItemDisabled in virtualList

---

packages/ui/CHANGELOG.md
packages/ui/GridListImageItem/GridListImageItem.js
packages/ui/GridListImageItem/GridListImageItem.less

`ui/GridListImageItem` was missing `.selected` definition for `publicClassName`. It affected `moonstone/GridListImageItem` to not set `selected` style properly. This is a regression from #1864
Added `.selected` definition to less file. Also cleaned up cruft for setting `caption` and `subCaption` classes as well.

ENYO-5600: Fix GridListImageItem to properly set selected style

---

packages/moonstone/CHANGELOG.md
packages/moonstone/TooltipDecorator/TooltipDecorator.js
packages/sampler/stories/qa/Tooltip.js

Even if length of tooltipText, the position of tooltip is not recalculated.
I added  function to calculate position when text changed.
ENYO-5604

ENYO-5604: Tooltip is not repositioned when text changed

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/ScrollableNative.js
packages/ui/Scrollable/Scrollable.js
packages/ui/Scrollable/ScrollableNative.js

Fixed a bug that the overscroll effect shows only for the first wheel input when repeating wheel inputs. 
Due to the bug of an internal logic, repeating inputs were ignored. Fixed a wrong condition and now it works well.
ENYO-5578

ENYO-5578: Fixed a bug not to show overscroll effect on repeating wheel input

---

packages/moonstone/CHANGELOG.md
packages/moonstone/TooltipDecorator/TooltipDecorator.js
packages/sampler/stories/qa/Tooltip.js

There's the problem when tooltipText is changed to an empty string or changed from an empty string to a string.
I added exception handling for cases where refs don't exist. If there's no ref, that returns.
[ENYO-5616]
[GT-25843]

ENYO-5616: Added exception for cases where refs don't exist

---

packages/ui/CHANGELOG.md
packages/ui/Scrollable/ScrollableNative.js

`ui/ScrollableNative` needs to update scroll buttons when it scrolls. Using `requestAnimationFrame` helped us to increase performance (#1891), but setting `timeout` (i.e. 16ms) will throttle the event, and will not properly use the last input from the event.
Removed `timeout` parameter from the job.
We could retain the throttling part of it to reduce the amount of work to be done while scrolling, and update the scroll buttons after scroll stop event. Note that since the wait time for scroll stop event is 200ms, there's a slight delay in a state change. But maybe it's okay as JS version scroller changes the …

ENYO-5605: Fix ScrollableNative to update scroll buttons

---

packages/ui/Scrollable/Scrollable.js
packages/ui/Scrollable/ScrollableNative.js

We have a requirement to notify a list or a scroller reached the scroll edge. With the existing APIs, an app should keep an eye on the info provided by _onScroll_ callback function and it is not good on the performance aspect.
In this PR, we provide (maybe little limited) alternative solution to provide reaching status by _onScrollStop_ callback to help apps to choose more light method if possible.
_onScrollStop_ callback provides `reachedEdgeInfo` which contains reaching status of `top`, `bottom`, `left`, and `right` edge. …

PLAT-48029: Added reachedEdgeInfo within `onScrollStop` callback

---

packages/ui/CHANGELOG.md
packages/ui/Marquee/MarqueeController.js

In #1301, we added a `Job` to manage cancelling marquee instances in `MarqueeController` to allow synchronized marquees to continue when a stop event (e.g. blurring) was immediately followed by a start event (focusing, pointer enter). As a result, it became possible (either through impeccable timing or sluggishness on lower powered hardware) to blur a synchronized marquee during the restart timer causing the job to be scheduled but then reset by the "complete" trigger before it fires.
* Remove the call to stop the cancel job on "complete"
[//]: # (Are there any …

ENYO-5623: Fix ui/Marquee to stop when blurred during restart timer

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/VideoPlayer.js

handle blur() before setTimeout and live with spotlight blinking issue
Do not merge with PR below. (option 1)
https://github.com/enactjs/enact/pull/1931
Fixed the timing to read out `infoComponents` accessibility value when `moreButton` or `moreButtonColor` is pressed.
I have fixed the timing of reading `infoComponents` temporarily using setTimeout due to an unknown cause.
(The unknown cause is being tracked in the web engine, and a framework-side workaround until web engine fix is identified and implemented.)
ENYO-5612

ENYO-5612: Fix VideoPlayer a11y for infoComponents

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js

We did not support that VirtualList scrolls page by page when any item and any paging control in the VirtualList did not get focus.
If pressing Channel Up or Down keys when any item and any paging control did not get focus, VirtualList scrolls page by page.
I also fixed the following bug.
*Condition*
- the list is at the top position
- the Up Paging Control is disabled
- the cursor is on the gap between items (pointer mode)
- a Channel Down is pressed
*Expected …

ENYO-5504: Scroll page by page via Channel Up / Down keys without focused item

---

packages/moonstone/Scrollable/ScrollButton.js
packages/moonstone/Scrollable/ScrollButtons.js

`Scrollbutton`'s `direction` prop is useless now. We had to remove it when refactoring the `ScrollButton`.
I removed the `direction` prop in the `ScrollButton`.
PLAT-64865

PLAT-64865: Remove `direction` prop in ScrollButton

---

CHANGELOG.md
packages/moonstone/FormCheckbox/FormCheckbox.less
packages/moonstone/FormCheckboxItem/FormCheckboxItem.less
packages/sampler/stories/qa/FormCheckboxItem.js

Spotlight retains when it's disabled by default.
In the case of FormCheckboxItem, FormCheckbox Icon can be focused only.
But, when it's disabled, area that except for icon is focused. The background of the text area should be transparent always.
I fixed to set `background-color` of toggleItem to `transparent` always and to be retained spotlight in `FormCheckbox`. 
[ENYO-5637]

ENYO-5637: Fix FormCheckboxItem style when focused and disabled

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/VideoPlayer.js

Fix playback rate value is shown on the `FeedbackTooltip` in the middle of changing playback
`FeedbackTooltip` has `playbackRate` and `playbackState` props
1) `play`() is called during 4x(or etc) playback
2) `playbackRate` is changed to 2x and then `FeedbackTooltip` is rendered.
3) `playbackState` is changed to 'play' and then `FeedbackTooltip` is rendered.
Despite the presence of `setState` in the `play()` , it is performed synchronously.
as a result, render occur twice
`playbackRate` and `playbackState` must be changed at once for rendering of `FeedbackTooltip`
I think that the simplest way at this time is to do `prevCommand` variable allocation first.

ENYO-5638: Fix VideoPlayer to show correct playback rate feedback on play or pause

---

CHANGELOG.md
packages/moonstone/IncrementSlider/IncrementSlider.js
packages/moonstone/Slider/Slider.js
packages/moonstone/Slider/SliderBehaviorDecorator.js
packages/sampler/stories/qa/IncrementSlider.js

The knob is blurred while dragging. So, it can focus to other components while dragging.
I fixed to pass `dragging` props from `SliderBehaviorDecorator` to `IncrementSlider`.
So, when `dragging` prop is `true`, it's impossible to spotlight to the increment/decrement buttons.
[ENYO-5626]

ENYO-5626: Fix Spottable to respect pause state when it becomes enabled

---

packages/moonstone/VideoPlayer/MediaControls.js
packages/moonstone/VideoPlayer/VideoPlayer.js

If `VideoPlayer` were focused from the outside, the default spotlight logic is ignored and spots to the closest element.
Removed unnecessary config option `enterTo: default-element` from outer container of `MediaControls`. This is okay as `VideoPlayer` explicitly handles the "down" arrow key to focus to `this.mediaControlsSpotlightId` which will eventually focus to `defaultElement` set by the container config.
We may need to look into `SpotlightContainer` behavior …

ENYO-5586: Fix 5-way navigation into VideoPlayer

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Panels/Breadcrumb.js
packages/moonstone/Panels/BreadcrumbDecorator.js
packages/ui/CHANGELOG.md
packages/ui/ViewManager/TransitionGroup.js

The root cause here is the interplay between popup and breadcrumb. Currently, breadcrumb blurs itself when selected to ensure that it isn't focused when the panel transition completes. Popup refocuses its activator (or the last focused component if there isn't an activator or the activator has been unmounted) when closed. Since the breadcrumb is focused when the popup is shown, it's stored as the activator and refocused when the popup closes. If you blur the breadcrumb before opening the popup, it still receives the focus when the popup closes because it was the last focused element. As a result, even though the breadcrumb blurs itself on select, it is refocused by the popup and still has focus when the panel …

ENYO-5635: Fix Panels to blur breadcrumbs on transition

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scroller/Scroller.js

Do not adjust `scrollTop` when nested item is focused
When expandable opens, `calculateScrollTop` is called two times. (expandable -> nested item)
I tried to skip second adjustment because it makes title invisible.
Not sure it's right approach but I'm trying to modify as small as possible
ENYO-5634
Enact-DCO-1.0-Signed-off-by: Yeram Choi yeram.choi@lge.com

ENYO-5634: Fix title of expandable is invisible when expandable opens

---

packages/moonstone/CHANGELOG.md
packages/moonstone/GridListImageItem/GridListImageItem.js

GridListImageItem should be support voice control feature
data-webos-voice-intent='Select' is used as default.
But depending on the app, data-webos-voice-intent can be used another value.
ENYO-5642

ENYO-5642: Add voice control to GridListImageItem

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scroller/Scroller.js

Fixed moonstone/Scroller not to scroll stops when focusing on a child element while scrolling
`setContainerDisabled` function of moonstone/Scroller is not working properly since it set `data-spotlight-container-disabled` to the wrong element.
It seems we did not change the code for finding the spotlight container node inside of the function after we combined spotlight containers.
So, fixed above problem by adding private prop `spotlightId` to get the right node like the same way of VirtualList.
ENYO-5647

ENYO-5647: Fixed Scroller not to scroll stops when focusing on a child element while scrolling

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scroller/Scroller.js

When `ExpandableList` is inside `Scroller` and the focused item is far enough to make the title of `ExpandableList` out of a viewport, `Scroller` scrolls abnormally more than expected by closing `ExpandableList`.
We have two logics inside `Scroller`. The first one is to re-position the scroll position when contents is shortened, the second one is to compensate position when the next focused element is passed up the top of a viewport.
This issue occurs when both logic is performed in a single focus event. We don't actually need to perform the second logic if we already handle the case in the first logic, so …

ENYO-5609: Fix Scroller to set correct position when ExpandableList is closed

---

packages/i18n/I18nDecorator/I18nDecorator.js
packages/ui/CHANGELOG.md
packages/ui/Layout/Cell.js
packages/ui/Layout/Layout.js
packages/ui/Skinnable/Skinnable.js
packages/ui/Transition/Transition.js

A collection of changes are needed to support other work and extend the base components to allow more dynamic usage outside of moonstone.
* `Cell` and `Layout` now accept any type of children, since the `component` that may be set could accept any format of `children`.
* Transition now supports customizable styling via the `css` prop.
* Add `prop` HOC config to `ui/Skinnable` to support passing the effective skin to the wrapped component

PLAT-66183: Add agate-related enhancements

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VirtualList/VirtualListBase.js
packages/spotlight/src/container.js
packages/spotlight/src/navigate.js

`VirtualList` and `VirtualGridList` can experience unexpected results when 5way navigating container items where focus incorrectly changes to a focusable scroll button instead of the next expected item.
PR #1495 added a spotlight change where it added an algorithm that helps decide which "next" element should gain focus. Generally we use a 1px/5px-relative multiplier for straight/oblique elements - where a straight element will be favored over an oblique one unless the oblique one is closer than 5x the amount of the next eligible straight one. This works in most cases, but in `VirtualGridList`, the default spacing between items is 12px. If the scroll buttons are focusable, there are positions the scroller can be in which will cause the scroll button to be favored over the next eligible …

PLAT-64866: Allow configurable nav multipliers for containers

---

CHANGELOG.md
packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/VideoPlayer.js

The spotlight focus stays in control button even if media controls are hidden.
I added exception for checking pointer mode when focus to `controlsHandleAbove`.
ENYO-5648

ENYO-5648: VideoPlayer: focus stays in control button even if hidden

---

packages/moonstone/VideoPlayer/VideoPlayer.js

Hovering a media controls component when they hide would cause focus to be restored to it rather than the video player.
Set the active container to video player when in pointer mode
I omitted a change log since it was an additional fix to a previously reported change.

ENYO-5648: Fix setting focus in VideoPlayer in pointer mode

---

packages/ui/CHANGELOG.md
packages/ui/Touchable/Hold.js

When a hold is cancelled (e.g. by setting a component to disabled) by the `onHold` handler, Touchable will throw an error.
Add a test to determine if the hold is still active before continuing to emit events.

ENYO-5653: Fix Touchable to handle canceled holds correctly

---

CHANGELOG.md
packages/moonstone/CHANGELOG.md
packages/moonstone/DayPicker/DayPicker.js

In current status, aria-label of LabeledItem is updated when check/uncheck sub items of DayPicker.
For this reason, LabeledItem of DayPicker can be selected unexpectedly when try to check/uncheck sub items with voice.
Explicitly declare voice label to LabeledItem
ENYO-5655

ENYO-5655: Add voice label to DayPicker

---

packages/ui/CHANGELOG.md
packages/ui/Marquee/Marquee.less
packages/ui/Marquee/MarqueeBase.js
packages/ui/Marquee/MarqueeDecorator.js

Many composite layers with a scroller impact scroll performance on low powered hardware due to the need to frequently update the layer tree.
Defer promoting the marquee layers to the compositor until shortly before they are needed to reduce the memory consumed and time required to update layer tree.
Fixed - ~Currently, this breaks synchronized marquees but I haven't had a chance to investigate yet.~
Added - ~It also naively skips deferment for `marqueeOn="render"` …

ENYO-5521: Defer promoting marquee composite layers

---

packages/moonstone/Scroller/Scroller.js
packages/spotlight/src/container.js
packages/spotlight/src/spotlight.js

There is a significant performance cost of determining if focus will leave the scroller on every key down.
In order to improve scroll on focus performance of scrollers with many spottable children, this PR adds new (private, unsafe for public use!) spotlight container events to notify containers when focus enters, leaves, or fails to leave them.

ENYO-5524: Add container events for focus changes

---

packages/spotlight/CHANGELOG.md
packages/spotlight/src/spotlight.js

The separate `blur()` and `focus()` calls caused a second style recalculation that impacted performance on rapid focus changes on low powered hardware.
Remove the explicit focus and rely on the platform to manage the blur and focus actions.
This provides the added benefit of correctly populating the `relatedTarget` member of the `focus` and `blur` events to inform consumers of where focus was moving from or to.

ENYO-5524: Change Spotlight to not explicitly blur the currently focused element

---

packages/spotlight/CHANGELOG.md
packages/spotlight/src/container.js
packages/spotlight/src/spotlight.js

#1956 introduced a regression where you could not enter a restricted (overflow/last-focused) container when the last-focused element was outside the view of the overflow container.
The validation we were using was in the wrong location. By returning this value in `getContainerNavigableElements`, we are able to more conveniently/accurately return which elements should gain focus next depending on their container configs. In this case, we check for what priority should be used when entering another container: we should focus last-focused > default > first in-view.

ENYO-5656: Correctly focus last-focused elements when entering restricted containers

---

packages/i18n/CHANGELOG.md
packages/i18n/src/Loader.js

Fix warning log during i18n initailization
Use `this._pathjoin` function when merging paths
I refer code from https://github.com/enactjs/enact/blob/master/packages/i18n/src/Loader.js#L186
I assume `const` is suitable here, but use `let` for now.
ENYO-5668
Enact-DCO-1.0-Signed-off-by: Yeram Choi yeram.choi@lge.com

ENYO-5668: Fix incorrect eval on merging paths

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js
packages/ui/Scrollable/ScrollableNative.js

Base on UX requirement of Voice Control, proper message has to shown when scrolling is not possible
In enact side, we need to check scroll is possible or not before control scroll position with voice.
ENYO-5614
Enact-DCO-1.0-Signed-off-by: Changgi Lee changgi.lee@lge.com

ENYO-5614: Fix Scrollable to notify user when scrolling is not possible via voice command

---

packages/moonstone/CHANGELOG.md
packages/moonstone/TimePicker/TimePickerBase.js

When changing the value on webOS with audio guidance enabled, the picker would announce the current value plus the meridiem label. This is consistent with the other pickers (hour and minute) but doesn't make much sense given the meridem label.
Remove the `accessibilityHint` property from the `DateComponentPicker` to suppress the extra text read out.

ENYO-5671: Fix TimePicker to not read meridem label when changing value

---

packages/ui/CHANGELOG.md
packages/ui/Marquee/MarqueeDecorator.js

Marquee would not start in sampler when in 5-way mode (now the default). The QA
sampler shows this off best as it starts on a button that has long text.  Reloading the
page showed off the error.
This removes a measurement forced when focus occurs.  There's no need to remeasure
at this time and we can safely defer it until later as we already remeasure.
The only additional downside is that now when we go to …

Fix marquee measure before CSS load

---

packages/i18n/CHANGELOG.md
packages/i18n/ilib/lib/DurationFmt.js

Fix passing unexpected parameters to `IString.loadPlurals`
Pass `sync` and `loadParams` instead of `options.sync` and `options.loadParams`
ENYO-5670
Enact-DCO-1.0-Signed-off-by: Yeram Choi yeram.choi@lge.com

ENYO-5670: passing corresponding parameters

---

packages/spotlight/CHANGELOG.md
packages/spotlight/src/target.js

It is impossible to navigate into a spotlight container with overflow configured when the focusable element inside the container is much larger than the container itself. The result can be that the center of the large item is below the source element causing it to be skipped when navigating 5-way up.
Add clamping to element rects to "resize" them based on the bounding rect of the overflow container.

ENYO-5672: Fix navigating into a spotlight container with overflow 

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/Scrollable.js

When pressing page up/down key in `moonstone/Scroller` the container shakes. This is due to the browser handling the page up/down key in overflow container to reposition, but `moonstone/Scrollerable` handles `onScroll` to set `scrollTop` to the "updated" position which was not updated via the component event handler.
Add `preventDefault()` to page up/down key handling. This is aligned with `moonstone/ScrollableNative`. https://github.com/enactjs/enact/blob/3c9cd97407de3fe8accda22f3d7201ed5bbff0ff/packages/moonstone/Scrollable/ScrollableNative.js#L526
[//]: # (Are …

ENYO-5682: Fix scroller stutter on page up/down

---

packages/core/CHANGELOG.md
packages/core/util/Job.js
packages/core/util/tests/Job-specs.js
packages/moonstone/ExpandableList/tests/ExpandableList-specs.js

It is possible for a race condition to be exposed when multiple calls to a `Job`'s `idle` method are executed when the main thread is overloaded and finally released.  Multiple jobs can end up with the same `id` and if the component that the `Job` is operating on is unmounted at the time the thread is released, a console warning can occur:
```
Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
```
`Job`'s `idle` method is …

ENYO-5687: Enact core Job.idle() should stop an existing job before scheduling a new job

---

packages/ui/CHANGELOG.md
packages/ui/Scrollable/Scrollable.js

Repeatedly attempting to scroll to the same position slows the velocity of the scroller.
Track the last requested target scroll position and bail on scroll attempts for the same position

ENYO-4581: Fix slowed scrolling due to duplicate scroll requests

---

packages/moonstone/Scrollable/Scrollable.js

Default scroll action is only prevented for non-repeated keys.
`preventDefault()` on every page up down key

ENYO-5682: Prevent default scroll action on repeated page up down key

---

packages/ui/CHANGELOG.md
packages/ui/Scrollable/Scrollable.js
packages/ui/Scrollable/ScrollableNative.js

Repeatedly attempting to scroll to the same position slows the velocity of the `NativeScroller`.
Track the last requested target scroll position and bail on scroll attempts for the same position
ENYO-5681
Same solution with #1986

ENYO-5681: Fix slowed scrolling due to duplicate scroll requests for native scroller

---

packages/sampler/.storybook/webos-meta/appinfo.json

We can't test with the `BACK` key manually or automatically(TAS).
I suggest adding `"disableBackHistoryAPI": true` to `appInfo.json` of Storybook.
ENYO-5690

ENYO-5690: Add `disableBackHistoryAPI` to appinfo.json of Storybook

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/MediaSliderDecorator.js

When pointer is located on the left side of the progress bar,
Knob is located to minimum X position
clamp `clientX` of pointer

ENYO-5692: Fix VideoPlayer to clamp knob position

---

packages/spotlight/CHANGELOG.md
packages/spotlight/src/target.js

The center calculation was incorrect when an element was partially visible in an overflow container causing them to "appear" to be closer to spotlight in certain circumstances.
Fix the calculation to offset the center from the the left/top position

ENYO-5695: Fix spotlight target selection of clipped elements

---

packages/moonstone/Notification/Notification.js

If `Notification` has an odd-numbered height/width, the CSS centering logic cause it to be rendered on subpixels resulting in blurry text.
The proposed fix is a workaround until a more significant refactor can take place to use flexbox instead of CSS transforms to position the notification.
This workaround will only resolve the rendering issue on mount and may not be effective if the content of the notification changes. While it's common to update the content in …

ENYO-5691: Fix Notification text to be rendered clearly

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js

Even though the `data-spotlight-container-disabled` prop in Scroller is true, the Scroller Spotlight container becomes enabled when clicking the item in the Scroller.
When clicking the item in the Scroller, the `stop` in the Scroller was called, then it always made the Scroller Spotlight container enabled by calling `this.childRef.setContainerDisabled(false)`. Before calling it, I just checked if `data-spotlight-container-disabled` is false.
[//]: # (Related issues, …

ENYO-5683: Fix handling pointer events in Scroller when spotlight disabled

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js

Add type for prevent scroll move to reverse direction in RTL
In current status, NLP server provide only direction type(ex. left, leftmost, right, rightmost, up, down, top, bottom) scroll info.
For this reason, scroll can be move reverse direction in RTL.
Add additional type(previous, next, first, last) for scroll movement
ENYO-5700
Enact-DCO-1.0-Signed-off-by: Changgi …

ENYO-5700: Fix scrolling by voice commands in RTL locales

---

packages/moonstone/CHANGELOG.md
packages/moonstone/DayPicker/DayPicker.js
packages/moonstone/DaySelector/DaySelectorDecorator.js

fa-IR locale uses `u+060c` as a list separator but `DayPicker` used `,` for all locales.
Patch `DayPicker` to use the correct character in `fa-IR`
Longer term, we'll want to adopt `ilib/ListFmt` for all locales for both `DayPicker` and `ExpandableList`

PLAT-67667: Fix DayPicker separator character for fa-IR locale

---

packages/moonstone/Checkbox/Checkbox.js
packages/moonstone/FormCheckboxItem/FormCheckboxItem.js
packages/moonstone/RadioItem/RadioItem.js
packages/moonstone/SelectableItem/SelectableIcon.js
packages/moonstone/SwitchItem/SwitchItem.js
packages/moonstone/ToggleIcon/ToggleIcon.js

Also fixed spelling of "toggleable"
ToggleIcon docs are confusing and the intent of the component isn't conveyed.
Added docs to describe what the component is for, why one would use it, and what some of the possibilities for using it are.
Also fixed spelling of "toggleable" globally.

ENYO-5395: Improve documentation of moonstone/ToggleIcon

---

packages/ui/CHANGELOG.md
packages/ui/Transition/Transition.js

`ExpandableList` that initially render with no children, fools the system to think that no measurements are ever necessary, and once children are added, that fact is ignored because it assumes the fact that it measured 0 the first time is still the correct value.
`Transition` now treats `null`, `undefined` and `0` as cases where a measurement should be taken again.

ENYO-5708: Transition to support children changing after initial render

---

packages/moonstone/CHANGELOG.md
packages/moonstone/MoonstoneDecorator/MoonstoneDecorator.less
packages/moonstone/styles/text.less

MoonstoneDecorator is not receiving any non-latin rules, but it **is** receiving latin rules. This discrepancy causes unexpected behavior in components that inherit rules.
Added a new argument to several mixins which dictate **where** to apply the non-latin set of rules. In this case, MoonstoneDecorator now leverages this by instructing the mixin thusly:
```
.moon-text-base(@moon-sub-header-font-size, self);
```
`self` instructs the mixin collection to apply the non-latin rules to itself rather than expecting that the rules will be on some ancestor.
Several mixins have been updated with this functionality due to the relationships necessary in the affected mixins. A->B->C->D so each A, B, C, and D must have and support the feature. They all work though now, so we get a more complete API as …

ENYO-5703: Fix MoonstoneDecorator to Latin and non-Latin font rules to the root

---

packages/moonstone/CHANGELOG.md
packages/ui/VirtualList/VirtualListBase.js

There is no way to pass custom parameters from app to VirtualList's itemRenderer.
Define `childProps` prop in VirtualList and spread it as arguments of the `itemRenderer`.
PLAT-67660

PLAT-67660: Pass childProps through VirtualList

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/VideoPlayer.js

`focusElement` call return `false` because of pointer mode.
The reason the pointer mode is false, `preventDefault` and `stopImmediate` is called in `handleSliderKeyDown` handler
call `Spotlight.setPointerMode(false)`

ENYO-5721: Fix VideoPlayer to disable pointer mode when hiding media controls

---

packages/moonstone/styles/text.less

Added for app convenience, not necessarily for framework use.
Occasionally app developers have a need to set the font size of *their* components, and it's awkward to set both latin and non-latin manually.
Added a mixin to facilitate this need.
The changelog was intentionally _not_ updated since this is more of a "special request" rather than a new official API feature.

ENYO-5697: Added .moon-font-size mixin

---

packages/i18n/CHANGELOG.md
packages/i18n/I18nDecorator/I18nDecorator.js
packages/sampler/CHANGELOG.md
packages/sampler/src/MoonstoneEnvironment/MoonstoneEnvironment.js

Unable to use device language in sampler. Selecting the `'local'` value of `''` resulted in the custom knobs reverting to the default value of `'en-US'`.
* Update sampler to use the local language as the default to avoid the knob overriding with a non-falsey default
* Update I18nDecorator to allow a prop change of `locale` to a falsey value triggering the existing logic in `updateLocale` to use the device language

ENYO-5720: Use device locale as default in sampler

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/VideoPlayer.js
packages/sampler/stories/default/VideoPlayer.js

If `mediaControls` disappear when `mediaSlider` has focus and pointer mode is `true`,
focus stays in `mediaSlider`.
Blur focus when hiding `mediaControls`
Related issues : https://github.com/enactjs/enact/pull/1952

ENYO-5725: Fix VideoPlayer to blur slider when hiding media controls

---

packages/ui/CHANGELOG.md
packages/ui/Marquee/MarqueeDecorator.js

The change in #2019 introduced a regression that would allow text that fits in its container to marquee if the subpixel size of the text container were smaller than the rounded `scrollWidth`.
This should resolve both the issues from ENYO-5731 and ENYO-5724:
1. text that is long enough to cause an ellipsis but not enough to cause marquee (the text length using `getBoundingClientRect()` is a subpixel value [e.g. `165.5px`] and would round up) causing it to never fully be visible to the user
2. text that fits in its container but its size is a subpixel value that would round up (e.g. `165.5px`) causing it to marquee just a little
[//]: # (What is the impact of this change and …

ENYO-5731: Fix Marquee to avoid very small animations

---

packages/sampler/stories/qa/Header.js
packages/ui/CHANGELOG.md
packages/ui/Marquee/MarqueeDecorator.js

I'm a little fuzzy on the specifics of the bug but it relates to some recent changes to Marquee. There are two related issues it seems.
First, when changing from short text to long text, the long text should display an ellipsis until animation starts. If the long text is set after the `marqueeRenderDelay` timeout fires, it won't show an ellipsis but will start animating after the requisite delay.
Second, when the above occurs, the subsequent state change to update `overflow` to `'ellipsis'` causes marquee to attempt to start the animation which prevents resetting when complete because the `timerState` is pending due to the spurious animation start request.
[//]: # (What is …

ENYO-5735: Fix Marquee to show ellipsis when children change

---

packages/moonstone/VirtualList/tests/VirtualList-specs.js
packages/ui/CHANGELOG.md
packages/ui/Scrollable/Scrollable.js
packages/ui/VirtualList/tests/VirtualList-specs.js

After removing animations during scroll by arrow key down,
onScrollStart and onScrollStop are called back on every focus movement.
If an app sets at least one of those callbacks, this behavior may affect the performance.
To reduce unnecessary callbacks,
this PR changes lists to fire onScrollStop after waiting a certain period of time
from the last update of the scroll position.
ENYO-5726

ENYO-5726: Reduced onScrollStart and onScrollStop calls on key down

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scroller/Scroller.js

Changing the size of a container within a Scroller causing some unpredictable scrolling behavior.
The logic for scrolling on focus had become overly complex due to changing requirements over time. I've restated the requirements and reimplemented the method in light of those requirements.
My goal for this PR was to standardize behaviors so there may be scenarios that behave differently than before. If we decide on specific deviations to the current behavior, we can …

ENYO-5710: Fix Scroller to better handle scrolling due to focus

---

packages/moonstone/CHANGELOG.md
packages/moonstone/ExpandableInput/ExpandableInput.js

There is a Spotlight issue that causes `<input>` to retain focus when closing `ExpandableInput` right when `<input>` receives focus while `Expandable` is opening. 
In `ExpandableInput`, there are multiple components pausing `Spotlight` so when `Expandable` closes, the following line doesn't highlight `LabeledItem` because `Spotlight` is still paused by `ExpandableInput`
```
//ExpandableSpotlightDecorator.js L179-L182
handleHide = () => {
this.resume();
this.highlight(this.highlightLabeledItem);
}
```
Call `resume()` in `ExpandableInput` when its `open` prop changes to false. This will allow `ExpandableSpotlightDecorator` to resume its instance of Spotlight and then highlight …

ENYO-5734: Resume Spotlight when ExpandableInput closes

---

docs/testing-components/unit-testing/index.md
packages/core/dispatcher/tests/dispatcher-specs.js
packages/core/handle/tests/handle-specs.js
packages/core/util/tests/memoize-specs.js
packages/moonstone/Button/tests/Button-specs.js
packages/moonstone/DatePicker/tests/DatePicker-specs.js
packages/moonstone/DaySelector/tests/DaySelector-specs.js
packages/moonstone/ExpandableInput/tests/ExpandableInput-specs.js
packages/moonstone/ExpandablePicker/tests/ExpandablePicker-specs.js
packages/moonstone/IncrementSlider/tests/IncrementSlider-specs.js
packages/moonstone/Input/tests/Input-specs.js
packages/moonstone/Panels/tests/Breadcrumb-specs.js
packages/moonstone/Panels/tests/IndexedBreadcrumbs-specs.js
packages/moonstone/Panels/tests/Panels-specs.js
packages/moonstone/Panels/tests/Router-specs.js
packages/moonstone/Scroller/tests/Scroller-specs.js
packages/moonstone/Slider/tests/Slider-specs.js
packages/moonstone/TimePicker/tests/TimePicker-specs.js
packages/moonstone/internal/Picker/tests/Picker-specs.js
packages/ui/Cancelable/tests/Cancelable-specs.js
packages/ui/Changeable/tests/Changeable-specs.js
packages/ui/Group/tests/Group-specs.js
packages/ui/Item/tests/Item-specs.js
packages/ui/RadioDecorator/tests/RadioDecorator-specs.js
packages/ui/Slottable/tests/Slottable-specs.js
packages/ui/ToggleIcon/tests/ToggleIcon-specs.js
packages/ui/ToggleItem/tests/ToggleItem-specs.js
packages/ui/Toggleable/tests/Toggleable-specs.js
packages/ui/Touchable/tests/Touchable-specs.js

Requires: https://github.com/enactjs/cli/pull/157
* Our usage of Sinon spies/stubs was no longer needed now that we've switched to Jest, which includes built-in support for mocking and spies.
* Switch to use Jest built-ins.
* https://jestjs.io/docs/en/mock-function-api
* https://github.com/maurocarrero/sinon-jest-cheatsheet

PLAT-70230: Drop Sinon in favor of using Jest built-ins for mocking/spies

---

CHANGELOG.md
packages/moonstone/CHANGELOG.md
packages/moonstone/ExpandableItem/ExpandableItem.js
packages/sampler/stories/qa/Spotlight.js
packages/spotlight/CHANGELOG.md
packages/spotlight/src/container.js

`moonstone/ExpandableItem` (and related components) did not disable its spotlight container when the component was disable. As a result, it was still treated as a spotlight candidate even though it isn't navigable. When placed first inside a Scroller which itself is inside a restricted container (`enterTo: 'last-focused'`), it causes spotlight to abandon target detection for the scroller prematurely.
1. Spotlight retrieves the spottable descendants for the scroller which includes the `ExpandableItem`
2. The scroller is an overflow container (meaning it may have spottable descendants which are out of view) so the candidate list is pruned down to the visible elements and the first visible element is returned.
3. …

ENYO-5745: Fix ExpandableItem and Scroller handling of disabled containers

---

packages/spotlight/src/container.js
packages/spotlight/src/tests/container-specs.js
packages/spotlight/src/tests/target-specs.js

A handful of spotlight tests were skipped during the jest migration due to incompatibilities.
Add a bailout to `isNavigable` when `NODE_ENV === 'test'` since jsdom reports all nodes as having no size
We don't current have any tests for "sizeless" nodes but this change precludes adding them in the future.

PLAT-70229: Fix Spotlight unit tests

---

packages/sampler/stories/qa/Scroller.js
packages/spotlight/CHANGELOG.md
packages/spotlight/src/container.js

If a spotlight container configured for overflow (e.g. a `moonstone/Scroller`) contains a container larger than its viewport, that container could be ignored as a focus target.
* Use `getDeepSpottableDescendants` to check contents of unrestricted containers
* Use `intersects` to prioritize large restricted containers
I avoided `getDeepSpottableDescendants` in #2037 to minimize change. Upon reviewing the code for this change, I realized that the affected code path is …

ENYO-5746: Fix Spotlight prioritization within overflow containers

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scroller/Scroller.js
packages/sampler/stories/qa/Scroller.js

A single function, `roundToBoundary` was used for scrolling to the boundary when the target was either above or below the bounds of the scroller. As a result, when the scroller's contents were larger than the scroller but less so than the value of `threshold`, the function would always round to 0 even trying to scroll to an item below the viewport.
Refactor the method into two methods -- one for `roundToStart` and one for `roundToEnd` and use each based on the position of the target item.

ENYO-5752: Fix scrolling to boundary for short scrollers

---

packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js
packages/ui/Scrollable/Scrollable.js
packages/ui/Scrollable/ScrollableNative.js

Per @Baekwoo-s's analysis, the change in #1878 to move the rtl publish to `componentDidMount` causes a layout failure for Scrollable and related components.
Add `rtl` as a prop for `ui/Scrollable` + native and populate it via `I18nContextDecorator` in `moonstone`. Keeps i18n out as a dependency for ui for the time being.
No change log entry since the bug was introduced within this release.

ENYO-5723: Fix retrieving rtl prop for Scrollable

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Popup/Popup.js

When opening and closing a popup quickly (particularly on low-powered hardware), `Transition`'s `onShow`/`onHide` events aren't fired because the CSS transition is added and removed in the same frame. As a result, Popup isn't notified that opening or closing completes and is unable to clean up its internal state to hide the floating layer.
* Expanded `popupOpen` to support three modes: closed, opening, and open.
* Updated usage of `popupOpen` to test for the new states rather than a boolean
* Fixed the condition in `componentWillReceiveProps` to close the floating layer when the popup is opening but not yet …

ENYO-5756: Fix closing Popup's floating layer when closed without animation

---

packages/sampler/stories/qa/Spotlight.js

Adding a QA sample to test a case where `Spottable` becomes disabled while focused and sets state that is needed by `Marquee` to allow marquee behavior to restart.

PLAT-61824: Add QA sample to test disabling spottable-marqueeable button

---

packages/i18n/CHANGELOG.md
packages/i18n/src/Loader.js

Including `@enact/i18n` without the ilib plugin causing a runtime error because the `ILIB_` "globals" are not injected by the plugin.
Add existence checks to avoid run time errors.
This does not cause ilib to "work" without the plugin but does allow an app with moonstone to still run without the ilib resources.

PLAT-72250: Fix i18n loader to fail gracefully when paths are not injected

---

packages/spotlight/SpotlightContainerDecorator/SpotlightContainerDecorator.js

This PR updates the lifecycle in `SpotlightContainerDecorator`.
This update exposed an issue in how `SpotlightContainerDecorator` currently sets spotlight container configs when there is no `spotlightId` prop provided - it will not respect the `spotlightRetrict` prop. This happens when attempting to add or update the specified container by calling `Spotlight.add(spotlightId, options)` when `spotlightId` is `undefined`. In order to update the lifecycle, I also addressed this issue, since we need the correct data in `getDerivedStateFromProps`.

PLAT-72738: Update lifecycle method in SpotlightContainerDecorator

---

packages/moonstone/ContextualPopupDecorator/ContextualPopupDecorator.js

Update `ContextualPopupDecorator` life cycle methods
- Remove `componentWillReceiveProps`
- Instead of positioning the popup container in ref callback function, it positions when `FloatingLayer`'s `onOpen` is invoked. This guarantees that both `this.clientNode` and `this.containerNode` are present
- `onOpen` essentially can replace the `open` condition in `componentWillReceiveProps`. Spotlight caching can be moved here.
- Similarly, `onClose` event can be used for the `close` condition in `componentWillReceiveProps`. Resets Spotlight activator and leavefor
- `shouldSpotActivator` requires to check whether …

PLAT-72730: Update ContextualPopupDecorator life cycle methods

---

packages/moonstone/CHANGELOG.md
packages/moonstone/MoonstoneDecorator/screenTypes.json

Loading Moonstone on an 8k display, things look tiny.
Added a new screenType to support the new larger screen resolution

PLAT-72875: Add support for 8k display in Moonstone

---

packages/moonstone/VideoPlayer/MediaControls.js
packages/moonstone/VideoPlayer/MediaTitle.js
packages/moonstone/VideoPlayer/VideoPlayer.js

Update VideoPlayer life cycle methods. 
**General**
_style_ updates to components are moved to `componentDidUpdate` life cycle
- Remove `style` attribute from JSX
- Remove any _state_ keeping track of the DOM values as managing DOM values via _state_ can result in different values depending on which life cycle it's accessed from
**MediaControls**
- Counting the left/right components and resetting width of the controls is moved from `componentWillReceiveProps` to `componentDidUpdate`
- Setting `showMoreComponents` on `visible` prop change is unnecessary as it is set in associated event handlers …

PLAT-72726: Update VideoPlayer life cycle methods

---

packages/moonstone/DatePicker/tests/DatePicker-specs.js
packages/moonstone/TimePicker/tests/TimePicker-specs.js
packages/moonstone/internal/DateTimeDecorator/DateTimeDecorator.js

Update `moonstone/internal/DateTimeDecorator` life cycle methods
- `date` prop converts from JS `Date()` to unix time and stored as `state.date`. `static getDerivedStateFromProps` handles the job for conversion.
- Since `setState` calls were invoked only when `open` props changed, we can achieve the same effect by handling it in `onOpen` and `onClose` handlers.
- `initI18n` is moved to `render` and added `I18nContextDecorator` to handle `locale` change through props.
[//]: # (Were any side-effects caused by the …

PLAT-72734: Update DateTimeDecorator life cycle methods

---

packages/sampler/stories/qa/IncrementSlider.js

The qa-sampler did not have a sample to test max, min, and value knobs of IncrementSlider
Implemented using number function so that max, min, and value are passed to the IncrementSlider sample.

PLAT-72618: [qa-sampler] Add `max`, `min`, and `value` knobs to IncrementSlider sample

---

packages/sampler/stories/qa/Scroller.js

When you change the knob's value in the scroller qa-sampler, the app is refreshed when you press enter key.
Modified input tag to slider tag so that you can test without using Enter key
1. The order of the props to pass to the number function was incorrect.
Incorrect
number('Spacer size', {min: 0, max: 300}, 100);
Correct
number('Spacer size', 100, {min: 0, max: 300});
2. Fixed overlapping of text when `Spacer size` knob is reduced in height

ENYO-5766: [qa-sampler] Fixed qa-sampler not being refreshed when entering values for knob

---

packages/moonstone/DaySelector/DaySelectorDecorator.js
packages/moonstone/DaySelector/tests/DaySelector-specs.js

Update `DaySelectorDecorator` life cycle methods
Used `getDerivedStateFromProps` to set states with new props, and divided getLocaleStates into two parts so that these can be called independently.
Enact-DCO-1.0-Signed-off-by: Hailey Ryu hangyeol.ryu@lge.com

PLAT-72731: DaySelectorDecorator life cycle methods updates

---

packages/core/internal/ApiDecorator/ApiDecorator.js

In StrictMode, certain lifecycle methods are invoked twice to surface unintended side-effects. `ApiDecorator` was implemented too defensively and was throwing errors when attempting to redefine an API endpoint on a second call to `setApiProvider` which is often called in the constructor of the consumer of the HOC.
The proposed fix makes the properties defined by ApiDecorator configurable. Originally, I was trying to build in some "security" by preventing changes to the props but that isn't protecting against any real threats and instead prevents real use cases for consumers updating the API endpoint if the …

PLAT-72655: Fix ApiDecorator to be compatible with StrictMode

---

packages/ui/Marquee/MarqueeDecorator.js

Removed the `UNSAFE_componentWillReceiveProps ` life cycle in `MarqueeDecorator`.
The `UNSAFE_componentWillReceiveProps` life cycle was being used in more of a procedural manner rather than state management - mostly to invalidate metrics (`this.invalidateMetrics()`) and cancel animations (`this.cancelAnimation()`) - even though each ultimately updated a piece of state. The combination of that and the amount of new state we would have to manage in order to add a `getDerivedStateFromProps` (to update those minor state changes) leads me to believe that the least impactful solution is to handle things in `componentDidUpdate`.
`componentDidUpdate` already includes code that will cause an additional `setState` re-render (`this.validateTextDirection()`), which is guarded against happening when …

PLAT-72740: MarqueeDecorator lifecycle update

---

packages/moonstone/internal/Picker/Picker.js

A recent change to `Picker` in #1893 refactored how picker works a bit - however, it failed to include passing `spotlightDisabled` and `onSpotlightDisappear` to joined pickers. This PR re-adds that support. `onSpotlight[direction]` event support is still handled correctly.

ENYO-5786: Joined Picker -> re-add spotlightDisabled and onSpotlightDisappear support

---

packages/sampler/CHANGELOG.md
packages/sampler/stories/qa/Marquee.js

Marquee sample broke because of MarqueeDecorator change. Refs no longer work for Marquee, but nobody should be using them in the first place.
Using `querySelector` instead of refs
ENYO-5784

ENYO-5784 - Qa-Sampler: Marquee - with short content: Cannot read property 'scrollWidth' of undefined

---

packages/moonstone/internal/Picker/Picker.js
packages/ui/Scrollable/Scrollable.js
packages/ui/Scrollable/ScrollableNative.js

Remove _componentWillReceiveProps_ from Picker and _componentWillUpdate_ from Scrollable.
Validation code of Picker is moved to _render_ function to validate values both for mounting and updating cases.
Code for _scrollTo_ method of Scrollable is moved to _componentDidUpdate_.
If we don't need to validate values of Picker for mounting, we can move the code into _getDerivedStateFromProps_ from _componentWillReceiveProps_ instead.
For Scrollable, the behavior of …

PLAT-72716: Picker and Scrollable - Update lifecycle method

---

packages/ui/Changeable/Changeable.js
packages/ui/Changeable/tests/Changeable-specs.js
packages/ui/Toggleable/Toggleable.js
packages/ui/Toggleable/tests/Toggleable-specs.js

We changed how we determined that an instance of Changeable or Toggleable was controller in #2057 but it has had some unintended side effects in our components and would likely in app usage as well.
Reverting that bit of logic in both coomponents
May consider revising this in a future (e.g. 3.0) release.

ENYO-5794: Revert logic for controlled state for Changeable/Toggleable

---

packages/moonstone/Popup/Popup.js

In an attempt to simplify Popup's open logic in #2068, we removed mid-`OPENING` state of the transition container. However, since `ui/Transition` relies on `onTransitionEnd` event to notify whether it is opened or not, changing the `visible` state in the midst of transition makes states to go out of sync.
Restored `OPENING` state in Popup. We can revisit later on cleaning up Popup's code, but I think this is okay FWIW.

ENYO-5793: Restore OPENING state in Popup

---

packages/moonstone/ContextualPopupDecorator/ContextualPopup.module.less
packages/moonstone/ExpandableList/ExpandableList.js
packages/moonstone/ExpandableList/ExpandableList.module.less
packages/moonstone/LabeledItem/LabeledItem.module.less
packages/moonstone/Slider/Slider.module.less
packages/moonstone/internal/Picker/Picker.module.less

With the changes to the CSS structure of supporting largeText as a skin variant, Picker is generating selectors that don't match the reality of the DOM structure any longer.
Rearrange the `.moon-custom-text` mixin rules in the Picker LESS file to apply the correct classes only to the base element. Secondarily, the rules have been consolidated into a single mixin, replicating the selector structure for better readability.
Includes updates to `ContextualPopup`, `LabeledItem`, and `Slider` as well.

PLAT-73583: Consolidated Picker's largeText rules into one section

---

packages/ui/VirtualList/VirtualListBase.js

Fix taken from https://github.com/enactjs/enact/pull/2108
Signed-off-by: Jason Robitaille <jason.robitaille@lge.com>
* Edgecase syntax error in latest Babel release regarding complex `let` usage caused Babel parsing to fail. A fix has been pushed upstream and will be integrated in CLI appropriately. However in the meantime, a basic reordering of syntax can provide a fix for our 2.3.0 release and linting.
* Re-arrange `let` declaration structure, such that the destructuring operation is last.
* Solution originally from https://github.com/enactjs/enact/pull/2108

Workaround syntax fix for Babel bug involving `let` edge case usage.

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Slider/SliderBehaviorDecorator.js

`SliderBehaviorDecorator` can be focused when it is disabled, which can result in unintended actions - such as a `Slider` displaying a tooltip when a click action occurs on the slider bar.
Preventing forwarding the focus event and setting an internal focused state when the component is `disabled` fixes the issue.

ENYO-5795: SliderBehaviorDecorator - prevent setting focus when disabled

---

packages/sampler/stories/qa/Marquee.js

This patch adds a knob for `marqueeOnRenderDelay` for `Marquee` qa stories.
At least one of the stories has multiple `Marquee`s but currently offer no knobs at all, so they have been left out of this patch as well.
ENYO-5798

ENYO-5798: Update QA Sampler to add marqueeOnRenderDelay knob for Marquee > LTR sample or create new sample

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Slider/utils.js

Fixed an issue where using 5way directional keys on an active `Slider` knob resulted in default browser scroll behavior.
We simply need to call `preventDefault` on the `keydown` event used to increment/decrement the slider. It turns out that we have the necessary guards in place to only call this behavior when needed.

ENYO-5808: Slider knob > prevent default browser scroll behavior when using 5way

---

packages/ui/CHANGELOG.md
packages/ui/Changeable/Changeable.js
packages/ui/Changeable/tests/Changeable-specs.js
packages/ui/Toggleable/Toggleable.js
packages/ui/Toggleable/tests/Toggleable-specs.js

Developers should not assign both `[defaultProp]` and `[prop]` at the same time so we add a console warning if that is the case.
- Components and apps that have used the pattern will start seeing warnings in the console
- Existing tests for `ui/Changeable` and `ui/Toggleable` have been updated to expect warnings
- There are some tests in `ui/Toggleable` that still warn even when both props are not present
PLAT-73546

PLAT-73546: ui/Changeable & ui/Toggleable: Add warning if both [defaultProp] and [prop] are declared

---

packages/ui/ViewManager/TransitionGroup.js
packages/ui/ViewManager/ViewManager.js
packages/ui/ViewManager/tests/ViewManager-specs.js

Update `TransitionGroup` to use `getDerivedStateFromProps`

PLAT-73547: Update ViewManager internal lifecycle methods

---

packages/sampler/src/MoonstoneEnvironment/MoonstoneEnvironment.js
packages/sampler/src/MoonstoneEnvironment/MoonstoneEnvironment.module.less
packages/sampler/src/enact-knobs/select.js
packages/sampler/src/utils/propTables.js

Storybook addons don't adhere to our idealized styling policy, and as such, some addons simply inject unstylable DOM nodes into the hierarchy. This causes layout problems when a child component expects to have a container which doesn't auto-shrink to minimum size.
There is a typo in an enact-knob code.
And some knobs do not properly group themselves when the page is reloaded even though they do properly group when switching stories.
Added better layout support (by using Layout) to the story workspace area, and restored the positioning rules for the unstylable foreign DIV.
Fixed said typo
Added a `groupId` key to the Config object so the component name isn't discovered after several of the knobs are rendered (into the wrong tab-group category). May not be the *best* place to put it, but it …

ENYO-5839: Fix Storybook story workspace positioning

---

packages/ui/VirtualList/VirtualListBase.js

When metrics props (e.g. `direction`, `spacing`, etc.) update, children are incorrectly positioned. For example, changing `direction` in `VirtualGridList` after scrolling a bit, it will show a blank page.
Prior to lifecycle method update PR (#2108), it used to reset `firstIndex` state directly prior to making an updated `setState` call, but it's been removed as part of the fix. This left us with incorrect value of the "new first index", thus resulting in wrong positioned items.
Removed references of `this.state` in all related calculation logic and added parameters to each function that accepts "firstIndex" …

PLAT-72723: Fix first index reset on props update

---

packages/ui/VirtualList/VirtualListBase.js

`UNSAFE_componentWillMount()`, `UNSAFE_componentWillReceiveProps()`, and `UNSAFE_componentWillUpdate()` will be deprecated.
- Move the code in `UNSAFE_componentWillMount()` to `constructor`.
But `updateStatesAndBounds` was renamed as `getStatesAndUpdateBounds` to get a new state instead of calling `setState` in the `updateStatesAndBounds`.
- Move the code in `UNSAFE_componentWillReceiveProps()` to `componentDidUpdate`.
But we still need the `this.hasDataSizeChanged` variable used in `moonstone/VirtualList`.
In addition, `this.cc = []` for RTL was removed.
- Move the code in `UNSAFE_componentWillUpdate()` …

PLAT-72723: Update ui/VirtualList lifecycle method

---

packages/moonstone/MoonstoneDecorator/AccessibilityDecorator.js

Extra semicolon was lingering in the JSX
Removed it!

ENYO-5853: Remove trailing semicolon from AccessibilityDecorator

---

packages/moonstone/CHANGELOG.md
packages/moonstone/ContextualPopupDecorator/ContextualPopupDecorator.js

`ContextualPopup` does not focus on popup content when the popup is first opened. This is due to the popup node not being available at the time when `spotPopupContent()` is called.
Move popup content spotlight timing to `onOpen` to ensure the popup node is rendered.

ENYO-5791: Fix timing of popup content spotlight to onOpen

---

packages/moonstone/CHANGELOG.md
packages/moonstone/internal/DateTimeDecorator/DateTimeDecorator.js
packages/sampler/stories/default/DatePicker.js
packages/sampler/stories/default/TimePicker.js

In certain cases, most notably in `TimePicker`, an `undefined` value is incorrectly overriding a supplied `defaultValue` on render.
I opted to use a state value (`derived`), initially `false`, that is checked in `getDerivedStateFromProps` and prevents updating in the case where a decorated component is rendered `open`.  Once the props have been derived the first time, the state is updated and the component will update properly.
Component and UI tests seem to work …

ENYO-5852: Enact-ui-tests: DatePicker and TimePicker - running same test on different builds gives different result

---

packages/ui/CHANGELOG.md
packages/ui/Repeater/Repeater.js
packages/ui/Repeater/tests/Repeater-specs.js

`ui/Repeater` always renders a `<span>` tag. It's often useful to be able to change this.
Added a `component` prop to `ui/Repeater` to allow customization of its base level element. This logically makes sense because the child component can already be customized (via `childComponet`) and fits in line with the way other components' base elements are customized (via the `component` prop).
This simple change greatly improves the flexibility and utility of this component.

ENYO-5843: Added a component prop to Repeater to allow customization

---

packages/moonstone/Spinner/Spinner.module.less

`conic-gradient` isn't supported on chrome 68. An alternate approach is required.
Implemented a replacement gradient that uses a positioned radial-gradient to get a similar effect.

PLAT-73235: Fix Spinner to use chromium 68-compatible gradient

---

packages/ui/ProgressBar/ProgressBar.js
packages/ui/ProgressBar/ProgressBar.module.less
packages/ui/ProgressBar/tests/ProgressBar-specs.js

Mandating a unit in the proportion CSS values not only doesn't make sense (it's a numeric proportion, not a percentage), but it also makes division and subtraction impossible in the CSS `calc` function.
One is also not free to use `ui/ProgressBar` to its fullest potential in unique themes because `orientation` is "locked" to two finite values.
Switch ui/ProgressBar to unitless proportions from percents.
Also allow any string in the `orientation` prop, since we can't make assumptions about what orientations a theme may want to implement.

ENYO-5842: Switch ui/ProgressBar to unitless proportions from percents

---

.travis.yml

* Currently using latest NodeJS release for Travis. However new/changed APIs and cause breaks in our process. To allow for vetting and update-time, it's safer to lock in to using latest LTS release.
* Use latest LTS release

Use latest LTS release of NodeJS for increased stability.

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/VideoPlayer.js

When hovering the slider to show the thumbnail, pressing playback keys (play/pause) would hide the thumbnail.
Remove the state update in `showFeedback` to `feedbackAction` and instead rely on the other existing triggers (`hideFeedback`, `hideControls`).
This feature was added by #1798. I've checked this against that bug report and didn't notice a regression. cc: @viodragon2 in case you recall specifics on why this code was added originally.

ENYO-5764: Fix VideoPlayer to continue to show thumbnail on playback keypress

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Spinner/Spinner.js
packages/moonstone/Spinner/Spinner.module.less

On some devices, the spinner animation can get out-of-sync after props changes
Due to the way DOM nodes are laid out in react, `::before` and `::after` pseudo-elements get rendered slightly later on some hardware. Being tardy-to-the-party means that their animations aren't perfectly in sync. The `Spinner` is (was) using 3 DOM nodes, the first 2 of which had 2 pseudo-elements each (for a total of 4), which compose the "fan" part of the `Spinner`. The ball was its own DOM node, so it never got out of sync with where it should have been; the DOM node and the pseudo-elements were rendering at different times, causing the effect.
By switching the pseudo-elements to real DOM nodes, they all get rendered at the same time, allowing them to stay in sync when props change on the component.

ENYO-5867: Switched Spinner away from pseudo-elements for animation fidelity

---

packages/ui/CHANGELOG.md
packages/ui/Scrollable/Scrollable.js
packages/ui/Scrollable/ScrollableNative.js
packages/ui/VirtualList/VirtualListBase.js

After migration to React 16.7, items are not displayed properly if an app calls `scrollTo` during VirtualList is being updated by prop changes.
When props are changed, a list should be reset by data change or bounds change. And if the scroll area is expanded or shrunk by scrollbar visibility, a list needs at least two rendering cycles due to measuring. So we had a logic to defer a `scrollTo` request until internal updating is finished.
Note that the first index to render is managed through `state` and it is very tightly coupled with the scroll position of a list which is _updated by browser outside of React …

PLAT-73358: Fix to perform `scrollTo` callback during the list is updated by prop changes

---

packages/i18n/CHANGELOG.md
packages/i18n/I18nDecorator/I18nDecorator.js
packages/i18n/I18nDecorator/tests/windowFocus-specs.js
packages/i18n/I18nDecorator/windowFocus.js

On webOS, when the app is in the background, the system still dispatches the {{languagechange}} event but XHR requests are disabled causing I18nDecorator to fail to update the locale.
Enqueue the update locale logic until the window regains focus.
I generalized the window focus monitoring logic into another file to separate the logic and ease testability. For now, it's private to `I18nDecorator` but it could be moved elsewhere for reuse if the need arises.

PLAT-69081: Fix I18nDecorator to defer locale change until window focus

---

packages/i18n/I18nDecorator/windowFocus.js

If `onWindowFocus` was called without a window or before the window was ready then the callback function could be executed.
Only set `focused` once the window is ready
Current usage guards against a problem but things could easily change.
ENYO-5881

Prevent focused functions until window ready

---

packages/moonstone/TooltipDecorator/TooltipDecorator.js

Accessing `window` in the constructor is bad for isomorphic builds
Move the MutationObserver and ResizeObserver initialization to `componentDidMount` which is safe for iso

ENYO-5881: Fix TooltipDecorator in iso builds

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js
packages/moonstone/Scroller/Scroller.js
packages/moonstone/VirtualList/VirtualListBase.js
packages/ui/Scrollable/Scrollable.js
packages/ui/Scrollable/ScrollableNative.js
packages/ui/VirtualList/VirtualListBase.js

When unmounting the page including VirtualList or Scroller, there is the following error.
- Cannot read property 'removeEventListener' of undefined
I passed the wrong object and referenced its wrong property before.
So I fixed it and updated the guard condition. 
ENYO-5885

ENYO-5885: Fix that 'removeEventListener' was undefined in VirtualList and Scroller samples

---

packages/sampler/CHANGELOG.md
packages/sampler/stories/qa/Notification.js

It is difficult to quickly enter enough text with the VKB to make the `Notification` resize.  This QA sample lets you add or remove lines to allow quick verification of height changes.
Added a QA sample for `moonstone/Notification` and dynamic text.
ENYO-5822

ENYO-5822: Enact QA-Sampler: create a sample to test long text and verify height of Notification extends

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Popup/Popup.js

When creating the popup with the {open: true, noAnimation: false} props, Spotlight could not be on any controls when hovering them after closing the popup.
Analysis
- When creating the popup with the {open: true, noAnimation: false} props
\- The `popupOpen` status in the `Popup` was initialized with `OpenState.OPENING`
\- When `FloatingLayer` opened, `this.handleFloatingLayerOpen` in the popup was called, then the `popupOpen` status was reset to `OpenState.OPENING` again.
\- The `popupOpen` status was always updated to `OpenState.OPEN` when the popup animation ended and `this.handlePopupShow` callback in …

PLAT-75865: Fix to resume spotlight pauses when closing with animation

---

packages/sampler/stories/qa/VirtualGridList.js
packages/sampler/stories/qa/VirtualList.js

In `VirtualList` and `VirtualGridList` samples in QA-sampler, if `dataSize` is set to any number grater than 1000, no item is rendered after 'Item 999'.
Data were initially generated with the size of 1000 and was never updated even if `dataSize` was changed.
To support any number of items, items will be re-generated whenever `dataSize` is changed. It is a natural behavior since the change of  `dataSize` means the change of data in real apps.
Heading '0's for list …

ENYO-5818: Fix list QA samples when dataSize is greater than 1000

---

packages/spotlight/CHANGELOG.md
packages/spotlight/src/container.js
packages/spotlight/src/tests/container-specs.js
packages/spotlight/src/utils.js

Attempting to focus a configured container that wasn't mounted threw a runtime error.
Add a couple guards to prevent throwing errors
This was originally manifest in unit testing an application but could be reproduced in standalone scenarios as well.

ENYO-5728: Fix spotlight to guard against accessing non-existent containers

---

packages/moonstone/Scrollable/ScrollButton.js
packages/moonstone/Scrollable/ScrollButtons.js

When pressing the 5-way Up on the Down scroll button, Spotlight jumps not to the Up scroll button but to the item in the VirtuaList.
We have to compare the current spotted DOM element and the Up / Down scroll button DOM elements to navigate between the Up / Down scroll buttons. But we compared the current spotted DOM element and the scroll button ref (Not DOM element). So Ryan fixed to pass the ref to the DOM element properly.
ENYO-5890

ENYO-5890: Fix to move Spotlight between scroll buttons properly via 5-way keys

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Panels/Viewport.js

This issue is related to ENYO-5630. So, I can reproduce it since `2.4.0`.
In viewport, it tries to make Panel when child is null.
If application defines child(panel) depend on any condition or state, Panel child array have a null value.
Viewport generate `spotlightId` using with information from props. But, it shouldn't get props when child is null.
I added condition whether child is valid or not before generating spotlightId of Panel.
ENYO-5897

ENYO-5897: Viewport: it tries to make panel when child is null

---

packages/ui/Marquee/MarqueeDecorator.js

`MarqueeDecorator` queues up `demoteJob` and fires `setState` calls when it's not promoted.
Add check before queuing up

ENYO-5906: Add check for demote to avoid setState call

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Input/pointer.js

ExpandableInput does not close when touching the second ExpandableInput.
Touch events needed a separate handler. 
Interesting test data.
https://patrickhlauke.github.io/touch/tests/results/

PLAT-75397: Fix ExpandableInput to close on touch platforms when tapping off it

---

packages/core/CHANGELOG.md
packages/core/kind/kind.js

Recent React release added warnings for invalid `contextType` values on a component. We are currently blindly applying several statics in `core/kind` even when those are not set by authors.
Conditionally apply statics outside the class body

PLAT-76545: Fix core/kind to only apply static component props when provided

---

packages/ui/Touchable/ClickAllow.js
packages/ui/Touchable/Touchable.js

5-way select of Expandables and ToggleItems doesn't work after #2192 
Spottable's mouse emulation was running afoul of Touchable which was checking the event type against starting with `'mouse'`. Removing that condition -- which isn't necessary due to method only used in a mouse event handler -- resolves the bug.
I also moved the event forwarding before the method call where it should have always been since we are guarding against Touchable reacting to the event and not the event itself.

ENYO-5910: Fix Touchable forwarding of mousedown events

---

packages/ui/CHANGELOG.md
packages/ui/Touchable/Touchable.js

Spotlight is on item when 'data-spotlight-container-disabled' is touched.
Removing focus and blur from Touchable resolved this issue. Removing these don't affect other issues. Spotlight is taken care of from Spottable.

PLAT-76786: Change Touchable to not gain focus when activated by touch

---

package.json

* The NPM task scripts `link-all` and `unlink-all` were executing indiscriminately on all packages. however the Sampler app is not designed to be linked.
* Skip `enact-sampler`package during linking/unlinking processes.
* Not high priority in any way, but nice cleanup for future.
Signed-off-by: Jason Robitaille <jason.robitaille@lge.com>

PLAT-77101: Ignore sampler in Enact NPM link/unlink tasks

---

packages/ui/CHANGELOG.md
packages/ui/Touchable/ClickAllow.js
packages/ui/Touchable/Touchable.js

When touching on a component that handles `onTap` *and* reveals another Touchable instance in the same position as the tap, the mouse events could occur on a different target than the touch events.
The event order for touch events and mouse events in Touchable:
* `onTouchStart`
* `onDown`
* `onTouchEnd`
* `onUp`
* `onTap`
* `onMouseDown`
* `onMouseUp`
* `onClick`
If `onTap` changes the DOM, the subsequent `onMouseDown` might happen over a different DOM node causing this bug.
Add (back? possibly a regression from #2195) a global Touchable variable to verify that the `mousedown` came from the same `target` as …

PLAT-76981: Fix Touchable to prevent handling events on multiple nodes

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/VideoPlayer.js

Pressing a remote button to play/pause the video while the slider was focused would trigger the timer to hide the feedback. Instead, the thumbnail should remain visible while the slider is focused and visible.
Add a condition to only hide the feedback when it isn't being shown due to slider focus.

ENYO-5898: Fix VideoPlayer to continue to display thumbnail image

---

CHANGELOG.md
packages/moonstone/CHANGELOG.md
packages/moonstone/Input/Input.js
packages/moonstone/Input/Input.module.less
packages/moonstone/Input/InputSpotlightDecorator.js
packages/moonstone/Panels/Header.js
packages/moonstone/Panels/Header.module.less
packages/moonstone/styles/colors.less

`moonstone/Header` needs to be updated to reflect the new designs when using a `headerInput`
* Expose the `focused` class on `moonstone/Input` to adjust the necessary colors from `Header`
* Update the CSS in `Header` for the new designs
* Changed the `.title` margin to 2px which, though non-standard and not divisible by 3, allows the input and title text to match in all resolutions except HD (where 3px does the trick). Would like to find a better alternative to this approach.

PLAT-75346: Update design of moonstone/Header with Input

---

packages/moonstone/Button/Button.module.less
packages/ui/CHANGELOG.md
packages/ui/Skinnable/Skinnable.js
packages/ui/Skinnable/tests/Skinnable-specs.js

Default `skinVariant` values configured on `Skinnable` are overriding inherited `skinVariant` values from ancestral `Skinnable` instances.
Fix the merge logic to override default variants with parent variants and parent variants with author variants.
Reordered a couple unit test expected outputs to match the updated the logic.

ENYO-5926: Fix overriding default skin variants from Skinnable

---

packages/moonstone/CHANGELOG.md
packages/moonstone/EditableIntegerPicker/EditableIntegerPicker.js

The content of the picker when not editing was slightly off center. The root cause was an extra space in the DOM content.
Fix up the logic to only add the space when `unit` is also valued

ENYO-5919: Fix alignment of content in moonstone/EditableIntegerPicker

---

packages/moonstone/Scrollable/ScrollableNative.js

We have a logic to prevent a list or a scroller from unexpected scrolling by focus. But the restoring logic consumes CPU more than expectation on embedded systems.
We are using `{preventScroll: true}` option to focus a node without scrolling already, so simply removed the restoring logic.
This change does not affect any public components, so the changelog is not updated.
PLAT-77722 …

PLAT-77722: Removed logic for restoring the scroll position on focus for old browsers

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Input/Input.js
packages/sampler/stories/default/Input.js
packages/sampler/stories/qa/Input.js

`focused` prop will be removed by #2200 in 3.0 and must be deprecated in 2.x
Mark the prop `@deprecated` and add a dev-mode wrapper to warn on prop usage.

PLAT-77194: Deprecate moonstone/Input.InputBase focused prop

---

packages/sampler/stories/qa/Header.js

Fixed to check whether marquee is flowing without touch or hover on cross-platform(iOS, Android) when the title of header component is long.
[qa-sampler] Added selector of marqueeOn prop to header sample to make it possible to test marquee with long title.

PLAT-77050: Update to check marqueeOn prop behavior with long title header

---

packages/core/CHANGELOG.md
packages/core/util/util.js
packages/moonstone/CHANGELOG.md
packages/moonstone/EditableIntegerPicker/EditableIntegerPicker.js
packages/moonstone/Input/Input.js
packages/moonstone/Picker/Picker.js
packages/moonstone/RangePicker/RangePicker.js
packages/moonstone/Slider/utils.js
packages/moonstone/internal/Picker/Picker.js

When `min` exceeded `max`, `EditableIntegerPicker`, `Picker`, and `RangePicker` would throw a runtime error from ramda's `clamp` method.
* Add a `clamp` method to `core/util` that safely clamps values
* Use `core/util.clamp` in the Pickers and Slider (which doesn't currently error but should use the same logic)
The logic used in clamp mirrors the logic used by `<input type="range">` in that it uses `min` as the value when `min` exceeds `max`.

ENYO-5920: Fix Pickers to not error when min > max

---

packages/moonstone/MoonstoneDecorator/MoonstoneDecorator.module.less

Android browser adds a tap highlight color to tapped elements and it clashes with Moonstone.
Make the tap highlight color be `transparent`.
PLAT-77150

PLAT-77150: Fix moonstone to suppress tap highlighting on Android

---

packages/moonstone/CHANGELOG.md
packages/moonstone/LabeledIcon/LabeledIcon.module.less
packages/moonstone/styles/variables.less

The text for `LabeledIcon` and `LabeledIconButton` is too large and doesn't match the designs.
The font size for the text of the aforementioned components has been decreased, to `24px`.

PLAT-78052: Updated LabeledIcon and LabeledIconButton text size

---

packages/moonstone/BodyText/BodyText.js
packages/moonstone/BodyText/BodyText.module.less
packages/moonstone/CHANGELOG.md
packages/moonstone/styles/variables.less
packages/sampler/stories/default/BodyText.js

The main BodyText size needs to be a bit smaller and an alternate size is needed as an option.
Font size decreased to 30px, added a `size` prop to allow the user to specify a "small" value for a font size of 27px. Also updated the Storybook sample.

PLAT-78047: Updated font size for BodyText and added size prop

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Panels/Panel.module.less
packages/moonstone/Panels/Panels.js
packages/moonstone/Panels/Panels.module.less
packages/moonstone/styles/variables.less

Panel rules must be updated to account for the new smaller `@moon-spotlight-outset` universal spacing rule.
Updated Panel and Panels margins/paddings. Included a PropTypes update to accommodate the newer `ref` format.
Included the new spotlight-outset spacing value (though it's duplicated by another PR) to make this PR more straightforward to review.
Also, some minor cleanup of CSS quoting characters.

PLAT-78053: Updated Panel and Panels margins/paddings

---

packages/ui/Scrollable/Scrollable.js
packages/ui/Scrollable/Scrollable.module.less
packages/ui/Scrollable/ScrollableNative.js

A flick gesture does not work smoothly on iOS
Added `-webkit-overflow-scrolling: touch` which is non-standard CSS property used only for Safari iOS for 'ui/ScrollableNative' to scroll smoothly.
PLAT-77904
https://developer.mozilla.org/ko/docs/Web/CSS/-webkit-overflow-scrolling

PLAT-77904: Fix flick action only for Safari browser on iOS

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/MediaSliderDecorator.js
packages/moonstone/VideoPlayer/VideoPlayer.js

`moonstone/VideoPlayer` doesn't support touch moves properly.
1. The media controls hiding timeout does not get reset when a user drags the knob and would eventually be closed. 
2. When `preview` is available, the knob would not follow the dragging position
Both of these are due to lack of touch move event handling.
Add `touchmove` event handlers that match the `mousemove` events.

PLAT-77089: Add touch move handlers for VideoPlayer

---

packages/sampler/src/MoonstoneEnvironment/MoonstoneEnvironment.js

Remove the duplicate `(Default)` from the knob

ENYO-5923: Remove duplicate label from locale knob

---

packages/spotlight/CHANGELOG.md
packages/spotlight/src/spotlight.js

On iOS, tapping non-spottable targets when another element is focused will not remove focus from it. Tapping on another focusable element will move focus to the new target.
Appears that when tapping a focusable element, iOS emits `mouseover` events triggering spotlight logic but it does not do so on non-focusable elements.
* Add a `touchend` handler in spotlight for touch platforms to blur the currently focused element if it doesn't contain the target of the touch event.

PLAT-76982: Fix spotlight to unspot when tapping on a non-spottable target

---

packages/sampler/.qa-storybook/addons.js
packages/sampler/.storybook/addons.js
packages/sampler/src/global.module.less

During cross-platform testing, the basic functionality of iOS safari and android chrome apps hinders testing.
iOS safari: When I try to scroll something in the sample, the entire viewport is moved, which interferes with the test.
Android chrome: When I try to scroll something downward, the page reloads with the reload icon, which interferes with the test.
- This issue is caused by the height of the samples being rendered larger than the viewport.
Add CSS to prevent sampler and qa-sampler apps from scrolling by placing CSS in the app body
- I changed samples to render to the viewport size, added CSS to disable the ios viewport movement and the android reload feature.
Code of css to prevent iOS viewport from being scrolled
`
body {
position: fixed;
width: 100%;
height: 100%;
}
`
Code of css …

PLAT-77739: [sampler, qa-sampler] Add css to prevent features that interfere with iOS, Android testing

---

packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js
packages/sampler/stories/qa/Scroller.js

Turning on `data-spotlight-container-disabled` in qa-sampler still allows touch devices to focus elements. The problem is two-fold. 1) Touch hold will focus the element on touch devices and 2) `SpotlightContainerDecorator` handles the focus event and prevents by checking `spotlightDisabled` prop, not `data-spotlight-container-disabled` attribute.
- Switch `data-spotlight-container-disabled` to `spotlightDisabled` in the sampler
Technically this would be enough to resolve the immediate issue, but also cleaned up the structure so that it respects `SpotlightContainerDecorator` props properly.
- Removed …

PLAT-77085: Remove data-spotlight-* props from Scrollable

---

packages/moonstone/Button/Button.module.less
packages/moonstone/styles/variables.less

New designs for the color-dot were supplied as well as custom margins for a special case, and the disabled+transparent Button looks awkward (being not transparent).
Changes include:
* Refactoring and cleanup color-dot rules and variables for better maintainability and readability, with included inline docs
* Large spacing between consecutive large buttons (30px)
* Removed bad disabled+transparent background color rule (we're back to always-transparent transparent buttons)
A CHANGELOG entry was **not** created for this because the existing 3.0.0 changelog already has an entry loosely describing what this PR does: "updated the appearance to match designs"
The `@moon-alt-font-family` variable was also updated in this PR to "Moonstone" due to its visual impact on this component. This is …

PLAT-78051: Updated Button designs

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js

In #2198, we removed the behavior of setting focus due to touch events in Touchable. This had a side-effect of preventing focus changes from a last-focused element when performing an initial touchstart event on a new element. This issue was most easily seen when changing focus from a list item to holding the scroll button - where a focused element would be recycled while scrolling in a list, resulting in obvious odd spotlight behavior.
This is a more localized fix than the one proposed in #2254 (which we concluded may have been too aggressively setting focus) and a more generalized approach than proposed in #2256 (where we set focus to the scroll buttons). I don't believe we want to set focus - rather letting the platform set focus as appropriate.
This fix merely removes focus when a …

PLAT:77174: Adjust focus in Scrollable due to touch events

---

packages/ui/CHANGELOG.md
packages/ui/Scrollable/Scrollable.module.less

The `Scrollable` component's container was using an incorrect value which could result in the horizontal scroll bar being rendered out of the viewport of the scroller.
We need to remove the specified `100%` height value and let the flex layout handle the height instead.

PLAT-78026: Adjust Scrollable container height

---

packages/moonstone/Panels/Header.js

Extra padding in the header when there are no header components
Don't render the headerComponents node if there are no children in it

 ENYO-5949: Header hides components block if there are none

---

packages/moonstone/Button/Button.module.less
packages/moonstone/CHANGELOG.md
packages/moonstone/EditableIntegerPicker/EditableIntegerPickerDecorator.js
packages/moonstone/ExpandableItem/ExpandableItem.js
packages/moonstone/ExpandableItem/ExpandableItem.module.less
packages/moonstone/Input/Input.module.less
packages/moonstone/LabeledItem/LabeledItem.module.less
packages/moonstone/MediaOverlay/MediaOverlay.module.less
packages/moonstone/Slider/Slider.js
packages/moonstone/Slider/Slider.module.less
packages/moonstone/VirtualList/VirtualListBase.js
packages/moonstone/internal/Picker/Picker.js
packages/moonstone/internal/Picker/Picker.module.less
packages/moonstone/internal/Picker/SpottablePicker.js
packages/moonstone/styles/colors-highcontrast.less
packages/moonstone/styles/colors-light-highcontrast.less
packages/moonstone/styles/colors.less
packages/sampler/stories/default/MediaOverlay.js
packages/sampler/stories/qa/Button.js
packages/spotlight/CHANGELOG.md
packages/spotlight/Spottable/Spottable.js
packages/spotlight/Spottable/tests/Spottable-specs.js

Disabled spottable elements should be focusable.
Update `Spottable` to allow focus onto disabled items.  Disabled items themselves are still non-interactive but can have spotlight.  Updated focus CSS for many items as disabled + focused was not used before.  Also, I removed the `isItemDisabled` property from VL and VGL.
Design of some components may still be in flux so it is possible these designs will …

PLAT-77054: Change components to allow disabled components to be focusable

---

packages/ui/CHANGELOG.md
packages/ui/Scrollable/ScrollableNative.js
packages/ui/Scroller/Scroller.js
packages/ui/VirtualList/VirtualListBase.js

[Safari only] Scroller and VirtualLists does not scroll and items disappear when RTL, Horizontal mode.
If the platform is safari or ios, I modified to scroll using the correct scrollLeft value.
- Chrome and Safari have different scrollLeft values in RTL, horizontal mode.
- Chrome: The left endpoint is 0, the right endpoint is the size of a positive content (e.g., 0 to 1000)
- Safari: The left endpoint is the size of negative content, the right endpoint is 0 (e.g., -1000 to 0)

PLAT-77177, 77175: Fix issues where scroller and lists does not scroll when in RTL, horizontal  mode

---

packages/sampler/stories/qa/Scroller.js

Touch devices invoke `focus` on long touch hold and focus handler in `SpotlightContainerDecorator` prevents focus on `spotlightDisabled` prop and not `data-spotlight-container-disabled` attribute.
Change qa sampler to use `spotlightDisabled` prop instead of `data-spotlight-container-disabled`
See https://github.com/enactjs/enact/pull/2265 for the other possible solution

PLAT-77085: Fix scroller sample to use spotlightDisabled

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/ScrollableNative.js
packages/sampler/stories/qa/Scroller.js
packages/ui/CHANGELOG.md
packages/ui/Scrollable/Scrollable.js
packages/ui/Scrollable/ScrollableNative.js

If a scroller/list is inside another scroller/list, wheel input invokes scrolling on both scrollers.
- Fixed a scroller/list to consume the wheel input when it scrolls on the input. If it does not scroll since it already reached to the edge on the direction, then the outer scroller/list can scroll by the wheel input.
- Added a prop `noScrollHorizontalByWheel` to disable horizontal scrolling by wheel which may be useful to disable the inner scroller for UX reasons
PLAT-76988

PLAT-76988: Add noScrollByWheel to prevent scrolling on wheel events

---

packages/moonstone/styles/variables.less

Breadcrumb text in Panels wraps when it really shouldn't, now with the new fonts.
Updated the font size to match the body text font size. (Probably in-line with the GUI/UX plan.)

PLAT-78612: Updated the font-size in breadcrumb to not wrap

---

packages/moonstone/Slider/SliderBehaviorDecorator.js
packages/spotlight/src/spotlight.js

On touch platforms, dragging an element before a press applies focus will result in focus not being applied with the drag/touch ends.
Rather than have `Spotlight` blur an incorrectly focused element, make it always focus the element that ends the touch.
PLAT-78459

PLAT-78459: Spotlight focus not applied to Slider knob after dragging

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js
packages/moonstone/VirtualList/VirtualListBase.js
packages/ui/Scrollable/Scrollable.js
packages/ui/Scrollable/ScrollableNative.js

Restore animation in `Scrollable` family
Revert changes from #2015. This entails removing animate/noAnimation props from the components. If we want to leave this option, then the fix should only fix the defaultProp value.

PLAT-74475: Restore animation in Scrollable family

---

packages/moonstone/Button/Button.js
packages/moonstone/CHANGELOG.md
packages/moonstone/Dropdown/Dropdown.js
packages/moonstone/ExpandableInput/ExpandableInput.js
packages/moonstone/Icon/Icon.js
packages/moonstone/IconButton/IconButton.js
packages/moonstone/Input/Input.js
packages/moonstone/ToggleButton/ToggleButton.js
packages/sampler/stories/default/Button.js
packages/sampler/stories/default/Dropdown.js
packages/sampler/stories/default/ExpandablePicker.js
packages/sampler/stories/default/IconButton.js
packages/sampler/stories/default/Input.js
packages/sampler/stories/default/LabeledIcon.js
packages/sampler/stories/default/LabeledIconButton.js
packages/sampler/stories/default/ToggleButton.js
packages/sampler/stories/qa/Button.js
packages/sampler/stories/qa/LabeledIcon.js
packages/sampler/stories/qa/LabeledIconButton.js
packages/sampler/stories/qa/ToggleButton.js

The latest design calls for all smaller components.
Default `size="small"` set for all components with a size prop.
Several tests/samples needed updates to support properly detecting of default values.

PLAT-78617: Update default size to "small"

---

packages/sampler/stories/qa/ContextualPopupDecorator.js

When `direction` prop is 'up', ContextualPopup shows only down direction in qa-sampler.
Compared to the develop branch, the ui-update branch has a reduced height of the header.
As a result, there is not enough space to display ContextualPopup above the button.
So I enlarged the space above the button to display ContextualPopup.

ENYO-5959: [qa-sampler] Fix to display ContextualPopup above the button when direction prop is up

---

packages/moonstone/Input/Input.module.less
packages/moonstone/styles/colors.less

…ocused.
The value was not visible when it's is disabled and focused. The color of the input is white and we lower the opacity of white color which doesn't affect anything.
Changed the color to black for disabled input so that it's value is visible for both not-focused and focused states.
Maybe we have applied low opacity on color white somewhere else.

ENYO-5950: Fix Input text to be visible when disabled and focused

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Slider/Slider.module.less

Dragging a Slider on touch platforms would scroll the viewport (if it could scroll).
Add `touch-action: none` to slider to prevent scroller when interacting.
Does allow scrolling when the slider is disabled. It _shouldn't_ scroll the sampler in this case either but that's a side effect of the sampler being a tad larger than the viewport. I have not fixed that issue here since it is sampler-specific and not a priority.

ENYO-5961: Fix slider to not scroll viewport on touch platforms

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/ScrollButtons.js

By enabling focus on disabled items, a focus should be able to move from a scrollbar button to the opposite button by page up/down key if `focusableScrollbar` is true in a scroller or a list.
Update a key handling logic to move a focus.
PLAT-78718

PLAT-78718: Update disabled scrollbars to get a focus on page up/down

---

packages/ui/Scrollable/Scrollable.module.less

This reverts code added by a previous commit to restore dropdown's sizing
I'm unclear as to what this change was made to support, or what the consequences outside of dropdown are for reverting this.

ENYO-5964: Restore full height Scrollable

---

packages/moonstone/ContextualPopupDecorator/ContextualPopup.js
packages/moonstone/ContextualPopupDecorator/ContextualPopup.module.less
packages/moonstone/styles/variables.less

Close button overlaps with the content of the contextual popup when `showClose` is set to true. This is because `.showArrow` class padding definition wins over `.reserveClose`.
Padding for the contextual popup is always 18px with or without showing the arrow so we can remove `.showArrow` and simply update the contextual popup padding value to 18px.

ENYO-5965: Fix ContextualPopup padding

---

packages/moonstone/styles/colors-light.less
packages/moonstone/styles/colors.less

`LabeledItem`'s item should have the same text color as the label.

ENYO-5966: Fix LabeledItem font color

---

packages/moonstone/IconButton/IconButton.module.less
packages/moonstone/Switch/Switch.module.less
packages/moonstone/styles/variables.less

as well as large-text Switch
IconButton and Switch are too translucent when disabled and focused.
Switch is misshapen when in large-text mode.
Updated/simplified the disabled focused rules for IconButton and Switch, added proper sizes for Switch in large-text mode

ENYO-5975: Fix Disabled+Focused IconButton and Switch

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/MediaControls.js

root cause is same as https://github.com/enactjs/enact/pull/2173
Change following function to arrow function
`areMoreComponentsAvailable`
`showMoreComponents`
`hideMoreComponents`
ENYO-5955

ENYO-5955: Fix ContextualPopupDecorator methods to be bound to the instance

---

packages/moonstone/CHANGELOG.md
packages/moonstone/DayPicker/DayPicker.js
packages/moonstone/RadioItem/RadioItem.module.less
packages/moonstone/SelectableItem/SelectableIcon.module.less
packages/moonstone/styles/variables.less

RadioItem and SelectableItem Icons are www.waytoobig.com
Added large-text mode sizing values and rules for these components.

ENYO-5978: Fixed large-text mode icon size for SelectableItem and RadioItem

---

packages/sampler/stories/qa/Button.js

…and only include relevant knobs
QA Sample is incorrect, not setting button sizes and including lots of irrelevant knobs for this test
Simplified the sample, statically assigned sizes, and updated the Divider to Heading instead.

ENYO-5980: Updated sample to statically set button sizes

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Dropdown/Dropdown.module.less
packages/moonstone/Item/Item.module.less
packages/moonstone/styles/variables.less

Dropdown shows scroll arrows with 5 items listed (when it shouldn't) in non-latin locales.
Item line-height was based on an `em` value in non-latin, which is variable and was adding one unintentional pixel to the Item height. This cascaded into problems with the Dropdown's sizing. Large-text mode support was also added to Dropdown so it always respects the design doc's wishes of "5 items visible without scrolling". The max-height was updated to correlate with the height of 5 items as well, instead of a static value.

ENYO-5982: Fix Dropdown item height in non-latin locales and large-text mode

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Input/Input.module.less
packages/moonstone/Panels/Header.js
packages/moonstone/Panels/Header.module.less
packages/moonstone/styles/colors.less

Caret color is too pink.
Caret color has been reverted to natural (default) state.
This is based on #2293 to allow validation of the caret color on a non-white background color. It's not 💯 necessary, but this hierarchy is helpful for testing.

PLAT-78894: Updated caret color for latest designs

---

packages/moonstone/Button/Button.module.less
packages/moonstone/CHANGELOG.md
packages/moonstone/styles/colors-light.less
packages/moonstone/styles/colors.less

The background colors for translucent and lightTranslucent Buttons are incorrect.
Updated translucent and lightTranslucent background colors in light and dark skins to match the design-intent.
In dark skin, the lightTranslucent button should appear identical to the normal button when on the default black background. Conversely, the sight skin translucent button should appear identical to the normal button when on the standard off-white background. All versions should have a translucent background, through which, you can see a background-image, if one is present behind the button.

ENYO-5986: Fix the color of the translucent family of buttons

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Heading/Heading.js
packages/ui/Heading/Heading.js

All `moonstone/Heading` components should have the same `spacing` (`"small"`) regardless of their `size` prop by default.
Set a default value for the `spacing` prop in `moonstone/Heading`.
PLAT-78893

PLAT-78893: Add moonstone/Heading prop spacing

---

packages/core/package.json
packages/i18n/package.json
packages/moonstone/package.json
packages/spotlight/package.json
packages/ui/package.json
packages/webos/package.json

* We previously restricted `prop-types` to a locked version in https://github.com/enactjs/enact/pull/2111/ as a way to avoid an issue with null values in `oneOf`.
* However the latest versions of React have greater dependencies of `prop-types`. As a result, there are multiple copies of `prop-types` within `./node_modules`
* Updates `prop-type` dependencies to `^15.7.2`.
* The `prop-types@15.7.2` release fixes the null `oneOf` issue, so we are safe to use that as a base for the variable-range.

ENYO-5990: Update prop-types to variable range dependency.

---

packages/sampler/CHANGELOG.md
packages/sampler/src/MoonstoneEnvironment/MoonstoneEnvironment.js
packages/sampler/stories/default/Header.js

There is no sample for Header and its many options. There is also no way to make alterations to the MoonstoneEnvironment kind.
Added both things!
Moonstone stories now accept props and toggle specific components' presence.

PLAT-79105: Add Header sample

---

packages/moonstone/CHANGELOG.md
packages/moonstone/MoonstoneDecorator/fontGenerator.js
packages/moonstone/styles/internal/fonts.less
packages/moonstone/styles/variables.less

The font definition file(s) refer to the PostScript names, which seem to not be available on the TV. The configs need to be updated to refer to the "full name" for the font files, rather than the PostScript names.
Updated font names
Also updated the defined name of the international font. Changed from "Moonstone LG Display" to "Moonstone Global" to be more in-line with a font-name-agnostic naming convention for the generalized fonts.

ENYO-5985: Fix font names from PostScript names to full names

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/ScrollButtons.js
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js
packages/moonstone/Scrollable/Scrollbar.js
packages/moonstone/Scroller/Scroller.js
packages/moonstone/VirtualList/VirtualListBase.js
packages/sampler/stories/qa/Scroller.js

If a user press 5-way `down` key on the last spottable component when there is non-spottable content at the end of a scroller, scroller's behavior depends on the position of the last spottable item and `focusableScrollbar` option. If `focusableScrollbar` is false, it can scroll to the end. If `focusableScrollbar` is true, the behavior will be determined by the relative position of the currently focused item and a scrollbar button.
So, user experience is not consistent and a user may need to move focus to a scrollbar button to see underlying contents.
The UX rule for `Scroller` is changed not to scroll to …

PLAT-77055: Change Scroller to scroll and focus button when no focus target found

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/MediaControls.js
packages/sampler/stories/default/VideoPlayer.js

Default button size is changed to small recently.
`MediaControls` currently follow default size.
Button size is explicitly changed to large.
ENYO-6001

ENYO-6001: Fix MediaControls to change button size to large

---

packages/moonstone/Divider/Divider.js

Doc warning when parsed, bad doc output
Text must come at top!
ENYO-6006

ENYO-6006: Fix doc warning in Divider

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Dropdown/Dropdown.js
packages/moonstone/ExpandableList/ExpandableList.js
packages/ui/Group/Group.js
packages/ui/Repeater/Repeater.js

Enact-DCO-1.0-Signed-off-by: Blake Stephens <blake.stephens@lge.com>
`Dropdown` uses `Group` internally, but doesn't accept the same set of features as `Group`
Updated the propType definition for `children` of `Dropdown` to include the same options as `Group`.

ENYO-5999: Extended Dropdown to support objects, like Group

---

packages/moonstone/VirtualList/VirtualListBase.js

There are some cases where 5way navigation in a VirtualList does not behave as expected
When a VirtualList calculates the next target to set focus, there were cases where it was not taking into account whether there were available controls to focus before attempting to set focus to them (whether the controls were disabled or no further controls were available in the specified direction).
I've attempted to modify how VirtualList decides where focus should change to by determining whether or not spottable controls are first available in the 5way direction pressed. It's tough determining where to set focus in some cases where there are disabled components - strictly from a VirtualList POV - since we want to set focus on the nearest eligible component using spotlight proximity rules. In cases …

PLAT-78786: Fix 5way navigation in VirtualList

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/Scrollable.js

Tapping within the input field of an expandable input would close the expandable. If you tapped in the right place at the right time, the pointer would also get locked by the input field.
Prevent blurring on touch start when spotlight is paused.
The pointer lock was a red herring in this case. It was caused by quickly tapping such that `InputSpotlightDecorator` lost and regained focus while the input was closing. Since it thought it had focus (but didn't), it locked the pointer. This was exacerbated by the logic in `SpotlightContainerDecorator` which would also blur the input (via `silentBlur()`) when the …

ENYO-5957: Fix Scroller to not blur when spotlight is paused

---

packages/moonstone/Dropdown/Dropdown.js

The dropdown would not display a title when using `children` of type array of objects. 
If the `children` are an array of objects, use the `children` prop of the object as the `title`. This behavior mirrors `ExpandableList`.

ENYO-5999: Dropdown title fix for children of type array-obj

---

packages/sampler/src/MoonstoneEnvironment/MoonstoneEnvironment.js

There's no gap between the Sampler Header and content.
`Slottable` does not recognize/handle `React.Fragment`. The Sampler Environment component was updated to use a more traditional component layout to allow `Slottable` to continue to function normally in this scenario.

ENYO-6007: Corrected spacing between Header and content

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Dropdown/Dropdown.js

If select a selected value again, selected is removed. Because selected will be null value.
I added select prop to `radio` to retain a selected value.
ENYO-6017

ENYO-6017: Change Dropdown to use radio selection
