enactjs/enact

packages/moonstone/GridListImageItem/GridListImageItem.js
packages/moonstone/Scroller/Scroller.js
packages/moonstone/VirtualList/VirtualList.js
packages/moonstone/VirtualList/VirtualListBase.js
packages/ui/Placeholder/PlaceholderControllerDecorator.js
packages/ui/Placeholder/PlaceholderDecorator.js
packages/ui/Placeholder/index.js
packages/ui/VirtualList/VirtualList.js

Cleanup the JSDoc for VirtualList, Scroller, and PlaceholderDecorator

Cleanup the JSDoc for VirtualList, Scroller, and PlaceholderDecorator

---

packages/moonstone/GridListImageItem/GridListImageItem.js
packages/moonstone/Scroller/Scroller.js
packages/moonstone/VirtualList/VirtualList.js
packages/moonstone/VirtualList/VirtualListBase.js
packages/ui/Placeholder/PlaceholderControllerDecorator.js
packages/ui/Placeholder/PlaceholderDecorator.js
packages/ui/Placeholder/index.js
packages/ui/VirtualList/VirtualList.js

Reverts enactjs/enact#1510
oops! We will do it later..

Revert "Cleanup the JSDoc for VirtualList, Scroller, and PlaceholderDecorator"

---

packages/moonstone/GridListImageItem/GridListImageItem.js
packages/moonstone/Scrollable/Scrollbar.js
packages/moonstone/Scroller/Scroller.js
packages/moonstone/VirtualList/VirtualList.js
packages/moonstone/VirtualList/VirtualListBase.js
packages/ui/Placeholder/PlaceholderControllerDecorator.js
packages/ui/Placeholder/PlaceholderDecorator.js
packages/ui/Placeholder/index.js
packages/ui/VirtualList/VirtualList.js

Cleanup the JSDoc for VirtualList, Scroller, and PlaceholderDecorator

PLAT-50771: Cleanup the JSDoc for VirtualList, Scroller, and PlaceholderDecorator

---

packages/sampler/stories/qa-stories/ProgressBar.js

Update ProgressBar QA sample
ENYO-5065

ENYO-5065: Update ProgressBar QA Sample

---

packages/ui/CHANGELOG.md
packages/ui/Scroller/Scroller.js

horizontal scrolling in RTL locale caused exception
ENYO-5127

Fix Scroller RTL position calculation

---

packages/core/internal/Broadcast/Broadcast.js
packages/core/internal/Broadcast/Subscriber.js
packages/moonstone/ContextualPopupDecorator/ContextualPopup.js
packages/moonstone/ContextualPopupDecorator/ContextualPopupDecorator.js
packages/moonstone/DaySelector/DaySelectorItem.js
packages/moonstone/EditableIntegerPicker/EditableIntegerPicker.js
packages/moonstone/EditableIntegerPicker/EditableIntegerPickerDecorator.js
packages/moonstone/ExpandablePicker/ExpandablePicker.js
packages/moonstone/Input/InputDecoratorIcon.js
packages/moonstone/Notification/Notification.js
packages/moonstone/Panels/Breadcrumb.js
packages/moonstone/Panels/Routable.js
packages/moonstone/Panels/Router.js
packages/moonstone/Picker/Picker.js
packages/moonstone/Popup/Popup.js
packages/moonstone/RangePicker/RangePicker.js
packages/moonstone/Scrollable/ScrollButton.js
packages/moonstone/Scrollable/ScrollButtons.js
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js
packages/moonstone/VideoPlayer/MediaTitle.js
packages/moonstone/VideoPlayer/Times.js
packages/moonstone/internal/Picker/Picker.js
packages/ui/Item/Item.js
packages/ui/Scrollable/Scrollable.js
packages/ui/Scrollable/ScrollableNative.js
packages/ui/Scrollable/Scrollbar.js
packages/ui/Spinner/Spinner.js
packages/ui/ToggleItem/ToggleItem.js
packages/ui/ViewManager/View.js

Some props that are required were not labeled as such.
PLAT-53082
Enact-DCO-1.0-Signed-off-by: Dave Freeman dave.freeman@lge.com

PLAT-53082: Enact docs: ensure @required doc tags for required props

---

packages/ui/CHANGELOG.md
packages/ui/Placeholder/PlaceholderControllerDecorator.js
packages/ui/Placeholder/PlaceholderDecorator.js

Render performance of ui/Placeholder was poor. I also noticed some weird scrolling artifacts likely introduced by the boundary scrolling logic added since this code was originally implemented.
* Converted ui/Placeholder.PlaceholderDecorator to be a `PureComponent` to limit the perf impact
* Add a `thresholdFactor` config option to `PlaceholderControllerDecorator` to better configure and determine when to render new elements
We could probably further optimize this …

PLAT-48047: Improve render performance of ui/Placeholder

---

packages/moonstone/Slider/Slider.less
packages/moonstone/VideoPlayer/VideoPlayer.less
packages/ui/Slider/Knob.js
packages/ui/Slider/Slider.js
packages/ui/Slider/Slider.less

Refactored Slider's pieces to position friendlier

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Notification/Notification.less

Added a positioning rule for RTL
ENYO-5135

ENYO-5135: Notification RTL Positioning Fix

---

docs/accessibility.md
docs/creating-components.md
docs/testing-components/test-driven-development/index.md
docs/why-use-kind.md

Fix broken link and typo error in enact web page
PLAT-53275
Enact-DCO-1.0-Signed-off-by: Jeonghee Ahn jeonghee27.ahn@lge.com

PLAT-53275: Fix broken link and documentation errors

---

packages/webos/VoiceControlDecorator/package.json
packages/webos/VoiceReadout/package.json
packages/webos/speech/VoiceControlDecorator.js
packages/webos/speech/index.js
packages/webos/speech/package.json
packages/webos/speech/readAlert.js

Consolidate speech modules

---

packages/sampler/stories/moonstone-stories/VirtualGridList.js
packages/sampler/stories/moonstone-stories/VirtualList.js

Accidently sampler of VirtualList and VirtualGridList modified to Natives 
Roll back the mistake

Fix sampler of VirtualList and VirtualGridList

---

packages/moonstone/Panels/ApplicationCloseButton.js
packages/moonstone/Scrollable/ScrollButton.js
packages/moonstone/internal/DateComponentPicker/DateComponentPicker.js

PLAT-54712: Fix doc errors

---

packages/moonstone/CHANGELOG.md
packages/moonstone/ToggleButton/ToggleButton.less

Support RTL positioning and padding using padding and position mixins
ENYO-5125

ENYO-5125: Fix moonstone/ToggleButton layout in RTL locales

---

packages/moonstone/VideoPlayer/Video.js

removed loadstart workarounds

---

packages/moonstone/DatePicker/tests/DatePicker-specs.js
packages/moonstone/ExpandablePicker/tests/ExpandablePicker-specs.js
packages/moonstone/TimePicker/tests/TimePicker-specs.js
packages/moonstone/internal/Picker/tests/Picker-specs.js

Added a11y unit test of DatePicker, ExpandablePicker, TimePicker, internal/Picker
PLAT-54096

PLAT-54096: Add unit test for DatePicker, ExpandablePicker, TimePicker, internal/Picker

---

packages/moonstone/Button/Button.js
packages/moonstone/CHANGELOG.md
packages/moonstone/IconButton/IconButton.js
packages/moonstone/IconButton/IconButton.less

If IconButton is customized, the Icon doesn't respect the new size.
This updates `IconButton` to allow consumers to customize the vertical alignment of the internal `Icon` component by setting the `line-height` property

ENYO-5143: Fix IconButton to allow adjustments to Icon vertical alignment

---

packages/webos/speech/VoiceControlDecorator.js
packages/webos/speech/readAlert.js

Add a description of how to use VoiceControlDecorator component

PLAT-57949: Add description to VoiceControlDecorator

---

packages/sampler/stories/qa-stories/Header.js

Add `subTitleBelow` to Header QA-Sample
ENYO-5260

ENYO-5260: Header QA-Sample add subTitleBelow knob

---

docs/migration/index.md
docs/migration/migrating-enact-apps.md

Added a migration guide for Enact 1.x to 2.0.
ENYO-5200
Enact-DCO-1.0-Signed-off-by: Dave Freeman dave.freeman@lge.com

ENYO-5200: Enact docs: prepare 1.x to 2.0 migration guide

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/FeedbackIcons.js
packages/moonstone/VideoPlayer/FeedbackTooltip.js
packages/moonstone/VideoPlayer/VideoPlayer.js

The video feedback wasn't working according to spec.
Some changes were made in the past to `FeedbackIcons` we're reverting some so `Feedback` and `MiniFeedback` work properly. Also added some logic so play should work properly now.
ENYO-5187

ENYO-5187: Fix VideoPlayer feedback timeouts

---

docs/contributing/index.md

Add links to GitHub

---

packages/i18n/README.md

There was a link that could not be connected.
There is typos.
Edited links that can't connect
Edited typo in Docs
PLAT-58654

PLAT-58654: Fix readme file (enact/i18n)

---

packages/moonstone/ExpandableItem/ExpandableItem.js
packages/moonstone/Input/Input.js
packages/moonstone/Input/util.js

Voice control related attribute added to input tag for support voice control.

PLAT-58152: Fix forwarding voice control props for Input and ExpandableItem

---

packages/moonstone/VideoPlayer/Video.js

Change `<Video>`'s `noAutoPlay` to `autoPlay`

ENYO-5307: Change noAutoPlay to autoPlay in Video

---

packages/moonstone/CHANGELOG.md
packages/moonstone/ToggleButton/ToggleButton.less
packages/moonstone/styles/variables.less

Removed redundant RTL rules and apply proper position and padding mixin to `.small` as well.
ENYO-5318

ENYO-5318: Small ToggleButton RTL CSS fix

---

docs/creating-components.md
docs/theming.md

No docs on theming
Added docs on theming

PLAT-50075: Added introduction to component customization docs

---

docs/migration/migrating-enyo-apps.md
packages/core/handle/handle.js
packages/core/handle/tests/handle-specs.js
packages/core/keymap/tests/keymap-specs.js
packages/spotlight/src/container.js
packages/spotlight/src/spotlight.js
packages/spotlight/src/tests/pointer-specs.js
packages/ui/Cancelable/modalHandler.js
packages/ui/Changeable/tests/Changeable-specs.js

Fix docs and comments to use "falsy"

---

packages/sampler/src/MoonstoneEnvironment/MoonstoneEnvironment.js
packages/sampler/stories/qa-stories/ExpandableList.js

QA-sample add default selected ExpandableList
ENYO-5047

ENYO-5047: Add QA sample for ExpandableList with default selection

---

docs/contributing/documentation.md
packages/moonstone/Dialog/Dialog.js
packages/moonstone/Input/Input.js
packages/ui/Touchable/Touchable.js

Docs were not up-to-date with our standard
Updated and added a section on tone.

Update documentation guidelines

---

packages/moonstone/SwitchItem/SwitchItem.js
packages/moonstone/ToggleButton/ToggleButton.js

Change intent name from SelectToggleItem to SetToggleItem

PLAT-61178: Change intent name of toggle item

---

docs/performance.md

Need Docs for performance
PLAT-61027

PLAT-61027 - Add Performance Docs

---

packages/webos/LS2Request/LS2Request.js
packages/webos/application/application.js
packages/webos/deviceinfo/deviceinfo.js
packages/webos/docs/luna-service-api.md
packages/webos/docs/webos-features.md
packages/webos/keyboard/keyboard.js
packages/webos/platform/platform.js
packages/webos/pmloglib/pmloglib.js
packages/webos/speech/VoiceControlDecorator.js
packages/webos/speech/index.js
packages/webos/speech/readAlert.js

ENYO-4992: Update webos module docs

---

packages/moonstone/EditableIntegerPicker/EditableIntegerPicker.js
packages/moonstone/ExpandablePicker/ExpandablePicker.js
packages/moonstone/IncrementSlider/IncrementSlider.js
packages/moonstone/Picker/Picker.js
packages/moonstone/RangePicker/RangePicker.js
packages/moonstone/VideoPlayer/MediaControls.js
packages/moonstone/internal/Picker/Picker.js

Fix missing link in docs for icons

---

packages/i18n/util/util.js

Fix missing memberof tag in i18n/util

---

packages/core/dispatcher/dispatcher.js
packages/core/handle/handle.js
packages/core/hoc/hoc.js
packages/core/keymap/index.js
packages/core/keymap/keymap.js
packages/core/kind/computed.js
packages/core/kind/kind.js
packages/core/kind/styles.js
packages/core/platform/platform.js
packages/core/snapshot/snapshot.js
packages/core/util/Job.js
packages/core/util/util.js

Docs are refreshed to meet documentation guidelines.
PLAT-61276
Enact-DCO-1.0-Signed-off-by: Dave Freeman (dave.freeman@lge.com)

PLAT-61276: Update core docs

---

docs/contributing/documentation.md

Clarify how to document properties and methods.

Clarify doc standards

---

packages/moonstone/Popup/Popup.js
packages/moonstone/Spinner/Spinner.js

Some important docs were missing from `Popup` and `Spinner`

Clarify popup and spinner docs

---

docs/interoperability.md

Added Docs for Interoperability with third-party libraries
PLAT-61631
Enact-DCO-1.0-Signed-off-by: Derek Tor <derek.tor@lge.com>

PLAT-61631 - Added Docs for Interoperability

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js

Fix unexpected scrolling animation when calling scrollTo API
Move settings some values inside the condition that starts scroll
ENYO-5424

ENYO-5424: VirtualListNative: scroll animation occurs when calling scrollTo with animate false (1 QE)

---

packages/moonstone/DatePicker/DatePickerBase.js
packages/moonstone/ExpandableItem/ExpandableItem.js
packages/moonstone/Picker/Picker.js
packages/moonstone/RangePicker/RangePicker.js
packages/moonstone/TimePicker/TimePickerBase.js
packages/moonstone/internal/DateComponentPicker/DateComponentPicker.js
packages/moonstone/internal/DateComponentPicker/DateComponentRangePicker.js
packages/moonstone/internal/Picker/Picker.js

- This PR will be support picker value setting with voice
(Picker, RangePicker, DatePicker, TimePicker are added this feature)
- "Select" intent is used for implement this feature
- When user speak like "Group Name" + "value", matched value will be set in Picker
PLAT-58297

PLAT-58297: Add voice control to Pickers

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/FEATURE.md
.github/ISSUE_TEMPLATE/SUPPORT.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
SUPPORT.md
docs/contributing/dco.md

Adds issue templates
Don't know if it works!  No way to preview, AFAIK.
Perhaps I should rebase this back to `master` so we can try it out now?

ENYO-5348: Add issue templates

---

packages/moonstone/Panels/Header.js
packages/moonstone/Panels/index.js
packages/sampler/src/enact-knobs/boolean.js
packages/sampler/src/enact-knobs/number.js
packages/sampler/src/enact-knobs/object.js
packages/sampler/src/enact-knobs/select.js
packages/sampler/src/enact-knobs/text.js
packages/sampler/stories/moonstone-stories/RadioItem.js
packages/sampler/stories/moonstone-stories/VideoPlayer.js
packages/sampler/stories/qa-stories/Header.js
packages/sampler/stories/qa-stories/RadioItem.js

Sampler: VideoPlayer: Selecting 'noAutoPlay' knob causes console 'Uncontrolled input' Warning
Set defaultValue for boolean props that are not defined to false.

ENYO-5431 Sampler: VideoPlayer: Selecting 'noAutoPlay' knob causes console 'Uncontrolled input' Warning

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Popup/Popup.js
packages/spotlight/CHANGELOG.md
packages/spotlight/src/container.js
packages/spotlight/src/spotlight.js

ENYO-5482 When popup is open, focus to background item (1 QE)
Set active container correctly and spot on the content of popup.

ENYO-5482: Fix restricting spotlight to Popup when open on mount

---

packages/moonstone/internal/Picker/PickerButton.js
packages/ui/CHANGELOG.md
packages/ui/Skinnable/Skinnable.js

We discovered non-trivial performance improvements on low powered devices using the new context API for Skinnable which is used in every component in the framework.
* Adopt new context API
* Remove `withSkinnableProps` method which is no longer applicable and can be fulfilled using `Skinnable` if necessary.

PLAT-62487: Update ui/Skinnable to use new context API

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/VideoPlayer.js
packages/sampler/stories/moonstone-stories/VideoPlayer.js

An alternative to #1805 to control auto showing with props

ENYO-5434: Add prop for auto showing media controls in VideoPlayer

---

.github/PULL_REQUEST_TEMPLATE.md
docs/contributing/index.md

Update contributing and PR template

---

packages/moonstone/CHANGELOG.md
packages/moonstone/GridListImageItem/GridListImageItem.js
packages/moonstone/GridListImageItem/GridListImageItem.less
packages/ui/GridListImageItem/GridListImageItem.less

Having the aspect ratio of the GridListImageItem be variable based on which text is present seems like a component design problem. 
Make the images in the GridListImageItem visually lined up
ENYO-5426

ENYO-5426: Make the images visually lined up

---

packages/ui/CHANGELOG.md

Downgrade change to a fix

---

packages/sampler/stories/moonstone-stories/Slider.js

[Sampler] Slider: action logger added for existing sampler to verify 'onActivate'
Enact-DCO-1.0-Signed-off-by: Hailey Ryu <hangyeolryu@lge.com>:

ENYO-5477: Added Action logger for the slider onActivate.

---

packages/moonstone/Icon/Icon.js
packages/ui/Touchable/config.js
packages/webos/platform/platform.js

Found some documentation errors while investigating a docs feature

Fix jsdoc errors

---

packages/sampler/stories/qa-stories/LabeledIcon.js
packages/sampler/stories/qa-stories/LabeledIconButton.js

The QA samples for LabeledIcon and LabeledIconButton are confusing and unhelpful.
Simplified the samples by giving them a specific purpose and improved their usability.

ENYO-5534: Simplified and improved QA Stories

---

packages/sampler/stories/qa-stories/Scroller.js

ENYO-5553: Added sample to qa-sampler with many ExpandableLists

---

packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js
packages/ui/Scrollable/Scrollable.js
packages/ui/Scrollable/ScrollableNative.js

Refactored overscroll logic.
Removed redundant code.
Note: No change log. This PR is to refactor code and no behavior or API is changed.
PLAT-63105

PLAT-63105: Refactored overscroll logic

---

packages/moonstone/Picker/Picker.js

Example code would render poorly when correct CSS applied.
Change sample to send an array rather than a collection of elements.
ENYO-5565

Fix picker sample

---

packages/moonstone/Scrollable/ScrollableNative.js
packages/moonstone/VirtualList/VirtualListBase.js
packages/spotlight/SpotlightContainerDecorator/SpotlightContainerDecorator.js
packages/spotlight/src/container.js

ENYO-5562: Optimize spotlight container configuration

---

packages/spotlight/Pause/Pause.js
packages/spotlight/src/spotlight.js

The documentation for `spotlight/Pause` was wrong and reflected and earlier design that wasn't implemented.
Fix the documentation and add `@function` pragmas to the global pause/resume methods that were rendering wrong

ENYO-5631: Fix spotlight/Pause documentation

---

packages/sampler/stories/qa/Popup.js

QA sample for Popup from self-only container.
Add test case for check when Popup is triggered from self-only container.
ENYO-5557
GT-25753

ENYO-5557: Add QA sample for Popup from self-only container

---

packages/ui/Marquee/Marquee.less
packages/ui/Marquee/MarqueeController.js

Update marquee docs

---

packages/sampler/stories/qa/Scroller.js

ENYO-5673: Add Top Most Visible Item in the Scroller sample to QA sampler

---

packages/i18n/I18nDecorator/I18nDecorator.js
packages/i18n/Uppercase/Uppercase.js
packages/moonstone/DaySelector/DaySelectorDecorator.js
packages/moonstone/EditableIntegerPicker/EditableIntegerPickerDecorator.js
packages/moonstone/ExpandablePicker/ExpandablePickerDecorator.js
packages/moonstone/Image/Image.js
packages/moonstone/MoonstoneDecorator/AccessibilityDecorator.js
packages/moonstone/MoonstoneDecorator/I18nFontDecorator.js
packages/moonstone/Spinner/Spinner.js
packages/moonstone/VideoPlayer/MediaControls.js
packages/moonstone/VideoPlayer/MediaSliderDecorator.js
packages/ui/RadioDecorator/RadioControllerDecorator.js
packages/ui/Slider/PositionDecorator.js
packages/webos/speech/VoiceControlDecorator.js

Disable unused variable warning for hoc config

---

packages/sampler/stories/qa/Scroller.js

ENYO-5679 Add QA sample for Scroller with 2 ExpandableLists

---

packages/core/util/Job.js

This patch cleans up `Job` a little to add a type for throttled jobs and to ensure that all instances of the job execution are performed by `run`.
ENYO-5665
Enact-DCO-1.0-Signed-off-by: Dave Freeman dave.freeman@lge.com

ENYTO-5665: Job needs cleanup

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js
packages/moonstone/VirtualList/VirtualListBase.js
packages/ui/CHANGELOG.md
packages/ui/Scrollable/Scrollable.js
packages/ui/Scrollable/ScrollableNative.js

Fix stuttering issue by disabling animation with 5-way navigation
Allow `animate` as a prop and use it to branch whether it animate or not
Not pass to `ui/VirtualListBase` at this time since it doesn't have any logic relate to animation
PLAT-64690
Enact-DCO-1.0-Signed-off-by: Yeram Choi yeram.choi@lge.com

PLAT-64690: Disable scroll animation with 5-way navigation

---

.travis.yml
packages/sampler/stories/qa/Header.js

* 2.2.8 release branch was using `develop` CLI branch, which now contains the edge Jest work. This caused failures in Travis
* Use `5382f263d24c112195166ae3e45edca8ae96b232` CLI commit just before Jest was merged to test on Travis using old/stable CLI with Karma/PhantomJS. (gets arounds Enzyme issue currrently being invesigated which will allow us to switch again to `#master`)

Use master CLI branch for 2.2.8 release branch in Travis.

---

packages/moonstone/Button/tests/Button-specs.js
packages/moonstone/DatePicker/tests/DatePicker-specs.js
packages/moonstone/ExpandableItem/tests/ExpandableItem-specs.js
packages/moonstone/ExpandableList/tests/ExpandableList-specs.js
packages/moonstone/ExpandablePicker/tests/ExpandablePicker-specs.js
packages/moonstone/IncrementSlider/tests/IncrementSlider-specs.js
packages/moonstone/Input/tests/Input-specs.js
packages/moonstone/Picker/tests/Picker-specs.js
packages/moonstone/Popup/tests/Popup-specs.js
packages/moonstone/TimePicker/tests/TimePicker-specs.js
packages/ui/VirtualList/tests/VirtualList-specs.js

Components should be checked voice control related props
Add unit test to components
ENYO-5742

ENYO-5742: Add unit tests of voice control for moonstone components

---

packages/sampler/stories/qa/Scroller.js

ENYO-5702: Within QA-Sampler Focus target is inconsistent with sample code
Added ScrollerWithSpotlightTargetCalculation sample.

ENYO-5702: Add QA sample to test navigating into an overflow container

---

packages/moonstone/Slider/SliderBehaviorDecorator.js

* [] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [] At least one test case is included for this feature or bug fix
* [] This is an API breaking change
Updated Slider to use getDerivedStateFromProps.
PLAT-72736

PLAT-72736: Update Slider to getDerivedStateFromProps

---

packages/moonstone/TimePicker/TimePickerBase.js

Update lifecycle in `TimePickerBase`
PLAT-72737

PLAT-72737: TimePickerBase - Update lifecycle method

---

packages/moonstone/Panels/Router.js
packages/moonstone/Panels/tests/Router-specs.js

Update modal component life cycle methods to adapt new API.
Compute the route object on render
Could consider memoizing the computation later but it is a premature optimization at this point
Enact-DCO-1.0-Signed-off-by: Hailey Ryu hangyeol.ryu@lge.com

PLAT-72735: Router - update router lifecyle method

---

packages/ui/Touchable/Touchable.js

Updating the `ui/Touchable` lifecycle method to not use `UNSAFE_componentWillReceiveProps`

PLAT-72742: Update ui/Touchable lifecycle method

---

packages/sampler/stories/qa/Scroller.js

ENYO-5775: Add QA sample to test scroller and marquee

---

packages/core/kind/kind.js
packages/moonstone/Panels/Panels.js

Revise types for a couple docs for better TS compatibility

PLAT-68622: Update docs for Panels and kind()

---

packages/moonstone/ExpandablePicker/ExpandablePicker.js
packages/moonstone/ExpandablePicker/ExpandablePickerDecorator.js

Update lifecycle in `ExpandablePickerDecorator` 
PLAT-72733

PLAT-72733: ExpandablePicker lifecycle update

---

packages/moonstone/VideoPlayer/VideoPlayer.js

`getDurFmt` was not guarded for isomorphic rendering
Add a `window` check before calling the memoized version

PLAT-73840: Fix DurFmt retrieval for isomrphic rendering

---

.travis.yml
packages/core/kind/tests/computed-specs.js
packages/core/kind/tests/styles-specs.js
packages/ui/Group/tests/Group-specs.js

New linting errors and a Travis testing failure were discovered overnight.
* Remove the unnecessary `globals` definitions
* Switch tests to `--runInBand` instead of `--maxWorkers`

PLAT-73957: Fix linting errors post 2.3.0 release

---

.travis.yml
packages/i18n/package.json

Added code coverage analysis through codecov
Theoretically working but unsure when/how it will get the base branch for comparison.
Adds a comment on the PR with the coverage report.
Does not fail PR for coverage changes -- informational only
Could be too spammy, have to see.
PLAT-72247

Test code coverage

---

packages/moonstone/ExpandableList/ExpandableList.module.less
packages/sampler/CHANGELOG.md
packages/sampler/package.json
packages/sampler/src/MoonstoneEnvironment/MoonstoneEnvironment.js
packages/sampler/src/MoonstoneEnvironment/MoonstoneEnvironment.module.less

* Setting background images is not as useful as it should be
* Custom QUERY_STRING handling is unnecessary and can be offloaded into a module
* Several layers of DOM are unnecessary
* getPropFromURL is cumbersome to use for Boolean knobs
* Story description is never set
* Classes aren't being applied to MoonstoneEnvironment correctly
Numerous bits of refactoring. The most noticible bits are the background image is now blured and faded to improve text readability and it responds to the skin background color; as well as the story description now (finally) displays on each story.
We may have to hide the descriptions if it causes problems, however they likely won't be technical, just preferential. The usefulness of the descriptions will improve over time, now that they'd be visible instead of …

ENYO-5815: Storybook Improvements

---

packages/moonstone/Button/Button.module.less
packages/moonstone/CHANGELOG.md
packages/moonstone/Checkbox/Checkbox.module.less
packages/moonstone/DaySelector/DaySelector.module.less
packages/moonstone/EditableIntegerPicker/EditableIntegerPicker.module.less
packages/moonstone/GridListImageItem/GridListImageItem.module.less
packages/moonstone/Input/Input.module.less
packages/moonstone/RadioItem/RadioItem.module.less
packages/moonstone/Scrollable/Scrollbar.js
packages/moonstone/Scrollable/Scrollbar.module.less
packages/moonstone/Slider/Slider.module.less
packages/moonstone/Switch/Switch.module.less
packages/moonstone/ToggleButton/ToggleButton.module.less
packages/moonstone/VideoPlayer/Overlay.js
packages/moonstone/VideoPlayer/VideoPlayer.module.less
packages/moonstone/internal/Picker/Picker.module.less
packages/moonstone/styles/colors-highcontrast.less
packages/moonstone/styles/colors-light-highcontrast.less
packages/moonstone/styles/colors-light.less
packages/moonstone/styles/colors.less
packages/moonstone/styles/skin.less
packages/moonstone/styles/variables.less

PLAT-64279: High Contrast color support.
The high contrast for dark and light skins. Also alphabethesized the order of variable sections in `colors.less` and `colors-light.less`
PLAT-64279

PLAT-64279: High Contrast color support

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Spinner/Spinner.js
packages/moonstone/Spinner/Spinner.module.less
packages/moonstone/styles/colors-light.less
packages/moonstone/styles/colors.less
packages/moonstone/styles/variables.less
packages/sampler/stories/default/Spinner.js
packages/ui/CHANGELOG.md
packages/ui/Spinner/Spinner.js

New design for a Spinner has come in and it's pretty different.
Built a first attempt at implementing the new designs. Some new variables were added to support the current customizability of it.
It _should_ be a drop-in replacement for the existing spinner, but you never know with these things.

PLAT-73235: Updated Spinner to new GUI spec

---

docs/interoperability.md
docs/migration/enact/migrating-to-enact-2.md
docs/theming.md

Documentation is needed for integrating Enact with existing projects and other libraries.
Added documentation for how to integrate Enact with existing projects and other libraries:
- Using third-party components in Enact apps
- Using Enact in React apps
- Special case for using `@enact/i18n` in ejected CRA apps
In order to get the style override example to work, I had to use `!important` which is :sadpanda:
PLAT-74086

PLAT-74086: Update interop docs for 2.3.0

---

packages/sampler/stories/qa/Tooltip.js

`<i>` was deprecated more than a decade ago.
`<em>` replaced it.

Let's use em

---

CHANGELOG.md

Section got lost in CHANGELOG
Found it!

Add missing CHANGELOG section

---

packages/sampler/stories/qa/BodyText.js

ENYO-5888: Add BodyText to QA sampler 

---

packages/sampler/stories/qa/Tooltip.js

We were referencing an undefined key in state thereby breaking the "toggle" logic.
Reference the correct state member

ENYO-5905: Fix QA Tooltip sample typo

---

packages/moonstone/ExpandableInput/ExpandableInput.js
packages/moonstone/ExpandableInput/ExpandableInput.module.less
packages/moonstone/Input/Input.module.less
packages/moonstone/Input/InputDecoratorIcon.js
packages/moonstone/styles/colors-light.less
packages/moonstone/styles/colors.less
packages/moonstone/styles/variables.less

PLAT-73234: Update design of moonstone/Input

---

packages/ui/Scrollable/ScrollableNative.js

Fix made in #1891 does not contribute any perf improvement and create complexity.
Remove `requestAnimationFrame` from onScroll handler

ENYO-5909: Remove rAF in onScroll handler

---

packages/moonstone/TooltipDecorator/TooltipDecorator.js

`TooltipDecorator` had out-of-date and unclear docs.
Improve it.
Requires related docs PR
ENYO-5899

Update docs for TooltipDecorator

---

packages/moonstone/MoonstoneDecorator/fontGenerator.js
packages/moonstone/styles/internal/fonts.less

We've received new font files with their (perhaps) final names.
Updated the main fonts file and the references to the "Global" font name in the fontGenerator code.

PLAT-75399: Updated font names

---

packages/moonstone/VirtualList/VirtualListBase.js
packages/spotlight/src/spotlight.js

When focus changes between items within a `VirtualList`, the spotlight and/or keydown-driven events take too long - which add to poor performance when scrolling. This is especially the case when holding 5-way to navigate - where focus changes accelerate and occur rapidly.
When using spotlight to direct 5-way navigation, there is some inherent overhead that comes along with it. Spotlight must curate the available spottable controls and calculate where to set focus next. In the case of `VirtualList`, we have a contained/known amount of components, so we can specify where to set focus - saving some time. Ultimately, we can shave 1/3 of the time off a single event.
There are some other micro-optimizations that have been made in the event-handling logic to help speed up those rapidly-occurring …

PLAT-75887: VirtualList Perf - Manage focus within VirtualList

---

packages/sampler/stories/qa/Button.js
packages/sampler/stories/qa/Button.module.less

PLAT-77661: QA Sampler-Button with tap area displayed: added taparea to IconButton and a divider to viewport

---

packages/sampler/stories/qa/ContextualPopupDecorator.js

PLAT-77119 - Added sample to test change layout to arrow function

---

packages/sampler/stories/qa/Button.js
packages/sampler/stories/qa/Button.module.less

Revert "PLAT-77661: QA Sampler-Button with tap area displayed: added taparea to IconButton and a divider to viewport"

---

packages/moonstone/VirtualList/VirtualListBase.js

VGL did not account for RTL when in vertical mode
Refactor logic to adjust direction for RTL/LTR

ENYO-5933: Fix 5-way navigation for RTL with VirtualGridList

---

packages/moonstone/EditableIntegerPicker/EditableIntegerPicker.module.less
packages/moonstone/styles/colors-highcontrast.less
packages/moonstone/styles/colors-light-highcontrast.less
packages/moonstone/styles/colors.less

`moonstone/EditableInteger` needs to be updated to stay consistent with `moonstone/Input`
3px focus border for non high contrast and 6px focus border for high contrast

PLAT-77910: Update design of EditableIntegerPicker

---

packages/moonstone/Input/Input.module.less
packages/moonstone/styles/colors-highcontrast.less
packages/moonstone/styles/colors-light-highcontrast.less
packages/moonstone/styles/colors.less

As per Crane: thicker focus outline for high contrast Input (6px)
PLAT-76788

PLAT-76788: Update designs for Input in high contrast

---

packages/moonstone/Button/Button.module.less
packages/sampler/stories/qa/Button.js

The clickable area in IconButton is too large (exceeds the round bounds of the visible part of IconButton). Update QA sample to include IconButton, now that IconButton and Button are different shapes.
Fixed IconButton showing a false positive when focusing a corner.
Update QA sample to include headings and IconButtons of both sizes.

PLAT-77661: Add IconButton to Taparea QA-sample

---

packages/sampler/stories/default/ExpandableInput.js

ENYO-5940: Updated display name in ExpandableInput

---

packages/moonstone/CHANGELOG.md
packages/moonstone/ContextualPopupDecorator/ContextualPopup.js
packages/moonstone/ContextualPopupDecorator/ContextualPopup.module.less
packages/moonstone/ContextualPopupDecorator/ContextualPopupDecorator.js
packages/moonstone/styles/colors-light.less
packages/moonstone/styles/colors.less
packages/moonstone/styles/variables.less

Update contextual popup GUI
- change border radius
- change border color
- change border width
- adjust arrow SVG accordingly to match the new border width
- add drop shadow

PLAT-73522: Change ContextualPopup appearance to match new designs

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Notification/Notification.module.less
packages/moonstone/styles/colors-light.less
packages/moonstone/styles/colors.less
packages/moonstone/styles/variables.less

Update `moonstone/Notification` styles to match the latest GUI design doc
Changes:
- border changed
- add box shadow
- button gaps updated
- padding updated
- GUI doc specifies #EFEFEF to be the background color, but I left it as-is to match all light-skin color background

PLAT-77851: Change Notification appears to match new designs

---

packages/moonstone/CHANGELOG.md
packages/moonstone/FormCheckbox/FormCheckbox.module.less
packages/moonstone/FormCheckboxItem/FormCheckboxItem.module.less
packages/moonstone/styles/colors.less
packages/moonstone/styles/variables.less

New design for FormCheckbox and FormCheckboxItem
Who wants to look at crusty old designs? Not me, that's for sure. These components were updated to the latest look. :sogood:
We finally have square checkboxes. WOO!

PLAT-78054: Updated the appearance of FormCheckboxItem (and friends)

---

packages/moonstone/CHANGELOG.md
packages/moonstone/RadioItem/RadioItem.module.less
packages/moonstone/styles/colors-highcontrast.less
packages/moonstone/styles/colors-light-highcontrast.less
packages/moonstone/styles/colors-light.less
packages/moonstone/styles/colors.less
packages/moonstone/styles/variables.less

Selected RadioItems are not easily differentiated from non-selected ones
Added a "selected dot" into the selected Radio circle.
I was able to remove lots of the custom code we added to accommodate calculations for non-3px based values by using styling which doesn't affect layout (solid shadow).
I had to also update the high-contrast values because it looked terrible without changing them.

PLAT-78050: Added a "selected dot" into the selected Radio circle

---

packages/moonstone/CHANGELOG.md
packages/moonstone/styles/colors-light.less
packages/moonstone/styles/colors.less
packages/moonstone/styles/mixins.less

New designs come with new generalized rules
Updated global styling rules affecting:
* standard font-weight from bold to normal. _This affects any component who does not specify their own weight rules._
* disabled opacity, from `0.6` to `0.3`
* LESS color variable definitions (`@moon-gray`)

PLAT-78048: Updated general/global rules

---

packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/ScrollableNative.js
packages/sampler/stories/qa/Scroller.js

Reverts #2250 due to some spotlight and layout issues

Revert PLAT-77085: Remove data-spotlight-* props from Scrollable

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Checkbox/Checkbox.module.less
packages/moonstone/styles/colors.less
packages/moonstone/styles/variables.less

Checkbox and CheckboxItem are round and those shenanigans just don't fly anymore! #ComeOnNowHey
Updated the styles to match the latest designs, squaring the corners and tuning the colors for better contrast. :sogood:

PLAT-78043: Updated Checkbox style a little bit

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Spinner/Spinner.js
packages/moonstone/Spinner/Spinner.module.less
packages/moonstone/styles/variables.less
packages/sampler/stories/default/Spinner.js

App designers need a safe way to incorporate a spinner into an item (for action Items that initiate a waiting period of some sort).
A new `size` prop was added to Spinner with some dimensions built-in to help this usage scenario and others like it.

ENYO-5948: Spinner - Added a size prop to support "small"

---

packages/moonstone/ProgressBar/ProgressBarTooltip.module.less
packages/moonstone/TooltipDecorator/TooltipDecorator.js
packages/moonstone/styles/variables.less
packages/sampler/stories/qa/Tooltip.js

Fixes for:
Relative tooltip initial positioning
slider/incrementslider/progressbar and input invalid tooltip position
PLAT-78512

PLAT-78512: Fix Tooltip regressions

---

packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/styles/variables.less

`ToggleButton` and `DaySelector` should have been reverted to use circular selection "icons" in #2245 but were missed.
Reverts the visual changes back to circular shapes

PLAT-78579: Fix ToggleButton and DaySelector icon shape

---

packages/moonstone/docs/virtual-list-scroller.md

Missed removing docs reference to `isItemDisabled`
Removed it.
PLAT-77054

PLAT-77054 Update docs to remove isItemDisabled

---

packages/moonstone/VirtualList/VirtualListBase.js

`wrap` feature is broken after #2239. (A kind of regression)
Added missing condition.
Fixed the regression before any release, so there is no change log.
PLAT-78725

PLAT-78725:  Fix VirtualGridList to work properly with `wrap` prop

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Panels/Header.js
packages/moonstone/Panels/Header.module.less

Headers with Input have a distracting white background.
Header Inputs now fully blend in with the normal title text.

ENYO-5988: Fix background color of Input in Header

---

packages/sampler/stories/qa/Dropdown.js

ENYO-5973: Add QA sample for Dropdown

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Checkbox/Checkbox.module.less
packages/moonstone/styles/colors-light.less
packages/moonstone/styles/colors.less

Colors for Checkbox are all kinds of whack, yo.
:sogood: much new very colors :wow:
The color values also had wonky names that didn't match the format of the other variable names, so they were updated and synced across dark and light skins.

ENYO-5981: Fixed colors for Checkbox in both skins

---

packages/moonstone/CHANGELOG.md
packages/moonstone/FormCheckbox/FormCheckbox.module.less
packages/moonstone/FormCheckboxItem/FormCheckboxItem.module.less
packages/moonstone/styles/colors-light.less
packages/moonstone/styles/colors.less
packages/moonstone/styles/variables.less

Light skin FormCheckbox doesn't match designs
Component and colors updated to match latest designs
Also updated the light skin disabled opacity to match design

ENYO-5992: Fix FormCheckbox size and colors

---

packages/moonstone/Checkbox/Checkbox.module.less

Disabled+focused light skin CheckboxItem looks wrong.
Checkbox was updated for the case when the parent element is disabled and focused.

ENYO-5981: Corrected Light skin disabled+focused checkbox

---

packages/sampler/stories/qa/Dropdown.js

remove sample 'with 10 options'

Feature/ENYO-5995: Enact QA Sampler Dropdown: remove sample 'with 10 options'

---

packages/sampler/stories/qa/Header.js

ENYO-5996: qa-sampler: added a character in front of tall-glyph string to attach to the small flag

---

packages/sampler/stories/qa/Spotlight.js

ENYO-5997- Increased size of button label to test marquee

---

docs/migration/enact/migrating-to-enact-2.md
docs/migration/enact/migrating-to-enact-3.md
docs/migration/index.md

This PR adds the Enact 3.0 migration doc, focused on component and prop changes.
Use https://github.com/enactjs/docs to view the documentation.
ENYO-5991

ENYO-5991: Create 2.0 to 3.0 migration guide

---

packages/ui/CHANGELOG.md
packages/ui/Touchable/Hold.js
packages/ui/Touchable/Touchable.js

fix emitting extra hold pulse event on re-enter

---

packages/sampler/stories/qa/Touchable.js
packages/ui/CHANGELOG.md
packages/ui/Touchable/Hold.js

The Touchable sample is confusing regarding what it's attempting to demonstrate.
Added a visual element to show where the tap-start radius is checking for when pulses should be fired.

PLAT-79212: Updated the Touchable sample to better demonstrate its intent

---

packages/moonstone/Button/Button.module.less
packages/moonstone/CHANGELOG.md
packages/moonstone/Input/Input.module.less
packages/moonstone/styles/colors-light.less
packages/moonstone/styles/colors.less
packages/moonstone/styles/variables.less

Update light skin colors for `moonstone/FormCheckbox`, `moonstone/Input`, `moonstone/ProgressBar`, `moonstone/RadioItem`, `moonstone/SwitchItem`, and `moonstone/Tooltip`.
Made `moonstone/FormCheckbox` icon smaller to fit the specs better
PLAT-78225

PLAT-78225: Update light skin colors

---

packages/sampler/stories/qa/Button.js
packages/sampler/stories/qa/Header.js
packages/sampler/stories/qa/ToggleButton.js

ENYO 6008: added a letter 'a' in front of special character so text displays fully

---

packages/sampler/stories/qa/Dropdown.js

QA sample to verify https://github.com/enactjs/enact/pull/2320

PLAT-79578: Add Dropdown QA sample with array of children

---

packages/sampler/stories/qa/LabeledIcon.js

ENYO-6002: added a sample to test tall characters with LabeledIcon

---

packages/moonstone/ToggleButton/ToggleButton.js
packages/moonstone/ToggleButton/ToggleButton.module.less
packages/ui/styles/core.less

Fix debug aria labels from overflowing.
Also moved `ToggleButton`'s indicator pseudo element to its `.toggleIndicator` so it doesn't clash or get overwritten by the debug aria labels.
ENYO-5971

ENYO-5971: Aria debug label fix

---

packages/ui/Layout/Layout.js

The docs for Layout aren't very good at explaining the real-ultimate-power of the component.
Improved docs with a more elaborate description, some example, and even some ASCII art. Hopefully, it translates acceptably on the website.

PLAT-78971: Improved docs for Layout

---

packages/moonstone/internal/validators/validators.js
packages/ui/internal/validators/validators.js

Don't warn on fractional step

---

packages/sampler/stories/qa/Header.js

ENYO-6060: Increased length of string Title in Header component for sample 'with long text and headerComponent' in Header component

---

docs/accessibility.md

Minor update to the guide for accessibility
PLAT-80784

PLAT-80784: Update accessibility developer guide

---

packages/sampler/stories/default/Input.js
packages/sampler/stories/qa/Dropdown.js
packages/sampler/stories/qa/Input.js

Add missing QA sampler knobs
ENYO-6048

ENYO-6048: Add missing QA sampler knobs

---

packages/sampler/stories/qa/Header.js

QA Header stories are a mess. Finding anything and doing anything with them is cumbersome.
Cleaned up, organized, standardized, and added missing scenarios.

PLAT-80782: Refactor Header QA Samples for better usability

---

packages/sampler/stories/qa/Header.js

ENYO-6077: Add marqueeOn knob to Header QA samples

---

packages/sampler/src/MoonstoneEnvironment/MoonstoneEnvironment.js
packages/sampler/stories/qa/VirtualList.js

We lack a sample to test VirtualList in Panels
Adds a sample in QA sampler to test variable length virtual lists in an instance of panels

ENYO-6042: Add qa sample for VirtualList in panels

---

docs/redux/redux-async.md
docs/redux/redux-intro.md

Order or articles on redux are in the wrong order in the sidebar navigation.
Add `order` frontmatter prop to configure that correctly.

PLAT-79889: Fix Redux doc sort order

---

packages/sampler/stories/qa/Scroller.js

Enyo 6073: Added QA Sample to Scroller to test focus in a container

---

packages/ui/VirtualList/VirtualListBase.js

Needed to expand item height dynamically.
Support Expandable Item in VirtualList.
PLAT-80872

PLAT-80872: Support Expandable Item in VirtualList

---

packages/moonstone/Panels/Arrangers.js

* Travis linting error due to unused variables.
* Remove unused variables.

Remove unused to/from variables.

---

docs/migration/enact/migrating-to-enact-3.md

Information about upgrading apps that use `@enact/i18n` is added to the migration guide.
PLAT-81707

PLAT-81707: Docs: update Enact 3 migration guide for beta.1

---

packages/moonstone/CHANGELOG.md
packages/moonstone/styles/variables.less

`Spinner` line is thicc.
Updated the `Spinner` component visuals to match the new GUI designs by updating its dimensions, thinning the line, and thickening the padding.

PLAT-81343: Updated Spinner to use the latest designs

---

packages/moonstone/Button/Button.js
packages/moonstone/Button/Button.module.less
packages/moonstone/CHANGELOG.md
packages/moonstone/Dropdown/Dropdown.js
packages/moonstone/Dropdown/Dropdown.module.less

Remove Dropdown Button animation
PLAT-81337

PLAT-81337: Remove Dropdown Button animation

---

packages/moonstone/VirtualList/VirtualList.js
packages/ui/VirtualList/VirtualListBase.js

Needed Horizontal Scrolling in VirtualList with Different Width Item in some apps
Support Horizontal Scrolling in VirtualList with Different Width Item
PLAT-81452

PLAT-81452: Support Horizontal Scrolling in VirtualList with Different Width Item

---

packages/moonstone/VirtualList/VirtualListBase.js
packages/ui/VirtualList/VirtualListBase.js

Needed to calculate the item position properly based on the different item size.
Calculate the item position properly with internal variables  having item position based on the different item size.
Calculate the `firstVisibleIndex` and `lastVisibleIndex` to provide them when the list stops or starts scrolling.
PLAT-81468

PLAT-81468: Fix 5-way navigation for VirtualList with different height items

---

docs/migration/enact/migrating-to-enact-3.md
packages/moonstone/CHANGELOG.md
packages/moonstone/GridListImageItem/GridListImageItem.module.less
packages/moonstone/MoonstoneDecorator/MoonstoneDecorator.module.less
packages/moonstone/Panels/Header.js
packages/moonstone/Panels/Header.module.less
packages/moonstone/Panels/Panels.module.less
packages/moonstone/VideoPlayer/VideoPlayer.module.less
packages/moonstone/styles/colors-light.less
packages/moonstone/styles/colors.less
packages/moonstone/styles/mixins.less
packages/moonstone/styles/variables.less
packages/sampler/src/MoonstoneEnvironment/MoonstoneEnvironment.module.less
packages/sampler/stories/default/Header.js

A new type of `Header` is requested for `AlwaysViewing` types of panels.
A new type was added called "dense". This new type of header can be chosen using the
`<Header type="dense">` prop.

PLAT-83080: Added a new type to Header: "dense"

---

docs/migration/enact/migrating-to-enact-3.md
packages/moonstone/Button/Button.module.less
packages/moonstone/styles/mixins.less
packages/moonstone/styles/variables.less

Many of `Button`s LESS variables are old and don't follow good naming conventions or linking practices.
`Button` LESS variables have been restructured and alphabetized in the `variables.less` file while the rules of `.moon-large-button-text()` and `.moon-small-button-text()` mixins, in the `mixins.less` file, have been pointed to their better-named equivalents.
This change intends zero visual (perceptible) difference from `develop`.

PLAT-83166: Organized the Button CSS rules

---

packages/moonstone/CHANGELOG.md
packages/moonstone/styles/colors-light.less
packages/moonstone/styles/colors.less

Who initially came up with these RadioItem dot colors?? J/k, it was likely me. New design colors have been delivered and need to be implemented.
Implemented new colors to match designs, which also bring dark and light skins inline with each other.

PLAT-81342: Assigned proper colors to RadioItem dot

---

docs/redux/index.md
docs/redux/redux-intro.md

Which version of Redux to use was not documented
Update Redux docs to show how to find latest version
ENYO-6011

ENYO-6011: Update Redux integration docs

---

packages/sampler/stories/qa/RadioItem.js

ENYO-6146: Increase string length of RadioItem QA sample

---

packages/moonstone/Panels/tests/Panels-specs.js

Missed adding a unit test for the failure case I found
Added a test case.
ENYO-6122

Test Panels aria-owns if controls exist

---

packages/core/dispatcher/dispatcher.js
packages/core/handle/handle.js
packages/core/kind/kind.js
packages/moonstone/Checkbox/Checkbox.js
packages/moonstone/ContextualPopupDecorator/ContextualPopupDecorator.js
packages/moonstone/ExpandableInput/ExpandableInput.js
packages/moonstone/GridListImageItem/GridListImageItem.js
packages/moonstone/Heading/Heading.js
packages/moonstone/Marquee/Marquee.js
packages/moonstone/Panels/Panels.js
packages/moonstone/Slider/Slider.js
packages/ui/ToggleIcon/ToggleIcon.js
packages/ui/Touchable/Touchable.js

Some core docs needed review and the `@see` tag was not correct
Fixed it.
ENYO-6147

ENYO-6147 Fix @see and some core docs

---

packages/core/kind/kind.js
packages/core/platform/platform.js
packages/ui/resolution/resolution.js
packages/webos/platform/platform.js

Many typedefs specified that fields were required when they were optional.
Update declarations to be more accurate.
Needs corresponding docs PR before a visual difference will appear

Fix typedef declarations

---

packages/sampler/stories/default/Platform.js

ENYO-6122: Improve platform sampler

---

packages/sampler/stories/qa/Scroller.js

There is no sampler for vertical and horizontal scrollable scroller with spottable items.
Add vertical and horizontal scrollable scroller qa-sampler with spottable items.
PLAT-83440

PLAT-83440: Add vertical and horizontal scrollable scroller qa-sampler

---

packages/sampler/stories/qa/VirtualList.js
packages/sampler/stories/qa/VirtualListNative.js

ENYO-6164: Add QA sample for VirtualListNative with extra items outside list

---

packages/moonstone/VirtualList/VirtualList.js
packages/moonstone/VirtualList/VirtualListBase.js
packages/ui/Scrollable/Scrollable.js
packages/ui/Scrollable/ScrollableNative.js
packages/ui/VirtualList/VirtualList.js
packages/ui/VirtualList/VirtualListBase.js

To deliver VirtualList with different item size, it is needed to clean up interface, code, and JS doc for it.
Cleanup interfaces, code, and JS Doc for VirtualList with different item size
PLAT-84230

PLAT-84230: Cleanup interfaces, code, and JS Doc for VirtualList with different item size

---

packages/moonstone/CHANGELOG.md
packages/moonstone/MediaOverlay/MediaOverlay.js

There is no sound output.
I inquired whether sound should always be unmuted to all App developers who use this component.
As a result, everyone need that there is sound output.
Remove `muted` attribute
ENYO-6175

ENYO-6175: Remove muted attribute in MediaOverlay

---

packages/sampler/stories/qa/LabeledItem.js

* [] At least one test case is included for this feature or bug fix

ENYO-6129: Add LabeledItem QA samples

---

packages/moonstone/CHANGELOG.md
packages/moonstone/ContextualPopupDecorator/ContextualPopup.module.less

The tooltip on Slider can sometimes cause the contextual popup arrow to disappear
Workaround the chromium bug by promoting the arrow to a GPU-accelerated layer

PLAT-84596: Fix ContextualPopup arrow rendering issue

---

packages/sampler/stories/qa/VirtualGridList.js
packages/sampler/stories/qa/VirtualList.js
packages/sampler/stories/qa/VirtualListNative.js

There is no way to change props of VirtualListNative in QA Sample.
Add useful knobs and actions to QA VirtualListNative sample in order to do a wider variety of test.
PLAT-84364

PLAT-84364: Add useful knobs and actions for QA VirtualListNative sample

---

packages/moonstone/CHANGELOG.md
packages/moonstone/FormCheckboxItem/FormCheckboxItem.module.less

Ellipses don't occur in FormCheckboxItem.
It is reproduced from rc.2.
Add `overflow: hidden` to `span` tag which contain `children`.
ENYO-6188

ENYO-6188: Add overflow hidden property to FormCheckboxItem

---

packages/moonstone/CHANGELOG.md
packages/moonstone/VideoPlayer/MediaControls.js
packages/sampler/stories/default/VideoPlayer.js

New designs call for different jump forward/back icon
Use new icons added in #2479.
Updated defaults in storybook as well.  Test with latest Moonstone font.
ENYO-6155

ENYO-6155: Update jump forward/backward icon

---

packages/i18n/Text/Text.js

`Text` docs needed some touch-up
Touched them.
#2503 
ENYO-6186

ENYO-6186: Fix type of children

---

packages/sampler/stories/qa/Marquee.js
packages/sampler/stories/qa/Resizable.js

ENYO-6226: Fix text strings length in QA samples to allow for marquee 

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Switch/Switch.module.less
packages/moonstone/styles/colors-light.less
packages/moonstone/styles/colors.less
packages/moonstone/styles/variables.less
packages/sampler/stories/default/FormCheckboxItem.js

Switch colors needs to be adjusted for better visibility
Stroke added and colors adjusted.
Colors are close but should be reviewed (in particular the dark skin stroke which was difficult for me to snag from the source PNG).

PLAT-85426: Fix Switch colors for improved visibility

---

packages/i18n/I18nDecorator/I18nDecorator.js
packages/moonstone/MoonstoneDecorator/MoonstoneDecorator.js
packages/moonstone/Skinnable/Skinnable.js
packages/spotlight/SpotlightContainerDecorator/SpotlightContainerDecorator.js
packages/spotlight/SpotlightRootDecorator/SpotlightRootDecorator.js
packages/spotlight/Spottable/Spottable.js
packages/ui/A11yDecorator/A11yDecorator.js
packages/ui/AnnounceDecorator/AnnounceDecorator.js
packages/ui/Cancelable/Cancelable.js
packages/ui/FloatingLayer/FloatingLayerDecorator.js
packages/ui/Marquee/MarqueeDecorator.js
packages/ui/Placeholder/PlaceholderDecorator.js
packages/ui/Resizable/Resizable.js
packages/ui/Skinnable/Skinnable.js
packages/ui/Toggleable/Toggleable.js
packages/ui/Touchable/Touchable.js

HoCs didn't clearly state when they passed props that needed to be consumed by wrapped components
Clarify the docs.
ENYO-6251

ENYO-6251: Fix HoC docs

---

docs/migration/enact/migrating-to-enact-3.md

Updates text inside migration document

---

packages/sampler/stories/qa/Heading.js

ENYO-6063: added Heading to QA Sampler with 3 new qa samples 

---

packages/sampler/stories/default/IncrementSlider.js

ENYO-6200: add deprecated to IncrementSlider side prop

---

packages/sampler/stories/qa/Popup.js

ENYO-6118: Add QA sample to Popup to test focus resumes after open state

---

packages/moonstone/styles/colors-light.less
packages/moonstone/styles/colors.less

As the GUI specification has been updated.
I've updated the colors.
ENYO-6257

ENYO-6257: RadioItem: background-color doesn't match GUI spec

---

packages/sampler/src/MoonstoneEnvironment/MoonstoneEnvironment.js

ENYO-6265: Fix knob text for am-ET locale

---

packages/core/CHANGELOG.md
packages/core/kind/kind.js

Update: ComputedFunction and HandlerFunction in kind make event, props and context

PLAT-86061: Fix TypeScript types for handlers and computed functions in kind

---

packages/sampler/src/manager-styles.js

* While future official Storybook releases plan to make an actual option to disable the notifier, currently Storybook updates result in both a popup and a yellow circle indicator.
* Hide the version notification popup and the notification circle.

PLAT-86243: Disable Storybook update notifications

---

packages/core/handle/handle.js
packages/core/kind/kind.js

PLAT-86061 : Fix docs for event handlers and adaptEvent

---

packages/sampler/stories/qa/Header.js

ENYO 6287: Add QA Header sample for RTL with long string

---

docs/accessibility.md
docs/contributing/documentation.md
docs/creating-components.md
docs/interoperability.md
docs/migration/enact/migrating-to-enact-2.md
docs/migration/enact/migrating-to-enact-3.md
docs/migration/enyo/migrate-fittables.md
docs/migration/enyo/migrate-i18n.md
docs/migration/enyo/migrating-enyo-apps.md
docs/performance.md
docs/redux/redux-async.md
docs/redux/redux-intro.md
docs/theming.md
docs/why-use-kind.md
packages/i18n/docs/ilib.md
packages/i18n/docs/index.md
packages/i18n/docs/updating-locale.md
packages/moonstone/docs/virtual-list-scroller.md
packages/spotlight/docs/index.md
packages/webos/docs/luna-service-api.md
packages/webos/docs/webos-features.md

PLAT-86414: Fix syntax highlighting

---

CHANGELOG.md
packages/i18n/CHANGELOG.md
packages/moonstone/CHANGELOG.md
packages/moonstone/ContextualPopupDecorator/ContextualPopupDecorator.js
packages/moonstone/Scrollable/ScrollButtons.js
packages/spotlight/CHANGELOG.md
packages/ui/CHANGELOG.md
packages/ui/Scrollable/Scrollable.js
packages/ui/Scrollable/ScrollableNative.js
packages/ui/Scroller/Scroller.js
packages/ui/Touchable/Touchable.js
packages/ui/VirtualList/VirtualListBase.js

Ficks spelline

---

packages/moonstone/Panels/Header.js
packages/sampler/stories/qa/Marquee.js

`eslint-plugin-enact` finds new classes of problems
Preemptively fix warnings that will be discovered
PLAT-86931

Fix future eslint warnings

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/FEATURE.md
.github/ISSUE_TEMPLATE/SUPPORT.md

Issue template checkboxes were not working
Fixed them to be a list

Fix issue templates

---

packages/ui/Marquee/MarqueeBase.js

Marquee docs had warnings during parsing
Fix it

Fix marquee docs

---

packages/sampler/stories/qa/VirtualGridList.js

ENYO-6121: Add VGL QA sample

---

packages/sampler/stories/qa/Dropdown.js

ENYO-6310: added new Dropdown sample to qa-sampler

---

packages/sampler/stories/qa/ToggleButton.js

ENYO-6337: increased the label length of ToggleButton with long text 

---

packages/core/util/Job.js

`Job` docs were a bit confusing
Remove references to non-existent function `setTimeout`
We could add an API to change the originally configured timeout as was discussed in the docs.
ENYO-6350

Update core/util.Job timeout docs

---

packages/moonstone/Spinner/Spinner.js
packages/sampler/stories/qa/Spinner.js

ENYO-6308: Add QA sample for Spinner with Input

---

packages/sampler/src/MoonstoneEnvironment/MoonstoneEnvironment.js
packages/sampler/stories/qa/Notification.js
packages/sampler/stories/qa/Text.js

ENYO-6353: Add QA sample for Notification with Sinhala language

---

packages/moonstone/CHANGELOG.md
packages/moonstone/Scrollable/Scrollable.js
packages/moonstone/Scrollable/Scrollable.module.less
packages/sampler/stories/default/Scroller.js
packages/ui/Scrollable/Scrollable.js

Add scroll to top button that appears at the edge of the screen.

PLAT-90768: Add ScrollToTop Button

---

packages/sampler/stories/qa/Marquee.js

ENYO-6354: Add new qa-sample to test Marquee resumes without jitter when text is centered

---

packages/sampler/stories/default/Button.js
packages/sampler/stories/default/ExpandableInput.js
packages/sampler/stories/default/Icon.js
packages/sampler/stories/default/icons.js
packages/sampler/stories/qa/Button.js
packages/sampler/stories/qa/ExpandableInput.js
packages/sampler/stories/qa/Input.js
packages/sampler/stories/qa/Item.js
packages/sampler/stories/qa/LabeledIcon.js
packages/sampler/stories/qa/Picker.js

ENYO-6336: Sort icons in sampler knobs

---

packages/moonstone/Button/Button.js
packages/sampler/stories/default/ExpandableInput.js

Typo in comment and a missing spread operator
Fixed

A few typos in the source

---

packages/moonstone/Icon/IconList.js

ENYO-6370: added description to comment for icon 's' in IconList

---

packages/moonstone/CHANGELOG.md
packages/moonstone/LabeledIconButton/LabeledIconButton.js
packages/ui/VirtualList/VirtualListBase.js

Some voice control props should be delegate to sub items
Declare props and delegate to target node
https://jira2.lgsvl.com/browse/PLAT-97909

PLAT-97909: Delegate voice props to sub items

---

README.md
packages/core/README.md
packages/i18n/README.md
packages/moonstone/README.md
packages/sampler/README.md
packages/spotlight/README.md
packages/ui/README.md
packages/webos/README.md

2020 update for all packages
PLAT-9821

PLAT-98217: Update Copyright to 2020

---

packages/ui/VirtualList/tests/VirtualList-specs.js

After #2683, we encountered an error message on tests of a list component about `Invalid hook call` and we could not find the cause of this error for now.
Disable tests for now and keep a topic to re-enable them after fixing the error.
PLAT-100226

PLAT-100226: Disabled tests on ui/VirtualList

---

packages/ui/CHANGELOG.md
packages/ui/Scroller/Scroller.js
packages/ui/Scroller/ScrollerBasic.js
packages/ui/VirtualList/VirtualListBasic.js
packages/ui/useScroll/Scrollable.js
packages/ui/useScroll/useScroll.js

The new prop `scrollMode` is added.
- 'translate': the scroll content is scrolled by CSS translate.
- 'native': the scroll content is scrolled by scrolltop (native way).
The new prop is added with the default value of `translate` for better consistent experience between browsers.
PLAT-101272

PLAT-101272: Add a new prop `scrollMode`

---

packages/ui/GridListImageItem/GridListImageItem.js

Need to support variable sub-components below image.
Added subComponents prop
PLAT-99124

PLAT-99124: Support for subComponents in GridListImageItem

---

packages/sampler/stories/default/Scroller.js
packages/sampler/stories/default/VirtualGridList.js
packages/sampler/stories/default/VirtualList.js
packages/ui/CHANGELOG.md

* Update samplers based on `VirtualList` and `Scroller` APIs
* Check updated props in samplers
*  Add `scrollMode` knob in `VirtualList`, `VirtuaiGridList`, and `Scroller` samplers
PLAT-101530

PLAT-101530: Update samplers based on VirtualList and Scroller APIs

---

packages/sampler/stories/default/VirtualGridList.js
packages/ui/CHANGELOG.md
packages/ui/GridListImageItem/GridListImageItem.js
packages/ui/ImageItem/ImageItem.js
packages/ui/ImageItem/ImageItem.module.less
packages/ui/ImageItem/package.json
packages/ui/ImageItem/tests/ImageItem-specs.js
packages/ui/Layout/Layout.js

Need to support vertical and horizontal image item
Added ImageItem with `orientation` prop
PLAT-101893

PLAT-101893: Add ImageItem

---

packages/sampler/stories/default/Scroller.js

In some samples, the layout is different depending on the resolution.
[//]: # (What is the impact of this change and *why* was it made?) 
Apply ri.scale properly. In most cases, use scaleToRem.
N/A
ENYO-6440

ENYO-6440: Apply ri-scale on sampler and qa-sampler

---

packages/ui/Slider/Slider.js

PLAT-105261: Update ui/Slider orientation proptypes to string

---

packages/core/internal/prop-types/prop-types.js
packages/ui/BodyText/BodyText.js
packages/ui/Button/Button.js
packages/ui/GridListImageItem/GridListImageItem.js
packages/ui/Group/Group.js
packages/ui/IconButton/IconButton.js
packages/ui/ImageItem/ImageItem.js
packages/ui/Item/Item.js
packages/ui/LabeledIcon/LabeledIcon.js
packages/ui/Layout/Cell.js
packages/ui/Layout/Layout.js
packages/ui/Marquee/MarqueeBase.js
packages/ui/Repeater/Repeater.js
packages/ui/Routable/Router.js
packages/ui/Scroller/ScrollerBasic.js
packages/ui/Slider/Knob.js
packages/ui/Slider/Slider.js
packages/ui/SlotItem/SlotItem.js
packages/ui/Spinner/Spinner.js
packages/ui/ToggleIcon/ToggleIcon.js
packages/ui/ToggleItem/ToggleItem.js
packages/ui/Transition/Transition.js
packages/ui/ViewManager/TransitionGroup.js
packages/ui/ViewManager/ViewManager.js
packages/ui/VirtualList/VirtualListBasic.js

Update prop types for refs
PLAT-105483

PLAT-105483: Update ref prop types

---

packages/ui/Button/Button.js
packages/ui/Icon/Icon.js
packages/ui/IconButton/IconButton.js
packages/ui/LabeledIcon/LabeledIcon.js

PLAT-105260: Fixed docs for `size` prop in `enact/ui`

---

packages/ui/useScroll/useScroll.js

Removed unused variable `isUpdatedScrollbarTrack`
ENYO-6446

ENYO-6446: Remove 'isUpdatedScrollbarTrack'

---

packages/core/useChainRefs/useChainRefs.js

useChainRefs throws error in docs parsing
Properly scope functions.
PLAT-111221

PLAT-111221 Fix doc parsing error

---

packages/ui/CHANGELOG.md
packages/ui/VirtualList/VirtualListBasic.js

Revert "PLAT-111412: VirtualList: Fix items are not shown when changing RTL locales"

---

packages/core/util/tests/util-specs.js

Tests were missed with a previous PR
Added tests
Replaces some existing tests with ones from the missing code.
PLAT-111891

PLAT-111891: Add missing tests

---

packages/i18n/package.json

* Updates `@enact/ui-test-utils` dependency to `0.5.1`

PLAT-113569: Update @enact/ui-test-utils to 0.5.0

---

packages/ui/CHANGELOG.md
packages/ui/Scroller/ScrollerBasic.js

Revert "PLAT-116068: Fixed Scroller to observe children's size"

---

packages/spotlight/CHANGELOG.md
packages/spotlight/SpotlightContainerDecorator/SpotlightContainerDecorator.js

Revert "PLAT-117036: Fix SpotlightContainerDecorator to allow use of ref"

---

packages/spotlight/src/spotlight.js

Add guards for getBoundingClientRect

---

packages/ui/CHANGELOG.md
packages/ui/Item/tests/Item-specs.js

Enact-DCO-1.0-Signed-off-by: Jeongran Jang (jeongran.jang@lge.com)
There is no test for `onClick` event handler in `ui/Item`
Add unit tests 
PLAT-125213

PLAT-125213: Add unit tests in `ui/Item`

---

packages/ui/useScroll/Scrollbar.js

Agate isomorphic test failed
Added guard for the failed point
PLAT-127311

PLAT-127311: Fix isomorphic test

---

packages/sampler/CHANGELOG.md
packages/sampler/stories/default/Routable.js

Currently, there is no sample to test Routable that using relative path.
Add Routable sampler 
https://github.com/enactjs/enact/pull/2856
PLAT-128620

PLAT-128620: Add Routable sampler

---

packages/ui/CHANGELOG.md
packages/ui/Marquee/MarqueeDecorator.js

Revert "PLAT-108976: Fix Marquee to restart animation when text changed while focus retained"

---

packages/spotlight/package.json

Dependency error on spotlightRootDecorator from #2897
Add webos package for spotlight
PLAT-134190

Add webOS dependency to spotlight

---

docs/accessibility.md

accessibility.md was a guide for the moonstone. it needs to be updated for the sandstone.
Update the description and example code for the sandstone.
PLAT-139104

PLAT-139104: Update accessibility.md for Sandstone

---

package-lock.json
package.json
packages/core/package.json
packages/spotlight/CHANGELOG.md
packages/spotlight/SpotlightRootDecorator/SpotlightRootDecorator.js
packages/spotlight/styles/mixins.less
packages/ui/Item/tests/Item-specs.js
packages/ui/package.json
packages/ui/useScroll/useScroll.js

We want to provide better UX on touchable display.
Tweaks spotlight effect not to show on touch inputs.
PLAT-132837

PLAT-132837: Enhance touch support

---

packages/spotlight/Spottable/Spottable.js
packages/spotlight/Spottable/SpottableCore.js
packages/spotlight/Spottable/useSpottable.js

In some samples, we've seen the below console error
```Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:...```
Removed invalid hook calling in a class and replaced it with a function call that has `forceUpdate()`.
PLAT-139596

PLAT-139596: Fix console error on Spottable

---

packages/ui/AnnounceDecorator/useAnnounce.js

Fix typo in useAnnounce

---

packages/spotlight/CHANGELOG.md
packages/spotlight/SpotlightRootDecorator/SpotlightRootDecorator.js

Isomorphic build failed due to `document` access.
Update to avoid `document` access.
PLAT-143754

PLAT-143754: Fixed isomorphic build failure

---

packages/spotlight/SpotlightRootDecorator/SpotlightRootDecorator.js

The current API to handle the last input type exported by callback prop for `SpotlightRootDecorator` and it will be better to be exported in a normal way.
Updated to export key APIs from the module, not through callback function prop.
Also, for more safe recognition of input type, separate catching events for mouse input and touch input.
PLAT-140745

PLAT-140745: Refine logic to handle the last input type

---

.travis.yml
packages/core/internal/ApiDecorator/tests/ApiDecorator-specs.js
packages/core/kind/kind.js
packages/core/kind/tests/kind-specs.js
packages/core/useChainRefs/tests/useChainRefs-specs.js
packages/core/useClass/tests/useClass-specs.js
packages/core/useHandlers/tests/useHandlers-specs.js
packages/i18n/I18nDecorator/tests/I18nDecorator-specs.js
packages/i18n/I18nDecorator/tests/useI18n-specs.js
packages/i18n/I18nDecorator/tests/windowFocus-specs.js
packages/spotlight/SpotlightContainerDecorator/tests/useSpotlightContainer-specs.js
packages/spotlight/Spottable/tests/useSpot-specs.js
packages/ui/Cancelable/tests/Cancelable-specs.js
packages/ui/RadioDecorator/RadioControllerDecorator.js
packages/ui/RadioDecorator/tests/RadioDecorator-specs.js
packages/ui/Repeater/tests/Repeater-specs.js
packages/ui/Skinnable/tests/useSkins-specs.js
packages/ui/Slider/PositionDecorator.js
packages/ui/Slottable/tests/Slottable-specs.js
packages/ui/Slottable/tests/useSlots-specs.js
packages/ui/Toggleable/tests/Toggleable-specs.js
packages/ui/Touchable/tests/Touchable-specs.js
packages/ui/Touchable/tests/useTouch-specs.js
packages/ui/ViewManager/TransitionGroup.js
packages/ui/ViewManager/tests/View-specs.js
packages/ui/ViewManager/tests/ViewManager-specs.js
packages/ui/VirtualList/tests/VirtualList-specs.js
packages/ui/internal/IdProvider/tests/useId-specs.js
packages/ui/useControlledState/tests/useControlledState-specs.js
packages/webos/speech/VoiceControlDecorator.js

Enyo-5941 : Fix --report-unused-disable-directives warnings and enable for Travis

---

packages/core/hoc/hoc.js

Need to compare if HOC default config is changed like API change 
Add a displayName and defaultConfigs 
WRN-1264

WRN-1264 : Add support for iterating over HOC configs

---

docs/theming.md

Add guide how to create theme by using enact template
WRN-3707

WRN-3707: Add guide how to create theme by using template

---

packages/sampler/stories/default/ViewManager.js
packages/sampler/stories/default/ViewManager.module.less

There is no ViewManager sampler in ui/ViewManger to verify the behavior with Arranger.
ViewManager sample needs to be added.
Add ViewManager sample that works with Arranger.
WRN-1635

WRN-1635: Make ui/ViewManager Sampler

---

packages/i18n/I18nDecorator/tests/I18nDecorator-specs.js
packages/i18n/I18nDecorator/tests/useI18n-specs.js

Migrated unit tests for i18nDecorator to testing-library
WRN-9786

WRN-9786: Migrated unit tests for i18nDecorator to testing-library

---

packages/ui/Touchable/tests/Touchable-specs.js
packages/ui/Touchable/tests/useTouch-specs.js

Migrated unit tests to React Testing Library
WRN-9779

WRN-9779: Apply React testing lib to Enact Touchable

---

packages/core/platform/platform.js

There was a typo about platform.touchscreen in the JSDoc which affects IDE suggestions

Fixed typo in JSDoc for enact/core/platform

---

packages/spotlight/CHANGELOG.md
packages/spotlight/styles/debug.less

"debug spotlight" option is not working in each theme sampler
`:global` keyword is css module syntax.
So removed it.
WRN-12918

WRN-12918 : Fixed "debug spotlight" option to work in samplers

---

package-lock.json
package.json
packages/core/package.json
packages/i18n/package.json
packages/sampler/npm-shrinkwrap.json
packages/sampler/package.json
packages/spotlight/package.json
packages/ui/package.json
packages/webos/package.json

For preventing malware issues, we need to update node modules that fix severity vulnerabilities.
Update node modules' warnings via checking "npm audit"
WRN-12919

WRN-12919: Update dependencies

---

packages/spotlight/SpotlightRootDecorator/SpotlightRootDecorator.js

Unused code is found. It was added in #64 and it should have been removed in #703.
Removed unused code.
#64 PLAT-64864
#703 PLAT-39961

WRN-845: SpotlightRootDecorator: removed unused code

---

packages/core/package.json
packages/i18n/package.json
packages/sampler/package.json
packages/spotlight/package.json
packages/ui/package.json
packages/webos/package.json

Updated React18 dependencies
WRN-15947

WRN-15497: React18 POC Setup

---

packages/ui/CHANGELOG.md
packages/ui/ViewManager/View.js
packages/ui/ViewManager/tests/View-specs.js

Fixed skipped unit test for ui/View
WRN-14394

WRN-14394: Fixed skipped unit test for ui/View

---

packages/ui/Drawing/Drawing.js

Added JSDoc for ui/Drawing
WRN-17311

WRN-17311: Added JSDoc for ui/Drawing

---

packages/sampler/stories/default/Drawing.js

Added sampler for ui/Drawing
WRN-17310

WRN-17310: Add sampler for Drawing in enact/packages/sampler

---

packages/ui/Drawing/Drawing.js

Added functionality for drawing a single point on click/touch.
WRN-17313
Enact-DCO-1.0-Signed-off-by: Clapou George-Vladut [[vladut.clapou@lgepartner.com](mailto:vladut.clapou@lgepartner.com)]

WRN-17313: [Drawing POC] Draw point on touch

---

packages/ui/Drawing/Drawing.js

Draw single point functionality added.
WRN-17313

WRN-17313: Draw point on touch

---

packages/ui/RadioDecorator/tests/RadioDecorator-specs.js

Fixed skipped tests for RadioDecorator
WRB-14392

WRN-14392: Fixed skipped tests for RadioDecorator

---

packages/ui/ViewManager/tests/ViewManager-specs.js

Migrated unit test for ui/ViewManager to testing-library
WRN-14395

WRN-14395: Migrated unit test for ui/ViewManager to testing-library

---

packages/ui/AnnounceDecorator/tests/Announce-specs.js

Fixed skipped tests for ui/Announce
Used `ref` to access component's instance
WRN-14515

WRN-14515: Fixed skipped tests for Announce

---

packages/sampler/stories/default/Drawing.js
packages/ui/Drawing/Drawing.js
packages/ui/Drawing/utils.js

Added fill functionality for ui/Drawing
WRN-17312

WRN-17312: Added fill functionality for ui/Drawing

---

packages/ui/Drawing/Drawing.js

Created a function in useImperativeHandle called saveCanvas that saves the current canvas (background color / image included).
WRN-17317

WRN-17317: Add canvas export functionality.

---

packages/ui/Touchable/tests/Touchable-specs.js
packages/ui/Touchable/tests/useTouch-specs.js

Created new events that pass the timestamp prop.
WRN-14393

WRN-14393: Create unit test for Touchable.

---

packages/ui/Drawing/Drawing.js
packages/ui/Drawing/Drawing.module.less

Applied proper styling for drawing component.
WRN-18219

WRN-18219: [Drawing POC] - Styling

---

packages/ui/Drawing/Drawing.js

Added geometric shapes to drawingTool
WRN-17507

WRN-17507: Add functionality to draw geometrical shapes (line, circle, triangle, rectangle)

---

packages/ui/Drawing/Drawing.js
packages/ui/Drawing/Drawing.module.less

Change component to use pointer .
Changed the component to register one single set of pointer actions instead of touch, mouse etc...
In the future this will help us better control the behavior relative to the platform the app is running on,
WRN-18220

WRN-18220: Check events for pen/stylus.

---

packages/sampler/stories/default/Drawing.js
packages/ui/Drawing/Drawing.js

Updated sampler and fixed some issues
WRN-17507

WRN-17507: Update enact sampler

---

packages/sampler/stories/default/VirtualGridList.js

Changed image service.
WRN-17786

WRN-17786: Changed Placehold.it Image service

---

packages/ui/Drawing/Drawing.js

Fixed Triangle shape
WRN-18703

WRN-18703: Fixed Triangle shape

---

packages/ui/Drawing/Drawing.js

Updated offset for pointer events.
WRN-18704

WRN-18704: Fix extra brush line on landscape mode.

---

packages/ui/Drawing/Drawing.js

Added dynamic size for eraser cursor
WRN-18619

WRN-18619: Added dynamic size for eraser cursor

---

packages/ui/Drawing/Drawing.js
packages/ui/Drawing/utils.js

Implemented undo/redo functionality for the Drawing component
WRN-18994

WRN-18994: [Drawing POC] Undo/Redo Functionality

---

packages/ui/Drawing/Drawing.js
packages/ui/Drawing/utils.js

Added ratio for better drawing on retina devices.
WRN-18705.

WRN-18705: Research why lines are blured on mobile.

---

packages/i18n/CHANGELOG.md
packages/i18n/src/Loader.js
packages/i18n/src/glue.js

Add support of setting multiple ilib resource paths
Cherry picked https://github.com/enactjs/enact/pull/2957
WRN-19698

WRN-19698: Add support of setting multiple ilib resource paths

---

packages/sampler/stories/default/Drawing.js

Added color picker control for drawing component story
WRN-19924

Feature/WRN-19924:  Add color picker control in storybook

---

packages/ui/Scrollable/Scrollbar.js
packages/ui/VirtualList/UiVirtualListBase.js
packages/ui/VirtualList/VirtualListBasic.js
packages/ui/package.json
packages/webos/LS2Request/LS2Request.js

Isomorphic test failed
Added default props value for required props.
WRO-2550

WRO-2550: Fix isomorphic test fail

---

packages/ui/Drawing/Drawing.js

Fixed bug on iPad: when drawing a circle with Apple pen, the circle resulted in a polygon.
WRO-339

WRO-339: Fix drawing a circle on iPad with a stylus

---

docs/migration/enact/migrating-to-enact-4.5.md

Added 4.5 migration guide
WRO-739

WRO-739: Update 4.5 migration guide

---

docs/migration/enact/migrating-to-enact-4.5.md

Fix broken samples link
Added an example of installing CLI 5.0.0-alpha.1
WRO-739

WRO-739: Fix migration guide

---

packages/spotlight/CHANGELOG.md
packages/spotlight/src/container.js

The current spotlight found target including invisible elements.
In that case the element cannot get focus. So consequently focus is trapped.
- Exclude invisible element when searching target (display none / visibility hidden)
- Improve performance of "querySelector" function
- Use isNavigable rather than navigableFilter to exclude disabled  container.
WRO-692

WRO-692: Changed Spotlight to not focus on an invisible element

---

packages/ui/Marquee/MarqueeDecorator.js

There was double space on https://github.com/enactjs/enact/pull/3050
I removed unnecessary space.
WRO-608

WRO-608: Fix mistake (remove double space)

---

packages/ui/Skinnable/tests/Skinnable-specs.js

One of `Skinnable` unit test cases was skipped.
Fix the test code to work and updated the code to check more.
WRO-266

WRO-266: Unskip one of `Skinnable` unit test cases

---

packages/ui/Drawing/Drawing.js

Code cleanup for drawing component
WRN-20739

WRN-20739: Code cleanup for drawing component

---

.travis.yml
packages/ui/VirtualList/UiVirtualListBase.js

Since npm is cached by default in Travis CI, there is no need for code related to the npm cache.
- npm is cached by default on Travis CI from July 2019. (https://docs.travis-ci.com/user/caching/)
Remove cache description and set the prefer-offline config value to false so that stale check on cached data are not bypassed.
- npm is cached by default on Travis CI from July 2019. (https://docs.travis-ci.com/user/caching/)
- …

WRO-5043:Update .travis.yml

---

packages/ui/FloatingLayer/FloatingLayer.js

`noAutoDismiss` prop doesn't explain about clicking the outside of the floating layer
Update doc
WRO-5805

WRO-5805: Fix docs for 'noAutoDismiss'

---

docs/migration/enact/migrating-to-enact-4.5.md

As we release the official version of 4.5.0, we need to update the 4.5 migration guide documentation.
Update docs based on the review from #3045.
WRO-2899

WRO-2899: Update migration guide for enact 4.5

---

packages/spotlight/docs/index.md

Update Spotlight guide - https://enactjs.com/docs/developer-guide/spotlight/#spotlightrootdecorator
moonstone use cases -> sandstone use cases

Update Spotlight doc from MoonstoneDecorator to ThemeDecorator

---

packages/sampler/.storybook/main.js
packages/sampler/.storybook/preview.js
packages/sampler/CHANGELOG.md
packages/sampler/package.json
packages/sampler/stories/default/VirtualGridList.js
packages/sampler/stories/helper/svg.js

Updated enact sampler to storybook 6.5 and webpack5
N\A
WRO-11700

WRO-11700: Updated enact sampler to storybook 6.5 and webpack5

---

codecov.yml

Codecov coverage needs to be increased by 80% or more
Ignore the modules that do not need unit test.
(ref : https://docs.codecov.com/docs/ignoring-paths)
WRO-11044

WRO-11044: Ignore the modules that do not need unit test

---

packages/spotlight/Accelerator/tests/Accelerrator-specs.js
packages/spotlight/Pause/tests/Pause-specs.js
packages/spotlight/SpotlightRootDecorator/tests/SpotlightRootDecorator-specs.js
packages/spotlight/src/tests/spotlight-specs.js
packages/spotlight/src/tests/target-specs.js
packages/spotlight/src/tests/utils-specs.js

Increased test coverage of spotlight package
Added unit tests for Pause, Accelerator, SpotlightRootDecorator and src.
WRO-12238

WRO-12238: Increased test coverage of spotlight

---

packages/ui/Media/tests/Media-specs.js

Increased test coverage of Media component
Added unit tests for Media
WRO-12243

WRO-12243: [Codecov] Increase coverage for Media

---

codecov.yml
packages/i18n/$L/tests/$L-specs.js
packages/i18n/util/tests/util-specs.js

Increased test coverage of i18n package
Added unit tests for $L and util
Excluded files that cannot be tested since they need webOS
WRO-12237

WRO-12237: Increased test coverage of i18n

---

packages/core/internal/ApiDecorator/tests/ApiDecorator-specs.js
packages/core/internal/Registry/tests/Registry-specs.js
packages/core/internal/deprecate/deprecate.js
packages/core/internal/deprecate/tests/deprecate-specs.js
packages/core/internal/prop-types/tests/prop-types-specs.js

Unit tests could be added to packages/core/internal files for quality management.
Added unit tests to cover more cases.
WRO-12241

WRO-12241: Update unit test for packages/core/internal files

---

packages/ui/Scroller/tests/Scroller-specs.js

Increased test coverage of Scroller component
- Create Scroller test file. (Copy from sandstone)
WRO-12244

WRO-12244: Increased test coverage of Scroller- part1

---

packages/core/platform/tests/platform-specs.js
packages/core/snapshot/tests/snapshot-specs.js
packages/core/util/tests/Job-specs.js
packages/core/util/tests/util-specs.js
packages/core/util/util.js

Unit tests could be added to packages/core files for quality management.
Added unit tests to cover more cases.
WRO-12239

WRO-12239: Update unit test for packages/core files

---

packages/ui/VirtualList/tests/VirtualGridList-native-specs.js
packages/ui/VirtualList/tests/VirtualGridList-specs.js
packages/ui/VirtualList/tests/VirtualList-native-specs.js
packages/ui/VirtualList/tests/VirtualList-specs.js

Increased test coverage of VirtualList component
- Add some `VirtualList` test cases
-  I removed some native tests. (I tried to simulate scrolling for native scroll scroller. But it failed)
WRO-12245

WRO-12245: Increased test coverage of VirtualList - part2

---

packages/sampler/.storybook/main.js

Fixed legacy hierarchy separator storybook warning by adding `warnOnLegacyHierarchySeparator: false` in storybook configuration
WRO-13686

WRO-13686: sampler: Fix warning warnOnLegacyHierarchySeparator

---

.travis.yml
package-lock.json
package.json
packages/core/dispatcher/tests/dispatcher-specs.js
packages/core/package.json
packages/i18n/package.json
packages/sampler/package.json
packages/spotlight/package.json
packages/ui/package.json

For preventing malware issues, we need to update node modules that fix severity vulnerabilities.
Update node modules' warnings via checking "npm audit"
WRP-858

WRP-858: Fix security vulnerabilities

---

packages/ui/Layout/Cell.js

CellDecorator link is broken on enactjs.com 
Modify the link to fit the jsdocs format
WRP-3682

WRP-3682: Modify @link tag for ui/Layout.CellDecorator

---

.travis.yml
docs/creating-components.md

Add Sandstone skin customization guide
Where to add this guide? 
Duplicated some of the guides like a folder structure. Shall I use the link instead? 
Updated
@MikyungKim Added a workaround command for travis error. See details in WRP-4450
WRO-12293

WRO-12293: Add Sandstone skin customization guide

---

codecov.yml
packages/ui/CHANGELOG.md
packages/ui/Touchable/Pinch.js
packages/ui/Touchable/PinchZoom.js
packages/ui/Touchable/Touch.js
packages/ui/Touchable/Touchable.js
packages/ui/Touchable/config.js
packages/ui/Touchable/tests/Touchable-specs.js
packages/ui/Touchable/useTouch.js

New feature to support pinch Zoom gesture
Add PinchZoom.js to ui/Touchable
I cannot simulate multi touch event in unit test.
WRO-4836

WRO-4836: Support PinchZoom gesture

---

packages/ui/CHANGELOG.md

PR #3114 missed the CHANGELOG update for pinchConfig API.
add "pinchConfig" API to CHANGELOG
WRP-6259
PR #3114 
Enact-DCO-1.0-Signed-off-by: Hoeun Ryu <hoeun.ryu@lge.com>

WRP-6259:ui:CHANGELOG: add missing pinchConfig API for Touchable

---

.travis.yml
packages/ui/internal/IdProvider/tests/useId-specs.js

Enact-DCO-1.0-Signed-off-by: Alexandru Morariu alexandru.morariu@lgepartner.com
Removed unused property from unit test.
WRP-6651

WRP-6651: Fixed lint warnings in enact.

---

packages/i18n/package.json
packages/sampler/package.json

Update ilib v14.17.0
- Update ilib v14.17.0
WRP-10590

WRP-10590: Update ilib v14.17.0

---

docs/contributing/adding-automated-ui-tests.md

screenshot test guide example was wrong
fixed screenshot test example

Fix the wrong screenshot test example

---

packages/i18n/package.json

Update ilib-webos version to v14.17.0-webos1
Update ilib-webos version to v14.17.0-webos1
WRP-7019
Enact-DCO-1.0-Signed-off-by: Taeyoung Hong taeyoung.hong@lge.com

WRP-7019: Update ilib-webos version to v14.17.0-webos1

---

packages/ui/Touchable/Touch.js

There is a trailing comma eslint warning.
Removed trailing comma.
WRP-12241

WRP-12241: Fixed `trailing comma` eslint warning

---

packages/spotlight/Spottable/Spottable.js
packages/ui/Button/Button.js
packages/ui/GridListImageItem/GridListImageItem.js
packages/ui/IconButton/IconButton.js
packages/ui/Item/Item.js
packages/ui/Layout/Cell.js
packages/ui/Layout/Layout.js
packages/ui/Routable/Routable.js
packages/ui/Routable/Router.js
packages/ui/Spinner/Spinner.js
packages/ui/ToggleIcon/ToggleIcon.js
packages/ui/ToggleItem/ToggleItem.js
packages/ui/ViewManager/TransitionGroup.js

There are broken links that refer to other `prop`s in the documentation.
Broken links
- https://enactjs.com/docs/modules/ui/Button/#ButtonBase.iconFlip
- https://enactjs.com/docs/modules/ui/GridListImageItem/#GridListImageItem.placeholder
- https://enactjs.com/docs/modules/ui/IconButton/#IconButtonBase.children
- https://enactjs.com/docs/modules/ui/Layout/#Layout
- https://enactjs.com/docs/modules/ui/Layout/#CellBase.shrink
- https://enactjs.com/docs/modules/ui/Layout/#CellBase.size
- https://enactjs.com/docs/modules/ui/Layout/#LayoutBase
- https://enactjs.com/docs/modules/ui/Routable/#Routable.defaultConfig.navigate
- https://enactjs.com/docs/modules/ui/Spinner/#SpinnerBase.blockClickOn
- …

WRP-11279 : Fix broken links referencing other props in documentation

---

packages/core/kind/kind.js

Some of the `core/kind` descriptions in the document(enactjs.com) need to be updated.
Removed `suitable for use with React hooks` for `functional` property for preventing confusion.
Added missing descriptions for kind configuration.
WRP-3140

WRP-3140: Update `core/kind` documentation

---

.travis.yml
docs/resources/index.md

Fix broken links in the enactjs documentation website
The Official React documentation `link` and the Official React tutorial `link` was changed 
WRP-14749
Enact-DCO-1.0-Signed-off-by: Ion Andrusciac ion.andrusciac@lgepartner.com

WRP-14749: Fix broken links in the enactjs documentation website

---

packages/core/internal/Registry/tests/Registry-specs.js
packages/core/kind/tests/kind-specs.js
packages/i18n/I18nDecorator/tests/I18nDecorator-specs.js
packages/spotlight/SpotlightContainerDecorator/tests/SpotlightContainerDecorator-specs.js
packages/ui/Button/tests/Button-specs.js
packages/ui/Group/tests/Group-specs.js
packages/ui/Item/tests/Item-specs.js
packages/ui/RadioDecorator/tests/RadioDecorator-specs.js
packages/ui/Routable/tests/Routable-specs.js
packages/ui/ToggleIcon/tests/ToggleIcon-specs.js
packages/ui/ToggleItem/tests/ToggleItem-specs.js

`@testing-library/user-event` version 14 introduced API changes so we need to update unit tests.
Updated tests that are using `@testing-library/user-event` module.
TBD
This PR should be merged after @enact/cli 6.0.0 is released, otherwise, Travis will be broken.
WRP-14328

WRP-14328: Fix unit tests to work with `@testing-library/user-event` v14

---

README.md
packages/core/README.md
packages/spotlight/README.md

Update README.md
Added more information about the Enact and useful doc links.
Updated some outdated information in the core and spotlight module
WRP-593

WRP-593: Update README.md 

---

packages/spotlight/CHANGELOG.md
packages/spotlight/SpotlightContainerDecorator/SpotlightContainerDecorator.js
packages/spotlight/docs/index.md

There is no description about 'leaveFor' of SpotlightContainerDecorator. 
Add the docs for 'leaveFor'
WRP-21714

WRP-21714: Add docs about `leaveFor`

---

packages/i18n/src/Loader.js
packages/i18n/src/zoneinfo.js
packages/spotlight/src/pointer.js
packages/spotlight/src/spotlight.js
packages/webos/application/application.js
packages/webos/deviceinfo/deviceinfo.js
packages/webos/keyboard/keyboard.js
packages/webos/platform/platform.js
packages/webos/pmloglib/pmloglib.js

In 2018, PalmSystem was renamed to webOSSystem. (Note: in a browser environment, the same object has old and new names.) And PalmSystem is only used for backward compatibility purposes.
Replace PalmSystem with webOSSystem while still using PalmSystem as a fallback.
WRP-12308
Enact-DCO-1.0-Signed-off-by: Hoeun Ryu <hoeun.ryu@lge.com>

WRP-12308: replace PalmSystem with webOSSystem

---

packages/i18n/src/zoneinfo.js

Isomorphic build failed due to missing check of 'window'
Fixed missing check routine
WRP-12308

WRP-12308: hotfix of isomorphic build failure

---

package-lock.json
package.json
packages/i18n/package.json
packages/sampler/package.json

Updated dependencies' minor version.
Updated dependencies' minor version.
WRP-21914

WRP-21914: Updated dependencies' minor version

---

packages/ui/useScroll/utilDOM.js

An internal logic to call DOM API fails due to unsafe check condition.
Update check condition to be safe.
WRP-27604

Fix unsafe condition check when trying to call DOM API internally

---

packages/ui/Marquee/tests/Marquee-specs.js

Remove unused code in Marquee-specs.js file
WRQ-2421

WRQ-2421: Remove unused Marquee-specs code

---

packages/i18n/package.json
packages/sampler/package.json

Updated dependencies' minor version.
Updated dependencies' minor version.
WRQ-13128

WRQ-13128: Update minor dependencies to fix vulnerabilities

---

lerna.json
package-lock.json
package.json

`lerna` v8 has been released.
This module needs to be updated to the latest node modules to fix security vulnerabilities and prevent malware.
Update `lerna` v8
- Fix the `lerna.json` script via `lerna repair`(automated fix).
https://github.com/lerna/lerna/releases/tag/v8.0.0
WRQ-7041

WRQ-7041: Update lerna v8

---

packages/ui/Marquee/MarqueeController.js
packages/ui/Marquee/useMarqueeController.js

Refactor `MarqueeController` to be hook-based implementation.
Add `useMarqueeController` custom hook that returns the MarqueeControllerContext provider and handlers related to Marquee synchronization.
WRQ-342

WRQ-342: Implement useMarqueeController

---

packages/sampler/npm-shrinkwrap.json
packages/sampler/package.json
packages/ui/package.json

Storybook 8.2 introduced an error for our configuration in the theme libraries
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#failed-to-resolve-import-storybookx-error 
Updated storybook to 8.2 and installed missing depedency
Fixed interlink script and added ilib dependency for enact/ui
WRQ-29126
Enact-DCO-1.0-Signed-off-by: Daniel Stoian ([daniel.stoian@lgepartner.com](mailto:daniel.stoian@lgepartner.com))

WRQ-29126: Updated storybook to 8.2 and fixed enact/ui interlink script

---

packages/sampler/package.json

Update babel-loader v9
Update babel-loader v9
Breaking changes in babel-loader v9 (https://github.com/babel/babel-loader/releases/tag/v9.0.0)
- Require babel ^7.12.0 and Node.js >= 14.15.0 versions
- Remove dependency on loader-utils and drop webpack 4 support
WRQ-28043

WRQ-28043: Update babel-loader v9

---

codecov.yml
packages/webos/CHANGELOG.md
packages/webos/signLang/SignLangDecorator.js
packages/webos/signLang/index.js
packages/webos/signLang/package.json
packages/webos/signLang/signLang.js

Sign language services are added and require framework support.
Added a function to support HoC for communicating with sign language service in Enact Framework.
WRR-1052
#3270
#3272
This PR is a cherry-picking from #3270 authored by @changgilee 

WRR-1052: Add sign language feature (backport to 4.7.x)

---

codecov.yml
packages/webos/CHANGELOG.md
packages/webos/signLang/SignLangDecorator.js
packages/webos/signLang/index.js
packages/webos/signLang/package.json
packages/webos/signLang/signLang.js

Sign language services are added and require framework support.
Added a function to support HoC for communicating with sign language service in Enact Framework.
WRR-1052
#3270
#3273
This PR is a cherry-picking from #3270 authored by @changgilee 

WRR-1052: Add sign language feature (backport to 4.9.x)

---

package-lock.json
package.json
packages/i18n/package.json
packages/sampler/package.json
packages/ui/package.json

Update dependencies' minor and patch version
Update dependencies' minor and patch version
WRR-1519

WRR-1519: Update dependencies' minor and patch version

---

.travis.yml

This is a PR that modified the node version to fit the release target environment.
It is not directly related to WRR-976 implementation and was written only for node version changes.
Fixed travis' nodejs version to 16
WRR-976
Enact-DCO-1.0-Signed-off-by: Hyelyn Kim (myelyn.kim@lge.com)

WRR-976: Modify node version to match with the release target environments

---

packages/core/internal/Registry/tests/Registry-specs.js
packages/core/kind/kind.js
packages/i18n/I18nDecorator/I18nDecorator.js
packages/i18n/I18nDecorator/useI18nContext.js
packages/ui/FloatingLayer/useFloatingLayer.js
packages/ui/FloatingLayer/useFloatingLayerDecorator.js
packages/ui/Marquee/useMarqueeController.js
packages/ui/Placeholder/PlaceholderControllerDecorator.js
packages/ui/Placeholder/tests/PlaceholderDecorator-specs.js
packages/ui/Resizable/tests/Resizable-specs.js
packages/ui/Resizable/tests/useResize-specs.js
packages/ui/Resizable/useResize.js
packages/ui/Routable/Routable.js
packages/ui/Routable/useLink.js
packages/ui/Scroller/Scroller.js
packages/ui/Skinnable/useSkins.js
packages/ui/VirtualList/VirtualList.js
packages/ui/useScroll/useScroll.js

I replaced Context.Provider with Context for our enact components  and replaced useContext with use.
WRR-15901

WRR-15901: Replace Context.Provider to Context

---

packages/core/internal/Registry/tests/Registry-specs.js
packages/core/kind/kind.js
packages/i18n/I18nDecorator/I18nDecorator.js
packages/i18n/I18nDecorator/useI18nContext.js
packages/ui/FloatingLayer/useFloatingLayer.js
packages/ui/FloatingLayer/useFloatingLayerDecorator.js
packages/ui/Marquee/useMarqueeController.js
packages/ui/Placeholder/PlaceholderControllerDecorator.js
packages/ui/Placeholder/tests/PlaceholderDecorator-specs.js
packages/ui/Resizable/tests/Resizable-specs.js
packages/ui/Resizable/tests/useResize-specs.js
packages/ui/Resizable/useResize.js
packages/ui/Routable/Routable.js
packages/ui/Routable/useLink.js
packages/ui/Scroller/Scroller.js
packages/ui/Skinnable/useSkins.js
packages/ui/VirtualList/VirtualList.js
packages/ui/useScroll/useScroll.js

Enact-DCO-1.0-Signed-off-by: Alexandru Morariu alexandru.morariu@lgepartner.com
This reverts commit 44ee2d71066442add1d0209518bb118e5bd33f31.
WRR-15901

WRR-15901: Revert Replace Context.Provider to Context

---

packages/ui/Card/Card.module.less

Fixed Card component to position children properly.
Set children width to be 100% when captionOverlay prop is true
WRR-21105

WRR-21105: Fixed Card component to position children properly

---

packages/core/internal/Registry/tests/Registry-specs.js
packages/core/kind/kind.js
packages/i18n/I18nDecorator/I18nDecorator.js
packages/i18n/I18nDecorator/useI18nContext.js
packages/ui/FloatingLayer/useFloatingLayer.js
packages/ui/FloatingLayer/useFloatingLayerDecorator.js
packages/ui/Marquee/useMarqueeController.js
packages/ui/Placeholder/PlaceholderControllerDecorator.js
packages/ui/Placeholder/tests/PlaceholderDecorator-specs.js
packages/ui/Resizable/tests/Resizable-specs.js
packages/ui/Resizable/tests/useResize-specs.js
packages/ui/Resizable/useResize.js
packages/ui/Routable/Routable.js
packages/ui/Routable/useLink.js
packages/ui/Scroller/Scroller.js
packages/ui/Skinnable/useSkins.js
packages/ui/VirtualList/VirtualList.js
packages/ui/useScroll/useScroll.js

I replaced Context.Provider with Context for our limestone components  and replaced useContext with use.
WRR-15901

WRR-15901: Updated Context for React19

---

docs/migration/enact/migrating-to-enact-5.md

As new version of design tokens is released, some variables needs to be renamed.
Also, migration guide needs to mention changes of beta version
Updated 5.0 migration guide 
WRR-24644

WRR-24644: Updated 5.0 migration guide according to the latest design tokens and added changes included in beta version

---

.travis.yml
packages/core/internal/WithRef/WithRef.js
packages/spotlight/src/spotlight.js

Changes made to Enact MR will also be applied to develop.
I applied 3 changes related to `ContextualPopupDecorator` and `InputField`. Please check the links below.
WRR-22121
(WRR-21642, WRR-22638, WRR-24070)
Enact-DCO-1.0-Signed-off-by: Hyelyn Kim (myelyn.kim@lge.com)

WRR-22121: Apply Enact MR version changes

---

README.md
package-lock.json
package.json
packages/core/package.json
packages/i18n/package.json
packages/sampler/npm-shrinkwrap.json
packages/sampler/package.json
packages/spotlight/package.json
packages/ui/package.json
packages/webos/package.json

Update dependencies to fix vulnerabilities
Update dependencies to fix vulnerabilities
- Update copyright years in README.md file
WRR-24909

WRR-24909: Update dependencies to fix vulnerabilities

---

docs/migration/enact/migrating-to-enact-5.md

Migration guide needs to mention changes of Limestone 1.0.0 version
Updated 5.0 migration guide 
WRR-27070

WRR-27070: Updated 5.0 migration guide according to the latest design tokens and added changes included in 1.0 version

---

package-lock.json
package.json
packages/core/package.json
packages/i18n/package.json
packages/sampler/npm-shrinkwrap.json
packages/sampler/package.json
packages/ui/package.json
packages/webos/package.json

Update minor dependencies to fix vulnerabilities
Update minor dependencies to fix vulnerabilities
NXT-588

NXT-588: Update minor dependencies to fix vulnerabilities
