- packages/moonstone/RadioItem/RadioItem.module.less
- packages/moonstone/styles/variables.less
`RadioItem` dot does not horizontally align with its intended boundaries.
Updated the implementation to be closer to the intended design. The design specifies a 20px size, so the new size is 21, up from 18 with a 2px outset (for a final size of 22). The new dot has a 21 total outer width, and a 2px inset stroke. The center selected dot is now 4px, and although it's not a multiple of 3, the element this size is assigned to does not impact the layout in any way, so it seems permissible, given the drastic visual difference if we choose any other size than what is specified in the design. The positive size is now the stroke and the pink area when selected now match in width, which was previously off by 1px.
> ENYO-6015: Updated Radio Dot to more closely match the design

- packages/moonstone/CHANGELOG.md
- packages/moonstone/ExpandableList/ExpandableList.js
- packages/moonstone/ExpandableList/tests/ExpandableList-specs.js
It was possible for an `ExpandableList` to error if an array of selected items was passed to
a non-multi-select.
Refactor the logic to deal better with `selected` as array.
Added tests
ENYO-6019
> ENYO-6019 Fixed ExpandableList with selected array

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Scrollable/ScrollButtons.js
…n switching modes
`Scroller` cannot change focus from a scroll button to the opposite scroll button when changing from pointer to 5way mode. Additionally, the browser (not the `Scroller`) will scroll in the 5way direction pressed.
We programmatically set focus to the opposite scroll button, but failed to prevent the default browser scroll behavior or turn off pointer mode. It should be safe to explicitly turn off pointer mode, since we are guarded by a directional key press.
> ENYO-6021: Fix Scroller paging control focus behaviors

- packages/sampler/stories/qa/Scroller.js
Previously, when a scroll button was focused & disabled - then the window was blurred and re-focused, we would set focus to the top-most spottable element in the scroller - since the scroll button would be disabled and couldn't become focused again. However, now that disabled components can be re-focused, it means that the disabled scroll button is the last-focused element and regains focus.
This appears to be expected behavior now. We could revisit this behavior later, but I think we can remove this sample (and associated test cases), since this test does not benefit us for now.
> ENYO-6014: Remove Unneeded Scroller sample

- packages/moonstone/VirtualList/VirtualListBase.js
There are cases where `VirtualList` focus could unexpectedly change to a last-focused item.
Each time when setting focus to "next" items, `VirtualList` was needlessly setting the current index value to `this.nodeIndexToBeFocused`. This value only needs to be set prior to explicitly setting scroll position/focus elsewhere (e.g. a wrap or page event). As a result, `this.nodeIndexToBeFocused` was not being nullified, causing unexpected focus changes when items were mounted.
> ENYO-5979: Fix VirtualList unexpectedly changing focus to last focused item

- packages/moonstone/VirtualList/VirtualListBase.js
- packages/ui/VirtualList/VirtualListBase.js
When items of list is small, initial focus is not exist in VirtualList
When items is small, componentDidUpdate is not called.
In current status, restoreFocus() is only declared in componentDidUpdate.
https://jira2.lgsvl.com/browse/ENYO-6022
> ENYO-6022: Fix setting initial focus of short VirtualList

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Dropdown/Dropdown.js
[New requirement]
Not allowed to move spotlight past the top and bottom of the popup.
Users can close the Dropdown list via back key or selecting any options.
I added prop `spotlightRestrict: "self-only"` to ContextualButton of Dropdown.  
ENYO-6020
> Dropdown: Not allowed to move spotlight past the top and bottom of the popup

- packages/moonstone/CHANGELOG.md
- packages/moonstone/VideoPlayer/VideoPlayer.module.less
Fix VideoPlayer to hide scrim if bottom controls are hidden
Add `high-contrast-scrim` class name.
This class name is add or removed accoring to bottom controls visibility
ENYO-6023
> ENYO-6023: Fix VideoPlayer to hide scrim if bottom controls are hidden

- docs/migration/enact/migrating-to-enact-3.md
Adds `moonstone` styling changes to the Enact 3.0 migration guide.
ENYO-6005
> ENYO-6005: Add moonstone style changes to 3.0 migration guide

- packages/moonstone/CHANGELOG.md
- packages/moonstone/styles/internal/fonts.less
- packages/sampler/stories/qa/Text.js
Mixing Latin and non-Latin text when in a non-Latin locale causes mismatched font weights.
Assigned the Latin-fallback for non-Latin rules to be a weight that matches the available non-Latin fonts.
> PLAT-79791: Update font weights for non-latin mixed text

- packages/moonstone/Slider/Slider.module.less
Slider may display with wrong opacity when disabled and focused. This is due to disabled rule applied has the same specificity with general moonstone disable negation rule (i.e. .moonstone[disabled] [disabled]).
Extra opacity rule should only be applied when it's focused and disabled, which would increase the specificity.
See also #2347 
> ENYO-6032: Fix slider opacity when disabled and focused

- packages/moonstone/RadioItem/RadioItem.module.less
RadioItem may display toggle icon with wrong opacity when disabled and focused. This is due to disabled rule (i.e. `[disabled] .RadioItem_toggleIcon__3GiLZ.moonstone`) applied to toggle icon has the same specificity with general moonstone disable negation rule (i.e. `.moonstone[disabled] [disabled]`).
Extra opacity rule should only be applied when it's focused and disabled, which would increase the specificity.
> ENYO-6031: Fix specificity for focused and disabled

- packages/moonstone/CHANGELOG.md
- packages/moonstone/ContextualPopupDecorator/ContextualPopup.module.less
- packages/moonstone/Dropdown/Dropdown.js
- packages/moonstone/Dropdown/Dropdown.module.less
- packages/moonstone/styles/variables.less
- packages/sampler/stories/default/Dropdown.js
Added support for `'small'`, `'medium'`, and `'large'` sizes for `Dropdown`.
The sizes were based on `Button` sizes:
`'small'` = small button min-width + 100px
`'medium'` = large button max-width - 100px
`'large'` = large button max-width
PLAT-79571
> PLAT-79571: Add prop width to moonstone/Dropdown

- packages/moonstone/CHANGELOG.md
- packages/moonstone/VirtualList/VirtualListBase.js
The logic within VL to restore focus assumed that the vl-placeholder element would be the only spottable on first render when trying to restore. By forcing the vertical scrollbar and setting focusableScrollbar and support focused + disabled (since the scroll buttons are initially disabled until the bounds and scroll position are sorted out), the assumption breaks down and VL fails to cache the last focused index.
Replace that assumption and instead find the placeholder, if it exists, set the index and return.
> ENYO-5993: Fix VirtualList to restore focus to an item when scrollbars are visible

- packages/moonstone/VirtualList/VirtualListBase.js
The component will throw an error when attempting to wrap, causing applications to crash.
Re-adding back the `findSpottableItem` method that was removed in #2262 - the method was being used elsewhere in the component.
> ENYO-6033: VirtualList: Add missing findSpottableItem method

- packages/ui/Measurable/Measurable.js
New linting rules caused Travis errors
Made the suggested change and put the `ref.current` into a variable.
> ENYO-6046: Fix Measurable linting

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Panels/Header.js
- packages/moonstone/Panels/Header.module.less
The title is not center-aligned when centeted is set.
Fixed center alignment issue of Header by adding CSS `padding-start` when centered.
ENYO-6047
> ENYO-6047: Header: title is not center-aligned

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Dropdown/Dropdown.js
A Dropdown with an open menu will remain open when it becomes disabled.
Dropdown closes if it is disabled after opening.
> ENYO-6035: Dropdown closes if it is disabled after opening

- packages/moonstone/styles/variables.less
Dropdown uses made-up sizes
Updted the size values
Dropdown supports the `size` prop which lets you choose what size (Button) the activator/text should be. The medium and large `width` plus the combination of `size` small and large result in the **same** width button/activator, while `width=small` + `size=small` vs `width=small` + `size=large` results in a **different** button/activator width.
This is due to `<Button size="large">` having a smaller `min-width` than the small Dropdown width size.
> PLAT-79571: Updated to prescribed Dropdown widths

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Dropdown/Dropdown.js
- packages/moonstone/Dropdown/tests/Dropdown-specs.js
Apply accessibility on new Dropdown component
Remove `role=alert` from the ContextualButton for avoiding read all internal items when drop opens
Add `role=checkbox` and `aria-checked` for reading selected status and X of Y
> PLAT-79783: Apply accessibility on Dropdown

- packages/moonstone/Scrollable/Scrollable.js
- packages/moonstone/Scrollable/ScrollableNative.js
After #2262, a list scrolls twice by a single page up/down key press.
We already have a scrolling logic by page keys on scrollbars to cover its own behavior, and another logic is added from #2262 for a general scrolling feature originally designed for contents not for scrollbars.
So, I changed a newly added general logic to be applied to the contents area only.
ENYO-6034
PLAT-65757
> ENYO-6034: Fix Scroller to scroll once by page up/down

- packages/ui/CHANGELOG.md
- packages/ui/ViewManager/View.js
- packages/ui/ViewManager/tests/View-specs.js
Arrangers that rely on `previousIndex` and `index` to position views could throw on first render.
Default `previousIndex` to `index` for arrangers to ensure there's a valid value
Also added a test to verify the input API of arranger methods.
> ENYO-6050: Fix ViewManager to provide a default value for previousIndex

- packages/moonstone/Scrollable/ScrollButtons.js
- packages/moonstone/Scrollable/ScrollThumb.js
- packages/moonstone/Scrollable/Scrollable.js
- packages/moonstone/Scrollable/ScrollableNative.js
- packages/moonstone/Scrollable/Scrollbar.js
- packages/moonstone/Scroller/Scroller.js
- packages/moonstone/VirtualList/VirtualList.js
- packages/moonstone/VirtualList/VirtualListBase.js
- packages/ui/Scrollable/ScrollAnimator.js
- packages/ui/Scrollable/ScrollThumb.js
- packages/ui/Scrollable/Scrollable.js
- packages/ui/Scrollable/ScrollableNative.js
- packages/ui/VirtualList/VirtualListBase.js
We need to cleanup VirtualList and Scroller because we missed some patches and applied uncompleted patches in them.
* Remove unused `findSpottableItemWithPositionInExtent()`
* Apply the patch for `Scrollable` in ENYO-5957 to `ScrollableNative`
* Cleanup `onAcceleratedKeyDown` parameters
* Reduce calling `getNextIndex() in VirtualList once
* Focus an item immediately when an app mounted and called the `cbScrollTo` in `VirtualList`
* Cleanup Scrollable and …
> PLAT-80079: Cleanup code in VirtualList and Scroller

- packages/i18n/CHANGELOG.md
- packages/i18n/Uppercase/Uppercase.js
- packages/i18n/Uppercase/tests/Uppercase-specs.js
- packages/moonstone/Button/Button.js
- packages/moonstone/Dialog/Dialog.js
- packages/moonstone/Divider/Divider.js
- packages/moonstone/Panels/Header.js
- packages/moonstone/TooltipDecorator/Tooltip.js
- packages/moonstone/TooltipDecorator/TooltipDecorator.js
Deprecate `i18n/Uppercase` HOC for `i18n/util`
Should `casing` prop added by the Uppercase HOC also be marked deprecated and warn?
> Deprecate Uppercase HOC

- CHANGELOG.md
- packages/core/CHANGELOG.md
- packages/i18n/CHANGELOG.md
- packages/moonstone/CHANGELOG.md
- packages/sampler/CHANGELOG.md
- packages/spotlight/CHANGELOG.md
- packages/ui/CHANGELOG.md
- packages/webos/CHANGELOG.md
I missed/mistyped the change log headers in alpha.6 so let's fix that before we move ahead.
> PLAT-80460: Fix change log titles from alpha.6

- packages/sampler/package.json
* `browserslist` is broken currently with a bad release on NPM interacting incorrectly with current `caniuse-lite`
* Setting top-level dependency `caniuse-lite@1.0.30000974` fixes the issue.
> ENYO-6062: BrowsersList failure on Enact Sampler

- packages/moonstone/CHANGELOG.md
- packages/moonstone/GridListImageItem/GridListImageItem.module.less
There is no `image` css class in `GridListImageItem.module.less` of moonstone.
`GridListImageItem` supports css overriding for image according to the specification of css prop
Add just `image` class
ENYO-6066
> ENYO-6066: Fix GridListImageItem to add 'image' css class

- packages/moonstone/CHANGELOG.md
- packages/moonstone/VirtualList/VirtualListBase.js
…t line
When pressing a 5way directional key in `VirtualList` - where the next target is a) out of the current viewable range and b) an oblique direction - focus is set on the control, but the control is not scrolled into view. This causes the appearance of "losing" spotlight focus.
Properly scroll the focused control into view.
> ENYO-6051: Fix VirtualList to scroll to focused item in next line

- packages/sampler/.qa-storybook/config.js
- packages/sampler/.storybook/config.js
- packages/sampler/src/configure.js
- packages/sampler/src/enact-knobs/select.js
- packages/sampler/stories/default/Button.js
- packages/sampler/stories/default/DayPicker.js
- packages/sampler/stories/default/Icon.js
- packages/sampler/stories/default/IconButton.js
- packages/sampler/stories/default/Layout.js
- packages/sampler/stories/default/VideoPlayer.js
- packages/sampler/stories/qa/Button.js
- packages/sampler/stories/qa/IncrementSlider.js
- packages/sampler/stories/qa/Item.js
- packages/sampler/stories/qa/Scroller.js
- packages/sampler/stories/qa/Slider.js
- packages/sampler/stories/qa/Spotlight.js
- packages/sampler/stories/qa/Text.js
- packages/sampler/stories/qa/Touchable.js
* The Sampler `select` knob doesn't assign a groupId when none if found. As a result, `select` knobs with no explicit group are appearing in an "Other" category. This can be observed in the Moonstone->Icon story.
* Add a fallback to use `displayName` as the default `groupId` value when not found. This is the technique already used on the other knob proxies.
> ENYO-6064: Derive groupId from displayName, when one is not set

- packages/sampler/stories/qa/Spotlight.js
Default size of buttons changed causing the sample to lack space between them which made it impossible to place the pointer in the middle without focusing either.
Space the buttons out independent of their size
> PLAT-80732: Fix Spotlight qa sample to add space between buttons

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Dropdown/Dropdown.js
- packages/moonstone/Scrollable/Scrollable.js
Added/fixed focus management for `Dropdown`
- When dropdown opens, the previously-selected item (if available) will be scrolled to (vertically-centered) and focused
- Pressing 5way horizontally will close the popup and move focus to the next eligible horizontal target
- Pressing 5way vertically (when at the top/bottom bounds of the `Dropdown` list) will not allow focus to leave the list
- Pointer can be used to begin an interaction with other components while a `Dropdown` is opened, effectively closing the `Dropdown` (removing the scrim)
> PLAT-79871: Fix spotlight support for Dropdown

- packages/moonstone/Input/Input.js
- packages/moonstone/Input/Input.module.less
- packages/moonstone/Panels/Header.module.less
- packages/moonstone/styles/colors-highcontrast.less
- packages/moonstone/styles/colors.less
- packages/moonstone/styles/variables.less
Update Header with Input to match new designs. 
Added a span, `.inputHighlight`, with the input value and background color to mimic highlighted text when the `InputDecorator` receives focus.
`.inputHighlight`'s opacity and background color are left up to `Header` to handle otherwise they are transparent in normal input because in normal input, they are not needed.
PLAT-79069
> PLAT-79069: Update Header with Input focus

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Scroller/Scroller.js
- packages/sampler/stories/qa/Scroller.js
When
* only the first item is spottable in Scroller,
* the item gets spot,
* the item locates at (0,0), 
* the item height is larger than the list height,
* paging controls can be spottable, and
* pressing a Down key,
Scroller does not scroll and Spotlight stays on the first item.
This was the edge case for the requirement. I fixed the condition, then it worked.
I added the qa Scroller sampler for the TC.
PLAT-80081
> PLAT-80081: Scroll and Move Spotlight to the paging control properly via 5-way Down if the current item sticking to the top is only spottable

- packages/moonstone/Scroller/Scroller.js
- packages/moonstone/VirtualList/VirtualListBase.js
- packages/ui/Scrollable/Scrollable.js
- packages/ui/Scrollable/ScrollableNative.js
- packages/ui/Scroller/Scroller.js
- packages/ui/VirtualList/VirtualListBase.js
Some public props for VirtualList do not show in JSDoc.
Major fix
- Expose `ui/Scrollable` public props to `ui/VirtualList.VirtualListBase` and `ui/Scroller.ScrollerBase` JS Docs.
- Expose `moonstone/Scrollable` public props to `ui/VirtualList.VirtualListBase` and `moonstone/Scroller.ScrollerBase` JS Docs.
- Fix to show `id` prop in `moonstone/VirtualList.VirtualListBase` and `moonstone/Scroller.ScrollBase`.
- Fix to show `direction` prop in `ui/VirtualList.VirtualListBase` and `ui/Scroller.ScrollBase`.
Minor fix
- Fix to show `data-webos-voice-focused` and  `data-webos-voice-group-label` props in not `m …
> PLAT-76949: Expose Scrollable public props to VirtualListBase and ScrollerBase JS Docs

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Popup/Popup.js
If `Popup`'s `open` state is changed while in transition, the floating layer closes before the transition is finished. One of the side effects of this is spotlight pause will not properly resume as it depends on transitionEnd event.
Fix setting `floatLayerOpen` state to check for both OPEN and OPENING `popupOpen` state.
> ENYO-6074: Fix FloatingLayer to be closed after transition ends

- packages/moonstone/Picker/Picker.js
- packages/moonstone/Slider/Slider.js
- packages/moonstone/internal/Picker/Picker.js
- packages/moonstone/internal/validators/validators.js
- packages/ui/Slider/PositionDecorator.js
- packages/ui/internal/validators/validators.js
`Slider` warns on every render if values/max are not divisible by steps.
Add functions in `validators` to display only once per validation.
> ENYO-6061: Warn only once for validation

- packages/ui/CHANGELOG.md
- packages/ui/Icon/Icon.js
- packages/ui/Icon/tests/Icon-specs.js
Icon names longer than one character that are outside of the iconsList were being treated as URLs.
Updated the checker code to look for URL-like symbols to determine "URL-ness" of a string.
> PLAT-78973: Updated Icon to support arbitrary strings as icon names

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Scrollable/Scrollable.js
- packages/moonstone/Scrollable/ScrollableNative.js
`scrollAndFocusScrollbarButton` function only accounts for vertical direction spotlight leave to focus to the closest scroller button. This results in an error where focus moving out horizontally from the container fails to find scroller to focus.
Checks both the vertical and horizontal direction and check if the scroller exists in the direction. A simple condition check whether scroller exists or not would probably be enough, but it's probably better to get the logic down correctly.
> ENYO-6073: Fix Scrollable to focus outside the container

- packages/sampler/src/MoonstoneEnvironment/MoonstoneEnvironment.js
- packages/sampler/stories/qa/VirtualList.js
The existing new sample nests Panels, which isn't ideal.
This change leverages the existing system for disabling the auto-inserted Panels element in favor of our own (defined in the sample). It now syncs-up with other samples and positions elements correctly on the page.
Also updated MoonstoneEnvironment to have better support for the (never before used) `noPanels` option.
> Updated sample to remove Panels-in-Panels problem

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Scrollable/Scrollable.js
- packages/moonstone/VirtualList/VirtualListBase.js
Keydown events in `VirtualList` do not bubble expectedly.
Fix `keydown` event bubbling when pressing 5way directional keys from either a list item or scroll buttons.
The changes in this PR have the potential to affect a number of 5way behaviors (all for the better hopefully 🤞 ). Since we need to be aware of `keydown` events on the scroll buttons, we need to change the dom where we are listening for events - from the wrapper to the spotlight container. This change means we need to act on the capture phase of the event in order to prevent an application from being able to act on the event when attached to the `VirtualList`, as was the intent behind the existing behavior. We should spend time thoroughly testing this change.
> PLAT-79985: Fix VirtualList event bubbling

- docs/best-practices.md
- docs/glossary.md
- docs/migration/enact/migrating-to-enact-2.md
- docs/migration/enact/migrating-to-enact-3.md
- docs/testing-components/unit-testing/index.md
- docs/theming.md
- packages/i18n/docs/index.md
- packages/spotlight/docs/index.md
enactjs/docs#109 adds support for a `toc` field in the front matter of our static docs. This PR configures it for some of them based on my review of their length and utility.
> PLAT-61546: Configure table of contents for docs

- packages/sampler/stories/default/VirtualGridList.js
Recent changes to font size (and/or spacing & minWidth prop sizing or ri) caused the `GridListImageItem` components to fully display the `title` and `subtitle` content, making them not able to marquee - which was required for TCs and internal testing. 
Create long content that is applied to the `title` and `subtitle`, based on a {{%}} mod operator (every 2nd index for title, every 3rd index for subtitle). This way, there are:
- some `GridListImageItem` components that have no marquee-able content
- some can only marquee `title`
- some can only marquee `subtitle`
- some can marquee both `title` and `subtitle`
> PLAT-81278: Add Long Content to VirtualList Sample

- packages/moonstone/CHANGELOG.md
- packages/moonstone/IncrementSlider/IncrementSlider.js
- packages/moonstone/IncrementSlider/tests/IncrementSlider-specs.js
There is no aria-label when the value is min or max in IncrementSlider
Because we support focus to disabled item, aria-label of IconButton in IncrementSlider should be set even the value is min or max.
ENYO-6101
> ENYO-6101: Set the aria-label of IconButton in IncrementSlider

- packages/moonstone/CHANGELOG.md
- packages/moonstone/MoonstoneDecorator/fontGenerator.js
- packages/moonstone/styles/internal/fonts.less
The `LG Smart UI Global` collection of fonts has been removed (renamed) and replaced by `LG Smart UI AR HE TH` family of fonts.
These fonts have been updated to the new names.
There is a change in font-weight definition. Previously we had `LG Smart UI-Light` and `LG Smart UI-Regular` yet we support at least 3 different weights: light, regular, and bold. These new fonts come in non-matching weights: `LG Smart UI AR HE TH Regular` and `LG Smart UI AR HE TH SemiBold`. Previously, we'd mapped light to light, regular to regular, and regular to bold. (regular and bold would look the same). Now, these new fonts are being mapped to regular to light, regular to regular, and semibold to bold. (light and regular will use the same font-weight, and bold will stand out as different, as light did in the …
> PLAT-79873: Updated Global font to 3-languages font name(s)

- packages/moonstone/CHANGELOG.md
- packages/moonstone/LabeledItem/LabeledItem.module.less
- packages/moonstone/styles/variables.less
`g` characters and other "tall"(?) descenders extend too far down in LabeledItem's label and are clipped.
This slightly reduces the font size for largeText mode of the label, and adjusts the line-height and paddings to keep the text is basically the same position but have more clearance below itself before getting clipped off.
> ENYO-6076: Updated largeText mode label size/position in LabeledItem

- packages/spotlight/CHANGELOG.md
- packages/spotlight/SpotlightContainerDecorator/SpotlightContainerDecorator.js
- packages/spotlight/SpotlightContainerDecorator/tests/SpotlightContainerDecorator-specs.js
SpotlightContainerDecorator consumed `onFocusCapture` and `onBlurCapture` events preventing authors from handling those events as well.
Fixed it to forward except when spotlight has suppressed a focus event due to `spotlightDisabled`
> ENYO-6103: Fix SpotlightContainerDecorator focus and blur event forwarding

- packages/sampler/stories/qa/Spotlight.js
Several QA samples for spotlight were not wrapped in `Scroller` components, which caused issues where components could extend out of the viewport - behind the actions/knobs pane - resulting in:
- the inability to perform QA tests
- the appearance of "lost" focus
We should wrap the necessary samples (or component groups) in `Scroller` components and build a proper layout using `ui/Layout` components.
> PLAT-80938: Update Spotlight QA Samples

- packages/sampler/src/configure.js
- packages/sampler/stories/default/VirtualGridList.js
- packages/sampler/stories/default/VirtualList.js
Since the storybook 5 update, addon knobs will convert string characters to html entities. This is causing problems in our `VirtualList` samples, where the value of the `wrap` prop set as `'noAnimation'` would be seen as `&#39;noAnimation&#39;`
This will ultimately lead to the `wrap` prop being passed an `undefined` value, causing seemingly incorrect component behavior.
Update the knob config to ensure the right value is passed to the component
> PLAT-81126: Fix VirtualList wrap knob configuration

- packages/sampler/stories/qa/VirtualGridList.js
- packages/sampler/stories/qa/VirtualList.js
There was no way to test when `VirtualList` prevented the `keydown` event to bubble, as is done internally in order to strictly regulate how focus is handled within the component.
We have existing QA samples for both `VirtualList` and `VirtualGridList`, so we can simply add the onKeyDown action/prop to those samples.
> ENYO-6041: Add onKeyDown action/prop to VirtualList QA samples

- packages/moonstone/CHANGELOG.md
- packages/moonstone/VirtualList/VirtualListBase.js
When you call `.scrollTo({index, focus: true})` on a `VirtualList` after it has updated (after `componentDidUpdate`), the children may not have re-rendered yet, meaning the dom is not available and focus will not be set on the specified `index`, once the children are rendered and scrolled into view.
We can utilize the `this.handleUpdateItems` method of `VirtualList` in order to set focus after the list has been updated and the dom is available. We simply set the value of the index to be focused in the previous call to `this.focusByIndex`.
> ENYO-6099: VirtualList to set focus correctly after an update

- packages/moonstone/VideoPlayer/VideoPlayer.js
- packages/moonstone/VirtualList/VirtualListBase.js
- packages/spotlight/src/container.js
- packages/spotlight/src/spotlight.js
- packages/spotlight/src/target.js
The standardization of spatial navigation is progressing for the lightweight spotlight.
(https://drafts.csswg.org/css-nav-1/)
We need to check up the standard is appropriate to implement lightweight spotlight.
In the POC, We aim to apply the latest standard to spotlight and replace the spotlight code to spatial-navigation-polyfill.
There are two kind of spatial navigation event, `navnotarget` and `navbeforefocus` which is helpful for lightweight spotlight.
As the second step of this POC,  simplify some enact code with spatial navigation event.
In more details, the following are implemented:
1) Transfer …
> PLAT-80385: Utilize spatial-navigation event

- packages/moonstone/Panels/Arrangers.js
- packages/moonstone/Panels/Panels.module.less
CSS `clip-path` was no longer removed post-transition on Panels' Viewport
Use the `.transitioning` class instead of the `data-clip` attribute
I left off a changelog since the fix is not author-facing in any material way.
#2292 changed the arrangers to use Web Animations and introduced the regression.
#615 added the `data-clip` because we lacked an indicator for transitioning. 
#1297 added the `.transitioning` class but didn't address the `data-clip` usage.
> ENYO-6107: Fix Panels clip path to only apply during transition

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Scrollable/Scrollable.js
- packages/moonstone/Scrollable/ScrollableNative.js
VirtualList scrolls one more time on page up/down keys when an item is focused in pointer mode.
Since the focus disappears after scrolling by page keys, another handling logic for non-focused case in pointer mode performs once more. This makes a list scrolls twice far.
Basically, this happens `keydown` event is not consumed by the event handler which handles scroll by page. So, this PR adds simply `stopPropagation`.
PLAT-80194
> PLAT-80194: Fix Scroller and VirtualList duplicate scrolling by page up/down

- packages/core/platform/platform.js
- packages/core/platform/tests/platform-specs.js
Addendum to https://github.com/enactjs/enact/pull/2397
- webOS 5 and indeterminate versions of webOS would be ommitted as "webos" in platform detection
* Adds a webOS 5 detection entry as well as a generalized LG webOS catchall for indeterminate versions and versions with unexpected corresponding Chrome releases.
> Additional webOS platform detection, including a generic LG webOS fallback

- packages/moonstone/MoonstoneDecorator/fontGenerator.js
All (almost) of the international fonts were renamed to their new font names.
Updated the fontGenerator to use these new names. Also included a new Bold for Japanese (finally), as that is available now too.
> PLAT-79873: Added/Updated full collection of localized fonts

- packages/moonstone/Scrollable/Scrollable.js
- packages/moonstone/Scrollable/ScrollableNative.js
Pressing page up/down on a paging control of Scroller/VL would not scroll the viewport.
#2418 added code to stop page up/down key events from propagating in order to avoid duplicate paging when in pointer mode. This was caused by the first handler blurring the focused item before scrolling causing the second to think that nothing was focused so _it_ should scroll.
However, when the paging controls are focused, the first handler doesn't blur the focused item _and_ doesn't trigger the scroll so _nothing_ scrolls the view. This is normally handled by an …
> ENYO-6112: Fix Scrollable to only stop propagation when in contents

- packages/moonstone/VirtualList/VirtualListBase.js
The item container Ref (`this.itemContainerRef`) was not properly passed to DOM element.
Wrong variable name for the item container Ref was passed to DOM element.
So I renamed `initItemContainerRef` as `itemContainerRef`.
PLAT-81551
> PLAT-81551: Fix wrong item container Ref in VirtualList

- CHANGELOG.md
- packages/moonstone/CHANGELOG.md
- packages/moonstone/Panels/Header.js
- packages/moonstone/Panels/Header.module.less
- packages/sampler/stories/default/Header.js
There're some cases that cannot use Header because of under line of that component.
Actually, GUI of some applications want to use Header without underline.
Added prop `hideLine` to hide `border-bottom` in the Header component.
ENYO-6120
> ENYO-6120: Req: hides border-bottom of the Header

- packages/moonstone/CHANGELOG.md
- packages/moonstone/FormCheckbox/FormCheckbox.module.less
- packages/moonstone/FormCheckboxItem/FormCheckboxItem.module.less
`FormCheckboxItem` is too large when in large-text mode.
Manually reset the size of `FormCheckboxItem` and the associated checkmark component when in large-text mode so there is no "net change" in the size, according to the specs.
> PLAT-81339: FormCheckboxItem no longer responds to `largeText` mode

- packages/moonstone/CHANGELOG.md
- packages/moonstone/TooltipDecorator/Tooltip.module.less
The inherited layer order of a Tooltip inside a ContextualPopup and conflict, so they visually layer incorrectly (stack and look wrong).
Added a finite `z-index` to tooltip to promote it to its own layer-space, rather than its inherited space, which relies on DOM ordering.
> ENYO-6116: Fix Tooltip Layering Order

- packages/moonstone/CHANGELOG.md
- packages/moonstone/LabeledItem/LabeledItem.js
- packages/sampler/stories/default/LabeledItem.js
- packages/ui/Marquee/MarqueeDecorator.js
`LabeledItem` had no way to adjust when it would marquee. A use case existed where
it was used as a non-focusable component, so the default `marqueeOn` of `"focus"`
prevented it from being able to marquee.
Pass `marqueeOn` prop to label and contents.
Another possible solution is to modify the component to detect `spotlightDisabled` and automatically set `marqueeOn` for the items.  This seemed a bit too …
> Fix LabeledItem to pass marqueeOn prop

- packages/sampler/stories/qa/VirtualGridList.js
VirtualGridList and VirtualList become located in the same hierarchy.
PLAT-81157
`.` is a hierarchy separator for the title when calling 'storiesOf' method. If the title is "VirtualList.VirtualGridList", VirtualGridList show up underneath VirtualList.
> PLAT-81157: Move VirtualGridList to the component directory in qa-sampler

- packages/moonstone/CHANGELOG.md
- packages/moonstone/internal/Picker/PickerButton.js
Picker buttons that became disabled were refocused by React causing a duplicate read out.
Remove the `hidden` prop which was cascading into the DOM causing the unintentional side effect.
I couldn't find anything that specified that a hidden element _should_ be blurred but it was nonetheless. It occurred as a result of setting the attribute on the node so it must be a decision made by chrome and presumably new since v53.
Sort of a …
> PLAT-83114: Fix Picker read out of disabled buttons

- packages/webos/CHANGELOG.md
- packages/webos/LS2Request/LS2Request.js
- packages/webos/LS2Request/tests/LS2Request-specs.js
- packages/webos/package.json
If an LS2 service returns `null` as the message, it will be treated as a success even though it isn't.
Update the failure logic to account for null and undefined messages.
> ENYO-6079: Fix LS2Request to return an error for null messages

- docs/migration/enact/migrating-to-enact-3.md
- packages/moonstone/CHANGELOG.md
- packages/moonstone/Heading/Heading.module.less
- packages/moonstone/styles/colors-light.less
- packages/moonstone/styles/colors.less
- packages/moonstone/styles/mixins.less
- packages/moonstone/styles/variables.less
Heading text is too close to the line. It gives people anxiety; like driving really close to the cement barrier on the highway.
Added some space (according to the spec) between the text and the line, when the line is present. The design doc indicates that the space should be `12px`, however, the 12px spacing is based on the bottom of Korean characters, which don't include descenders or a taller-than-what's-visible line-height. Therefore this PR sets a `9px` padding, which accounts for a roughly `3px` inherent gap added by the line-height rule respecting taller glyphs and descenders. The net visual effect should be 12px total.
Finally doing house-keeping on the ancient divider mixin, which should no longer be necessary with the built-in customizability of the newer `Heading` component.
> PLAT-83172: Space added for Heading with line, cleanup of divider cruft

- docs/migration/enact/migrating-to-enact-3.md
- packages/moonstone/CHANGELOG.md
- packages/moonstone/ProgressBar/ProgressBar.module.less
- packages/moonstone/Slider/Slider.module.less
- packages/moonstone/styles/colors-light.less
- packages/moonstone/styles/colors.less
- packages/moonstone/styles/variables.less
- packages/ui/CHANGELOG.md
- packages/ui/ProgressBar/ProgressBar.js
- packages/ui/ProgressBar/ProgressBar.module.less
ProgressBar, Slider, and IncrementSlider need new colors.
New colors applied and cleaned up variables, abandoning old ones that didn't follow consistent naming conventions and removing unused variables. (Noted in the migration guide.)
This includes a change to `ui/ProgressBar` which inserts a new DOM node in the stack, which decouples the styling of the bars from the knob. This allows the bars to be "grayed out" when disabled and leave the knob at full opacity, per the designs. I did experiment with several approaches that didn't necessitate adding a new node, but ultimately this seemed to be the cleanest.
> PLAT-81341: Fix ProgressBar and Slider to match current designs

- packages/moonstone/styles/mixins.less
- packages/moonstone/styles/variables.less
Items all over got their text set to be too small.
The font size for the commonly used mixin `.moon-text-base` was, for some legacy reason, using the Header titleBelow font size to set the non-Latin font size. When this changed, via normal GUI request to fix the header font size, the body text mixin, in turn, also got smaller for non-Latin.
The solution is to create a `base` variable for the mixin to use instead of depending on some unrelated value, since the two can diverge unexpectedly.
> PLAT-83255: Corrected a non-sequitur variable association

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Scrollable/Scrollable.js
- packages/moonstone/Scrollable/ScrollableNative.js
VirtualList scrolls to the incorrect direction in RTL languages.
`ui/Scrollable` had `RTL` information as not `state` but `props` from https://github.com/enactjs/enact/pull/2035. But `moonstone/Scrollable` tried to get the RTL information in `ui/Scrollable`'s `state` incorrectly. So I fixed to get it from the `props`.
ENYO-6082
> ENYO-6082: Navigate items properly in VirtualList in RTL languages

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Scrollable/Scrollable.js
- packages/moonstone/Scrollable/ScrollableNative.js
- packages/moonstone/Scroller/Scroller.js
A Scroller jumped to the top when right key is pressed in the right most item of vertical scroller
If 5-way right is pressed on the right most item in the scroller and the scroller can scroll only vertically, the scroller should not jump. But he scroller tried to scroll horizontally due to no condition. Then the scroller jumped to the top because the `native` scroller do jump with wrong scroll x position. So I fixed the condition.
ENYO-6109
> ENYO-6109: Not try to scroll horizontally if the scroller can scroll only vertically

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Scroller/Scroller.js
When 5-way Down on the first item in a horizontal scroller, the scroller scrolls horizontally.
If 5-way down is pressed and there is no more spottable items to the direction in a vertical scroller, the scroller scrolls vertically. But if it is a horizontal scroller, we don't have to scroll. So I guard this action with a condition not to scroll.
ENYO-6135
> ENYO-6135: Not scroll horizontally via 5-way down in horizontal scroller

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Scrollable/Scrollable.js
- packages/moonstone/Scrollable/ScrollableNative.js
- packages/sampler/stories/default/VirtualGridList.js
- packages/sampler/stories/default/VirtualList.js
- packages/sampler/stories/qa/VirtualGridList.js
- packages/sampler/stories/qa/VirtualList.js
- packages/ui/Scrollable/Scrollable.js
…r is hidden
A behavior change in needed for scrolling components (`Scroller`, `VirtualList`, etc) so that they can respond to and scroll when a remote paging key (channel up/down) is pressed when the scrollbar is hidden. Currently no action is taken.
We had specific guards against performing the requested scrolling action when scrollbars were hidden. We can remove this guard now. It should be noted that the existing behavior only affects vertical scrolling when a paging key is pressed.
> ENYO-6090: Change Scroller to support page up/down when scrollbars are hidden

- packages/moonstone/CHANGELOG.md
- packages/moonstone/VideoPlayer/FeedbackTooltip.module.less
- packages/moonstone/styles/variables.less
Moved positioning rules to `. feedbackTooltip`  from `.content` and `.thumbnail` so the elements within `.feedbackTooltip` has default non overlapping layout.
ENYO-6080
> ENYO-6080: Fix VideoPlayer feedback tooltip overlap

- packages/moonstone/CHANGELOG.md
- packages/moonstone/styles/colors-light.less
- packages/moonstone/styles/colors.less
Update `Input` disabled focus color so that it's not the same as the background color.
We could remove `@moon-input-disabled-text-color` all together, but decided to keep it for future references in case we do need to use disabled text color again.
ENYO-6128
> ENYO-6128: Fix Input disabled focus color

- packages/moonstone/CHANGELOG.md
- packages/moonstone/TooltipDecorator/Tooltip.module.less
Fix tooltip arrow gap with an updated width for `.tooltipArrow`
Fix tooltip arrow gap
> ENYO-6142: Fix tooltip arrow gap

- packages/moonstone/CHANGELOG.md
- packages/moonstone/internal/Picker/Picker.module.less
- packages/ui/ViewManager/Arranger.js
Picker currently renders all picker items visible and relies on the ViewManager arranger to position them correctly. Normally, this isn't visible but can be seen on lower powered hardware.
* Render the picker items out of the viewport by default and then move them into view.
* Add a "stay" animation to the SlideArrangers to correctly position the items on render
The "stay" animation is a no-op under typical ViewManager uses where the view was already at no …
> ENYO-6153: Fix Picker to avoid overlapping items on render

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Scrollable/ScrollButtons.js
If pressing a Channel Up or Down key on Scroll Buttons In pointer mode, VirtuaList or Scroller did not scroll and Spotlight is on the other Scroll Button if there is the Scroll Button to the direction.
For example,
1. Hover the Up Paging Control at the top of the VirtualList with focusableScrollbar prop of `true`
2. Channel Down
Expected Result: The VirtualList scrolls and Spotlight is still on the Up Paging Control
Actual Result: The VirtualList does not scroll and Spotlight is the other Scroll Button.
If it is pointer mode, then VirtualList and Scroller just scrolls. I added the condition to make a …
> PLAT-83422: Fix VirtualList to scroll via channel up and down keys on vertical paging controls in pointer mode

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Scrollable/ScrollButtons.js
- packages/sampler/stories/qa/VirtualList.js
VirtualList should not scroll via channel up or down keys on horizontal paging controls.
If scrollbar is vertical, then skip to scroll via channel up and down keys.
I added horizontal VirtualList qa-sampler to verify this issue.
PLAT-83423
> PLAT-83423: Fix VirtualList not to scroll via channel up and down keys on horizontal paging controls

- packages/moonstone/Button/Button.module.less
- packages/moonstone/CHANGELOG.md
- packages/moonstone/FormCheckboxItem/FormCheckboxItem.js
- packages/moonstone/FormCheckboxItem/FormCheckboxItem.module.less
- packages/moonstone/Input/Input.module.less
- packages/moonstone/styles/colors-light.less
- packages/moonstone/styles/colors.less
- packages/moonstone/styles/variables.less
Updated disabled focus and disabled opacity. 
Overall disabled opacity is changed from 30% to 40%.
Components that have some additional disabled focus changes:
- `Button` (disabled focus selected border color)
- `FormCheckboxItem` (disabled focus icon full opacity / content 40% opacity)
- `Input` (disabled focus ring full opacity)
-  Added some `Input` disabled focus colors for the focus ring to be full opacity and also be consistent in light skin.
- `<input>` placeholder opacity cannot be separated from`<input>` text opacity afaik.
- Fixed `FormCheckboxItem` light skin …
> PLAT-78618: Update disabled colors

- packages/moonstone/CHANGELOG.md
- packages/moonstone/MoonstoneDecorator/fontGenerator.js
- packages/sampler/src/MoonstoneEnvironment/MoonstoneEnvironment.js
- packages/sampler/stories/qa/Text.js
- packages/ui/internal/localized-fonts/localized-fonts.js
* Add support for zh-Hans font.
* Change the locale parser to handle the 4 character script code.
Hasn't been tested on TV but verified to work in Chrome with the font installed locally.
https://stackoverflow.com/questions/18902072/what-standard-do-language-codes-of-the-form-zh-hans-belong-to
> PLAT-84120: Add support for zh-Hans Font

- packages/moonstone/internal/Picker/Picker.js
When `noAnimation` is set on a Picker, items are often rendered out of the viewport caused by the changes in #2475.
Fix Picker to still set an `arranger` for `ViewManager` when `noAnimation` or `disabled` is set and rely on VM to short-circuit the animation (as it already did).
> PLAT-84242: Fix Picker item rendering when noAnimation is set

- packages/moonstone/ExpandableItem/ExpandableItem.js
- packages/moonstone/ExpandableItem/ExpandableItem.module.less
- packages/moonstone/LabeledItem/LabeledItem.module.less
There were a lot of disabled overriding caused by applying `disabled` on the container div. Removed `disabled` on that root node and removed the redundant disabled rules in `ExpandableItem`.
We don't need disabled to be applied on the container because we want to keep its opacity when spotted and we can let the child components handle disabled styling.
Also cleaned up `LabeledItem` disabled rule because moonstone disabled rules will handle it.
Not sure if `disabled` does anything else on the `ContainerDiv` of `ExpandableItem`. My guess is accessibility but that's already …
> ENYO-6169: Remove redundant disabled CSS rules

- packages/sampler/stories/default/Scroller.js
- packages/sampler/stories/default/VirtualGridList.js
- packages/sampler/stories/default/VirtualList.js
- packages/sampler/stories/qa/Scroller.js
- packages/sampler/stories/qa/VirtualGridList.js
- packages/sampler/stories/qa/VirtualList.js
Lack of knobs to test props in Scroller, VirtualList, and VirtualGridList samples
Added knobs to edit the different type of props provided in Scroller, VirtualList, and VirtualGridList components dynamically in samplers.
PLAT-83432
> PLAT-83432: Add missing knobs of Scroller, VirtualList and VirtualGridList saimples

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Input/Input.js
- packages/moonstone/Input/Input.module.less
- packages/moonstone/styles/variables.less
Vertically center the highlight node so it'll always align with input text no matter the`InputDecorator` height.
Flexbox centering is not working for TV for some reason so used translate to vertically center.
Some caveats are: the highlight won't align if `<input>` height is changed above 100%.
ENYO-6154
> ENYO-6154: Fix HeaderInput highlight positioning

- packages/sampler/stories/qa/ExpandableInput.js
- packages/sampler/stories/qa/LabeledItem.js
* LabeledItem and ExpandableInput QA samples have no displayName explicitly set and have "Pure" as its knob name.
* Adds explicit displayName like other samples
> ENYO-6181: LabeledItem and ExpandableInput QA Samples have "Pure" knob

- packages/moonstone/DayPicker/DayPicker.js
- packages/moonstone/DaySelector/DaySelectorDecorator.js
- packages/moonstone/Dropdown/Dropdown.js
- packages/ui/CHANGELOG.md
- packages/ui/Toggleable/Toggleable.js
`Toggleable` hoc was not generating `onToggle` type info
Added default value and overrode the settings in places where the default is not used.
When we apply `@omit` to decorators it seems it is not applying.
I did not look at all HOCs exhaustively.  There are certainly some others.  I did touch up `Changeable` at the same time.
Fixes #2510
> ENYO-6195: Fix typescript generation for some HoCs

- packages/i18n/CHANGELOG.md
- packages/i18n/Text/Text.js
- packages/i18n/docs/index.md
Some uses of `Text`/`TextDecorator` were causing errors
Corrected some parts of `TextDecorator` to work correctly with bare strings and to correctly recognize when a translation is not yet available.  Also, updated the documentation to better describe how to add `strings.json` since I could not find a reference on the ilib docs for this.
ENYO-6182
> ENYO-6186: Fix Text to determine when translations are available when async

- packages/moonstone/CHANGELOG.md
- packages/moonstone/EditableIntegerPicker/EditableIntegerPicker.js
- packages/moonstone/EditableIntegerPicker/EditableIntegerPickerDecorator.js
When editing `EditableIntegerPicker` an invalid value would cause the value in the picker to disappear
Regression from #2475 .  The input was reusing the `key` of the current value, so restoring the current value would not cause the old value to animate back in.  Solution: Use a different key for the edit mode.
ENYO-6186
> ENYO-6186: Fix EditableIntegerPicker to display value after editing

- packages/sampler/stories/default/CheckboxItem.js
- packages/sampler/stories/default/FormCheckboxItem.js
- packages/sampler/stories/default/Layout.js
- packages/sampler/stories/default/RadioItem.js
- packages/sampler/stories/default/SelectableItem.js
- packages/sampler/stories/default/SwitchItem.js
Console error from passing removed `small` prop
Remove `small` prop (replaced by `size="small", but `"small"` is the default now).
ENYO-6187
> ENYO-6187: Remove remaining small prop references

- packages/moonstone/CHANGELOG.md
- packages/moonstone/styles/internal/fonts.less
- packages/ui/CHANGELOG.md
- packages/ui/styles/mixins.less
Chinese fonts don't apply consistently.
The font generation mixins now, by default, assign the `font-weight: normal` rule, which motivates the browser to choose the correct font at the correct time. For Chinese specifically, each of the target weights had to be specified due to that font also including Latin characters, instead of just Chinese characters, like the other fonts. The primary mixins for generating rules are now significantly more robust, with advanced argument handling, in a hopefully easy to understand and read way. Font weight ranges and font stretching is now supported by the mixins which were added to support this change as well as LESS debugging tools which are intentionally included but comment out since they aren't necessary for code to function, but will be valuable …
> ENYO-6176: Implement a more complete font definition system

- packages/sampler/stories/qa/Scroller.js
It has been often needed to test `keydown`, `scrollstart`, and `scrollstop` events in Scroller and VirtualList. Nevertheless, all those events as actions are not supported in Scroller stories yet.
Add actions for `keydown`, `scrollstart`, and `scrollstop` events in Scroller stories.
PLAT-84362
`onKeyDown` is private property. So, it is not included in default samples.
VirtualList samples have included those three events as actions.
> PLAT-84362: Add additional actions in Scroller samples

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Slider/Slider.module.less
`Slider` and `IncrementSlider` fill color is incorrect when `noFill` is set and focused due to insufficient specificity of the subsequent CSS rules.
Add a ruleset for noFill + spottable which matches the specificity (5) of the focus rules earlier in the stylesheet.
> ENYO-6216: Fix Slider noFill style when focused

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Scrollable/Scrollable.js
- packages/moonstone/Scrollable/ScrollableNative.js
- packages/moonstone/Scroller/Scroller.js
When using a `Scroller` that is expected to be scrolled vertically and horizontally - using `direction="both"`, the `Scroller` cannot scroll horizontally when navigating contents via 5way left/right.
The issue stems from how `Scroller` is checking its `direction` prop and calculating the next scroll position because of it. It's only accounting for the values of `'vertical'` and/or `'horizontal'`. If `'both'` is used instead, it defaults to the behavior of `'vertical'`.
Check for all valid values of `direction` and calculate the next scroll position accordingly.
> ENYO-6165: Fix horizontal scroll behavior in Scroller

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Dropdown/Dropdown.js
- packages/moonstone/Dropdown/DropdownList.js
- packages/sampler/stories/default/Dropdown.js
Render performance of `Dropdown` is poor when using many options.
Adopt `VirtualList` within `Dropdown` instead of `Group` + `Scroller` to reduce the render load.
* Because `VirtualList` requires `itemSize` to lay out the list, I had to hard code the height of `Item` and include `skinVariants` from `Skinnable` to scale for large text mode.
* Dropdown.js was getting long so I refactored the list component into a new file and converted the previous list component into …
> PLAT-84674: Fix Dropdown performance with long lists

- packages/ui/CHANGELOG.md
- packages/ui/Scrollable/Scrollable.module.less
- packages/ui/Scroller/Scroller.js
- packages/ui/Scroller/Scroller.module.less
- packages/ui/VirtualList/VirtualList.module.less
- packages/ui/VirtualList/VirtualListBase.js
`ui/VirtualList` and `ui/VirtualGridList` have `will-change: transform` CSS property which is added mainly for scroller in #1857, and the CSS property was applied to an unintended node in lists due to the difference of node structure between lists and scrollers.
This PR moves `will-change` CSS property to the proper node in `ui/VirtualList` and `ui/VirtualGridList`.
PLAT-85170
> PLAT-85170: Apply `will-change` CSS property to the proper node in lists

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Skinnable/Skinnable.js
- packages/spotlight/Accelerator/Accelerator.js
- packages/spotlight/CHANGELOG.md
- packages/spotlight/Pause/Pause.js
- packages/spotlight/SpotlightContainerDecorator/SpotlightContainerDecorator.js
- packages/spotlight/SpotlightRootDecorator/SpotlightRootDecorator.js
- packages/spotlight/Spottable/Spottable.js
- packages/spotlight/src/spotlight.js
- packages/ui/CHANGELOG.md
- packages/ui/Scroller/Scroller.js
Many typescript signatures were incomplete
Updated jsdoc comments to properly generate the TS signatures
Requires updated jsdoc-to-ts to properly generate `spotlight` (the root) default export.
ENYO-6224
ENYO-6225
> ENYO-6224: Fix docs to improve generate TypeScript definitions

- packages/webos/CHANGELOG.md
- packages/webos/LS2Request/LS2Request.js
* Previously the Enact tutorial indicated `luna://` protocol was required in the `LS2Request` service property, however inline documents said it wasn't. Realistically, `LS2Request should be able to easily prefix as needed.
* Auto-prefixes the service path with `luna://` if it (or the old `palm://` are omitted.
> PLAT-85115: LS2Request should handle omitting luna:// prefix

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Scrollable/Scrollable.js
If pressing page up when Spotlight is on the item out of viewport while holding 5-way Down, Spotlight suddenly hides. There is the following error in console.
```
Cannot read property 'closest' of null
```
When pressing page up, we cache current position. But in this case, the position is out of viewport in Scroller. When trying to restore focus with the cached position, there is no item at the position and focus could not be restored. So when caching the position, I clamped it with the Scroller viewport area.
ENYO-6241
> ENYO-6241: Fix Scroller focusing when pressing page up after holding 5-way down in Scroller

- packages/moonstone/Button/Button.js
- packages/moonstone/Button/Button.module.less
- packages/moonstone/CHANGELOG.md
Button text was centered when `color` was set and should be start aligned.
Add `.hasColor` class which, along with `.hasIcon`, will suppress text centering
> PLAT-85023: Fix Button text alignment when color is set

- packages/moonstone/CHANGELOG.md
- packages/moonstone/FormCheckboxItem/FormCheckboxItem.js
- packages/moonstone/FormCheckboxItem/FormCheckboxItem.module.less
When using `itemIcon` with `FormCheckboxItem`, the contents would remain full opacity when focused and disabled.
Wrap `itemIcon` with an extra node to manage its opacity in this case.
It's possible to try to append the class to the node via `React.cloneElement` but it requires dipping into the Element struct (which should be black box) and doesn't guarantee the desired behavior since the `className` prop could be ignored by whatever component was passed.
This …
> ENYO-6227: Fix FormCheckboxItem itemIcon opacity

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Notification/Notification.js
- packages/moonstone/Notification/Notification.module.less
- packages/moonstone/Popup/Popup.js
The design of Notification sets the size to be too wide when there is small content and it looks awkward.
Added a new private prop to `Popup` to set the body cell to shrink, which allows the `width: fit-content` code in `Notification` to work as expected. By default, Cells try to fill their maximum space, so this was taking precedence over and child rules and preferences.
> ENYO-6173: Fix Notification to shrink to fit its content

- packages/sampler/stories/qa/IncrementSlider.js
Using a knob to set the value makes the `IncrementSlider` "controlled" and therefore unresponsive to internal state management.
Add some additional prop tracking to allow setting from both the knob and via interaction
The knob doesn't refresh with the value change which is a bit weird but probably okay for the purposes of the QA sample. If someone disagrees, we can discuss more.
> ENYO-6152: Fix IncrementSlider qa sample

- packages/moonstone/FormCheckboxItem/FormCheckboxItem.js
- packages/moonstone/FormCheckboxItem/FormCheckboxItem.module.less
- packages/moonstone/SlotItem/SlotItem.js
- packages/moonstone/ToggleItem/ToggleItem.js
- packages/moonstone/ToggleItem/ToggleItem.module.less
- packages/ui/ToggleItem/ToggleItem.module.less
Items change size when an icon is added
Remove the margin of child icons which bump the item to be taller than intended.
Also sets the block sizing so the new span element has the correct dimensions.
> ENYO-6227: Fix FormCheckboxItem styling of `itemIcon`

- packages/i18n/README.md
- packages/moonstone/README.md
- packages/spotlight/README.md
- packages/ui/README.md
Individual package `README`s for `@enact/i18n`, `@enact/moonstone`, `@enact/spotlight`, and `@enact/ui` had incorrect or incomplete example usages.
This patch updates the example usages with complete and functional code.
ENYO-6250
> ENYO-6250: Fix samples in READMEs

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Dropdown/Dropdown.js
- packages/moonstone/Dropdown/Dropdown.module.less
Fix conflicting class name in `Dropdown`. `Dropdown`'s `width` prop and `Button`'s `size` prop share the same set of names as values: `['small', 'large']`  that led to unintended css rule override and specificity issues when applying props such as `width="tiny"` and `size="small"`.
`Dropdown` has a class name `small` that is meant to only be used by the prop `width`, but it was passed down to `Button`  through `ContextualButton`, so the rule that was meant for `width` was also applied to `Button`'s `size`. Renaming the width classes avoids unintended css overrides. …
> ENYO-6237: Fix Dropdown tiny width

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Dropdown/Dropdown.js
- packages/moonstone/Dropdown/Dropdown.module.less
- packages/moonstone/styles/variables.less
- packages/sampler/stories/default/Dropdown.js
- packages/sampler/stories/qa/Dropdown.js
Channel Edit requested proper size for using `Dropdown` component.
It support additional x-large size in a short term.
In the feature, it can support customized size with pixel value.
> ENYO-6189: Add Dropdown size value x-large

- packages/moonstone/Scrollable/Scrollable.js
- packages/moonstone/Scrollable/ScrollableNative.js
Adjusting the next point to focus by 1 px, keeping focus *inside* the `Scroller` bounds after paging.
> Scrollable - adjust next focus position after paging

- packages/moonstone/CHANGELOG.md
- packages/ui/VirtualList/VirtualListBase.js
When an item in VirtualList with different item size expands or shrinks, the part of item or the item hides.
When changing the item size, the item sticks to the top when being shrunk and sticks to the bottom when being expanded.
As mentioned in JIRA description, the requirement of the expanded or shrunk item behavior is not defined yet because there is no app using it. So I implemented the behavior reasonably.
PLAT-83223
> PLAT-83223: An item scrolls into view when the item expands or shrinks dynamically

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Dropdown/Dropdown.js
- packages/moonstone/Dropdown/DropdownList.js
- packages/moonstone/Dropdown/tests/Dropdown-specs.js
There's no `data` prop in `onSelect` handler of `Dropdown` component.
Added `data` into the `onSelect` handler.
> ENYO-6260: Fix Dropdown to include `data` prop in `onSelect` handler

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Scrollable/Scrollable.js
- packages/moonstone/Scrollable/ScrollableNative.js
We have got a new requirement to move spotlight to the last item (especially on the same column for grid lists) when a list or a scroller is expected that no more scroll by page up/down keys is possible on a given direction. This behavior will be helpful to end users to indicate whether further scrolling is possible or not.
Added logic to lists and scrollers to move spotlight to the last item on the same column when a list/scroller is about to touch the edge as a result of scroll by page toward a given direction.
[//]: …
> PLAT-85351: Fix lists and scrollers spotlight behavior after page up/down

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Dropdown/Dropdown.js
- packages/moonstone/Dropdown/DropdownList.js
- packages/moonstone/VirtualList/VirtualListBase.js
- packages/ui/CHANGELOG.md
- packages/ui/VirtualList/VirtualListBase.js
The TV should read "X of Y" when focusing on items in Dropdown component.
Expected > "Option 1 + Checked + X of Y"
Actual > "Option 1 + Checked"
- To propagate `aria-posinset` and `aria-setsize` to the Item component to include the X of Y information of the item.
- For the expected behavior above, the `role` of VirtualList must be `group`, not `list`. So I modified the `role` prop given by the Dropdown component to apply to the VirtualList.
PLAT-85398
> PLAT-85398: Fix accessibility read out of the Dropdown components.

- packages/spotlight/CHANGELOG.md
- packages/spotlight/src/container.js
- packages/spotlight/src/spotlight.js
- packages/spotlight/src/target.js
- packages/spotlight/src/tests/spotlight-specs.js
While used internally, the API for `Spotlight.focus()` did not officially support passing nodes (either spottables or containers).
Officially adding support and extending the existing logic to handle container nodes correctly.
> ENYO-6252: Add support for focusing nodes with Spotlight.focus() 

- packages/core/internal/prop-types/prop-types.js
- packages/moonstone/CHANGELOG.md
- packages/moonstone/ProgressBar/ProgressBarTooltip.js
- packages/moonstone/ProgressBar/ProgressBarTooltip.module.less
- packages/sampler/stories/default/ProgressBar.js
- packages/sampler/stories/default/Slider.js
Authors are unable to control the position of `ProgressBarTooltip` and `SliderTooltip` effectively with the current API. For example, it is not possible to force the tooltip to always display to one side.
* Add `position` prop with broader set of values to replace `side`
* Deprecate `side`
* Reordered knobs in `ProgressBar` and `Slider` stories to force the component tab to appear before the tooltip tab
* Added an internal `deprecated` prop type to simplify …
> ENYO-6200: Add position prop to ProgressBarTooltip

- packages/moonstone/CHANGELOG.md
- packages/moonstone/internal/$L/$L.js
* When we switch from `@enact/i18n/ilib` v13.2.0 to an external `ilib` v14.2.0 package, it introduced an internal iLib change in how iLib cache ResBundles. It appears that now iLib only allow 1 of each kind of file, and caches it.  So when the app loads the app's `['strings.json', 'en/strings.json', 'en/US/strings.json']` from the app's `./resources` directory, those files/contents are cached to their respective objects on `ilib.data`.
Moonstone (and agate/other themes) have their own embedded localizations. When iLib then attempts to load the ResBundle strings from `./node_modules/@enact/moonstone/resources`, it's seeing the `'*strings.json'` files cached already in `ilib.data` and it uses that (the app's localization data) instead, to avoid what it thinks would be a repetitious XHR. As …
> ENYO-6278: Fix moontone internationalization resource loading

- packages/moonstone/Scrollable/Scrollable.js
- packages/moonstone/Scrollable/ScrollableNative.js
If pressing page down when Spotlight is on the item out of viewport while 5-way Down several times, Spotlight suddenly hides. There is the following error in console.
```
Cannot read property 'closest' of null
```
When pressing page down, then Spotlight stored the current focus point, then tried to restore focus from the point. But the point is out of viewport sometimes. So the point is clamped with the viewport.
ENYO-6272
This issue should be fixed in https://github.com/enactjs/enact/pull/2532 properly. But I forgot to update ScrollableNative part.
> ENYO-6272: Fix ScrollerNative generating console error when pressing page down after 5-way down several times in ScrollerNative

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Dropdown/Dropdown.js
Opening a `dropdownList` by clicking a button with `cursor` always invokes the 'onOpen' handler twice. This is because whenever we click on the `ContextualButton` of the `Dropdown`, it calls the 'onOpen' handler directly through the `onClick` event handler.
I added `handleOpen` handler in the `Dorpdown`. Once `click` event occurs, it forwards `onOpen` handler when current prop `open` is `false` only.
ENYO-6283
> ENYO-6283: Dropdown: calls onOpen handler twice

- packages/moonstone/Slider/SliderBehaviorDecorator.js
- packages/ui/Touchable/Touchable.js
Change in #2560 introduced a couple regressions:
* Unable to open context menu over elements using Touchable
* Slider was invoking unnecessary focus logic on platforms supporting touch events
* Move context menu logic to touch handlers rather than generalized handlers
* Change slider logic to use `platform.touchscreen` instead of `platform.touch`
> PLAT-86060: Fix touch-dependent logic

- packages/ui/Scrollable/Scrollable.js
`ui/Scrollable` did not forward drag events.
If the appropriate drag events are present (`onDrag`, `onDragStart`, `onDragEnd`), we will forward them.
- These event props are private, so I did not include a changelog. I also removed a reference to a non-existent `this.onTouchStart` class method.
> PLAT-85707: Forward drag events from Scrollable

- packages/ui/VirtualList/VirtualListBase.js
VirtualList with Different item Size could not reach the end via 5-way key or fast wheeling.
- Sometimes, a list was scrolled _backward_ during scroll down via 5-way key
- (Found after fixing the issue above) Sometimes, items at the end of a list did not display via fast wheeling
The first issue (backward scrolling) occurs due to not-yet-calculated position info of item to be rendered. A list already has all item sizes (from apps) but it doesn't calculate all item positions at the beginning to spread out computation cost at mounting. So, in some cases, position info could be not calculated yet. This is …
> ENYO-6248: Fix VirtualList with different item sizes to scroll properly

- packages/ui/Button/Button.js
- packages/ui/CHANGELOG.md
There is the following warning when using ui/Button with not `children` but `icon` prop.
```
Warning: Failed prop type: The prop `children` is marked as required in `ui:Button`, but its value is `undefined`.
```
ui/Button could conceivably be used with `children` or `icon` with the right CSS, so, we'll just make it all optional.
ENYO-6125
> ENYO-6125: ui/Button to not require `children`

- packages/ui/CHANGELOG.md
- packages/ui/VirtualList/VirtualListBase.js
When wheeling over a VirtualList, the VirtualList scrolls smoothly.
Due to the patch for ENYO-6230, VirtualList rendered again whenever the list scroll position updated. So I reverted the patch and create a new patch for ENYO-6230.
If firstIndex state is not updated, setState() in didScroll() is usually not called as before except the case when setState() is called in other functions so that the state could be always overriden when an app wants to scroll.
ENYO-6285
> ENYO-6285: VirtualList scrolls speedfully when wheeling

- packages/ui/CHANGELOG.md
- packages/ui/Scrollable/Scrollable.js
- packages/ui/Scrollable/ScrollableNative.js
- packages/ui/Touchable/Flick.js
`ui/Scroller` does not properly scroll with inertia after flick events are fired.
By default, `Touchable` configures a `maxDuration` time value where after `x` amount of time after a drag has begun, then the drag stops being tracked. At that point, flick events do not provide flick target data. In the case of `Scroller`, this means we're unable to scroll after flick events have occurred when a drag has continued for over `250ms` (the default config value). We need to continually track a drag, so I've configured a `null` value for `Scroller`'s `maxDuration` config and added some validation in `Touchable` to not cancel tracking unless a value is provided.
> PLAT-85817: Remove maxDuration from Scroller flick config

- packages/sampler/stories/qa/VirtualList.js
There is no sampler for VirtualList with with small `minSize` and large `size` props.
Created a new QA sampler with minSize of 1 and size of 200 props in VirtualList.
ENYO-6280
> ENYO-6280: Add QA Sampler for VirtualList with with small minSize and large size

- packages/core/CHANGELOG.md
- packages/core/handle/handle.js
The `oneOf` method did not have typing information for the handlers record type.
See sample in attached Jira or use the sample in the docs for `oneOf`
Add a new typedef for the `oneOf` function's parameters.
Also, added documentation for the various typedefs.
Needs updated jsdoc to typescript PR (in same ticket) and enactjs/docs#124 for best results
PLAT-86339
> PLAT-86339: Fix docs for core/handle.oneOf

- packages/moonstone/Button/Button.js
- packages/moonstone/CHANGELOG.md
- packages/moonstone/IconButton/IconButton.module.less
- packages/moonstone/styles/variables.less
Height of the color bar should be 9px for both small and large buttons.
* Added `client` class to `publicClassNames` in order to override it in `IconButton` which has different requirements for the size of the color bar.
* Added/updated LESS variables for the sizes
I included `client` in our "not for public consumption" note since we've avoided exposing it in the past. I feel like we've expanded the list enough that we're nearing the point where exposing everything …
> PLAT-86483: Fix Button color bar height

- packages/sampler/src/manager-styles.js
* The current Storybook update notification hide fix only appears to work on base-level hosting, like `npm run serve`, however we often host on subdirectories which factor into the CSS selector.
* Adjust the fix to support public path prefixes by changing CSS selector from `href=` to `href$=`
Signed-off-by: Jason Robitaille <jason.robitaille@lge.com>
> PLAT-86565: Hide Storybook Notification with non-root URLs

- packages/moonstone/Scrollable/Scrollable.js
- packages/moonstone/Scrollable/ScrollableNative.js
- packages/sampler/stories/qa/VirtualList.js
- packages/ui/Scrollable/ScrollableNative.js
After applying `overscrollEffectOn` prop with `{pageKey: true}` property in VirtualList, overscroll effect did not show via page keys on scroll bar.
- Scrollable did not cover that edge case. So I moved the following code out of the this.isContent(target) condition.
```
if (overscrollEffectOn.pageKey) {
this.checkAndApplyOverscrollEffectByDirection(direction);
}
```
- In addition, I added VirtualList sampler to verify this issue.
- For `ScrollableNative`, `onKeyDown` should be handled in not `VirtualListBase` but `ui/ScrollableNative` to capture the `onKeyDown` event on scroll bar.
- `overscrollEffectOn` …
> ENYO-6143: Apply overscroll effect via page keys on VirtualList scrollbar

- packages/moonstone/Input/Input.js
`moonstone/Input` is missing a description for the `inputHighlight` class that can be overridden via the `css` prop.
Added inline doc for `inputHighlight` class to let developers know of its existence.  This should be zero-impact :D
ENYO-6292
> ENYO-6292: Moonstone Input missing inline doc for `inputHighlight` css prop

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Slider/SliderBehaviorDecorator.js
There's no tooltip when changed disabled state.
So, if Slider retains spotlight while changing value and disabled state, tooltip doesn't show even if value is changed.
Currently, `SliderBehaviorDecorator` doesn't change focus state if that's disabled.
I removed condition that checking disabled state to show tooltip when disabled.
Because I thought users may want to know value via tooltip once they focus on knob when Slider is disabled.
ENYO-6296
> ENYO-6296: Fix Slider to display tooltip when disabled

- packages/moonstone/CHANGELOG.md
- packages/moonstone/TooltipDecorator/TooltipDecorator.js
Tooltip over a disabled component was hidden when changing from pointer mode to 5-way key mode.
Tooltip should be hidden before because a disabled component could not get focus and Spotlight would be on another component when changing to 5-way key mode. But now, the disabled component could get focus. So I removed the logic to hide the tooltip.
ENYO-6298
> ENYO-6298: Fix TooltipDecorator to retain visibility when to 5-way mode

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Scrollable/Scrollable.js
- packages/moonstone/Scrollable/ScrollableNative.js
- packages/ui/Scrollable/Scrollable.js
- packages/ui/Scrollable/ScrollableNative.js
If clicking on a paging control several times, the Scroller including the paging control did not scroll smoothly.
Historically to stop scrolling when pressing a mouse down on items while flicking, stop() in Scrollable was called in https://github.com/enactjs/enact/pull/1502.
But the DOM element having that mouse down event handler was changed from the container having items to the container having not only items but also paging controls in https://github.com/enactjs/enact/pull/2468.
Then whenever clicking on the paging controls, the stop() was called and the Scroller did not scroll smoothly.
So if clicking …
> ENYO-6299: Call stop() when clicking not on but out of paging controls

- packages/moonstone/CHANGELOG.md
- packages/moonstone/styles/colors-highcontrast.less
- packages/moonstone/styles/colors-light-highcontrast.less
- packages/moonstone/styles/colors-light.less
Update `FormCheckbox` and `RadioItem` high contrast colors.
Tested on TV with light and dark skins high contrast along with `ProgressBar`, which seems to match the specs as-is.
> ENYO-6124: Update FormCheckbox and RadioItem high contrast colors

- packages/ui/CHANGELOG.md
- packages/ui/FloatingLayer/FloatingLayer.js
`ui/FloatingLayer` does not attach a click handler when it is mounted while opened. This results in not being able to dismiss the component via clicks.
Attach the click handler during `componentDidMount` when appropriate.
> ENYO-6309: Properly attach click handler to FloatingLayer

- packages/moonstone/Input/pointer.js
The pointer handling for `moonstone/Input` removes the wrong handler function when releasing the pointer.  This could be a potential cause of memory leaks.
This patch makes sure the correct handlers are removed when the pointer is released.
ENYO-6311
> ENYO-6311: Fix moonstone/Input to remove correct event handler

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Input/InputSpotlightDecorator.js
Guard focus against paused Spotlight outside of `InputSpotlightDecorator`.
ENYO-6308
> ENYO-6308: Prevent Input focus when Spotlight is paused

- packages/moonstone/VideoPlayer/Feedback.module.less
- packages/moonstone/VideoPlayer/FeedbackIcon.js
- packages/moonstone/styles/variables.less
Before moonstone.ttf is changed recently, 
font size of PLAY, PAUSE dingbat was larger than the others.
After moonstone.ttf is changed, All fonts have been changed to the same size.
Therefore, font-size needs to be adjusted.
As a result of asking GUI member's review, I received  result that 2em is appropriate.
[ENYO-6314]
> ENYO-6314: Fix feedback icon to change to same font size

- docs/migration/enact/migrating-to-enact-3.md
- packages/i18n/CHANGELOG.md
- packages/i18n/package.json
- packages/i18n/src/Loader.js
- packages/moonstone/CHANGELOG.md
- packages/moonstone/internal/$L/$L.js
- packages/moonstone/package.json
- packages/sampler/CHANGELOG.md
- packages/sampler/package.json
* iLib 14.4.0 introduces new handling to ResBundle pathing in its cache. Specifically, added support for `basePath` ResBundle parameter as well as passing a root path argument in the Loader functions.
* Adds support for new iLib format, while still providing backward support for older copies of iLib temporarily.
> PLAT-87182: Update Enact to use updated ResBundle basepath format

- packages/ui/CHANGELOG.md
- packages/ui/Marquee/MarqueeDecorator.js
Focusing a disabled marquee element does not start marquee
Remove the `!disabled` check in `MarqueeDecorator`
This matches `MarqueeController` which already allowed marqueeing when it was disabled. This regression is a hold over from the change to allow focusing disabled elements.
> ENYO-6316: Fix Marquee to start on focus when disabled

- packages/moonstone/CHANGELOG.md
- packages/moonstone/EditableIntegerPicker/EditableIntegerPicker.js
TV does not read out strings of `unit` prop after `value` string
Set the string of `unit` prop to aria-valuetext of EditableIntegerPicker
PLAT-84350
> PLAT-84350: Fix EditableIntegerPicker to include the `unit` in the ARIA read out

- packages/moonstone/VideoPlayer/VideoPlayer.module.less
There is horizontal alignment issue between title and playing time.
The title has `bottom: -5px`.
I think that It is intended to be horizontally aligned with the baseline of the font.
But there is a problem in non latin languages.
title has bottom: 5px in non latin languages
[ENYO-6318]
> ENYO-6318: Fix mediaTitle to adjust horizontal alignment

- packages/moonstone/CHANGELOG.md
- packages/ui/VirtualList/VirtualListBase.js
When 5-way key input invokes scrolling by crossing the edge of horizontal lists, a list scrolls too far so the focused item is located on the other edge.
Fixed lists to cache a right value for the scroll position in RTL cases.
PLAT-88301
> PLAT-88301: Fix scrolling by 5-way key of horizontal lists in RTL locales

- packages/ui/Marquee/MarqueeDecorator.js
Text shakes before the restart animation with odd `width`
`spacing` can be calculated with a decimal point.
This causes `transition` using the decimal point value.
Fix to round `spacing` downward to its nearest integer using `Math.floor`
ENYO-6334
> ENYO-6334: Fix to round spacing downward to its nearest integer

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Panels/Header.js
For models without the Magic Motion remote control, there is no way to start marquee animation if marqueeOn is 'hover'
I contacted the app developers and found that the hover is not required.
So the app developers need to change the 'hover' to 'render'.
I think it's also a way to change default value in the framework so that all apps are applied in batches.
ENYO-6338
> ENYO-6338: Change default value of marqueeOn for Header

- packages/ui/CHANGELOG.md
- packages/ui/Marquee/MarqueeDecorator.js
When changing the content of a Marquee when it had been promoted, the text would not be truncated with an ellipsis.
The logic was close before in that we called `cancelAnimation()` when the content changed which would start the demote job. However, in cases where we immediately restart marquee on update (render, hover when hovered, focus when focused) the demote job is stopped by the promote job so `promoted` was never reset.
The proposed fix resets `promoted` to `false` when invalidating metrics to ensure it's in the correct state. It will then be re-promoted later just before the animation starts as …
> ENYO-6325: Fix Marquee to show ellipsis when content changes

- packages/ui/CHANGELOG.md
- packages/ui/Marquee/Marquee.module.less
- packages/ui/Marquee/MarqueeBase.js
- packages/ui/Marquee/MarqueeDecorator.js
If the length of the content of marquee is a sub-pixel value, the duplicate content doesn't line up correctly when the animation completes causing the text to "jump" when the animation restarts.
* Add an `IntersectionObserver` to calculate the difference and adjust the spacer to account for it
* Change the reset behavior to immediately re-render the original text to further mask any offsets in text alignment.
> ENYO-6334: Fix Marquee text alignment on restart

- packages/ui/CHANGELOG.md
- packages/ui/Routable/Link.js
`Linkable` doesn't support adding your own event handler, as it's clobbered by Linkable's own event handler.
Consumer-provided events are now _also_ fired, as expected, like in the rest of the framework.
> PLAT-86868: Fixed Routable.Linkable to properly support event forwarding

- packages/moonstone/CHANGELOG.md
- packages/moonstone/styles/mixins.less
I found this problem while testing translated text.
Notification popup use line-height of BodyText, not Popup's.
Thus, the line-height is calculated as `px` (rem). I think it should be changed in 'em' units.
When I changed the locale to a non-Latin language, the line-height did not change in 'em' units.
I fixed CSS `line-height` to use `em` unit for non-Latin locales.
ENYO-6347
> ENYO-6347: Sinhala text overlaps in Notification popup

- packages/sampler/stories/qa/Marquee.js
> ENYO-6343: add a sample to qa-sampler to test allipsis in marquee when content changes 

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Notification/Notification.js
- packages/moonstone/styles/variables.less
If Notification currently has more than three buttons, it adds wide CSS.
But currently it has two long buttons but the buttons overflow.
We need to improve the root cause and consider whether or not to add wide CSS when it has a three buttons.
I fixed `max-width` of Notification by `max-width` of Button and changed to add `wide` css if length of the buttons is greater than two.
ENYO-6348
> ENYO-6348: Fix Notification to show all buttons on one line

- packages/moonstone/CHANGELOG.md
- packages/moonstone/styles/variables.less
3 max-width buttons don't fit in a wide `Notification`.
The width of `Notification`is now based on the size of 3 max-width buttons. (It's wider now.)
> ENYO-6352: Fix Notification to support 3 full-width buttons in one line

- packages/ui/CHANGELOG.md
- packages/ui/Marquee/MarqueeBase.js
- packages/ui/Marquee/tests/Marquee-specs.js
A marqueeing item that needed to read again would read the contents twice
Set an `aria-label` if one was not supplied, the contents (`children`) is plain text and the marquee will animate
If the marquee does not contain 'plain' children, the readout could be  unexpected. Developers can override by setting `aria-label` directly in these cases.
PLAT-94352
> PLAT-94532: Prevent double read of marqueeing text

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Panels/Header.js
- packages/moonstone/Panels/Header.module.less
- packages/sampler/stories/default/Header.js
Add `minimized` prop to hide the title, only showing the header components, subtitles, and title below.
Using `Transition` to animate and then resize the title cell.
> PLAT-90766: Add support for minimized Header

- packages/moonstone/CHANGELOG.md
- packages/ui/CHANGELOG.md
- packages/ui/VirtualList/VirtualListBase.js
There is a bug to access a member property of `undefined` if `VirtualList` has no item when `itemSizes` prop is given. This PR adds conditions to avoid invalid access.
Even if there is no item inside a list, a hidden placeholder item for spotlight management gets focus and a list try to get/calculate the position of the item has index 0. This makes access to an invalid `undefined` object.
Also, a new potential risk is found in a case that `itemSIzes` does not have sizing info for a target index.
Added conditions to avoid invalid access.
[//]: # (Are there any …
> PLAT-86361: Fix VirtualList with different item sizes to render properly when dataSize is 0

- packages/ui/CHANGELOG.md
- packages/ui/Marquee/MarqueeBase.js
- packages/ui/Marquee/tests/Marquee-specs.js
If `children` changes to `null` during an animation an exception is thrown.
Because we must render `children` before we can measure, there can be a window when `Marquee` thinks it should animate but there are no children to render.  Additionally, `React.Children.map()` returns `undefined` or `null` instead of an empty array when passed `undefined` or `null` we must prevent chaining from the return in those cases.
[//]: # (Were any side-effects caused by the …
> Fix Marquee to not throw for null children

- packages/moonstone/Scrollable/Scrollable.js
- packages/moonstone/Scrollable/ScrollableNative.js
- packages/moonstone/Scroller/Scroller.js
- packages/moonstone/VirtualList/VirtualListBase.js
We want to migrate HoC and render props to hooks for all VirtualList and Scroller.
As the first step, I converted 4 moonstone scroller components defined by class to functional component.
4 moonstone scroller components have been converted to functional component.
* Target component
Moonstone/VirtualListBase
Moonstone/Scrollable
Moonstone/ScollableNative
Moonstone/Scroller
1) Change `class NameOfComponent extends Component` to `const NameOfComponent => (props){`
2) Change `defaultProp`, `propTypes` to `NameOfComponent.defaultProp`,  `NameOfComponent.propTypes`. 
3) Remove the constructor
4) Remove the …
> PLAT-98201: [VirtualList and Scroller] Convert from Moonstone React component to functional component

- packages/moonstone/CHANGELOG.md
- packages/moonstone/Input/InputSpotlightDecorator.js
1) One of `moonstone/Input` requirements is that users should not be able to click on other components while focusing on an input field. It caused confusing user interaction on touchable devices by a user have to tap twice to click any components.
By adding `unlockedPointer` config to InputSpotlightDecorator, we provide an optional way to avoid a pointer locked which block click and tap actions when the input has focus.
We set the default value of `unlockedPointer` …
> PLAT-87249: Add noLockPointer config to InputSpotlightDecorator

- packages/moonstone/Scrollable/Scrollable.js
- packages/moonstone/Scrollable/ScrollableNative.js
- packages/moonstone/Scroller/Scroller.js
- packages/moonstone/VirtualList/VirtualListBase.js
Resolve a problem about component method accessing using ref.
This problem cause by PLAT-98201.
We have converted 4 moonstone React components to functional component on PLAT-98201.
But there was many dependency on class instance. 
(ex, Scrollable call shouldPreventScrollByFocus() in  virtualListBase class using childRef.current.shouldPreventScrollByFocus())
It cause many console error, and some operations did not work.
I  used `useImperativeHandle` to access to functional component method on Moonstone functional component.
1. Use `useImperativeHandle`
2. Solve binding problem on `Scrollable`. 
3. Avoid a …
> PLAT-98204: Resolve dependency problem between Moonstone Scroller React components

- packages/moonstone/CHANGELOG.md
- packages/moonstone/VirtualList/VirtualListBase.js
If an app setup an _empty_ item size array for a list, a script error occurs due to unguarded access to internal position info that is based on the item size from the app.
Refined related logic to access position info safely;
- Changed to access position info through guarded getter function
- Merged logics for different sized items and single sized items into a unified logic
This fix just to avoid script errors during 5-way key inputs and does not mean that the …
> PLAT-95353:  Avoid unsafe access to unprovided position info

- packages/ui/Button/Button.js
- packages/ui/CHANGELOG.md
Customization the `iconComponent` of `ui/Button` don't behave as expected.
Example error:
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```
When using the `iconComponent` prop of `ui/Button`, the expectation is that it behaves the same way (supports the same features and capabilities) as other overridable components. `ui/Button` used a legacy approach to supporting custom component overrides and this proved to be problematic for customization.
The new code not only updates the approach to the modern Enact standard (`ComponentOverride`) but also now supports simpler usage of HTML elements, as now, you're no longer required to prune out unsupported non-HTML-safe props off your component.
> ENYO-6364: Upgraded ui/Button to leverage ComponentOverride for iconComponent

- packages/moonstone/Scrollable/ScrollThumb.js
- packages/moonstone/Scrollable/Scrollbar.js
Convert scrollbar and scroll thumb components into functional components
PLAT-98572
#2677 (for ui)
This PR is for moonstone components only and will be applied to the new repo along with the target branch later.
> PLAT-98572: Converted moonstone scrollbar components into function components

- packages/ui/Scrollable/ScrollThumb.js
- packages/ui/Scrollable/Scrollbar.js
Convert scrollbar and scroll thumb components into functional components
PLAT-98572
#2676 (for moonstone)
This PR is for ui components only
> PLAT-98572: Converted ui scrollbar components into function components

- packages/ui/Scrollable/Scrollable.js
- packages/ui/Scrollable/ScrollableNative.js
- packages/ui/Scroller/Scroller.js
- packages/ui/VirtualList/VirtualListBase.js
We want to migrate HoC and render props to hooks for all VirtualList and Scroller.
As the first step, I converted 4 UI scroller components defined by class to functional component.
And then, resolved a problem about component method accessing using ref.
4 UI scroller components have been converted to functional component.
* Target component
UI/VirtualListBase
UI/Scrollable
UI/ScollableNative
UI/Scroller
1) Change `class NameOfComponent extends Component` to `const NameOfComponent => (props){`
2) Change `defaultProp`, `propTypes` to `NameOfComponent.defaultProp`,  `NameOfComponent.propTypes`. 
3) Remove the …
> PLAT-98506: [VirtualList and Scroller] Convert from UI React component to functional component

- packages/ui/Scrollable/Scrollable.js
- packages/ui/VirtualList/VirtualListBase.js
When scrolling to the boundaries of the Scroller, the Scroller vibrates and it seems that the Scroller keeps scrolling.
Even though the type of the Scroller was 'JS', the Scroller received the 'onScroll' event and tried to scroll again like having the 'Native' type. So the Scroller is fixed not to receive the 'onScroll' event like before.
It's the side effect while unifying ui/Scrollable.js and ui/ScrollableNative.js into one custom hook.
Clean up some code related …
> PLAT-100231: Fix not to receive `onScroll` event if type is equal to `JS` in Scroller

- packages/ui/Scrollable/Scrollable.js
Event listeners for `Scroller` and `VirtualList` are added repeatedly on render cycles.
Fixed remove previous handlers when new handlers need to be added again.
PLAT-100369
> PLAT-100369: Fix event listeners to be added once

- packages/ui/VirtualList/VirtualList.module.less
- packages/ui/VirtualList/VirtualListBase.js
There were no default item size for horizontal VirtualList.
To support default item sizes for each direction, added `vertical` and `horizontal` classes to both JS and native list.
To specify css attributes only for native list, added `native` class.
Moved out `vertical` and `horizontal` classes of `virtualList`.
PLAT-98240
> PLAT-98240: Support to specify the item size of VirtualList

- packages/ui/Scrollable/Scrollable.js
The thumb does not hide after scrolling in VirtualList and scroller native type.
While migration with hooks, we made to create `scrollStopJob` once, while `scrollStopOnScroll` which is the actual "job" for `scrollStopJob` can be created multiple times.
So when `scrollStopJob` started, it started with "old" `scrollStopJob` that holds faulty `isVerticalScrollbarVisible` state.
To `scrollStopOnScroll` have the right state, I made to create `scrollStopJob` multiple times just like `scrollStopOnScroll` did.
[//]: # (Were …
> PLAT-100498 Fix thumb does not hide after scrolling in VL, Scroller native

- packages/ui/Skinnable/Skinnable.js
- packages/ui/VirtualList/VirtualListBase.js
There are the following JSDoc parse errors.
```
Invalid reference: ui/VirtualList.VirtualListBase:
type: extends - VirtualList in packages/ui/VirtualList/VirtualList.js:29
type: extends - VirtualGridList in packages/ui/VirtualList/VirtualList.js:137
Invalid link: moonstone/Skinnable:
Used in: ui/Skinnable
```
- Assign VirtualListBase displayName properly
- Remove moonstone theme component link.
PLAT-100708
> PLAT-100708: Fix JSDoc parse errors

- packages/ui/VirtualList/VirtualList.module.less
- packages/ui/VirtualList/VirtualListBasic.js
Items' layout is broken after structural changes of `VirtualList` so items on right bottom edges are not rendered fit into a content area of a list.
Updated internal calculation logic to handle items' position and size correctly.
PLAT-100713
> PLAT-100713: Fix item layout and an item being scrolled into view properly

- packages/ui/VirtualList/VirtualList.module.less
- packages/ui/VirtualList/VirtualListBasic.js
Reverts enactjs/enact#2708
We've encountered unwanted unit-test fail in sandstone/DropDown. So We want to rever this change for now.
> Revert "PLAT-100713: Fix item layout and an item being scrolled into view properly"

- packages/ui/VirtualList/tests/VirtualList-specs.js
Some voice control related features are added in PLAT-97909
This PR is unit test of newly added props.
N/A
N/A
ENYO-6421
Enact-DCO-1.0-Signed-off-by: Changgi Lee changgi.lee@lge.com
> Add unit test for data-webos-voice-disabled prop

- packages/ui/CHANGELOG.md
- packages/ui/VirtualList/VirtualListBasic.js
I've renamed `childProps` to `itemProps` from https://github.com/enactjs/enact/pull/2685.
I didn't realize there was a discussion on the prop name before in https://github.com/enactjs/enact/pull/2004#discussion_r230107198.
So I want to revert the change.
Revert renaming `childProps` to `itemProps` in VirtualList
PLAT-102033
> PLAT-102033: Revert renaming `childProps` to `itemProps` in VirtualList

- packages/ui/useScroll/useScroll.js
There was a change renaming `itemProps` to `childProps`, but not in https://github.com/enactjs/enact/pull/2711.
Fixed wrong name
PLAT-99533
> PLAT-99533: fix itemProps to childProps

- packages/sampler/stories/default/VirtualGridList.js
- packages/sampler/stories/default/VirtualList.js
According to the theme libraries, the styles of the VirtualList and the Scroller updates.
If we don't need to align with the theme sampler's UX/GUI, this PR could be discarded.
PLAT-101531
> PLAT-101531: Update VirtualList and Scroller styles in default samplers

- packages/core/util/util.js
When using CSS overrides with CSS modules in unit tests, the reflection proxy plugin is subverted by merging that object into a new one.
Add a test-only proxy that emulates the same behavior with support for merged class names.
> PLAT-101903: Add proxy support into mergeClassNames

- packages/ui/Scroller/ScrollerBasic.js
If there is paddings in the scroll area, the content couldn't be scrolled into a view properly. To fix it, it is needed to calculate the content size first.
The `getContentSize ` is provided to calculate the content size.
I'll add a change log after the first review.
ENYO-6427
> ENYO-6427: Scroller: calculate the content size properly with padding

- CHANGELOG.md
- packages/ui/CHANGELOG.md
- packages/ui/styles/mixins.less
Currently, the .position() LESS mixin only supports separated arguments.
This prevents the use of a single shorthand variable being used positioning. This leads to unnecessary variables being created, deleted, and altered any time a position design changes.
A new approach that supports the existing 1-4 arguments to the mixin, as well as a single argument list, deliverable as a single variable.
```less
.position(10px);
.position(10px, 20px);
.position(10px, 20px, 30px);
.position(10px, 20px, 30px, 40px);
```
```less
.position(10px);
.position(10px, 20px);
.position(10px, 20px, 30px);
.position(10px, 20px, 30px, 40px);
// Note no comma, like traditional shorthand
.position(10px 20px);
.position(10px 20px 30px);
.position(10px 20px 30px 40px);
```
1. Create 7 `<div>` elements
2. Add the …
> PLAT-102625: Support lists in the position mixin

- packages/ui/CHANGELOG.md
- packages/ui/useScroll/useScroll.js
When a scroller has another scroller inside, the outer scroller's thumb moves to the wrong place without scrolling of the outer scroller if the inner scroller scrolls.
Fixed `scroll` event to be caught from the inner scroller first by changing the event handler option from `capture` phase to `bubble` phase.
ENYO-6428
> ENYO-6428: Fixed the outer scroller's abnormal thumb moving on scroll inside the inner scroller

- packages/ui/useScroll/useScroll.js
We joined classNames for scrollers and lists, so we had to take care of falsy values when we deal with class names. For better and safe management, replaced related logic with `classNames` module.
ENYO-6435
> ENYO-6435: Use classNames rather than joining

- packages/ui/ComponentOverride/ComponentOverride.js
- packages/ui/ImageItem/ImageItem.js
* Adds `ComponentOverride` support for `imageComponent` so authors can provide either a built element (`<Image>`) or a component (`Image`) which will both receive the `placeholder`, `className`, and `src` props. Due to both `Cell` and `ComponentOverride` using the `component` prop, I've added a new `ImageComponent` component to redirect the `imageComponent` prop but have avoided the extra component layer by calling `ComponentOverride` directly (which it is designed to support).
* Some structural simplification of the caption block
> PLAT-101893: Add ComponentOverride support + structural updates

- packages/ui/useScroll/useScroll.js
Fixed Uncaught TypeErrorr when wheeling on ui native Scroller
Change to call getter `getContainerRef()` which referred to the wrong ref in the `onWheel`
ENYO-6430
> ENYO-6430: Fix console error when wheel on ui native Scroller

- packages/ui/Layout/Layout.js
UI in-line doc sample references Moonstone components
Replace with generic HTML elements
PLAT-101914
> PLAT-101914: Remove some moonstone references in inline docs

- packages/ui/useScroll/useScroll.js
- packages/ui/useScroll/useScroll.module.less
A scrim for a muted container of a scroller or a list does not cover scrollbars properly.
Moved related CSS to the top node of scrollable components.
This change is also required to support a muted container in other theme libs.
PLAT-99658
> PLAT-99658: Fixed to cover scrollbars also with scrim when container is muted

- README.md
- package.json
* If people `npm link` a library or `npm link-all`, then a bootstrap is required to fix the repo interlinking. This proves costly in time when done repeatedly/regularly.
* Adds 2 new `npm run <script>` entries:
* `npm run bootstrap-link` - Includes the functionality of bootstrap with npm global linking built-in.  Should be used whenever linking to global NPM userspace is desired.
* `npm run interlink` - Reconnects monorepo libraries together without the need to re-install/re-bootstrap.
> PLAT-105257: Enact repo package.json cleanup

- packages/ui/ProgressBar/ProgressBar.js
It's not possible to cleanly access the anchor point value style from a theme.
Incorporated the `progressAnchor` value into a new CSS variable, accessible to themes, for easier customization.
> PLAT-102877: Added a new CSS variable to simplify theme customization and features

- CHANGELOG.md
- packages/ui/CHANGELOG.md
- packages/ui/ViewManager/TransitionGroup.js
- packages/ui/ViewManager/ViewManager.js
- packages/ui/ViewManager/tests/ViewManager-specs.js
ViewManager fired two `onTransition` events for every transition
* Prevent firing `onTransition` for views that weren't transitioning
* Add some useful data to the event payload.
> PLAT-105314: Fix ViewManager to only fire onTransition once per transition

- packages/ui/CHANGELOG.md
- packages/ui/Spinner/Spinner.module.less
If the containing block of  `Spinner`has `padding-left` , the `Spinner` moves to the right by the size of the `padding-left`.
Because `left` is set to `padding-left` value. (for now, `left` is set to default value. not specified)
In moonstone, there is no issue because the `section` of `Panel` has no `padding-left`.
`left` is set to 0. (if rtl, right is set to 0)
ENYO-6462
> ENYO-6462: Fix spinner to align center

- packages/ui/AnnounceDecorator/AnnounceDecorator.js
- packages/ui/AnnounceDecorator/tests/useAnnounce-specs.js
- packages/ui/AnnounceDecorator/useAnnounce.js
Adopt hooks for `ui/AnnounceDecorator`
Chose to use `useCallback` rather than `useClass` in this case because it seemed like unnecessary complexity without any handlers and only one method. Thanks to @sugardave for reminding me of that earlier in the day. :)
> PLAT-102264: Convert AnnounceDecorator to use hooks

- packages/ui/Slottable/Slottable.js
- packages/ui/Slottable/tests/Slottable-specs.js
- packages/ui/Slottable/tests/useSlots-specs.js
- packages/ui/Slottable/useSlots.js
Convert `ui/Slottable` to use hooks. Not much else to say about it. :)
> PLAT-102259: Convert Slottable to use hooks

- packages/ui/Skinnable/Skinnable.js
- packages/ui/Skinnable/tests/Skinnable-specs.js
- packages/ui/Skinnable/tests/useSkins-specs.js
- packages/ui/Skinnable/useSkins.js
- packages/ui/Skinnable/util.js
Migrates Skinnable to use hooks
This is the first hook (I believe) to expose a context provider. I've gone with `provideSkins` as a member of the returned object from the hook. I like that this avoids exporting the context and doesn't require the user to assemble the provider but it's still a little awkward looking
```jsx
const skins = useSkins(config);
return skins.provideSkins(
<Component {...props} />
);
```
This model works okay with stacking multiple providers too
```
skins.provideSkins(
other.provideOther(
<Comp />
)
)
```
I've also adjusted the config parameter …
> PLAT-102257: Migrate Skinnable to hooks

- packages/ui/Slottable/Slottable.js
- packages/ui/Slottable/tests/Slottable-specs.js
The Slottable hook migration broke components that used slots along with default props. If the slot is unset and the downstream component has a defaultProps entry for that prop, the prop will be set to null and not receive the default value.
* Use `undefined` instead of `null` for placeholder value
* Adds tests for this scenario
> PLAT-106662: Fix Slottable to work with downstream defaultProps

- packages/ui/CHANGELOG.md
- packages/ui/Group/Group.js
- packages/ui/Group/GroupItem.js
- packages/ui/Group/tests/Group-specs.js
When working with a default `Changeable` component that uses `value` as the changing prop and has a `Group` of choices that it can be updated to (i.e. the group items have a `value` prop), you have to go through an interim step to adapt the `onSelect` event payload because it will have the selected item's value in the `data` key (`{data: theValue}` -> `{value: theValue}`).
See the inspiration here: enactjs/agate/pull/249
This change adds a `selectedEventProp` prop to `ui/Group` so that `onSelect` can use that key instead.  For example, `selectedEventProp: 'value'` would allow the event to be forwarded unchanged to the `onChange` handler of a `Changeable` component managing a `value` prop.
[//]: # (Does the code …
> PLAT-106519: ui/Group should allow specifying the key that contains the selected item's value when it is selected

- packages/i18n/src/glue.js
* The are a select few scenarios where we don't always want to load the iLib loader. Particularly in instances where XHR is forbidden or there are no assets to load.
* When global pre-populated iLib data is available (`global.ilibData` like with EnactBrowser), don't attach out Enact XHR Loader routine.
* When iLibPlugin has set the `ILIB_NO_ASSETS` constant, indicating this project does not include/use iLib assets, don't attach out Enact XHR Loader routine.
> ENYO-6436: Only use iLib loader when necessary.

- packages/i18n/src/glue.js
Reverts enactjs/enact#2768
This change has an unexpected side effect of causing some iLib routines to fail that otherwise work OK so long as the requests don't succeed.
> Revert "ENYO-6436: Only use iLib loader when necessary."

- packages/ui/Marquee/Marquee.module.less
- packages/ui/Marquee/MarqueeBase.js
- packages/ui/Marquee/tests/Marquee-specs.js
Each Marquee fires as many style recalculations and relayouts as it can while animating. This adds up quickly and overburdens the CPU. This amounts to ~50-60 recalculations every second, for each marquee.
It turns out that `right` and `left` CSS properties are not as optimized for recalculation as they likely should be in this case. By using `transform` instead, we get the same functionality at essentially zero CPU cost because we're not kicking-off hundreds of layout recalculations.
> PLAT-98771: Switched Marquee from position right/left to transform

- packages/ui/CHANGELOG.md
- packages/ui/Toggleable/Toggle.js
- packages/ui/Toggleable/tests/Toggleable-specs.js
- packages/ui/Toggleable/useToggle.js
`useToggle` did not update some required props (`disabled`, `onToggle`) after creation.
Update props when they change
We should watch for other to-be-implemented hooks that use `useClass()`.  The current uses seem to be OK.
PLAT-105588
> Fix Toggleable when props update

- CHANGELOG.md
- packages/core/CHANGELOG.md
- packages/core/handle/handle.js
- packages/core/handle/tests/handle-specs.js
We have often created one-off handlers to emit custom events.
Added `forwardCustom` to standardize emitting custom events to always include a `type` member along with the value returned from `adapter`.
> PLAT-107660: Add forwardCustom handler

- packages/i18n/CHANGELOG.md
- packages/i18n/I18nDecorator/useI18n.js
* Strings were not being correctly localized during localized prerendering.
* Restores locale value validation/logic from before https://github.com/enactjs/enact/pull/2727 in the old I18nDecorator so any established iLib locale value is used when needed. This restores the ability for Enact CLI to change locales for each localized render, without it getting overridden.
> PLAT-109178: Strings are not translated in prerendered HTML

- packages/ui/CHANGELOG.md
- packages/ui/useScroll/useScroll.js
Scroller and VirtualList scrolls horizontally by clicking contents in RTL locales
This issue occurs from `scrollContentHandle.current.scrollToPosition(mutableRef.current.scrollLeft + 0.1, mutableRef.current.scrollTop + 0.1);` in `stop` handler of native scrollmode.
To stop native scrolling, we added a very small number to the current scrollLeft.
But in the RTL case, we subtract the current scrollLeft from maxScrollLeft. So we get xxx.9 value from here and the value got rounded and finally, the scrollLeft added by 1.
To remedy this, we could replace the adding value 0.1 to -0.1 when RTL.
[//]: # (How should …
> ENYO-6461: Scroller: Fix horizontal scrolling by clicking in RTL locales

- packages/ui/Button/Button.js
- packages/ui/CHANGELOG.md
- packages/ui/Icon/Icon.js
* Users of `ui/Button` cannot easily flip the icon without overriding `iconComponent`.
* Add `ui/Button.iconFlip` to forward `flip` to `Icon`.
> PLAT-109159: Add Button prop iconFlip

- packages/ui/VirtualList/VirtualListBasic.js
The items disappear in VL with different item sizes.
* Cause 
The item is wrapped in another div (itemContaineRef) and the position value is already assigned by composeStyle(). applyItemPositionToDOMElement did not consider this case, and assign "translate3d" style to internal item elements. 
* Resolution
The node to which "translate3d" style is applied should be a direct descendant of VL.
Store the VL's direct descendant in the itemContainerRefs and apply "translate3d" style to it.
[//]: # (Are …
> ENYO-6470: Fix items are not rendered properly in case of various item sizes

- packages/ui/FloatingLayer/useFloatingLayer.js
`useFloatingLayer` could cause a state change during render.
Defer registering until the component is mounted.
There are other instances of registry use that seem like they could cause problems but those instances don't handle the `'register'` event which is what causes the problem.  `PlacholderControllerDecorator` does handle `register` but it doesn't update state directly and instead starts a job.
I did …
> PLAT-110785: Fix useFloatingLayer to defer update until mounted

- packages/spotlight/CHANGELOG.md
- packages/spotlight/src/target.js
When `leaveFor` for a container, failing to navigating in a direction due to that configuration should emit `onLeaveContainerFail `.
Return `null` when the earlier bail-out returning the source element occurs.
> PLAT-110783: Fix spotlight to trigger onLeaveContainerFail when leaveFor is configured

- packages/spotlight/CHANGELOG.md
- packages/spotlight/src/pointer.js
On webOS, spotlight will turn off pointer mode while the pointer is active when using the pointer to select the VKB "enter" key. This can lead to inadvertently setting focus to on-screen elements when the window gains focus while the pointer is active.
We need to handle the specific case on webOS where the "enter" keyCode is the cause of a keydown event that was triggered while the pointer is active.
> PLAT-109019: Correctly maintain pointer mode on webOS

- packages/ui/CHANGELOG.md
- packages/ui/VirtualList/VirtualListBasic.js
The items are gone when changing RTL locales.
The issue is only for scrollMode="native".
The internal scrollPosition was reset by 0 but the actual native scroller didn't scroll to 0.
Make the native scroller scroll to 0 position.
PLAT-111412
> PLAT-111412: VirtualList: Fix items are not shown when changing RTL locales

- packages/ui/CHANGELOG.md
- packages/ui/VirtualList/VirtualListBasic.js
The items are gone when changing RTL locales.
The issue is only for scrollMode="native".
The internal scrollPosition was reset by 0 but the actual native scroller didn't scroll to 0.
Make the native scroller scroll to 0 position.
PLAT-111412
> PLAT-111412: VirtualList: Items are not shown when changing RTL locales

- packages/ui/useScroll/useScroll.js
When re-render happens, scrollStopJob was stopped and created a new one.
This caused the status variable `scrolling` never set to `false` again.
`scrolling` variable is used when bailing out a scroll to the same position.
Since this variable set to the wrong value, the scroll that needs to occur didn't fire and caused problems.
Keep scrollStopJob instance instead of stopping and creating a new one on every render.
[//]: # (Were any side-effects caused by …
> PLAT-111999: VirtualList: Fix stopping scrollStopJob on every render

- packages/ui/CHANGELOG.md
- packages/ui/Scroller/ScrollerBasic.js
When client size changed from outside, Scroller couldn't recalculate its scrollBounds unless it's rerendered.
VirtualList on the other hand has `syncClientSize` function to handle this.
Add `syncClientSize` function to Scroller.
PLAT-112054
> PLAT-112054: Fix Scroller to update clientSize when it's changed

- packages/spotlight/CHANGELOG.md
- packages/spotlight/src/container.js
- packages/spotlight/src/spotlight.js
This adds a container config option `straightOnlyLeave` that prevents navigation to oblique containers when leaving the current container (as opposed to `straightOnly`, which prevents navigation to elements in an oblique position to the currently focused element).
> PLAT-110767: Add spotlight container option straightOnlyLeave

- packages/core/util/tests/util-specs.js
- packages/core/util/util.js
Some consumers of `React.Children.map` rely on the index arg of the callback to operate but `mapAndFilterChildren` did not forward it.
Forward `...rest` for safety to callback
Added unit tests!
> PLAT-111891: Fix mapAndFilterChildren to pass index to callback

- packages/i18n/I18nDecorator/I18n.js
- packages/ui/Changeable/Changeable.js
- packages/ui/Toggleable/Toggleable.js
- packages/ui/useControlledState/useControlledState.js
Several HOCs seem to be causing unnecessary re-renders by permuting props or updating state.
Avoid updating state or generating new props when not needed.
No regressions have been seen from this but if components were counting on the unnecessary re-renders, they could have problems.
PLAT-112393
> PLAT-112393: Prevent unnecessary renders

- packages/spotlight/CHANGELOG.md
- packages/spotlight/Spottable/Spottable.js
`Spottable` uses `forwardWithPrevent` to handle key events, so an outer component cannot call `stopPropagation` method. (e.g. ev.stopPropagation()) `forwardWithPrevent` is designed for a custom event, so it supports just `preventDefault` and does not provide other methods of a native event or a React synthetic event.
To make the outer component able to stop propagation, `Spottable` should not use `forwardWithPrevent` from `handle`.
Updated `Spottable` logic to use `forward` and check `defaultPrevented`
[//]: # (Were …
> PLAT-112276: Fixed to provide `stopPropagation` methods in key down hander from `Spottable`

- packages/ui/VirtualList/VirtualListBasic.js
The shadow of the last item is clipped when scroll by 'up' key from Item 0 with 'wrap' is true.
Also when `scrollMode` is 'translate', the last item's shadow is clipped with 5 way 'down' key.
The current scrollHeight is calculated with just itemSize but in sandstone, we need extra bottom margin for shadow.
Provide `getAffordance` to add extra space for the shadow
PLAT-113174
> PLAT-113174: Fix shadow of the last item is clippend when 'wrap' is true or 'scrollMode' is translate

- packages/ui/CHANGELOG.md
- packages/ui/ViewManager/TransitionGroup.js
- packages/ui/ViewManager/tests/ViewManager-specs.js
When the `stay` transition was added to `ui/ViewManager.Arranger.BasicArranger` it caused `onTransition` events to be sent even when no transition had actually occurred (i.e. on mount) for consumers using `BasicArranger`.
The fix is to modify `ui/ViewManager.TransitionGroup` to not send transition events when a view "appears" so that only `leave` and `enter` will send them.
PLAT-110252
> PLAT-110252: Sampler - WizardPanel: 'onTransition' event emit in Actions when story first loads

- CHANGELOG.md
- packages/spotlight/CHANGELOG.md
- packages/spotlight/src/container.js
- packages/spotlight/src/navigate.js
- packages/spotlight/src/spotlight.js
- packages/spotlight/src/target.js
- packages/ui/VirtualList/VirtualListBasic.js
When navigating from a container within a `straightOnlyLeave` container, the straight-only would be ignored.
Update the logic to:
* check upstream containers to find the first with `straightOnlyLeave` configured rather than only checkout the nearest container
* treat restricted containers (those with `enterTo` configured) as the "straight only" comparisons falling back to the target itself if it doesn't exist in any restricted containers
* limit the container search to those unique to the target to avoid comparing bounds of shared upstream containers
[//]: # (Are …
> PLAT-113458: Replace straightOnlyLeave with partition config option

- packages/spotlight/Spottable/Spottable.js
Moonstone 3.2.5 deconstructs `preventDefault` from the event but React's synthetic event doesn't support this (because it attempts to update `this.defaultPrevented` but fails because `preventDefault` is no longer bound to anything.
Add a proxy with a bound handler for `preventDefault` so moonstone doesn't break
We'll need to fix this in 3.2.6 of moonstone and then remove this in > 3.3.0 of enact
> PLAT-113576: Fix Spottable to be compatible with moonstone 3.2.5

- packages/ui/CHANGELOG.md
- packages/ui/useScroll/Scrollbar.js
TV requested to extend the time for showing scrollbar.
GUI confirmed the time to 1000ms instead of 400ms.
Change the time for exposing scrollbar to 1000ms from 400ms. 
PLAT-113646
> PLAT-113646: [VirtualList and Scroller] Extend the time for showing scrollbar

- packages/ui/CHANGELOG.md
- packages/ui/useScroll/Scrollbar.js
Due to changed GUI spec, Reverts enactjs/enact#2818
> Revert "PLAT-113646: [VirtualList and Scroller] Extend the time for showing scrollbar"

- packages/ui/useScroll/useScroll.js
[Enact QA Sampler] sandstone/Scroller>List of things: 'spotlightDisabled' dosen't take Spotlight on X Closing button
Spotlight Container Disabled prop does not work properly on Scroller and VirtualList
Because 'data-spotlight-container-disabled' prop is used in stop function of Scroller and VirtualList, the scrollStopJob function needs to be updated when the 'data-spotlight-container-disabled' prop is changed. 
But there was no dependency of 'data-spotlight-container-disabled' to create scrollStopJob.
This patch receives the …
> PLAT-111413: create scrollStopJob when changing spotlightContainerDisabled

- packages/spotlight/CHANGELOG.md
- packages/spotlight/Spottable/Spottable.js
`Spottable` does not update its `isHovered` state correctly in all cases
A change in https://github.com/enactjs/enact/pull/1667 added guards to ensure the pointer moved before changing the hovered state during mouse enter/leave events. This apparently was due to maintain consistency with webOS, which originally did not fire mouse enter/leave events when a background spottable element moved/transitioned past a stationary pointer. That does not appear to be the case in webOS now, so we can remove these guards.
https://github.com/enactjs/enact/pull/1667
I've run UI tests and they all pass with this change.
> PLAT-113895: Fix Spottable hovered state

- CHANGELOG.md
- packages/ui/Scroller/ScrollerBasic.js
- packages/ui/useScroll/useScroll.js
In current status, voice props only supported in VirtualList.
Fix to support voice props not only VirtualList but also Scroller.
N/A
PLAT-114532
Enact-DCO-1.0-Signed-off-by: Changgi Lee changgi.lee@lge.com
> PLAT-114532: Support voice props in Scroller

- packages/ui/CHANGELOG.md
- packages/ui/useScroll/useScroll.js
Sometimes, with a slow system, `onScrollStop` event fired redundantly when scrolling by 5 way
Removed unnecessary scrollStopJob start.
PLAT-104511
> PLAT-104511: Fixed Scroller and VirtualList to not firing `onScrollStop` event redundantly

- packages/ui/CHANGELOG.md
- packages/ui/useScroll/useScroll.js
When a Scroller or VirtualList changed its size dynamically by other elements, for example, in Panel from header height changing, it is not re-rendered so focus can be truncated.
Added `ResizeObserver` to make Scroller or VirtualList re-render when its size has been changed.
I left `resize` handler as is because it has an additional feature like scrollTo 0 position logic.
PLAT-114153
> PLAT-114153: Fix Scroller and VirtualList to re-render when its size changed

- packages/ui/CHANGELOG.md
- packages/ui/VirtualList/VirtualListBasic.js
- packages/ui/useScroll/useScroll.js
Sandstone Dropdown loses its focus when `dataSize`  of VL has changed to smaller.
The reason why Dropdown loses its focus is after calling `scrollTo` 0 index from Dropdown, VirtualList itself calls `scrollTo` to adjust its `scrollPosition` to update it with shrunk `maxPos` due to shrunk `dataSize`.
Before calling `scrollTo`, VirtualList checks current `scrollPosition` is bigger than `masPos`.
At this point, `scrollPosition` supposed to be '0' and VL shouldn't call `scrollTo` because Dropdown called `scrollTo` with `animate: false` option. However, by the nature of "native" scroller, `onScroll` event happens asynchronously and `scrollPosition` had the …
> PLAT-114518: Fix Dropdown to not lose focus when dataSize has changed

- CHANGELOG.md
- packages/ui/AnnounceDecorator/Announce.js
If the announce function is called quickly (within 500 ms), the announce function call is ignored.
- Add `clear` property for the announce function.
- Initialize the existing setTimeout.
PLAT-114699
> PLAT-114699: Add `clear` option in the ui/AnnounceDecorator.Announce.announce()

- packages/ui/CHANGELOG.md
- packages/ui/Marquee/MarqueeDecorator.js
* If the length of the text is < 1px longer than the size of the container, marquee will show an ellipsis initially and then switch to clipping
* If the marquee instance is within a scaled container, the measurements are incorrect resulting in the wrong animation behavior
Wrap the text in another DOM node for measurement so `getBoundingClientRect()` (which handles subpixel measurements and includes the effects of a transform) can be used for both the container and the content sizing.
[//]: # (Were any side-effects …
> PLAT-115093: Fix Marquee measurements for sub-pixel differences

- packages/ui/CHANGELOG.md
- packages/ui/ViewManager/Arranger.js
- packages/ui/ViewManager/View.js
- packages/ui/ViewManager/ViewManager.js
- packages/ui/ViewManager/tests/ViewManager-specs.js
Arrangers lack the data necessary to adjust their animation for locales with right-to-left reading order
Add `rtl` prop to `ViewManager` and the arranger config.
> PLAT-114531: Add rtl prop to ViewManager

- packages/ui/Marquee/MarqueeDecorator.js
I though `for / of` not be a live iterator and therefore not update when nodes were moved. It seems that it is so the method fails to move multiple children into and back out of the wrapper.
Use a `while` loop instead!
> PLAT-115093: Fix Marquee to move all nodes

- packages/i18n/package.json
* Previously only supported peer dependency of ilib `^14.4.0` (`ilib`) or `^14.4.0-webostv1` (`ilib-webos-tv`). Need to support `ilib-webos` as well (aka `#.#.#-webos#` versioning format).
* Use a general `^14.4.0 || ^14.6.0-webos` to support all webosa ilib variant version numbers. Then NPM aliases will work correctly.
> PLAT-113142: Use ilib-webos NPM package in webOS templates and framework setup

- packages/sampler/package.json
`prop-types` module is used by `sampler` but is not included in the dependencies.
Added dependency
PLAT-115947
> PLAT-115947 Add missing prop-types dependency

- packages/spotlight/src/container.js
- packages/spotlight/src/target.js
- packages/spotlight/src/tests/target-specs.js
We have cases (e.g. enyojs/sandstone#667) in which we want to imperatively focus either the last focused or default element of a container without requiring that the container always use that config for 5-way navigation.
Add a `preferredEnterTo` parameter to `getTargetByContainer` (and downstream files) to favor a particular target.
We should consider making this a new top-level `Spotlight` API (e.g. `focusContainer`) in a future release.
> PLAT-113429: Add preferredEnterTo parameter to getTargetByContainer

- packages/ui/styles/mixins.less
- packages/ui/styles/variables.less
Often, languages are given incorrect rules due to a naive categorization which states that all non-Latin languages are tall-height glyph languages. This isn't true and we need a more granular way to group these languages that need some extra height for tall glyphs vs languages that fit within the bounds of "normal" glyph metrics.
This PR adds a mechanism in LESS to apply rules to those languages specifically. This also updates the base-approach of how to access the `:global(.enact-locale-*) &` selector by adding a mixin that can target any feature of the localization classes.
The new mixins are as follows:
* `.enact-locale-line-height()` - A convenience function, since this is one of the most common cases
* `.enact-locale-tallglyph()` - A generalized function that has both shorthand and …
> PLAT-109024: Added "tallglyph" locale support

- packages/spotlight/CHANGELOG.md
- packages/spotlight/SpotlightContainerDecorator/SpotlightContainerDecorator.js
Passing `ref` to a component wrapped with `SpotlightContainerDecorator` throws an error
Wrap `SpotlightContainerDecorator` with `React.forwardRef` to restore support for the `ref` prop.
I had wanted to avoid adding `forwardRef` to all our HOCs during the hook migration but at least one regression surfaced with `SpotlightContainerDecorator` and it seemed appropriate to maintain compatibility here until we remove the HOC.
> PLAT-117036: Fix SpotlightContainerDecorator to allow use of ref

- packages/ui/styles/mixins.less
Some of the new locale mixins don't support targeting of their rules onto itself. It seemed, initially, that this complexity wasn't necessary, since the root node doesn't assign localized font rules to itself. It does, however, reference a mixin which does that very thing.
It was necessary to add support for the `@target` argument into the mixin collection to allow the argument to flow through to the appropriate destination. This rounds-out the feature set of the `.enact-locale-line-height` and `.enact-locale-tallglyph` mixins.
This is an additive change to a private LESS API.
> PLAT-117004: Improved support for mixin targeting

- packages/spotlight/src/spotlight.js
Could not restore focus when the last focused element was a container id (string)
We need to recurse into the container to find the last focused element
> PLAT-111880: Fix restoring focus when last focused is container

- packages/ui/CHANGELOG.md
- packages/ui/ViewManager/View.js
- packages/ui/ViewManager/ViewManager.js
- packages/ui/ViewManager/tests/View-specs.js
If a `View` was transitioning out and then was transitioned back before it was completely removed, the `enteringProp` was not reset.  This could cause the children to not update when the view arrived.  In `Panels`, this caused the child `Panel` to not get its `hideChildren` prop set and then cleared.  Because the view did not re-render after transitioning back, auto focus logic could not fire to focus the panel contents.
If `componentWillEnter` is called and `entering` isn't set, set it to allow for component to re-enter.
[//]: # (How should the …
> PLAT-116511 Fix a view re-entering

- packages/ui/Touchable/Flick.js
There is console error when flick Agate Picker. 
- TypeError: Cannot set property 'onFlick' of undefined
Change unintended assigned.
- It looks like regression from https://github.com/enactjs/enact/pull/2836/
- Flick.js has different structure with Drag.js and Hold.js. Flick store own config in `this` not `this.flickConfig`
PLAT-120781
> PLAT-120781: Fix console error when flick

- packages/ui/Button/Button.module.less
- packages/ui/CHANGELOG.md
- packages/ui/Touchable/Touchable.js
On touch devices, a button is pressed visually but not clicked in behavior when a user presses slightly out of a button.
Fixed with an updated condition to decide 'click' in `Touchable`.
Also fixed buttons not to have a browser-default press effect which is enabled only in a touch environment.
PLAT-115596
> PLAT-105596: Fix a touchable control to be clicked properly when pressed

- packages/ui/CHANGELOG.md
- packages/ui/Touchable/Touchable.js
After #2862 is merged, `onTab` is not fired properly on controls that do not set `activeProp` for `Touchable`.
We still need a fix for CSS to prevent browser's default style, so revert only Touchable changes from #2862.
PLAT-105596
> PLAT-105596: Revert Touchable fix for button click to avoid error on controls

- CHANGELOG.md
- packages/i18n/CHANGELOG.md
- packages/i18n/I18nDecorator/getI18nClasses.js
Although Korean is a language to which italic font styles can be applied, non-italic classes are being added.
It is deciding whether to add the `non-italic` class by checking the `scriptName`. 
We can check `Kore` to apply the italic font style to Korean.
PLAT-123726
> PLAT-123726: Heading: italic style font cut off

- packages/ui/styles/internal/utils.less
- packages/ui/styles/mixins.less
- packages/ui/styles/variables.less
All themes deserve to use the `.extract` mixin, and the `*-start-end` mixins should work with the developer instead of against.
* Migrated style-utils from Sandstone into ui
* Updated the `position-start-end`, `margin-start-end`, and `padding-start-end` mixins to support a single variable containing a list of values that can be parsed as shorthand to apply RTL-safe rules using the associated values.
This is a good addition and causes no known negative side effects. It encourages better, more readable, more maintainable coding practices.
Using `padding` as an example below, but `margin` and `position` work exactly the same way.
Here's the old usage, and the result:
```css
.padding-start-end(@start, @end);
.padding-start-end(12px, 24px);
.selector {
padding-left: 12px;
padding-right: 24px; …
```
> PLAT-118682: Refactored RTL mixins for better interoperability added extract mixin

- packages/spotlight/SpotlightRootDecorator/SpotlightRootDecorator.js
- packages/spotlight/styles/mixins.less
If touch events generates, then spottable visual effect should be shown when it is not focus but only active.
When pointerMode is `touch`, then Spotlight is on a component when it is active
PLAT-123775
> PLAT-123775: Spotlight is on a component when it is active in touch mode

- CHANGELOG.md
- packages/spotlight/SpotlightRootDecorator/SpotlightRootDecorator.js
- packages/spotlight/styles/mixins.less
When touching a component, focus effect has been gone, but focus is still on the component. So if pressing an `enter` key, the, the component receives the key and could execute something.
If pressing an `enter` key after touching, the key is ignored.
PLAT-125200
> PLAT-125200: Call stopPropagation when enter key is pressed in touch mode 

- CHANGELOG.md
- packages/spotlight/CHANGELOG.md
- packages/spotlight/SpotlightRootDecorator/SpotlightRootDecorator.js
In High Contrast mode, the font color doesn't change in a Button when tapping.
Then there are many screenshot test fails.
`enact-a11y-high-contrast` and `non-touch-mode` CSS classes are in one DOM element. But the CSS selector related with focus effect was defined as if in different DOM elements. So I wrapped the Enact root DOM element with a div element including `non-touch-mode` or `touch-mode` CSS class.
PLAT-125337
I think …
> PLAT-125337: Wrap the enact root DOM element with touch related CSS class

- packages/ui/CHANGELOG.md
- packages/ui/Media/Media.js
Issue: ui/Media `play` function does not return anything. 
Solution: Changed `play` function in ui/Media component in order to return promise.
PLAT-124525
https://github.com/enactjs/agate/tree/feature/PLAT-124525
> PLAT-124525: Media `play` function returns a Promise to see if it was rejected

- packages/ui/CHANGELOG.md
- packages/ui/useScroll/useScroll.js
A scroller/list reacts for `onFlick` event unexpectedly when outer component catches also `onFlick` for the orthogonal direction since a scroller/list was designed to scroll diagonally by flick if possible. For now, we don't have any request for diagonal scrolling, so it looks better to limit scrolling directions by flicking direction.
Updated scrolling logic to only react for flicking direction which is provided as a property of event object.
[//]: # (Related …
> PLAT-124923: Fixed Scroller and VirtualList not to scroll diagonally by flick

- packages/spotlight/CHANGELOG.md
- packages/spotlight/SpotlightRootDecorator/SpotlightRootDecorator.js
Touching `enter` key from VKB doesn't work
Revert the related code(https://github.com/enactjs/enact/pull/2866) and will revisit later
PLAT-126567
> PLAT-126567: Revert PLAT-125200

- CHANGELOG.md
- packages/spotlight/SpotlightRootDecorator/SpotlightRootDecorator.js
Image Item is checked when pressing an enter key in touch mode
Prevent default to prevent `onClick` event when pressing an enter key in touch mode
This patch preventDefault onKeyDown, it can block further `onClick` event firing.
But it does not call propergation, because key event is necessary when closing an input by enter.
Since the keyDown event is propagated as it is, the side effects of it have …
> PLAT-125200: Fix SpotlightRootDecorator to ignore `enter` key in touch mode

- packages/ui/CHANGELOG.md
- packages/ui/Scrollable/ScrollableNative.js
- packages/ui/Scroller/ScrollerBasic.js
- packages/ui/Scroller/UiScrollerBase.js
- packages/ui/VirtualList/UiVirtualListBase.js
- packages/ui/VirtualList/VirtualListBasic.js
- packages/ui/useScroll/useScroll.js
ScrollThumb in horizontalScrollbar is located abnormal position when clicking scrolltrack  with RTL.
Support new RLT scroller coordinate of Chrome 85 (https://www.chromestatus.com/feature/5759578031521792)
- Horizontal (or vertical) scroll position will be zero at its initial position and negative when scrolled leftward (or upward).
PLAT-124534
> PLAT-124534: Support new RTL scroller coordinate of Chrome 85

- packages/ui/Transition/Transition.js
A valid CSS duration value is only supported when `type` prop is `slide` or `fade`. But there is the following documentation.
```
Any valid CSS duration value is also accepted,
```
App developers could misunderstand that a valid CSS duration is used with `clip` type.
Added the condition in the documentation.
```
Any valid CSS duration value is also accepted when `type` is set to `'clip'`,
```
PLAT-128518 …
> PLAT-128518: Update ui/Transition duration prop description

- packages/spotlight/Spottable/Spottable.js
Workaround to bind `preventDefault` was added to ensure compatibility with `@enact/moonstone` 3.2.5.
Remove the workaround with the release of enactjs/moonstone#29 and 3.2.6
> PLAT-113577: Remove Spottable workaround for binding preventDefault

- packages/ui/styles/mixins.less
Newly added `.position-start-end` mixin broke the layout of `sandstone/Button` with `color` prop.
`sandstone/Button` uses `.position-start-end(-@sand-button-colordot-width, initial)` to set `left` and `right` styles to the color bar. But after the https://github.com/enactjs/enact/pull/2859/ PR, `top` and `bottom` styles were also added to the color bar and the position was broken. Because the following new mixin was called unexpectedly.
```
.position-start-end (@trbl; @target: "") when (length(@trbl) > 1) or ((iskeyword(@target)) or (@target = "")) { …
```
> PLAT-125327: Fix condition of .position-start-end mixin for backward compatibility

- CHANGELOG.md
- packages/ui/A11yDecorator/A11yDecorator.js
`ui/A11yDecorator` will be deprecated in Enact 4.0. So it is needed to warn it.
Warn ui/A11yDecorator deprercation
PLAT-130899
> PLAT-130899: Warn ui/A11yDecorator deprercation

- CHANGELOG.md
- packages/spotlight/CHANGELOG.md
- packages/spotlight/SpotlightRootDecorator/SpotlightRootDecorator.js
When press enter in touch mode, focus is not restored
Change touch state when enter key is occur in touch mode
N/A
PLAT-132612
N/A
> PLAT-132612: Fix SpotlightRootDecorator to show focus effect when enter key is pressed in touch mode

- packages/core/dispatcher/dispatcher.js
Due to React's changes of event delegation from version 17, event callback order is changed in some components which add event handlers to `document`.
An API is added to set up React DOM tree root for internal components which cannot determine which node is the right event target.
APIs to add/remove event handlers (`on` and `off`) already provide a parameter to specify the target node to attach or detach …
> PLAT-130865: Supports a custom default event dispatching target

- packages/sampler/.storybook/main.js
- packages/sampler/.storybook/manager.js
- packages/sampler/.storybook/preview.js
- packages/sampler/CHANGELOG.md
- packages/sampler/npm-shrinkwrap.json
- packages/sampler/package.json
- packages/sampler/src/Environment/Environment.js
- packages/sampler/stories/default/Group.js
- packages/sampler/stories/default/Layout.js
- packages/sampler/stories/default/Platform.js
- packages/sampler/stories/default/Routable.js
- packages/sampler/stories/default/Scroller.js
- packages/sampler/stories/default/VirtualGridList.js
- packages/sampler/stories/default/VirtualList.js
Enact-DCO-1.0-Signed-off-by: Jeongran Jang (jeongran.jang@lge.com)
`@storybook/addon-info` deprecated in storybook 6.0
`addon-docs` replaces the deprecated `addon-info`
PLAT-129635
Depends on https://github.com/enactjs/storybook-utils/pull/8
> PLAT-129635: Replace addon-info with addon-docs

- packages/spotlight/CHANGELOG.md
- packages/spotlight/SpotlightRootDecorator/SpotlightRootDecorator.js
Input type does not match when app launches on webOS
Invoke luna call for get last input type
PLAT-134190
> PLAT-134190: Apply the last Input type to show spotlight when app launches on webOS

- packages/ui/Button/Button.js
- packages/ui/CHANGELOG.md
- packages/ui/Icon/Icon.js
- packages/ui/IconButton/IconButton.js
- packages/ui/LabeledIcon/LabeledIcon.js
We've changed `size` prop values of `Button`, `Icon`, `IconButton`, and `LabeledIcon` to `String` from PLAT-105260.
We didn't change the default size value since it's API changing.
Now, we are in the alpha phase for 4.0.0, we'd like to remove default size values from them.
PLAT-107982
> PLAT-107982: Removed Button, Icon, IconButton, and LabeledIcon default size values

- docs/contributing/documentation.md
- packages/ui/CHANGELOG.md
- packages/ui/Touchable/Hold.js
- packages/ui/Touchable/Touchable.js
- packages/ui/Touchable/config.js
- packages/ui/Touchable/tests/Touchable-specs.js
Currently, `Touchable` dispatches `onHold`, `onHoldPulse`, and `onHoldEnd` events for holding down events and events' names are not matched with other regular events like `TouchStart` and `TouchEnd`.
To make the hold events to get the semantics the same, we'd like to rename `onHold` to `onHoldStart` and `onHoldPulse` to `onHold`.
Since `onHold` will have a different meaning after this change, we need to …
> PLAT-73431: Rename `onHold` and `onHoldPulse` to `onHoldStart` and `onHold` respectively

- packages/ui/CHANGELOG.md
- packages/ui/FloatingLayer/FloatingLayerContainer.js
From the theme libs, the Popup kind is not opened in some samples.
While we migrated `FloatingLayerDecorator` to use hooks, handler that uses modules from `@enact/core/handle` had some problem with binding `this`. So I replaced the related logic to not use the related modules. 
N/A
PLAT-137759
> PLAT-137759: Fix FloatingLayerDecorator to render the floating node properly

- packages/ui/CHANGELOG.md
- packages/ui/Touchable/Touchable.js
When popup is open, a touchable component underlying an open popup catches `onDrag` and `onFlick` events.
There was no target element checking in `Touchable`.
In this PR, `Touchable` checks whether `currentTarget` contains `target` or not.
PLAT-137855
> PLAT-137855: Fixed `Touchable` to handle touch related events only for valid targets

- packages/ui/CHANGELOG.md
- packages/ui/Touchable/Touchable.js
When popup is open, a touchable component underlying an open popup catches `onDrag` and `onFlick` events.
There was no target element checking in `Touchable`.
In this PR, `Touchable` checks whether `currentTarget` contains `target` or not.
PLAT-137855
> PLAT-137855: Fixed `Touchable` to handle touch-related events only for valid targets

- packages/ui/CHANGELOG.md
- packages/ui/useScroll/useScroll.js
There was console error when scrolling and close Dropdown
After the Scroller in DropDown has already been removed, the return part of useEffect is performed. So the bound value became undefined.
This is because the useEffect() is not synchronous so the scroll-related cleanup part is executed too late.
So I changed useEffect to useLayoutEffect
PLAT-136893
https://github.com/enactjs/sandstone/pull/852
Enact-DCO-1.0-Signed-off-by: …
> PLAT-136893: Fix console error when scrolling and close Dropdown

- packages/core/CHANGELOG.md
- packages/core/platform/platform.js
- packages/core/platform/tests/platform-specs.js
The list is not scrolling to right while wheeling down through MRCU.
The issue is related with https://github.com/enactjs/enact/pull/2874
To detect the chromium version in webOS, I set it into the platform variable.
```
userAgent: Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 WebAppManager
==> 
platform = {
chrome: "87"	// This was added
gesture: false
node: false
platformName: "webos"
touch: true
touchscreen: true
unknown: false 
webos: 7
}
```
[//]: # (How should the change be …
> PLAT-139332: Get Chromium version on webOS

- .travis.yml
- packages/spotlight/CHANGELOG.md
- packages/spotlight/SpotlightRootDecorator/SpotlightRootDecorator.js
Focus exist after input text with touch using VKB.
**AS-IS**: Set "key" mode unconditionally after KeyDown.
(https://github.com/enactjs/enact/pull/2892)
(https://github.com/enactjs/enact/pull/2897)
**TO-BE**:  Set key mode using lastInputType value. 
To invoke the setTouchMede function after receiving the lastInputType result, I used the setTimeout.
PLAT-139608
> PLAT-139608: SpotlightRootDecorator: Fixed setTouchMode in KeyDown to refer the lastInputType

- packages/spotlight/CHANGELOG.md
- packages/spotlight/src/spotlight.js
Spotlight exits out of `FixedPopupPanels`
`enterTo` parameter was added on `getTargetByContainer` (https://github.com/enactjs/enact/pull/2839)
I added `containerOption` parameter containing `enterTo`  on `Spotlight.focus` to passing the param to `getTargetByContainer `
PLAT-125057
> PLAT-125057: Add `containerOption` param in spotlight.focus function

- packages/spotlight/src/spotlight.js
New UX requirement to scroll a list by hover.
When a certain key input occurs during scrolling by hover, scrolling should stop and the focus needs to show on a spottable element near the last pointer position.
Implemented a new feature internally.
PLAT-126934
enactjs/sandstone/pull/947
> PLAT-126934: Support scroll by hover

- packages/sampler/.storybook/manager.js
- packages/sampler/.storybook/preview.js
- packages/sampler/src/Environment/Environment.js
The global knob setting stays even if the story changes.
Referred PR: https://github.com/enactjs/sandstone/pull/906
PLAT-142964
> PLAT-142964: Sampler: Fix global knob setting resets when component changes

- packages/ui/Routable/Link.js
- packages/ui/Routable/Routable.js
- packages/ui/Routable/Route.js
Routable docs were incomplete. Link and Linkable inside Routable docs were not documented.
The documentation for Link and Linkable is added.
Write the document for them.
The 'path' prop is not exposed explicitly in the Linkable HoC. It might need to be added with the documentation.
PLAT-142904
> PLAT-142904: Add documentation for Link and Linkable inside ui/Routable docs

- packages/ui/useScroll/useScroll.js
There is no efficient way for theme libraries based on UI lib to support an additional feature on scroll.
Add feature to call registered callbacks on scroll.
PLAT-145554
enactjs/sandstone/pull/972
> PLAT-145554: Support internal callbacks during scroll

- packages/ui/useScroll/useScroll.js
VirtualList should not stop scrolling to center by mouse down
If `snapToCenter` is true, calls prevent default and stops call stop function.
PLAT-145128
> PLAT-145128: Fix VirtualList to not stop scrolling to center by mouse down

- packages/spotlight/CHANGELOG.md
- packages/spotlight/SpotlightRootDecorator/SpotlightRootDecorator.js
When we build in isomorphic option with multiple locales, index.multi.html has important classes in the wrong div. 
Since we've added an extra 'div' from https://github.com/enactjs/enact/pull/2914 the issue occurred. So I've changed the containerRef to "root" dom.
WRN-2791
> WRN-2791: Fix SpotlightRootDecorator to not have an extra DOM

- packages/ui/CHANGELOG.md
- packages/ui/ViewManager/View.js
The issue can be seen in agate and sandstone samplers. The Panel body becomes hidden once noAnimation knob is unchecked/
Open sampler --> Panels --> Click on "Click me" button > Check 'noAnimation' knob> Click on "Click me" button > Uncheck 'noAnimation' prop.
Updated ui/ViewManager/View state to set `entering` to `false` when `noAnimation` prop becomes `true`
PLAT-141617
Enact-DCO-1.0-Signed-off-by: Daniel Stoian …
> PLAT-141617: Fixed ViewManager state when noAnimation is changed

- packages/sampler/.storybook/main.js
Resolve the warning related to the default PostCSS plugins that deprecated
As logs described, Default PostCSS plugins will be deprecated in the future(Storybook v7.0.0).
> DeprecationWarning: Default PostCSS plugins are deprecated. When switching to '@storybook/addon-postcss',
you will need to add your own plugins, such as 'postcss-flexbugs-fixes' and 'autoprefixer'.
So we fix the warning via using the below guide. 
(https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-implicit-postcss-loader) …
> WRN-3645: Sampler: Default PostCSS plugins are deprecated

- packages/ui/CHANGELOG.md
- packages/ui/Marquee/MarqueeDecorator.js
Marquee text with short content has willAnimate class
`willAnimate` prop follows `state.promoted`.
Logic about `promoted` It came from #1959, but the text length was not considered  from the beginning. It make  `state.promoted=true`  according to marqueeOn condition.
`state.promoted` prop becomes `true` in almost case by `promoteJob`. This is because the default value of `contentFits` was `false`. it was set on `invalidateMetrics()`;
on the other side, `InvalidateMetrics()` set `state.promoted` to `false` for reset, but in `promotedJob()` it …
> WRN-6365: Fixed Marquee to not separate layer when short text

- packages/core/package.json
- packages/core/util/util.js
- packages/ui/Marquee/MarqueeDecorator.js
- packages/ui/package.json
`recompose` has not been updated over 3 years and its dependencies have been made some troubles.
So, we'd like to replace `recompose` with other modules.
Enact has only 1 usage from `recompose`, `shallowEqual`.
I've made a utility function that performs the equivalent functionality.
And replaced `Component` with `PureComponent`.
WRN-2132
> WRN-2132: Replaced recompose usages

- packages/core/internal/ApiDecorator/tests/ApiDecorator-specs.js
- packages/core/useHandlers/tests/useHandlers-specs.js
Migrated `internal/ApiDecorator` and `useHandlers` unit tests to React Testing Library
WRN-9789
> WRN-9789: Apply React testing lib to Enact internal/ApiDecorator and useHandlers

- .travis.yml
- CHANGELOG.md
- packages/sampler/package.json
- packages/spotlight/SpotlightRootDecorator/SpotlightRootDecorator.js
Fixed `spotlightRootDecorator` to show focus when last input type is none
Set class to `non-touch-mode` when last input type is none (when tv is reboot)
WRN-11336
> WRN-11336: Fixed spotlightRootDecorator to show focus when last input type is `none`

- packages/sampler/package.json
- packages/spotlight/src/container.js
When reset the focus using spotlight.focus(container, 'default-focus');, the 'default-focus' option returns the first node in DOM order if no default is specified. 
When the visual order and DOM order do not match(ex `VirtualList`), the focus could be moved to somewhere in middle.
I add a new `topmost` option to decide the container target.
WRN-12780
> WRN-12780: Add topmost option for preferredEnterTo for getContainerFocusTarget

- packages/ui/styles/mixins.less
Fix .buildFontFace font mixins to work with multiple weight values.
As-Is
.buildFontFace("fontName", local("name"), 400 600) generates one font-face rule like below.
`@font-face {
font-family: "fontName";
src: local("name");
font-weight: 400 600;
}`
To-Be
.buildFontFace("fontName", local("name"), 400 600) generates multiple font-face rules like below.
`@font-face {
font-family: "fontName";
src: local("name");
font-weight: 400;
}
`
`
@font-face {
font-family: "fontName";
src: local("name");
font-weight: 600;
}
`
Fix .buildFontFace mixins to …
> WRN-12676: Fix .buildFontFace font mixins to work properly with multiple weight values

- .travis.yml
- packages/moonstone/CHANGELOG.md
- packages/moonstone/Panels/Panel.js
- packages/moonstone/Scrollable/ScrollButtons.js
- packages/moonstone/Scrollable/Scrollable.js
- packages/moonstone/Scrollable/ScrollableNative.js
- packages/sampler/stories/qa/ActivityPanels.js
After navigating panel with some button below the `Scroller`, focus is restored to another node.
Except for scrollbar buttons when restore focus
In version 4, spotlight and spottable should provide this feature.
WRN-14604
> WRN-14604: Fixed Panel to restore focus properly when it has Scroller with `focusableScrollbar`

- packages/spotlight/CHANGELOG.md
- packages/spotlight/src/utils.js
When elements' boundaries are not an integer value as a result of browser rendering, `spotlight` may miss focus navigation target by key inputs.
Apply epsilon value to catch navigable target elements.
WRN-14854
> WRN-14854: Move focus properly when elements have non-integer boundaries

- packages/spotlight/CHANGELOG.md
- packages/spotlight/Spottable/SpottableCore.js
- packages/spotlight/Spottable/tests/Spottable-specs.js
- packages/ui/CHANGELOG.md
- packages/ui/Cancelable/Cancelable.js
- packages/ui/Cancelable/tests/Cancelable-specs.js
- packages/ui/Changeable/Changeable.js
- packages/ui/FloatingLayer/FloatingLayer.js
- packages/ui/FloatingLayer/tests/FloatingLayer-specs.js
- packages/ui/Marquee/MarqueeBase.js
- packages/ui/Media/Media.js
- packages/ui/RadioDecorator/RadioDecorator.js
- packages/ui/RadioDecorator/tests/RadioDecorator-specs.js
- packages/ui/Scrollable/Scrollable.js
- packages/ui/Scrollable/ScrollableNative.js
- packages/ui/Toggleable/Toggle.js
- packages/ui/Toggleable/Toggleable.js
- packages/ui/Toggleable/tests/Toggleable-specs.js
- packages/ui/Transition/Transition.js
- packages/ui/Transition/tests/Transition-specs.js
- packages/ui/ViewManager/TransitionGroup.js
- packages/ui/ViewManager/ViewManager.js
- packages/ui/ViewManager/tests/ViewManager-specs.js
We've added `forwardCustom` in https://github.com/enactjs/enact/pull/2773.
And some of the custom events have no `type` when firing.
Fixed to use `forwardCustom` and add `type` when forwarding custom events.
WRN-848
> WRN-848: Updated to use `forwardCustom` and add `type` when forwarding custom events

- packages/ui/Touchable/Drag.js
- packages/ui/Touchable/Flick.js
- packages/ui/Touchable/Hold.js
Refactoring Flick.js, Drag.js, and Hold.js
Unify config structure of Flick.js, Drag.js, and Hold.js
- Fix Hold.js and Drag.js to not store handler function in `Config`
- Fix Flick.js to store variables(`maxDuration`, `maxMoves`, `minVelocity`) in `flickConfig`
WRN-844
> WRN-844: Unify config structure of Flick, Drag, and Hold

- packages/ui/Scroller/ScrollerBasic.js
- packages/ui/VirtualList/VirtualListBasic.js
- packages/ui/useScroll/useScroll.js
Lists and scrollers of Enact use the `scroll-behavior` CSS attribute to control `smooth` scrolling in a tricky way for legacy browsers that Enact supported. Now, it is time to focus on more modern browsers and to use the standard `scrollTo` option for elements.
Replace `scroll-behavior` based code with `scrollTo` option.
This PR works on browsers below:
- Chrome 61 or higher (including all versions of …
> WRN-13462: Use standard `scrollTo` option for lists and scrollers

- packages/ui/CHANGELOG.md
- packages/ui/Transition/Transition.js
- packages/ui/Transition/tests/Transition-specs.js
Enact-DCO-1.0-Signed-off-by: SJ RO (sj.ro@lge.com)'
Event not passed at transition end.
Modify to pass the necessary event at the transition end
- onTransitionEnd : this is not a custom event. So pass the event object as it is.
- onShow, onHide : this is a custom event and Popup(moonstone/sandstone) use the event.currentTarget.
So pass the event object with type and currentTarget.
WRN-17780
> WRN-17780: Fix Transition to pass the right event object

- packages/ui/CHANGELOG.md
- packages/ui/FloatingLayer/FloatingLayer.js
- packages/ui/FloatingLayer/FloatingLayer.module.less
- packages/ui/Spinner/tests/Spinner-specs.js
- packages/ui/styles/core.less
When two floatinglayers are displayed, there is a bug that a popup which open later shown on down of other popup .
Because `FloatingLayer `reuses nodes , If you reopen a previously opened Popup, it may open below other popups.
I removed unnecessary wrapper node that is reused on FloatingLayer
I wanted to remove the `state.nodeRendered` also, but I failed. There was much bug when I remove the variable
In the case of a popup that is start with open, re-rendering is …
> WRN-18494: Remove unnecessary wrapper node on FloatingLayer

- CHANGELOG.md
- packages/ui/CHANGELOG.md
- packages/ui/Marquee/MarqueeDecorator.js
Receiving the "className" config on MarqueeDecorator is not our standard way.
- Add `ui/MarqueeDecorator` config `css` to support customizing the MarqueeBase styles
- Deprecate `ui/MarqueeDecorator` config `className` to be removed in 5.0.0
WRO-608
> WRO-608: Replace MarqueeDecorator config `className` to `css`

- packages/webos/docs/webos-features.md
Our document for webOS feature shows an example to add webOS event handler to `window` not `document`.
Update the document.
WRO-514
> WRO-514: update webos-features.md

- packages/core/util/tests/Job-specs.js
- packages/ui/Touchable/tests/Touchable-specs.js
In some cases, when the code uses timers (setTimeout, setInterval, clearTimeout, clearInterval), the tests may become unpredictable, slow and flaky.
In fact, an unpredictable error occurs when performing unit tests on travis of this repository.
To solve this problem, most testing frameworks provide an option to replace the real timer in the test with a fake timer.
Use fake timers in all unit test cases that require timers.
(https://testing-library.com/docs/using-fake-timers)
[//]: # (Were any side-effects caused by the …
> WRO-2712: Use fakeTimers for unit test

- docs/testing-components/test-driven-development/index.md
- docs/testing-components/unit-testing/index.md
Changed the unit test library displayed in the documentation from Enzyme to React Testing Library.
WRO-438
> WRO-438: Update testing page with React Testing Lib

- .travis.yml
Requires travis test on multiple node versions including lts
Update .travis.yml so that it can be tested on multiple node versions (lts(16), node(18))
- ubuntu 20 is required for node 18 ( https://docs.travis-ci.com/user/reference/focal/)
Currently, @enact/storybook-utils is not updated, so an error occurs in node 18
So node18 test will be reflected after storybook-utils is updated
WRO-4551
Enact-DCO-1.0-Signed-off-by: SJ RO …
> WRO-4551:Update the node version of travis

- packages/ui/CHANGELOG.md
- packages/ui/useScroll/useScroll.js
Item list is disappear after the `VirtualList size is changed".
This problem is because the virtualList's `firstIndex` state is not updated properly.
Complex to explain, this is a timing issue.
After resizing VL, VL tried to sets a new `firstIndex`.
The problem is that immediately after this, another rerender is occured by the App.
In between, the `didScroll` event handler is called.
In this `didScroll`, It `setState` the previous `firstIndex`, and as a result, the `firstIndex` state is not updated properly.
Even if rerender occurs by the app, the state value should be updated by VL normally.
Due to the …
> WRO-7190: Fix timing issue when rerende VL by resizing

- packages/core/CHANGELOG.md
- packages/core/handle/handle.js
`focusCustom` method of `handle` module does not include `stopPropagation` in the event payload that it dispatches, so there is no way to stop propagation of the event in Enact apps when they use `focusCustom`.
This PR changes `forwardCustom` to include `stopPropagation` and `preventDefault` of the original event in a forwarded event payload.
The original issue is only about `stopPropagation` but `preventDefault` is also commonly called by apps. So two methods are …
> WRO-6848: Provide `stopPropagation` and `preventDefault` for custom events

- packages/spotlight/CHANGELOG.md
- packages/spotlight/src/container.js
Focus can leave the restrict container after when returning from another app.
(Element outside the popup receives focus.)
Cause: 
If the "lastContainer" is `popup container`, focus cannot escape because `popup container` is restrict container. ('self-only')
When button inside popup get focus, spotlight set `lastContainer` to `popup content container`.  `popup content container` is not restrict container.
When pointer leave the popup, spotlight set `lastContainer` to `popup container`.  In that case, there is no problem.
In the reproducible case, the pointer leave event did not occur and another app was …
> WRO-4003: check parent's container restrict condition when change activate container

- packages/spotlight/SpotlightContainerDecorator/SpotlightContainerDecorator.js
- packages/spotlight/docs/index.md
There is duplicated api description on `Spotlight`/index.md files.
- Leave only the APIs that are mainly used and remove others.
- Add link for full api list
- Merge some docs in `SpotlightContainerDecorator.js` (There was nothing to merge in the `Spottable` docs.)
- In the md document, the term "Parameters" is used, but in the api documents and code, the term "Configuration" is used. So, I modified it to use "Configuration Parameters."
`restrict` is not an …
> WRO-745: Clean up Spotlight document

- packages/ui/CHANGELOG.md
- packages/ui/Marquee/MarqueeDecorator.js
When marquee applied to item related components, marquee cannot restart animation after completes its marquee once.
When marquee completes its marquee once, restartAnimation() func in marqueeDecorator called to set animating state to be false and then called start() func. As react batchs its state, animating state is true when start() executed and it caused animation to be stopped.
Use flushSync in marqueeDecorator to synchronously update animating state to be false. …
> WRO-8481: Fixed `MarqueeDecorator` to restart animation properly with React 18

- packages/ui/CHANGELOG.md
- packages/ui/Marquee/MarqueeBase.js
- packages/ui/Marquee/tests/Marquee-specs.js
Cause : 
Perhaps due to the bidi rule, the div inserted in the middle is repositioned to unexpected position.
Resolve: 
Isolate cloned text to avoid reordering by bidi rule. 
WRO-9294, WRO-9284
> WRO-9294: Fix Marquee spacing for bidirectional text

- packages/ui/CHANGELOG.md
- packages/ui/Marquee/MarqueeBase.js
After one cycle of Marquee, the text stops over the start line and comes back incase of scaled Item.
Apply the scaled value to the spacing calculation so that it stops at the correct point.
When an item of size 100 is scaled by 120%,
The marquee component is well calculated the translateX as "120+spacing size" (=distance).
However, in browsers, it translate by 120px * 120%, eventually causing the marquee to pass more than expected.
We can consider the scale value …
> WRO-9768: Fix `Marquee` to stop at the proper position when scaled

- packages/core/package.json
- packages/i18n/package.json
- packages/spotlight/package.json
- packages/ui/package.json
- packages/webos/package.json
There is no homepage and repository information in the enact packages page of npmjs.com
Add 'homepage' and 'repository' field to package.json according to the guide of https://docs.npmjs.com/cli/v8/configuring-npm/package-json
WRO-11514
> WRO-11514: Add Repository/Hompage address to enact packages at npmjs.com

- docs/interoperability.md
Bootstrap 4 and above uses Sass instead of less so we need to add the recent guide.
Add the guide to import `.scss` files in bootstrap
(Guide page: https://enactjs.com/docs/developer-guide/interoperability/#using-third-party-components-inside-of-enact)
WRO-11530
> WRO-11530: Update guide for using `bootstrap` 4 and above with enact

- packages/sampler/.storybook/preview.js
- packages/sampler/package.json
- packages/sampler/src/Environment/Environment.js
In packages/sampler storybook, if controls are changed from Docs tab, it doesn't update the component preview.
Setting "inlineStories" to true causes bugs, so we agreed to keep inlineStories false and set a height to the iFrame. Also, controls were removed from the docs page.
WRO-13139
> WRO-13139: Sampler: Remove controls from Docs tab

- CHANGELOG.md
- packages/ui/CHANGELOG.md
- packages/ui/Marquee/MarqueeDecorator.js
- packages/ui/Marquee/tests/Marquee-specs.js
When using sync mode in `MarqueeDecorator` and set marqueeDelay to be 0, Marquee only works once and stopped.
`MarqueeDecorator` sync mode is set when `MarqueeController` is applied. ([source link](https://github.com/enactjs/enact/blob/develop/packages/ui/Marquee/MarqueeDecorator.js#L368))
In this PR, fixed `MarqueeDecorator` to enforce minimum resetDelay when sync mode.
If `MarqueeDecorator` is not a sync mode, 40ms is enforced for resetDelay by resetAnimation and restartAnimation functions.
```
resetAnimation = () => {
const delay = …
```
> WRP-2655: Fixed MarqueeDecorator to enforce minimum resetDelay when synchronized

- packages/i18n/CHANGELOG.md
- packages/i18n/docs/index.md
Fix broken link to a sample i18n app (github repo) on i18n docs
Developer Guide on enactjs.com has "i18n (Internationalization)" page and the page has "Sample" part having a broken link to a sample i18n app github repository. "sandstone/" is missing in the URL path.
Change the broken link to a valid URL ([pattern-locale-switching](https://github.com/enactjs/samples/tree/master/sandstone/pattern-locale-switching))
WRP-6139 …
> WRP-6139: fix broken link on enactjs.com i18n docs page

- packages/ui/Touchable/Pinch.js
- packages/ui/Touchable/Touchable.js
- packages/ui/Touchable/config.js
Commit "36e60f5e WRO-4836: Support PinchZoom gesture (#3084)" introduced pinch-zoom functionality and related APIs.
This patch adds and changes the commit partially to make the APIs more precise but leaves the functionality intact.
1. add 'scale' payload to pinch event docs
2. change names of min/maxZoom to min/maxScale
3. fix the typo of 'the coordinates' to 'The coordinates'
Just only rename 'zoom' to 'scale.' but the code has been changed.
[//]: # (Related …
> WRP-6259:ui:Touchable: add scale payload to pinch event doc

- packages/ui/useScroll/useScroll.js
Theme libraries can assume that a passing object reference is fixed, but `useScrollBase` is passing a literal object that is newly created for each call. And this could cause unexpected behavior of Scroller/VirtualList.
Instead of a literal object, pass a ref object from `useRef`.
WRP-5951
> WRP-5951: Scroller: Fixed to pass a ref object to theme libraries instead of a literal object

- packages/i18n/CHANGELOG.md
- packages/i18n/src/Loader.js
@enact/i18n/src/Loader couldn't load resources for theme libraries asynchronously due to not passing `rootPath` which has the path for resources of the theme libraries.
Fixed to pass a missing parameter when calling `_loadFilesAsync` function.
WRP-9232
> WRP-9232: Fixed to load resources for theme libraries asynchronously

- .travis.yml
There is a difference between 'npm install gitbranch' and 'git clone gitbranch' -> 'npm install'.
Need to use the git clone method to follow the already tested npm-shrinkwrap.json during travis build.
Update .travis.yml to download the cli source code with git clone and then run 'npm install' and 'npm link' in the cli directory. 
WRP-9221
> WRP-9221:Update .travis.yml to change the CLI downloading method

- packages/ui/Layout/Layout.js
We decided to add a prop to support gap . (ex. justify-content: space-between; ), but enact/ui/layout already has `align` prop to apply this. So we need more docs to guide it.
add more docs for `align` prop of `Layout` and for `justify-content` CSS property.
WRP-6258
Enact-DCO-1.0-Signed-off-by: Hoeun Ryu <hoeun.ryu@lge.com>
> WRP-6258:Layout: add docs for `justify-content` CSS property

- packages/spotlight/src/container.js
- packages/spotlight/src/spotlight.js
- packages/spotlight/src/utils.js
Spotlight needs to navigate standard focusable element when isStandardFocusableMode is set true.
If focusRingElement exists, when the spotlight focuses a certain element, focusRingElement needs to move.
Implement spotlight logic to determine if the element is standard focusable element.
Add `isStandardFocusMode` config in GlobalConfig(https://github.com/enactjs/enact/blob/master/packages/spotlight/src/container.js#L43).
`isStandardFocusMode` config can be set with spotlight.initialize function.
[//]: # (Were any …
> Add isStandardFocusableMode private globalConfig 

- packages/core/CHANGELOG.md
- packages/core/platform/platform.js
Microsoft ended support for windows mobile on December 10, 2019
So there is no need to keep windows phone on the list of platforms that enact recognizes.
Deprecated notice required before the removal.
Update a change log to add deprecated notice for deleting Windows phone from platform list.
WRP-9203
> WRP-9203: Add deprecated notification before removing 'window phone' from @enact/core/platform

- packages/core/platform/platform.js
- packages/core/platform/tests/platform-specs.js
There are many modules that access platform.js, so the deprecate message is displayed too often.
Fix to show deprecation message when platform is Windows Phone
WRP-9203
> WRP-9203: Fix to show deprecation message when platform is Windows Phone

- packages/sampler/stories/default/Layout.js
- packages/ui/CHANGELOG.md
- packages/ui/Layout/Cell.js
- packages/ui/Layout/Layout.module.less
- packages/ui/Layout/tests/Layout-specs.js
Reverts enactjs/enact#3128 
This PR affects centered prop of theme library components
> Revert "WRP-6257: Cell: Add `grow` prop to expand the size to its container"

- packages/ui/useScroll/useScroll.js
A scroller of theme libraries gets wrong RTL status from ui library when locale is changed on run-time.
The issue occurs since a getter function returns RTL status of a closure variable that is not updated in time. To resolve the issue, I re-write function to return RTL status from mutable object rather than closure.
WRP-10124
> WRP-10124: Fixed to apply RTL on a scroller of theme libraries when locale is changed

- packages/spotlight/CHANGELOG.md
- packages/spotlight/src/spotlight.js
As pointerHide event is not delivered to enact, getPointerMode() still true when executing Spotlight.focusElement().
Fix focusElement() to check cursor.visibility if it exists.
WRP-11795
> WRP-11795: Fix spotlight.focusElement to check cursor visibility

- packages/sampler/stories/default/Layout.js
- packages/ui/CHANGELOG.md
- packages/ui/Layout/Cell.js
- packages/ui/Layout/Layout.module.less
- packages/ui/Layout/tests/Layout-specs.js
A `grow`able cell will expand to its maximum size according to the remaining space of the container. This is used when you want to grow the size of this cell so that it fills the container.
This PR is reopened (#3128) to fix a screenshot test failing on Item component in sandstone.
add `grow` prop to `Cell` component.
A `grow`able Cell has a declaration of `flex: 1 1 100%` in CSS by default. However, the `flex-basis` property is overridden by the `var(--cell-size)` value passed from JS. And by combining `max-width: none` and `flex-grow: 1` declaration, its size can be increased by the size of its parent …
> WRP-6257: Cell: Add grow prop to expand the size to its container

- packages/ui/CHANGELOG.md
- packages/ui/resolution/resolution.js
- packages/ui/resolution/tests/resolution-specs.js
Enact-DCO-1.0-Signed-off-by: Juwon Jeong ([juwon.jeong@lge.com](mailto:juwon.jeong@lge.com))
When an undefined screen type layout is given, resolution calculates a base font size larger than it should be given.
Therefore, there are cases where apps are cropped from the layout. 
Fix getScreenType to select a screen type whose dimensions are smaller than but nearest to the screen.
Fix calculateFontSize to calculate the base font size for the given screen type by considering workspace bounds to support undefined screen type layout.  …
> WRP-7784: Fix resolution getScreenType and calculateFontSize to support undefined screenType layout

- packages/ui/CHANGELOG.md
- packages/ui/resolution/ResolutionDecorator.js
- packages/ui/resolution/resolution.js
- packages/ui/resolution/tests/resolution-specs.js
When the screen size is smaller than `hd (1280*720)`, getScreenType(ui/resolution) miscalculates best match screenType and It causes the font-size to be 96px.
Fix getScreenType to set the default screen type to the smallest one `hd(1280*720)`. In case no matches are found later, the best match screenType would be `hd(1280*720)`.
WRP-13532
> WRP-13532: Fix resolution/getScreenType to set default screen type to the smallest one

- .travis.yml
- packages/ui/useScroll/useScroll.js
Theme libraries can assume that a passing object reference is fixed, but `useScrollBase` is passing a literal object that is newly created for each call. And this could cause unexpected behavior of Scroller/VirtualList.
Instead of a literal object, pass a ref object from `useRef`.
(Cherry-pick #3118)
WRP-5951
WRP-16065
> WRP-16065: Scroller: Fixed to pass a ref object to theme libraries instead of a literal object

- packages/spotlight/src/tests/utils-specs.js
- packages/spotlight/src/tests/utils.js
PR #3127 was for Spotlight to support navigation between standard focusable elements. However, unit tests for the `isStandardFocusable` function, which plays an important role in its support, were not included.
Add unit tests for `isStandardFocusable` function. The following items are cases.
- should return false if tabIndex < 0
- should return false if hidden (too small)
- should return true if button tag
- should return false if button tag with disabled
- should return true if A tag with href
- should return true if input tag
Code coverage increased from 57.14% to 77.92%.
Code coverage results
| File …
> WRP-10830:spotlight: add unit tests for isStandardFocusable

- packages/core/platform/platform.js
- packages/core/platform/tests/platform-specs.js
The latest Edge platform cannot be detected as our enact/core/platform has an old regex of the Edge platform.
The regular expression for the Edge browsers is updated.
According to the documents
- https://learn.microsoft.com/en-us/microsoft-edge/web-platform/user-agent-guidance
- https://www.whatismybrowser.com/guides/the-latest-user-agent/edge.
The identifier token of Edge browsers can be one of the followings.
|          Platform |     UA |
|-------------------|--------|
|           Windows |    Edg |
|             macOS |    Edg |
|           Android |   EdgA |
|               iOS | EdgiOS |
| Windows 10 …
> WRP-11806:platform: update regular expression for Edge browser UA string

- packages/core/CHANGELOG.md
- packages/core/handle/handle.js
- packages/core/handle/tests/handle-specs.js
`core/handle/forwardCustom` and `core/handle/forwardCustomWithPrevent` do not bind given _adapter_ functions to `this` that is bound by native `bind` function or `bindAs` utility function from `core/handle/handle`. So, `core/handle/call` does not working as an adapter function.
Updated `core/handle/forwardCustom` and `core/handle/forwardCustomWithPrevent` to bind `this` to adapters properly.
Unit test cases are added also. …
> WRP-10827: Fixed `forwardCustom` and `forwardCustomWithPrevent` to bind adapters properly

- packages/sampler/package.json
When you initialize a storybook, the module related to the storybook is automatically installed in devDependencies.
(https://storybook.js.org/docs/react/get-started/install , in simply, $ npx storybook@latest init)
There was no reason to be managed as devDependencies even if you checked related documents or developer sites, and it is right to move to dependencies because the sampler directory itself aims to create samplers through storybooks.
Move storybook-related modules from devDependencies to dependencies
[//]: # …
> WRP-11048: Move storybook-related modules from devDependencies to dependencies

- packages/ui/VirtualList/VirtualListBasic.js
If both `minSize` in `itemSize` prop and `clientSize` are specified, `VirtualList` does not work properly.
Fixed uninitialized internal state in the given condition.
WRP-19306
WRP-4365
> WRP-19306: Fixed `VirtualList` to work properly when both `minSize` in `itemSize` and `clientSize` are given

- CHANGELOG.md
- packages/ui/CHANGELOG.md
- packages/ui/Marquee/Marquee.module.less
As the margin of marquee text is not defined, margin text can be cropped by the  `overflow:hidden` prop of `.marquee` class
Fix the margin of the marquee text to 0
WRP-24097
> WRP-24097: Fix margin of marquee text to be zero

- docs/redux/redux-async.md
- packages/webos/LS2Request/LS2Request.js
`PalmServiceBridge` was renamed as `WebOSServiceBridge` in 2018 with an fallback alias for compatibility on legacy webOS.
Updated docs to use `WebOSServiceBridge`, and updated `LS2Request` module to use `WebOSServiceBridge` with a fallback of `PalmServiceBridge`.
WRP-26268
> WRP-26268: Rename PalmServiceBridge as WebOSServiceBridge

- packages/i18n/CHANGELOG.md
- packages/i18n/src/Loader.js
For example, when the es-ES folder of original resources and the es folder of additional resources have the same key, the app wants key-value from the es folder of additional resources instead of the es-ES of original resources.
Fix i18n loader to traverse additional resources from the root later to override strings while loading resources files
This PR also cherry-pick https://github.com/enactjs/enact/commit/fca46f11eb3cee38069fe57197ac4c884850157d
[//]: # (Related …
> WRQ-1033: Fix i18n loader to traverse additional resources later while loading resources

- packages/ui/CHANGELOG.md
- packages/ui/Marquee/MarqueeDecorator.js
- packages/ui/Marquee/tests/Marquee-specs.js
When Marquee size is changed dynamically(for example, changing the screen size or rotating the screen) it is not re-rendered, so the text will not be able to start marquee animation and may be truncated.
Added `ResizeObserver` to make Marquee re-render when its size is changed. 
WRQ-2421
> WRQ-2421: Fix MarqueeDecorator to re-render marquee when its size changed

- packages/ui/Routable/Routable.js
- packages/ui/Routable/Router.js
- packages/ui/Routable/util.js
In babel version 7.23 or higher, an error occurs when exporting `propTypes` in `ui/Routable/util.js` when `enact transpile`.
Change variable name from `propTypes` to `RoutablePropTypes`
WRQ-2906
> WRQ-2906 : Change the variable name to prevent export error when 'enact transpile'

- packages/ui/CHANGELOG.md
- packages/ui/Marquee/MarqueeDecorator.js
- packages/ui/Marquee/tests/Marquee-specs.js
When Marquee size is changed dynamically(for example, changing the screen size or rotating the screen) it is not re-rendered, so the text will not be able to start marquee animation and may be truncated.
Manually cherry-pick https://github.com/enactjs/enact/pull/3183 to add ResizeObserver to make Marquee re-render when its size is changed.
I cherry-pick manually because in the enact 4.0 version we didn't use testing-library yet.
[//]: # (Were any …
> WRQ-2421: Fix MarqueeDecorator to re-render marquee when its size changed (enact 3.4.9 touch)

- packages/ui/CHANGELOG.md
- packages/ui/Marquee/MarqueeDecorator.js
- packages/ui/Marquee/tests/Marquee-specs.js
When Marquee size is changed dynamically(for example, changing the screen size or rotating the screen) it is not re-rendered, so the text will not be able to start marquee animation and may be truncated.
Cherry-pick #3183 to add `ResizeObserver` to make Marquee re-render when its size is changed
WRQ-2421
> WRQ-2421: Fix MarqueeDecorator to re-render marquee when its size changed (enact 4.5)

- packages/i18n/src/Loader.js
If locale changes are repeated multiple times, QuotaExceededError occurs when saving ilib cache data to localstorage.
Add try-catch block to handle exception cases. When QutoaExceededError occurs, filter which cache data to remove and then remove them.
WRQ-2287
> WRQ-2287: Fix i18n loader to handle exceeded error of localStorage data

- package-lock.json
- package.json
To fix the validate-docs error while Travis test, Update @enact/docs-utils version to 0.4.8.
Update @enact/docs-utils version to 0.4.8
> Update @enact/docs-utils version to ^0.4.8 in package.json file

- packages/spotlight/CHANGELOG.md
- packages/spotlight/src/target.js
- packages/spotlight/src/tests/utils-specs.js
- packages/spotlight/src/utils.js
Spotlight cannot choose the next focus target if the currently focused node is partially visible as clipped by an overflow container. Note that a clipped node within an overflow container can be a navigable target.
Updated a navigation logic to count only a visible part if the currently focused node is partially visible and its closest container is an overflow container.
WRQ-6220
Enact-DCO-1.0-Signed-off-by: Seungcheon Baek …
> WRQ-6220: Fixed `spotlight` navigation from the focused element clipped by an overflow container

- packages/spotlight/SpotlightRootDecorator/tests/SpotlightRootDecorator-specs.js
- packages/spotlight/docs/index.md
- packages/spotlight/src/container.js
`enterTo` default value is defined in `SpotlightContainerDecorator.js` and `container.js`. 
However, in SpotlightContainerDecorator.js, we set the default value of enterTo to `null`, and in container.js, we set the default value of enterTo to `''`.
We fix container.js to set the default value of enterTo to `null`.
Fix GlobalConfig in container.js.
Fix spotlight docs where explaining enterTo container config.
WRQ-179
> WRQ-179: Fix default value of `enteroTo` in GlobalConfig to null

- codecov.yml
- packages/spotlight/src/tests/inputType-specs.js
- packages/webos/lastInputType/lastInputType.js
- packages/webos/lastInputType/package.json
Added a new `lastInputType` module under `enact/webos`
Previously this LS2Request was located in `sandstone/ThemeDecorator` and forced apps to access this service without recognizing it.
Changed access permission from `platform.type === 'webos'` to `platform.tv === true`
Added `lastInputType` module to `codecov.yml` since it's a private module
WRQ-6498
> WRQ-6498: Added `lastInputType` module

- packages/ui/Scroller/Scroller.module.less
- packages/ui/Scroller/UiScroller.module.less
- packages/ui/VirtualList/UiVirtualList.module.less
- packages/ui/VirtualList/VirtualList.module.less
Scroller and VirtualList had 2 kinds of scrollbars in the Firefox browser.
Only the Sandstone scrollbar appears in the Firefox browser.
WRQ-9619
Enact-DCO-1.0-Signed-off-by: Ion Andrusciac [ion.andrusciac@lgepartner.com](mailto:ion.andrusciac@lgepartner.com)
> WRQ-9619: Fixed the scrollbar on Firefox browser

- packages/ui/resolution/tests/resolution-specs.js
As we support new resolution type QHD, we decided to test all supported screen types.
Because TV model which needs for QHD is based on enact 4.7.x version, this PR is for release/4.7.x.develop branch.
I copied changed code of https://github.com/enactjs/enact/pull/3228
added unit tests for screenTypes of supported resolutions.
WRQ-17933
Enact-DCO-1.0-Signed-off-by: Jiye Kim (jiye.kim@lge.com)
> WRQ-17933: Add unit tests for screenTypes matching supported resolutions

- packages/i18n/CHANGELOG.md
- packages/i18n/src/Loader.js
For example, when the es-ES folder of original resources and the es folder of additional resources have the same key, the app wants key-value from the es folder of additional resources instead of the es-ES of original resources.
Fix i18n loader to traverse additional resources from the root later to override strings while loading resources files
This PR is related to https://github.com/enactjs/enact/pull/3180
WRQ-20168
WRQ-1033
> WRQ-20168: Fix i18n loader to traverse additional resources later while loading resources

- packages/core/package.json
- packages/i18n/package.json
- packages/sampler/package.json
- packages/spotlight/SpotlightContainerDecorator/SpotlightContainerDecorator.js
- packages/spotlight/package.json
- packages/ui/Repeater/Repeater.js
- packages/ui/Scroller/Scroller.js
- packages/ui/Slottable/tests/Slottable-specs.js
- packages/ui/Toggleable/Toggleable.js
- packages/ui/Touchable/Touchable.js
- packages/ui/VirtualList/VirtualList.js
- packages/ui/package.json
- packages/ui/useScroll/Scrollbar.js
- packages/ui/useScroll/ScrollbarTrack.js
- packages/webos/package.json
In React 19, defaultProps in function components will be removed.
In React 18.3, There are warnings for key spreading
Remove defaultProps for function components and replaced them with ES6 default parameters.
Pass key directly to JSX without using spread
WRQ-19328
> WRQ-19328: Fix React 18.3 warnings in enact

- packages/i18n/CHANGELOG.md
- packages/i18n/src/Loader.js
Some apps need to override strings when the original strings file does not exist
Changed to read the resources file from the additional resource's path even if the original file does not exist.
Added the read json object ot the cache array.
Original PR of this patch is https://github.com/enactjs/enact/pull/3072
WRQ-20168
> WRQ-20168: Add support for overriding strings where original resources folder does not have the file

- packages/ui/CHANGELOG.md
- packages/ui/Marquee/MarqueeDecorator.js
- packages/ui/Marquee/tests/Marquee-specs.js
- packages/ui/Marquee/useMarqueeController.js
When <Marquee> is wrapped with MarqueeController to be synchronized and marqueeOn props is 'render' and the content changes, MarqueeDecorator cannot start the marquee animation. 
`MarqueeDecorator.componentDidUpdate()` called when content changed. 
As children is changed, `this.invalidateMetrics()`, `this.cancelAnimation()` are called and `forceRestartMarquee` variable set to true in `componentDidUpdate` function,
`this.tryStartingAnimation()` function is called because `forceRestartMarquee` is true.
However, In `tryStartingAnimation()`, it …
> WRQ-24303: Fix `marqueeDecorator` and `marqueeController` to start animation properly when content changed

- packages/spotlight/src/utils.js
- packages/ui/Scrollable/ScrollThumb.module.less
- packages/ui/Scrollable/Scrollable.module.less
- packages/ui/Scrollable/ScrollableNative.js
- packages/ui/Scrollable/Scrollbar.module.less
- packages/ui/styles/core.less
- packages/ui/styles/mixins.less
- packages/ui/useScroll/Scrollbar.module.less
- packages/ui/useScroll/ScrollbarTrack.module.less
- packages/ui/useScroll/useScroll.js
- packages/ui/useScroll/useScroll.module.less
Enact has CSS vendor prefixes. Most of them are not required anymore.
Considering browser versions we support, I removed unnecessary vendor prefixes.
WRQ-7108
Enact-DCO-1.0-Signed-off-by: Jiye Kim (jiye.kim@lge.com)
> WRQ-7108: Remove unnecessary vendor prefixes

- packages/spotlight/CHANGELOG.md
- packages/spotlight/src/spotlight.js
`enableSelector` needs to set selectorDisabled to true and `disableSelector` needs to set selectorDisabled to false.
WRQ-15921
> WRQ-15921: Fix spotlight.disableSelector to set selectorDisabled to false

- packages/ui/CHANGELOG.md
- packages/ui/Placeholder/PlaceholderControllerDecorator.js
- packages/webos/CHANGELOG.md
- packages/webos/speech/VoiceControlDecorator.js
When `VoiceControlDecorator` wrapped video player component in the app, video player component remounted continuously.
In the previous logic, every time `VoiceControlDecorator` render, the children of the `VoiceControlDecorator` are unmounted and then remounted. 
It means that `Video` and `Media` components are re-mounted continuously. 
To fix this issue, we modify `VoiceControlDecorator` and `PlaceholderControllerDecorator` to not use HOCs in the render method. …
> WRQ-28000: Fix `VoiceControlDecorator` and `PlaceholderControllerDecorator` not to remount its children when it rerenders

- packages/core/platform/platform.js
Previously, when accessing the core/platform module, you could see the deprecated warning below.
> DEPRECATED: webos. Will be removed in 5.0.0. Refer `@enact/webos`'s `platform` for webOS specific information..
It would be better to appear this to users accessing webos properties.
Users accessing other properties may not be interested in that information.
The warning has been modified to only be appeared to users accessing platform.webos
[//]: # (Related issues, …
> WRQ-28860: Modified so that related warnings appear only when accessing the webos property of core/platform

- packages/core/CHANGELOG.md
- packages/core/util/tests/util-specs.js
- packages/core/util/util.js
- packages/ui/CHANGELOG.md
- packages/ui/Scroller/Scroller.js
- packages/ui/VirtualList/VirtualList.js
In https://github.com/enactjs/enact/pull/3238, we removed defaultProps and implemented this feature manually.
After this implementation, if `undefined` is passed for a prop value, the prop value remains `undefined`. 
However, defaultProps(https://legacy.reactjs.org/docs/typechecking-with-proptypes.html#default-prop-values) sets prop value to default value when `undefined` value is passed for the prop. 
Fix `Scroller`, `VirtualList` and `VirtualGridList` to set prop value to default value when `undefined` is passed for the prop value
[//]: # (Are there any …
> WRQ-31515: Fixed `Scroller`, `VirtualList`, and `VirtualGridList` to set prop value to default when `undefined` is passed for the prop value

- packages/core/CHANGELOG.md
- packages/core/util/tests/util-specs.js
- packages/core/util/util.js
- packages/ui/CHANGELOG.md
- packages/ui/Scroller/Scroller.js
- packages/ui/VirtualList/VirtualList.js
In https://github.com/enactjs/enact/pull/3238, we removed defaultProps and implemented this feature manually.
After this implementation, if undefined is passed for a prop value, the prop value remains undefined.
However, defaultProps(https://legacy.reactjs.org/docs/typechecking-with-proptypes.html#default-prop-values) sets prop value to default value when undefined value is passed for the prop.
Add `setDefaultProps` util function
Fix `Scroller`, `VirtualList` and `VirtualGridList` to set prop value to default value when undefined is passed for …
> WRQ-31515: Fixed Scroller, VirtualList, and VirtualGridList to set prop value to default when undefined is passed for the prop value

- packages/sampler/.storybook/manager.js
Enact-DCO-1.0-Signed-off-by: Dongsu Won (dongsu.won@lgepartner.com)
The height of addons bottom panel has changed as the storybook has been updated to 8.0.
So we need to fix height of addons bottom panel.
Fix height of addons bottom panel.
This PR is basically the same with https://github.com/enactjs/sandstone/pull/1666.
WRR-393
> WRR-393: Update default height of bottom pannel in enact storybook

- packages/ui/CHANGELOG.md
- packages/ui/VirtualList/VirtualListBasic.js
There was an issue where the scroller could not move to the end of the scroller when the content of a VirtualList was changed.
This issue occurs when the content of virtualList is updated between fixed size content and variable size content and its minSize and dataSize is the same. 
For example, the size of the item contents is as follows:
contents A = [120, 120, 120]
contents B = [120, 240, 240]
In this case, the condition for recalculating the scroll bounds value is not met in the existing code. Because the minSizes and datasizes of the two content lists are the same.
If the scroll bounds value is not updated, scrollTo will not work because it will …
> WRR-2172: Fix `VirtualList` to update its scroll bounds when the total size of items is changed

- packages/ui/CHANGELOG.md
- packages/ui/VirtualList/VirtualListBasic.js
There was an issue where the scroller could not move to the end of the scroller when the content of a VirtualList was changed.
This issue occurs when the content of virtualList is updated between fixed size content and variable size content and its minSize and dataSize is the same.
For example, the size of the item contents is as follows:
contents A = [120, 120, 120]
contents B = [120, 240, 240]
In this case, the condition for recalculating the scroll bounds value is not met in the existing code. Because the minSizes and datasizes of the two content lists are the same.
If the scroll bounds value is not updated, scrollTo will not work because it will …
> WRR-2172: Fixed `VirtualList` to update scroll bounds when the total size of items is changed

- packages/ui/ProgressBar/ProgressBar.js
- packages/ui/ProgressBar/ProgressBar.module.scss
- packages/ui/Scroller/Scroller.module.scss
- packages/ui/Scroller/ScrollerBasic.js
- packages/ui/Slider/PositionDecorator.js
- packages/ui/Slider/Slider.js
- packages/ui/Slider/Slider.module.scss
- packages/ui/Spinner/Spinner.js
- packages/ui/Spinner/Spinner.module.scss
- packages/ui/ToggleIcon/ToggleIcon.js
- packages/ui/ToggleIcon/ToggleIcon.module.scss
- packages/ui/Transition/Transition.js
- packages/ui/Transition/Transition.module.scss
- packages/ui/VirtualList/VirtualList.module.scss
- packages/ui/VirtualList/VirtualListBasic.js
- packages/ui/useScroll/Scrollbar.js
- packages/ui/useScroll/Scrollbar.module.scss
- packages/ui/useScroll/ScrollbarTrack.js
- packages/ui/useScroll/ScrollbarTrack.module.scss
- packages/ui/useScroll/useScroll.js
- packages/ui/useScroll/useScroll.module.scss
Converted components' styling to SCSS: ProgressBar, Scroller, Slider, Spinner, Transition, useScroll and VirtualList.
WRR-4290
> WRR-4290: Convert components styling to SCSS: ProgressBar -> VirtualList

- packages/ui/BodyText/BodyText.js
- packages/ui/BodyText/BodyText.module.scss
- packages/ui/Button/Button.js
- packages/ui/Button/Button.module.scss
- packages/ui/FloatingLayer/FloatingLayer.js
- packages/ui/FloatingLayer/FloatingLayer.module.scss
- packages/ui/FloatingLayer/Scrim.js
- packages/ui/FloatingLayer/Scrim.module.scss
- packages/ui/Heading/Heading.js
- packages/ui/Heading/Heading.module.scss
- packages/ui/Icon/Icon.js
- packages/ui/Icon/Icon.module.scss
- packages/ui/Image/Image.js
- packages/ui/Image/Image.module.scss
- packages/ui/ImageItem/ImageItem.js
- packages/ui/ImageItem/ImageItem.module.scss
- packages/ui/Item/Item.js
- packages/ui/Item/Item.module.scss
- packages/ui/LabeledIcon/LabeledIcon.js
- packages/ui/LabeledIcon/LabeledIcon.module.scss
- packages/ui/Layout/Cell.js
- packages/ui/Layout/Layout.js
- packages/ui/Layout/Layout.module.scss
Converted components' styling to SCSS: `BodyText, Button, FloatingLayer, Heading, Icon, Image, ImageItem, Item, LabeledIcon, and Layout`.
WRR-4289
Enact-DCO-1.0-Signed-off-by: Ion Andrusciac ion.andrusciac@lgepartner.com
> WRR-4289: Converted components styles to SCSS `AnnounceDecorator -> Media`

- packages/spotlight/styles/mixins.scss
- packages/ui/styles/mixins.scss
- packages/ui/styles/utils.scss
Converted mixins to SCSS: `enact-composite`, `remove-margin-on-edge-children`, `remove-padding-on-edge-children`, `full-screen-video-player`, `hide-full-screen-ancestor` and `vendor-fullscreen`.
WRR-5235
> WRR-5235: Converted remaining Enact mixins to SCSS

- packages/webos/lastInputType/lastInputType.js
The last input type is not recognized properly when `requestLastInputType` is called on some platforms since the function do nothing on unsupported platforms.
The issue occurs after #3218 that adds `requestLastInputType`. At the moment we added this API, it is unclear that who is in charge of handling unsupported platforms among Enact, theme libraries, and apps.
The `requestLastInputType` function's role is simply to call LS2Request so the usage of this API depends on apps' logic. We'd like to remove platform checking and make this function to call LS2Request always. It means that Enact does not involve …
> WRR-1010: Fixed to recognize the last input type properly

- packages/ui/CHANGELOG.md
- packages/ui/VirtualList/VirtualListBasic.js
There was an issue that VirtualList did not re-calculate the positions of items when items in the VirtualList was changed. 
For example, the size(=width) of the item contents is as follows:
contents A = [120, 240, 480]
contents B = [480, 240, 120]
In this case, VirtualList needs to re-calculate the positions of items to render them properly. 
I fixed the code to compare arrays of item sizes instead of the total size of the items.
[//]: # (Were any …
> WRR-9866: Fix VirtualListBasic to update its item position when the size of each item is changed

- packages/ui/CHANGELOG.md
- packages/ui/VirtualList/VirtualListBasic.js
When `dataSize` of `VirtualList` changed when the item sizes are variable(e.g. removing an item), the scroll position goes to 0.
When we resolve other issues, we added a condition to recalculate metrics from https://github.com/enactjs/enact/pull/3275 and https://github.com/enactjs/enact/pull/3293.
In this case, it should not recalculate metrics when `dataSize` also changed.
So I added a condition that sees the `dataSize`. For previous issues, there is no change of `dataSize` so it should be fine. I've verified the related test cases from sandstone qa-sampler.
[//]: …
> WRR-12807: Fixed `VirtualList` to not abnormally scroll when `dataSize` and `itemSizes` changed

- packages/ui/styles/mixins.less
As we stopped supporting Internet Explorer browsers from 5.0.0-alpha.1, we don't need to keep IE related code. `.vendor-opacity()` LESS mixin has code for IE so that I want to remove it. But the mixin function itself is possibly used in apps and I will keep the mixin function even it simply provides the standard opacity CSS attribute.
Removed IE related code from `.vendor-opacity()` mixin.
WRR-9415
Enact-DCO-1.0-Signed-off-by: …
> WRR-9415: Remove styles for legacy IE 5 to 8 from vendor-opacity mixin

- packages/ui/resolution/resolution.js
- packages/ui/resolution/tests/resolution-specs.js
Added new `1920 * 804` screenType.
Tests were adapted to cover this change.
WRR-20103
> WRR-20103: Added new screenType

- .travis.yml
- packages/core/internal/WithRef/WithRef.js
There is a bug where the position of the Contextual Popup is incorrect when a component wrapped with Contextual Decorator is updated.
Added a function to update ref in WithRef.
WRR-21642
Enact-DCO-1.0-Signed-off-by: Hyelyn Kim (myelyn.kim@lge.com)
> WRR-21642: Added a function to update ref in WithRef

- packages/ui/Icon/Icon.js
Delete flip prop from rest to prevent it from being passed to the DOM element
Delete flip prop from rest to prevent it from being passed to the DOM element
WRR-21724
> WRR-21724: Delete flip prop from rest to prevent it from being passed to the DOM element

- packages/spotlight/src/spotlight.js
There is an issue where the instance value of `SpotlightAccelerator` is not updated when passing spotlight as `inputField`. This causes the callback to not be called and the spotlight to not move.
Added it as a private function so that reset can be called from onKeyDown of `InputFieldSpotlightDecorator`.
WRR-22638
Enact-DCO-1.0-Signed-off-by: Hyelyn Kim (myelyn.kim@lge.com)
> WRR-22638: Added reset method to spotlight to reseting an instance of Spotlight Accelerator

- package-lock.json
- packages/sampler/stories/default/ViewManager.js
- packages/sampler/stories/default/VirtualGridList.js
- packages/sampler/stories/default/VirtualList.js
- packages/ui/Button/Button.js
- packages/ui/Group/GroupItem.js
https://ko.react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-deprecated-react-apis
PropTypes were deprecated in April 2017 (v15.5.0).
However, the enact/prop-types rule still exists, so removing PropType causes a linting error.
Remove unused eslint-disable directive 'enact/prop-types'
WRR-23385
> WRR-23385: Remove unused eslint-disable directive 'enact/prop-types'

- packages/spotlight/src/spotlight.js
There is an issue where Spotlight does not move if there is an InputField and it is not wrapped with the same SpotlightContainerDecorator. this is because the 5WayKeyHold value is not updated when passing spotlight as inputField. This causes the callback to not be called and the spotlight to not move.
Fixed to reset 5WayKeyHold by extending the `resetSpotlightAccelerator` function to `resetSpotlightAcceleratorAndHoldKey` …
> WRR-24070: Changed function to reset 5WayKeyHold value

- package-lock.json
- package.json
We have already implemented eslint 9, and going forward, configs other than eslint.config.js (eslintrc files, eslintignore files, package.json, etc.) will no longer work.
Remove eslint-related configs in package.json
WRR-22888
> WRR-22888: Remove eslint-related configs in package.json

- docs/interoperability.md
- package-lock.json
Remove the old postcss module usage in docs
Remove the old postcss module usage in docs
WRR-24215
> WRR-24215: Remove the old postcss module usage in docs

- packages/webos/platform/platform.js
- packages/webos/platform/tests/platform-specs.js
We need to update webos/platform's webOS version list as new webOS versions were released.
updated supported webOS versions in enact/webos/platform
WRR-13376
Enact-DCO-1.0-Signed-off-by: Daniel Stoian ([daniel.stoian@lgepartner.com](mailto:daniel.stoian@lgepartner.com))
> WRR-13376: updated supported webOS versions

- packages/spotlight/Spottable/tests/Spottable-specs.js
- packages/spotlight/src/tests/spotlight-specs.js
- packages/ui/FloatingLayer/tests/FloatingLayer-specs.js
- packages/ui/Icon/tests/Icon-specs.js
- packages/ui/Media/tests/Media-specs.js
- packages/ui/Transition/tests/Transition-specs.js
- packages/ui/ViewManager/tests/View-specs.js
- packages/ui/VirtualList/tests/VirtualGridList-specs.js
- packages/ui/VirtualList/tests/VirtualList-specs.js
Migrate test code to apply Jest v30
Migrate test code to apply Jest v30
https://jestjs.io/docs/upgrading-to-jest30#removal-of-alias-matcher-functions
WRR-30001
> WRR-30001: Migrate test code to apply Jest 30

- packages/i18n/package.json
- packages/i18n/tests/ui/config/package.json
- packages/i18n/tests/ui/config/wdio.conf.js
- packages/i18n/tests/ui/config/wdio.docker.conf.js
- packages/i18n/tests/ui/config/wdio.tv.conf.js
- packages/i18n/tests/ui/wdio.conf.js
- packages/i18n/tests/ui/wdio.docker.conf.js
- packages/i18n/tests/ui/wdio.tv.conf.js
Adapted ui/screenshot test configuration for ESM
Moved wdio configuration in config folder in order to be able to mention module type, as ui and ss tests run in an ESM environment, while the rest of Limestone can remain CJS
Otherwise, there would be an error:
WRR-4293
> WRR-4293: Adapted ui test configuration for ESM

- CHANGELOG.md
- packages/spotlight/CHANGELOG.md
- packages/spotlight/src/container.js
In #2848, Spotlight was fixed to set next target to include all eligible elements, but also included hidden elements due to overflow
Fixed Spotlight to not choose next target to include hidden elements.
This condition is not applied when there is no previous focused element, to let spotlight focus any element on page load
WRR-29962
> WRR-29962: Fixed Spotlight to not choose next target to include overflow elements

- CHANGELOG.md
- packages/spotlight/CHANGELOG.md
- packages/spotlight/src/container.js
`Spotlight`: the last focused item is not restored in scroller
WRR-31889
Enact-DCO-1.0-Signed-off-by: Ion Andrusciac ion.andrusciac@lgepartner.com
> WRR-31889: `Spotlight`: the last focused item is not restored in scroller

- CHANGELOG.md
- packages/ui/CHANGELOG.md
- packages/ui/useScroll/useScroll.js
Scrollbar was not returning to the initial position after a simple left-righ-left change or a top-down-top change
I discovered that targetX and targetY are rounded up or down, based on the decimal value
I forced the round to go in the desired direction, based on the direction of the scroll change
NXT-618
> NXT-618: Fixed ui/scroller calculation of targetX and targetY

- CHANGELOG.md
- packages/ui/CHANGELOG.md
- packages/ui/useScroll/tests/useScroll-specs.js
- packages/ui/useScroll/useScroll.js
Scrollbar was not returning to the initial position after a simple left-righ-left change or a top-down-top change
I discovered that targetX and targetY are rounded up or down, based on the decimal value
I forced the round to go in the desired direction, based on the direction of the scroll change
NXT-618
> NXT-618: Fixed ui/scroller calculation of targetX and targetY 
